import { describe,expect,it } from "vitest";
import { CURRENT_SP_COLLECTION_POLICY,CURRENT_SP_INTERCHANGE_CONTRACT,CURRENT_SP_PROVENANCE,parseCurrentSpSnapshot } from "./currentSpSnapshot.js";
const A="a".repeat(64),B="b".repeat(64);
function fixture(over:Record<string,unknown>={}){return {format:"ahd-current-sp-snapshot",version:1,source:{product:"AHDGame",revision:CURRENT_SP_PROVENANCE.game.revision,sourcePath:CURRENT_SP_PROVENANCE.game.sourcePath},declaredRulesetSha256:A,declaredContentSha256:B,manifest:[{name:"gameConfig",documentCount:1,declaredSha256:A}],collections:{gameConfig:[{turn:12}]},...over};}
describe("#300 current SP snapshot contract",()=>{
it("pins provenance and validates metadata without enabling transfer",()=>{expect(CURRENT_SP_INTERCHANGE_CONTRACT.directions).toEqual({gameToNative:"contract-only",nativeToGame:"contract-only"});expect(parseCurrentSpSnapshot(fixture())).toMatchObject({transferStatus:"contract-only",snapshot:{collections:{gameConfig:[{turn:12}]}}});});
it("publishes a unique revision-bound allow/exclude collection policy",()=>{expect(new Set(CURRENT_SP_COLLECTION_POLICY.map(r=>r.name)).size).toBe(CURRENT_SP_COLLECTION_POLICY.length);expect(CURRENT_SP_COLLECTION_POLICY.every(r=>r.sourcePath.endsWith(`@${CURRENT_SP_PROVENANCE.game.revision}`))).toBe(true);expect(CURRENT_SP_COLLECTION_POLICY.filter(r=>r.status==="exclude").map(r=>r.name)).toEqual(["users","sessions","userApiKeys","botApiKeys","apiAccessLog","rateLimitBuckets","notifications"]);});
it("rejects drift, malformed declared hashes, unknown, excluded, duplicate, and undeclared collections",()=>{expect(()=>parseCurrentSpSnapshot({...fixture(),extra:true})).toThrow("unknown=extra");expect(()=>parseCurrentSpSnapshot({...fixture(),declaredRulesetSha256:"bad"})).toThrow("declaredRulesetSha256");expect(()=>parseCurrentSpSnapshot({...fixture(),source:{...fixture().source,revision:"wrong"}})).toThrow("provenance");for(const name of ["invented","users"])expect(()=>parseCurrentSpSnapshot({...fixture(),manifest:[{name,documentCount:0,declaredSha256:A}],collections:{[name]:[]}})).toThrow(name==="users"?"excluded":"unknown");expect(()=>parseCurrentSpSnapshot({...fixture(),manifest:[{name:"gameConfig",documentCount:1,declaredSha256:A},{name:"gameConfig",documentCount:1,declaredSha256:A}]})).toThrow("duplicate");expect(()=>parseCurrentSpSnapshot({...fixture(),collections:{gameConfig:[{}],bills:[]}})).toThrow("absent from manifest");expect(()=>parseCurrentSpSnapshot({...fixture(),manifest:[{name:"gameConfig",documentCount:2,declaredSha256:A}]})).toThrow("count mismatch");});
});
