/**
 * GENERATED from AHDGame office types; do not hand-edit.
 * Source: src/lib/constants/countries.ts at d4baf899fd8bd529099f03d7410807143604e2e5.
 * Source sha256: 830603bb8a63fbf7aa2aff3124c44cb2bc8ff6aaf83da526c90359466a44eb65.
 * Regenerate: node scripts/export-office-registry.mjs /path/to/AHDGame
 * Exports action bonuses and the first national executive office, matching
 * officeBonusRegistry and getExecutiveOfficeKey(countryId) used by appointments.
 * Era-specific overrides are not used by that appointment call in the reference.
 */

export interface OfficeRegistryEntry { countryId: string; officeType: string; actionBonus: number }

export const OFFICE_REGISTRY: readonly OfficeRegistryEntry[] = [
  { countryId: "US", officeType: "president", actionBonus: 4 },
  { countryId: "US", officeType: "vicePresident", actionBonus: 2 },
  { countryId: "US", officeType: "senate", actionBonus: 2 },
  { countryId: "US", officeType: "house", actionBonus: 1 },
  { countryId: "US", officeType: "governor", actionBonus: 2 },
  { countryId: "US", officeType: "stateSenate", actionBonus: 1 },
  { countryId: "US", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "UK", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "UK", officeType: "commons", actionBonus: 1 },
  { countryId: "UK", officeType: "regionalCouncil", actionBonus: 1 },
  { countryId: "UK", officeType: "governor", actionBonus: 2 },
  { countryId: "UK", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "DE", officeType: "chancellor", actionBonus: 4 },
  { countryId: "DE", officeType: "bundestag", actionBonus: 1 },
  { countryId: "DE", officeType: "ministerPresident", actionBonus: 2 },
  { countryId: "DE", officeType: "landtag", actionBonus: 1 },
  { countryId: "DE", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "JP", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "JP", officeType: "shugiin", actionBonus: 1 },
  { countryId: "JP", officeType: "sangiin", actionBonus: 1 },
  { countryId: "JP", officeType: "regionalCouncil", actionBonus: 1 },
  { countryId: "JP", officeType: "governor", actionBonus: 2 },
  { countryId: "JP", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "IE", officeType: "taoiseach", actionBonus: 4 },
  { countryId: "IE", officeType: "tanaiste", actionBonus: 2 },
  { countryId: "IE", officeType: "uachtaran", actionBonus: 3 },
  { countryId: "IE", officeType: "dail", actionBonus: 1 },
  { countryId: "IE", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "IE", officeType: "localCouncil", actionBonus: 1 },
  { countryId: "IE", officeType: "governor", actionBonus: 2 },
  { countryId: "SCO", officeType: "firstMinister", actionBonus: 4 },
  { countryId: "SCO", officeType: "holyrood", actionBonus: 1 },
  { countryId: "SCO", officeType: "governor", actionBonus: 2 },
  { countryId: "SCO", officeType: "regionalCouncil", actionBonus: 1 },
  { countryId: "SCO", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "WAL", officeType: "firstMinister", actionBonus: 4 },
  { countryId: "WAL", officeType: "senedd", actionBonus: 1 },
  { countryId: "WAL", officeType: "governor", actionBonus: 2 },
  { countryId: "WAL", officeType: "regionalCouncil", actionBonus: 1 },
  { countryId: "WAL", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "BR", officeType: "president", actionBonus: 4 },
  { countryId: "BR", officeType: "vicePresident", actionBonus: 2 },
  { countryId: "BR", officeType: "senate", actionBonus: 2 },
  { countryId: "BR", officeType: "chamber", actionBonus: 1 },
  { countryId: "BR", officeType: "governor", actionBonus: 2 },
  { countryId: "BR", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "CN", officeType: "premier", actionBonus: 4 },
  { countryId: "CN", officeType: "president", actionBonus: 0 },
  { countryId: "CN", officeType: "npcDelegate", actionBonus: 1 },
  { countryId: "CN", officeType: "peoplesCongress", actionBonus: 1 },
  { countryId: "CN", officeType: "governor", actionBonus: 2 },
  { countryId: "CN", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "NG", officeType: "president", actionBonus: 4 },
  { countryId: "NG", officeType: "vicePresident", actionBonus: 2 },
  { countryId: "NG", officeType: "senate", actionBonus: 2 },
  { countryId: "NG", officeType: "house", actionBonus: 1 },
  { countryId: "NG", officeType: "regionalCouncil", actionBonus: 1 },
  { countryId: "NG", officeType: "governor", actionBonus: 2 },
  { countryId: "NG", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "HU", officeType: "generalSecretary", actionBonus: 4 },
  { countryId: "HU", officeType: "chairmanOfPresidentialCouncil", actionBonus: 0 },
  { countryId: "HU", officeType: "assemblyDelegate", actionBonus: 1 },
  { countryId: "HU", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "PL", officeType: "firstSecretary", actionBonus: 4 },
  { countryId: "PL", officeType: "chairmanOfStateCouncil", actionBonus: 0 },
  { countryId: "PL", officeType: "sejmDeputy", actionBonus: 1 },
  { countryId: "PL", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "RO", officeType: "generalSecretary", actionBonus: 4 },
  { countryId: "RO", officeType: "presidentOfStateCouncil", actionBonus: 0 },
  { countryId: "RO", officeType: "assemblyDeputy", actionBonus: 1 },
  { countryId: "RO", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "YU", officeType: "president", actionBonus: 4 },
  { countryId: "YU", officeType: "assemblyDelegate", actionBonus: 1 },
  { countryId: "YU", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "BG", officeType: "generalSecretary", actionBonus: 4 },
  { countryId: "BG", officeType: "chairmanOfStateCouncil", actionBonus: 0 },
  { countryId: "BG", officeType: "assemblyDeputy", actionBonus: 1 },
  { countryId: "BG", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "BLR", officeType: "firstSecretary", actionBonus: 4 },
  { countryId: "BLR", officeType: "chairmanOfPresidium", actionBonus: 0 },
  { countryId: "BLR", officeType: "sovietDeputy", actionBonus: 1 },
  { countryId: "BLR", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "CS", officeType: "generalSecretary", actionBonus: 4 },
  { countryId: "CS", officeType: "president", actionBonus: 0 },
  { countryId: "CS", officeType: "assemblyDeputy", actionBonus: 1 },
  { countryId: "CS", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "UKR", officeType: "firstSecretary", actionBonus: 4 },
  { countryId: "UKR", officeType: "chairmanOfPresidium", actionBonus: 0 },
  { countryId: "UKR", officeType: "sovietDeputy", actionBonus: 1 },
  { countryId: "UKR", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "BAL", officeType: "firstSecretary", actionBonus: 4 },
  { countryId: "BAL", officeType: "chairmanOfPresidium", actionBonus: 0 },
  { countryId: "BAL", officeType: "sovietDeputy", actionBonus: 1 },
  { countryId: "BAL", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "RU", officeType: "premier", actionBonus: 4 },
  { countryId: "RU", officeType: "chairmanOfPresidium", actionBonus: 0 },
  { countryId: "RU", officeType: "supremeSovietDeputy", actionBonus: 1 },
  { countryId: "RU", officeType: "nationalitiesDeputy", actionBonus: 1 },
  { countryId: "RU", officeType: "republicSupremeSoviet", actionBonus: 1 },
  { countryId: "RU", officeType: "governor", actionBonus: 2 },
  { countryId: "RU", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "FR", officeType: "president", actionBonus: 4 },
  { countryId: "FR", officeType: "primeMinister", actionBonus: 3 },
  { countryId: "FR", officeType: "deputy", actionBonus: 1 },
  { countryId: "FR", officeType: "senator", actionBonus: 1 },
  { countryId: "FR", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "IT", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "IT", officeType: "president", actionBonus: 0 },
  { countryId: "IT", officeType: "deputy", actionBonus: 1 },
  { countryId: "IT", officeType: "senator", actionBonus: 1 },
  { countryId: "IT", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "ES", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "ES", officeType: "monarch", actionBonus: 0 },
  { countryId: "ES", officeType: "deputy", actionBonus: 1 },
  { countryId: "ES", officeType: "senator", actionBonus: 1 },
  { countryId: "ES", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "SE", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "SE", officeType: "monarch", actionBonus: 0 },
  { countryId: "SE", officeType: "member", actionBonus: 1 },
  { countryId: "SE", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "TR", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "TR", officeType: "president", actionBonus: 0 },
  { countryId: "TR", officeType: "deputy", actionBonus: 1 },
  { countryId: "TR", officeType: "senator", actionBonus: 1 },
  { countryId: "TR", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "GR", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "GR", officeType: "president", actionBonus: 0 },
  { countryId: "GR", officeType: "deputy", actionBonus: 1 },
  { countryId: "GR", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "AT", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "AT", officeType: "president", actionBonus: 0 },
  { countryId: "AT", officeType: "deputy", actionBonus: 1 },
  { countryId: "AT", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "FI", officeType: "primeMinister", actionBonus: 4 },
  { countryId: "FI", officeType: "president", actionBonus: 0 },
  { countryId: "FI", officeType: "deputy", actionBonus: 1 },
  { countryId: "FI", officeType: "centralBankChair", actionBonus: 3 },
  { countryId: "DD", officeType: "generalSecretary", actionBonus: 4 },
  { countryId: "DD", officeType: "chairmanOfStateCouncil", actionBonus: 0 },
  { countryId: "DD", officeType: "volkskammerDeputy", actionBonus: 1 },
  { countryId: "DD", officeType: "landAssembly", actionBonus: 1 },
  { countryId: "DD", officeType: "governor", actionBonus: 2 },
  { countryId: "DD", officeType: "centralBankChair", actionBonus: 3 },
];

export const EXECUTIVE_OFFICE_BY_COUNTRY: Readonly<Record<string, string>> = {
  US: "president",
  UK: "primeMinister",
  DE: "chancellor",
  JP: "primeMinister",
  IE: "taoiseach",
  SCO: "firstMinister",
  WAL: "firstMinister",
  BR: "president",
  CN: "premier",
  NG: "president",
  HU: "generalSecretary",
  PL: "firstSecretary",
  RO: "generalSecretary",
  YU: "president",
  BG: "generalSecretary",
  BLR: "firstSecretary",
  CS: "generalSecretary",
  UKR: "firstSecretary",
  BAL: "firstSecretary",
  RU: "premier",
  FR: "president",
  IT: "primeMinister",
  ES: "primeMinister",
  SE: "primeMinister",
  TR: "primeMinister",
  GR: "primeMinister",
  AT: "primeMinister",
  FI: "primeMinister",
  DD: "generalSecretary",
};
