import type { StateDemographicsSeed } from "./usStateDemographics1953.js";
/**
 * Germany region demographics for 2019. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateRosters.ts
 * Sources:
 * - src/lib/seeds/international/de.ts getDeModel("2019") via getCountryLayer1Model
 * - src/lib/seeds/international/derive.ts buildModelRegionDemographics (the path admin/seed/seedDE.ts runs)
 */
export const DE_DEMOGRAPHICS_2019: StateDemographicsSeed[] = [
  {
    stateId: "BW",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 11.99, economicLean: 0.2, socialLean: 1.5, turnout: 82 },
      gewerkschafter: { population: 9.75, economicLean: -0.9, socialLean: 0.6, turnout: 74 },
      urbane_progressive: { population: 8.18, economicLean: -1.1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 7.97, economicLean: 0.6, socialLean: -0.2, turnout: 83 },
      ost_post_industriell: { population: 8.24, economicLean: -0.5, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 8.55, economicLean: -0.8, socialLean: -1.1, turnout: 85 },
      rentner_west: { population: 10.94, economicLean: 0.3, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 2.09, economicLean: -1.7, socialLean: -1.2, turnout: 51 },
      landwirte_dorf: { population: 9.23, economicLean: 0.2, socialLean: 1.8, turnout: 78 },
      junge_grossstadt: { population: 5.53, economicLean: -1.8, socialLean: -1.9, turnout: 64 },
      protest_waehler_ost: { population: 9.08, economicLean: -0.3, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.45, economicLean: 0.4, socialLean: 0.8, turnout: 79 },
    },
  },
  {
    stateId: "BY",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 12.74, economicLean: 0.2, socialLean: 1.5, turnout: 82 },
      gewerkschafter: { population: 9.62, economicLean: -0.9, socialLean: 0.7, turnout: 74 },
      urbane_progressive: { population: 7.64, economicLean: -1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 7.66, economicLean: 0.7, socialLean: -0.2, turnout: 83 },
      ost_post_industriell: { population: 8.34, economicLean: -0.5, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 8.23, economicLean: -0.8, socialLean: -1, turnout: 85 },
      rentner_west: { population: 10.99, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.88, economicLean: -1.7, socialLean: -1.1, turnout: 51 },
      landwirte_dorf: { population: 10.43, economicLean: 0.3, socialLean: 1.9, turnout: 78 },
      junge_grossstadt: { population: 5.18, economicLean: -1.8, socialLean: -1.9, turnout: 64 },
      protest_waehler_ost: { population: 9.06, economicLean: -0.3, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.22, economicLean: 0.4, socialLean: 0.8, turnout: 79 },
    },
  },
  {
    stateId: "NW",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 11.57, economicLean: 0.1, socialLean: 1.4, turnout: 82 },
      gewerkschafter: { population: 10.28, economicLean: -1, socialLean: 0.6, turnout: 74 },
      urbane_progressive: { population: 8.71, economicLean: -1.2, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 7.22, economicLean: 0.6, socialLean: -0.2, turnout: 83 },
      ost_post_industriell: { population: 8.38, economicLean: -0.5, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 8.72, economicLean: -0.9, socialLean: -1.1, turnout: 85 },
      rentner_west: { population: 10.84, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 2.54, economicLean: -1.7, socialLean: -1.2, turnout: 51 },
      landwirte_dorf: { population: 8.73, economicLean: 0.1, socialLean: 1.7, turnout: 78 },
      junge_grossstadt: { population: 6.25, economicLean: -1.8, socialLean: -1.8, turnout: 64 },
      protest_waehler_ost: { population: 9.01, economicLean: -0.4, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.75, economicLean: 0.4, socialLean: 0.8, turnout: 79 },
    },
  },
  {
    stateId: "HE",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 12.04, economicLean: 0.2, socialLean: 1.5, turnout: 82 },
      gewerkschafter: { population: 9.35, economicLean: -0.9, socialLean: 0.6, turnout: 74 },
      urbane_progressive: { population: 8.49, economicLean: -1.1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 8.15, economicLean: 0.6, socialLean: -0.3, turnout: 83 },
      ost_post_industriell: { population: 8.03, economicLean: -0.5, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 8.88, economicLean: -0.9, socialLean: -1.1, turnout: 85 },
      rentner_west: { population: 10.8, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 2.11, economicLean: -1.7, socialLean: -1.1, turnout: 51 },
      landwirte_dorf: { population: 9.57, economicLean: 0.2, socialLean: 1.9, turnout: 78 },
      junge_grossstadt: { population: 5.53, economicLean: -1.8, socialLean: -1.8, turnout: 64 },
      protest_waehler_ost: { population: 8.89, economicLean: -0.3, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.16, economicLean: 0.5, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "RP",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 13.49, economicLean: 0.2, socialLean: 1.6, turnout: 82 },
      gewerkschafter: { population: 9.64, economicLean: -0.8, socialLean: 0.8, turnout: 74 },
      urbane_progressive: { population: 6.53, economicLean: -1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 7.29, economicLean: 0.5, socialLean: -0.1, turnout: 83 },
      ost_post_industriell: { population: 8.71, economicLean: -0.5, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 7.87, economicLean: -0.8, socialLean: -1, turnout: 85 },
      rentner_west: { population: 11.34, economicLean: 0.3, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.59, economicLean: -1.7, socialLean: -0.9, turnout: 51 },
      landwirte_dorf: { population: 11.42, economicLean: 0.3, socialLean: 2, turnout: 78 },
      junge_grossstadt: { population: 4.44, economicLean: -1.8, socialLean: -1.8, turnout: 64 },
      protest_waehler_ost: { population: 9.55, economicLean: -0.3, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.13, economicLean: 0.3, socialLean: 0.8, turnout: 79 },
    },
  },
  {
    stateId: "SL",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 13.18, economicLean: 0.2, socialLean: 1.5, turnout: 82 },
      gewerkschafter: { population: 10.14, economicLean: -0.9, socialLean: 0.9, turnout: 74 },
      urbane_progressive: { population: 6.22, economicLean: -1.1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 6.83, economicLean: 0.4, socialLean: 0, turnout: 83 },
      ost_post_industriell: { population: 9.17, economicLean: -0.6, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 7.57, economicLean: -0.8, socialLean: -0.9, turnout: 85 },
      rentner_west: { population: 11.94, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.65, economicLean: -1.7, socialLean: -0.8, turnout: 51 },
      landwirte_dorf: { population: 10.8, economicLean: 0.2, socialLean: 1.9, turnout: 78 },
      junge_grossstadt: { population: 4.35, economicLean: -1.8, socialLean: -1.7, turnout: 64 },
      protest_waehler_ost: { population: 10.02, economicLean: -0.4, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.14, economicLean: 0.2, socialLean: 0.9, turnout: 79 },
    },
  },
  {
    stateId: "NI",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 13.53, economicLean: 0.2, socialLean: 1.6, turnout: 82 },
      gewerkschafter: { population: 9.83, economicLean: -0.9, socialLean: 0.8, turnout: 74 },
      urbane_progressive: { population: 6.64, economicLean: -1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 6.9, economicLean: 0.6, socialLean: -0.1, turnout: 83 },
      ost_post_industriell: { population: 8.82, economicLean: -0.5, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 7.7, economicLean: -0.8, socialLean: -1, turnout: 85 },
      rentner_west: { population: 11.17, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.67, economicLean: -1.7, socialLean: -0.9, turnout: 51 },
      landwirte_dorf: { population: 11.5, economicLean: 0.3, socialLean: 2, turnout: 78 },
      junge_grossstadt: { population: 4.75, economicLean: -1.8, socialLean: -1.8, turnout: 64 },
      protest_waehler_ost: { population: 9.59, economicLean: -0.4, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.9, economicLean: 0.3, socialLean: 0.8, turnout: 79 },
    },
  },
  {
    stateId: "SH",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 13.77, economicLean: 0.3, socialLean: 1.6, turnout: 82 },
      gewerkschafter: { population: 9.35, economicLean: -0.8, socialLean: 0.9, turnout: 74 },
      urbane_progressive: { population: 6.37, economicLean: -1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 7.31, economicLean: 0.5, socialLean: -0.1, turnout: 83 },
      ost_post_industriell: { population: 8.73, economicLean: -0.5, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 7.84, economicLean: -0.8, socialLean: -1, turnout: 85 },
      rentner_west: { population: 11.52, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.4, economicLean: -1.7, socialLean: -0.8, turnout: 51 },
      landwirte_dorf: { population: 11.82, economicLean: 0.3, socialLean: 2, turnout: 78 },
      junge_grossstadt: { population: 4.19, economicLean: -1.8, socialLean: -1.7, turnout: 64 },
      protest_waehler_ost: { population: 9.67, economicLean: -0.3, socialLean: 1.5, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.04, economicLean: 0.3, socialLean: 0.8, turnout: 79 },
    },
  },
  {
    stateId: "HH",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 9.66, economicLean: 0.1, socialLean: 1.3, turnout: 82 },
      gewerkschafter: { population: 10.15, economicLean: -1.1, socialLean: 0.1, turnout: 74 },
      urbane_progressive: { population: 12.91, economicLean: -1.3, socialLean: -1.9, turnout: 80 },
      wirtschaftsliberale: { population: 7.42, economicLean: 0.6, socialLean: -0.6, turnout: 83 },
      ost_post_industriell: { population: 7.24, economicLean: -0.5, socialLean: 1.7, turnout: 68 },
      gruene_mittelschicht: { population: 10.51, economicLean: -1.1, socialLean: -1.4, turnout: 85 },
      rentner_west: { population: 9.39, economicLean: 0.4, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 3.44, economicLean: -1.8, socialLean: -1.4, turnout: 51 },
      landwirte_dorf: { population: 6.57, economicLean: 0.1, socialLean: 1.5, turnout: 78 },
      junge_grossstadt: { population: 8.92, economicLean: -1.9, socialLean: -1.9, turnout: 64 },
      protest_waehler_ost: { population: 7.53, economicLean: -0.4, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.25, economicLean: 0.8, socialLean: 0.6, turnout: 79 },
    },
  },
  {
    stateId: "BRE",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 10.11, economicLean: 0.1, socialLean: 1.3, turnout: 82 },
      gewerkschafter: { population: 11.11, economicLean: -1.1, socialLean: 0.2, turnout: 74 },
      urbane_progressive: { population: 11.77, economicLean: -1.4, socialLean: -1.9, turnout: 80 },
      wirtschaftsliberale: { population: 6.03, economicLean: 0.5, socialLean: -0.6, turnout: 83 },
      ost_post_industriell: { population: 7.99, economicLean: -0.6, socialLean: 1.7, turnout: 68 },
      gruene_mittelschicht: { population: 10.02, economicLean: -1, socialLean: -1.3, turnout: 85 },
      rentner_west: { population: 9.71, economicLean: 0.4, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 3.53, economicLean: -1.8, socialLean: -1.3, turnout: 51 },
      landwirte_dorf: { population: 6.87, economicLean: 0, socialLean: 1.5, turnout: 78 },
      junge_grossstadt: { population: 8.86, economicLean: -1.9, socialLean: -1.9, turnout: 64 },
      protest_waehler_ost: { population: 8.2, economicLean: -0.5, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 5.8, economicLean: 0.4, socialLean: 0.8, turnout: 79 },
    },
  },
  {
    stateId: "BE",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 9.41, economicLean: 0.1, socialLean: 1.3, turnout: 82 },
      gewerkschafter: { population: 10.72, economicLean: -1.1, socialLean: 0.2, turnout: 74 },
      urbane_progressive: { population: 12.88, economicLean: -1.4, socialLean: -1.9, turnout: 80 },
      wirtschaftsliberale: { population: 6.62, economicLean: 0.4, socialLean: -0.7, turnout: 83 },
      ost_post_industriell: { population: 7.45, economicLean: -0.6, socialLean: 1.7, turnout: 68 },
      gruene_mittelschicht: { population: 11, economicLean: -1.1, socialLean: -1.3, turnout: 85 },
      rentner_west: { population: 9.08, economicLean: 0.4, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 3.99, economicLean: -1.7, socialLean: -1.3, turnout: 51 },
      landwirte_dorf: { population: 6.27, economicLean: 0, socialLean: 1.5, turnout: 78 },
      junge_grossstadt: { population: 9.36, economicLean: -1.9, socialLean: -1.9, turnout: 64 },
      protest_waehler_ost: { population: 7.64, economicLean: -0.5, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 5.59, economicLean: 0.5, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "BB",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 15.14, economicLean: 0.3, socialLean: 1.7, turnout: 82 },
      gewerkschafter: { population: 10.11, economicLean: -0.8, socialLean: 1, turnout: 74 },
      urbane_progressive: { population: 4.63, economicLean: -1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 5.59, economicLean: 0.4, socialLean: 0, turnout: 83 },
      ost_post_industriell: { population: 9.79, economicLean: -0.6, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 6.64, economicLean: -0.7, socialLean: -0.8, turnout: 85 },
      rentner_west: { population: 11.95, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.09, economicLean: -1.8, socialLean: -0.3, turnout: 51 },
      landwirte_dorf: { population: 13.87, economicLean: 0.4, socialLean: 2.1, turnout: 78 },
      junge_grossstadt: { population: 3.48, economicLean: -1.8, socialLean: -1.6, turnout: 64 },
      protest_waehler_ost: { population: 10.39, economicLean: -0.4, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.34, economicLean: 0, socialLean: 1, turnout: 79 },
    },
  },
  {
    stateId: "MV",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 15.67, economicLean: 0.3, socialLean: 1.7, turnout: 82 },
      gewerkschafter: { population: 10.11, economicLean: -0.9, socialLean: 1.1, turnout: 74 },
      urbane_progressive: { population: 4.29, economicLean: -1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 5.11, economicLean: 0.3, socialLean: -0.1, turnout: 83 },
      ost_post_industriell: { population: 10.11, economicLean: -0.6, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 6.29, economicLean: -0.7, socialLean: -0.8, turnout: 85 },
      rentner_west: { population: 11.63, economicLean: 0.4, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.04, economicLean: -1.9, socialLean: 0, turnout: 51 },
      landwirte_dorf: { population: 14.99, economicLean: 0.4, socialLean: 2.1, turnout: 78 },
      junge_grossstadt: { population: 3.25, economicLean: -1.8, socialLean: -1.4, turnout: 64 },
      protest_waehler_ost: { population: 10.62, economicLean: -0.5, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.9, economicLean: -0.1, socialLean: 1, turnout: 79 },
    },
  },
  {
    stateId: "SN",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 13.86, economicLean: 0.2, socialLean: 1.6, turnout: 82 },
      gewerkschafter: { population: 10.36, economicLean: -0.9, socialLean: 0.9, turnout: 74 },
      urbane_progressive: { population: 6.1, economicLean: -1.2, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 5.87, economicLean: 0.3, socialLean: -0.1, turnout: 83 },
      ost_post_industriell: { population: 9.49, economicLean: -0.6, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 7.43, economicLean: -0.8, socialLean: -0.9, turnout: 85 },
      rentner_west: { population: 11.66, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.46, economicLean: -1.9, socialLean: -0.7, turnout: 51 },
      landwirte_dorf: { population: 11.76, economicLean: 0.3, socialLean: 1.9, turnout: 78 },
      junge_grossstadt: { population: 4.48, economicLean: -1.8, socialLean: -1.7, turnout: 64 },
      protest_waehler_ost: { population: 10.25, economicLean: -0.4, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.26, economicLean: 0, socialLean: 1, turnout: 79 },
    },
  },
  {
    stateId: "ST",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 14.65, economicLean: 0.2, socialLean: 1.6, turnout: 82 },
      gewerkschafter: { population: 10.62, economicLean: -0.9, socialLean: 1, turnout: 74 },
      urbane_progressive: { population: 4.87, economicLean: -1.1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 5.19, economicLean: 0.4, socialLean: 0, turnout: 83 },
      ost_post_industriell: { population: 10.11, economicLean: -0.6, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 6.44, economicLean: -0.7, socialLean: -0.8, turnout: 85 },
      rentner_west: { population: 11.99, economicLean: 0.4, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.29, economicLean: -1.9, socialLean: -0.5, turnout: 51 },
      landwirte_dorf: { population: 13.09, economicLean: 0.3, socialLean: 2, turnout: 78 },
      junge_grossstadt: { population: 3.85, economicLean: -1.8, socialLean: -1.5, turnout: 64 },
      protest_waehler_ost: { population: 10.67, economicLean: -0.5, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.23, economicLean: -0.1, socialLean: 1, turnout: 79 },
    },
  },
  {
    stateId: "TH",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 14.9, economicLean: 0.3, socialLean: 1.7, turnout: 82 },
      gewerkschafter: { population: 10.19, economicLean: -0.9, socialLean: 1, turnout: 74 },
      urbane_progressive: { population: 4.87, economicLean: -1, socialLean: -1.8, turnout: 80 },
      wirtschaftsliberale: { population: 5.58, economicLean: 0.4, socialLean: 0, turnout: 83 },
      ost_post_industriell: { population: 9.82, economicLean: -0.6, socialLean: 1.6, turnout: 68 },
      gruene_mittelschicht: { population: 6.69, economicLean: -0.7, socialLean: -0.8, turnout: 85 },
      rentner_west: { population: 11.88, economicLean: 0.3, socialLean: 1.6, turnout: 85 },
      migranten_communities: { population: 1.17, economicLean: -1.8, socialLean: -0.4, turnout: 51 },
      landwirte_dorf: { population: 13.53, economicLean: 0.3, socialLean: 2.1, turnout: 78 },
      junge_grossstadt: { population: 3.6, economicLean: -1.8, socialLean: -1.5, turnout: 64 },
      protest_waehler_ost: { population: 10.44, economicLean: -0.4, socialLean: 1.6, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.33, economicLean: 0, socialLean: 1, turnout: 79 },
    },
  },
];
