import type { StateDemographicsSeed } from "./usStateDemographics1953.js";
/**
 * Germany region demographics for 1991. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateRosters.ts
 * Sources:
 * - src/lib/seeds/international/de.ts getDeModel("1991") via getCountryLayer1Model
 * - src/lib/seeds/international/derive.ts buildModelRegionDemographics (the path admin/seed/seedDE.ts runs)
 */
export const DE_DEMOGRAPHICS_1991: StateDemographicsSeed[] = [
  {
    stateId: "BW",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 12.69, economicLean: -0.3, socialLean: 1.1, turnout: 82 },
      gewerkschafter: { population: 10.87, economicLean: -1.3, socialLean: 0.4, turnout: 74 },
      urbane_progressive: { population: 6.71, economicLean: -0.5, socialLean: -0.7, turnout: 80 },
      wirtschaftsliberale: { population: 6.4, economicLean: 0.8, socialLean: 0.6, turnout: 83 },
      ost_post_industriell: { population: 9.01, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 7.27, economicLean: -0.6, socialLean: -0.1, turnout: 85 },
      rentner_west: { population: 11, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 2.06, economicLean: -1.8, socialLean: -0.6, turnout: 51 },
      landwirte_dorf: { population: 10, economicLean: -0.2, socialLean: 1.2, turnout: 78 },
      junge_grossstadt: { population: 5.75, economicLean: -1.5, socialLean: -1.1, turnout: 64 },
      protest_waehler_ost: { population: 9.8, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.45, economicLean: -0.1, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "BY",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 13.53, economicLean: -0.2, socialLean: 1.1, turnout: 82 },
      gewerkschafter: { population: 10.68, economicLean: -1.3, socialLean: 0.4, turnout: 74 },
      urbane_progressive: { population: 6.22, economicLean: -0.5, socialLean: -0.7, turnout: 80 },
      wirtschaftsliberale: { population: 6.1, economicLean: 0.8, socialLean: 0.6, turnout: 83 },
      ost_post_industriell: { population: 9.13, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 6.99, economicLean: -0.6, socialLean: -0.1, turnout: 85 },
      rentner_west: { population: 11.1, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.81, economicLean: -1.8, socialLean: -0.6, turnout: 51 },
      landwirte_dorf: { population: 11.33, economicLean: 0, socialLean: 1.3, turnout: 78 },
      junge_grossstadt: { population: 5.22, economicLean: -1.5, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 9.84, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.05, economicLean: -0.1, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "NW",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 12.18, economicLean: -0.4, socialLean: 1, turnout: 82 },
      gewerkschafter: { population: 11.33, economicLean: -1.4, socialLean: 0.4, turnout: 74 },
      urbane_progressive: { population: 7.41, economicLean: -0.7, socialLean: -0.7, turnout: 80 },
      wirtschaftsliberale: { population: 5.73, economicLean: 0.8, socialLean: 0.6, turnout: 83 },
      ost_post_industriell: { population: 9.13, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 7.37, economicLean: -0.6, socialLean: -0.2, turnout: 85 },
      rentner_west: { population: 10.92, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 2.52, economicLean: -1.8, socialLean: -0.6, turnout: 51 },
      landwirte_dorf: { population: 9.32, economicLean: -0.3, socialLean: 1.1, turnout: 78 },
      junge_grossstadt: { population: 6.57, economicLean: -1.6, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 9.77, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.74, economicLean: -0.1, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "HE",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 12.67, economicLean: -0.3, socialLean: 1.1, turnout: 82 },
      gewerkschafter: { population: 10.58, economicLean: -1.3, socialLean: 0.4, turnout: 74 },
      urbane_progressive: { population: 7.05, economicLean: -0.5, socialLean: -0.7, turnout: 80 },
      wirtschaftsliberale: { population: 6.57, economicLean: 0.9, socialLean: 0.5, turnout: 83 },
      ost_post_industriell: { population: 8.84, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 7.46, economicLean: -0.6, socialLean: -0.2, turnout: 85 },
      rentner_west: { population: 10.87, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 2.09, economicLean: -1.8, socialLean: -0.6, turnout: 51 },
      landwirte_dorf: { population: 10.19, economicLean: -0.2, socialLean: 1.2, turnout: 78 },
      junge_grossstadt: { population: 5.81, economicLean: -1.5, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 9.63, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.25, economicLean: 0, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "RP",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 14.09, economicLean: -0.2, socialLean: 1.1, turnout: 82 },
      gewerkschafter: { population: 10.7, economicLean: -1.3, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 5.22, economicLean: -0.4, socialLean: -0.6, turnout: 80 },
      wirtschaftsliberale: { population: 5.83, economicLean: 0.7, socialLean: 0.6, turnout: 83 },
      ost_post_industriell: { population: 9.46, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 6.54, economicLean: -0.6, socialLean: 0, turnout: 85 },
      rentner_west: { population: 11.41, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.54, economicLean: -1.9, socialLean: -0.5, turnout: 51 },
      landwirte_dorf: { population: 12.02, economicLean: 0, socialLean: 1.3, turnout: 78 },
      junge_grossstadt: { population: 4.75, economicLean: -1.6, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 10.3, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.15, economicLean: -0.2, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "SL",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 13.73, economicLean: -0.3, socialLean: 1.1, turnout: 82 },
      gewerkschafter: { population: 11.02, economicLean: -1.3, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 5.12, economicLean: -0.5, socialLean: -0.7, turnout: 80 },
      wirtschaftsliberale: { population: 5.59, economicLean: 0.6, socialLean: 0.6, turnout: 83 },
      ost_post_industriell: { population: 9.77, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 6.41, economicLean: -0.6, socialLean: 0, turnout: 85 },
      rentner_west: { population: 11.71, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.6, economicLean: -1.9, socialLean: -0.5, turnout: 51 },
      landwirte_dorf: { population: 11.34, economicLean: -0.1, socialLean: 1.2, turnout: 78 },
      junge_grossstadt: { population: 4.8, economicLean: -1.6, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 10.71, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.19, economicLean: -0.3, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "NI",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 14.04, economicLean: -0.2, socialLean: 1.2, turnout: 82 },
      gewerkschafter: { population: 10.73, economicLean: -1.3, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 5.57, economicLean: -0.5, socialLean: -0.7, turnout: 80 },
      wirtschaftsliberale: { population: 5.62, economicLean: 0.7, socialLean: 0.6, turnout: 83 },
      ost_post_industriell: { population: 9.42, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 6.6, economicLean: -0.6, socialLean: 0, turnout: 85 },
      rentner_west: { population: 11.24, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.68, economicLean: -1.9, socialLean: -0.5, turnout: 51 },
      landwirte_dorf: { population: 11.99, economicLean: 0, socialLean: 1.3, turnout: 78 },
      junge_grossstadt: { population: 5.08, economicLean: -1.6, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 10.21, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 7.82, economicLean: -0.2, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "SH",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 14.32, economicLean: -0.2, socialLean: 1.2, turnout: 82 },
      gewerkschafter: { population: 10.38, economicLean: -1.3, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 5.12, economicLean: -0.3, socialLean: -0.6, turnout: 80 },
      wirtschaftsliberale: { population: 5.98, economicLean: 0.7, socialLean: 0.6, turnout: 83 },
      ost_post_industriell: { population: 9.41, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 6.52, economicLean: -0.5, socialLean: 0, turnout: 85 },
      rentner_west: { population: 11.57, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.35, economicLean: -1.9, socialLean: -0.5, turnout: 51 },
      landwirte_dorf: { population: 12.39, economicLean: 0.1, socialLean: 1.4, turnout: 78 },
      junge_grossstadt: { population: 4.48, economicLean: -1.6, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 10.32, economicLean: -1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 8.16, economicLean: -0.1, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "HH",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 10.5, economicLean: -0.5, socialLean: 0.9, turnout: 82 },
      gewerkschafter: { population: 11.52, economicLean: -1.4, socialLean: 0.2, turnout: 74 },
      urbane_progressive: { population: 11.16, economicLean: -0.8, socialLean: -0.8, turnout: 80 },
      wirtschaftsliberale: { population: 5.45, economicLean: 1, socialLean: 0.3, turnout: 83 },
      ost_post_industriell: { population: 8.17, economicLean: -1.2, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 9.14, economicLean: -0.7, socialLean: -0.4, turnout: 85 },
      rentner_west: { population: 9.57, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 3.41, economicLean: -1.7, socialLean: -0.7, turnout: 51 },
      landwirte_dorf: { population: 7.27, economicLean: -0.6, socialLean: 0.9, turnout: 78 },
      junge_grossstadt: { population: 9.24, economicLean: -1.5, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 8.4, economicLean: -1.1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.17, economicLean: 0.1, socialLean: 0.6, turnout: 79 },
    },
  },
  {
    stateId: "BRE",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 10.85, economicLean: -0.5, socialLean: 0.9, turnout: 82 },
      gewerkschafter: { population: 12.08, economicLean: -1.4, socialLean: 0.2, turnout: 74 },
      urbane_progressive: { population: 10.33, economicLean: -0.9, socialLean: -0.8, turnout: 80 },
      wirtschaftsliberale: { population: 4.62, economicLean: 0.9, socialLean: 0.4, turnout: 83 },
      ost_post_industriell: { population: 8.74, economicLean: -1.3, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 8.61, economicLean: -0.7, socialLean: -0.3, turnout: 85 },
      rentner_west: { population: 9.78, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 3.44, economicLean: -1.7, socialLean: -0.7, turnout: 51 },
      landwirte_dorf: { population: 7.55, economicLean: -0.6, socialLean: 0.8, turnout: 78 },
      junge_grossstadt: { population: 9.1, economicLean: -1.5, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 8.98, economicLean: -1.1, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 5.92, economicLean: -0.2, socialLean: 0.6, turnout: 79 },
    },
  },
  {
    stateId: "BE",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 10.84, economicLean: -0.5, socialLean: 0.9, turnout: 82 },
      gewerkschafter: { population: 11.95, economicLean: -1.4, socialLean: 0.2, turnout: 74 },
      urbane_progressive: { population: 10.54, economicLean: -0.9, socialLean: -0.9, turnout: 80 },
      wirtschaftsliberale: { population: 4.46, economicLean: 0.8, socialLean: 0.2, turnout: 83 },
      ost_post_industriell: { population: 8.68, economicLean: -1.3, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 8.96, economicLean: -0.7, socialLean: -0.4, turnout: 85 },
      rentner_west: { population: 9.75, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 3.47, economicLean: -1.8, socialLean: -0.7, turnout: 51 },
      landwirte_dorf: { population: 7.51, economicLean: -0.6, socialLean: 0.9, turnout: 78 },
      junge_grossstadt: { population: 9.31, economicLean: -1.5, socialLean: -1, turnout: 64 },
      protest_waehler_ost: { population: 8.98, economicLean: -1.2, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 5.56, economicLean: -0.2, socialLean: 0.6, turnout: 79 },
    },
  },
  {
    stateId: "BB",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 15.45, economicLean: -0.1, socialLean: 1.2, turnout: 82 },
      gewerkschafter: { population: 11.02, economicLean: -1.5, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 3.81, economicLean: -0.6, socialLean: -0.8, turnout: 80 },
      wirtschaftsliberale: { population: 4.06, economicLean: 0.2, socialLean: 0.5, turnout: 83 },
      ost_post_industriell: { population: 10.85, economicLean: -1.4, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 5.71, economicLean: -0.5, socialLean: 0, turnout: 85 },
      rentner_west: { population: 10.73, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.2, economicLean: -2.3, socialLean: -0.2, turnout: 51 },
      landwirte_dorf: { population: 14.43, economicLean: 0.2, socialLean: 1.5, turnout: 78 },
      junge_grossstadt: { population: 4.14, economicLean: -1.7, socialLean: -0.9, turnout: 64 },
      protest_waehler_ost: { population: 11.74, economicLean: -1.2, socialLean: 0.7, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.85, economicLean: -0.7, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "MV",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 16.01, economicLean: 0, socialLean: 1.3, turnout: 82 },
      gewerkschafter: { population: 11.03, economicLean: -1.5, socialLean: 0.6, turnout: 74 },
      urbane_progressive: { population: 3.38, economicLean: -0.5, socialLean: -0.7, turnout: 80 },
      wirtschaftsliberale: { population: 3.62, economicLean: 0.1, socialLean: 0.5, turnout: 83 },
      ost_post_industriell: { population: 11.08, economicLean: -1.4, socialLean: 0.7, turnout: 68 },
      gruene_mittelschicht: { population: 5.35, economicLean: -0.5, socialLean: 0, turnout: 85 },
      rentner_west: { population: 10.46, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.14, economicLean: -2.4, socialLean: -0.1, turnout: 51 },
      landwirte_dorf: { population: 15.55, economicLean: 0.3, socialLean: 1.5, turnout: 78 },
      junge_grossstadt: { population: 4, economicLean: -1.8, socialLean: -0.9, turnout: 64 },
      protest_waehler_ost: { population: 11.83, economicLean: -1.2, socialLean: 0.7, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.54, economicLean: -0.8, socialLean: 0.6, turnout: 79 },
    },
  },
  {
    stateId: "SN",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 14.23, economicLean: -0.2, socialLean: 1.1, turnout: 82 },
      gewerkschafter: { population: 11.49, economicLean: -1.4, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 4.99, economicLean: -0.8, socialLean: -0.8, turnout: 80 },
      wirtschaftsliberale: { population: 4.17, economicLean: 0.2, socialLean: 0.5, turnout: 83 },
      ost_post_industriell: { population: 10.64, economicLean: -1.3, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 6.31, economicLean: -0.6, socialLean: -0.1, turnout: 85 },
      rentner_west: { population: 10.78, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.54, economicLean: -2.1, socialLean: -0.4, turnout: 51 },
      landwirte_dorf: { population: 12.33, economicLean: 0, socialLean: 1.3, turnout: 78 },
      junge_grossstadt: { population: 5.08, economicLean: -1.7, socialLean: -0.9, turnout: 64 },
      protest_waehler_ost: { population: 11.54, economicLean: -1.2, socialLean: 0.8, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.9, economicLean: -0.7, socialLean: 0.6, turnout: 79 },
    },
  },
  {
    stateId: "ST",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 14.9, economicLean: -0.2, socialLean: 1.2, turnout: 82 },
      gewerkschafter: { population: 11.34, economicLean: -1.5, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 4.26, economicLean: -0.7, socialLean: -0.8, turnout: 80 },
      wirtschaftsliberale: { population: 3.97, economicLean: 0.2, socialLean: 0.5, turnout: 83 },
      ost_post_industriell: { population: 10.94, economicLean: -1.4, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 5.69, economicLean: -0.6, socialLean: 0, turnout: 85 },
      rentner_west: { population: 10.65, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.4, economicLean: -2.2, socialLean: -0.3, turnout: 51 },
      landwirte_dorf: { population: 13.56, economicLean: 0.1, socialLean: 1.4, turnout: 78 },
      junge_grossstadt: { population: 4.61, economicLean: -1.7, socialLean: -0.9, turnout: 64 },
      protest_waehler_ost: { population: 11.81, economicLean: -1.2, socialLean: 0.7, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.87, economicLean: -0.7, socialLean: 0.7, turnout: 79 },
    },
  },
  {
    stateId: "TH",
    categoryWeights: {"de_voterGroups":100},
    groups: {
      katholische_konservative: { population: 15.26, economicLean: -0.1, socialLean: 1.2, turnout: 82 },
      gewerkschafter: { population: 11.18, economicLean: -1.4, socialLean: 0.5, turnout: 74 },
      urbane_progressive: { population: 4, economicLean: -0.6, socialLean: -0.8, turnout: 80 },
      wirtschaftsliberale: { population: 4.04, economicLean: 0.2, socialLean: 0.5, turnout: 83 },
      ost_post_industriell: { population: 10.82, economicLean: -1.4, socialLean: 0.8, turnout: 68 },
      gruene_mittelschicht: { population: 5.81, economicLean: -0.5, socialLean: 0, turnout: 85 },
      rentner_west: { population: 10.73, economicLean: 0, socialLean: 1.5, turnout: 85 },
      migranten_communities: { population: 1.25, economicLean: -2.2, socialLean: -0.2, turnout: 51 },
      landwirte_dorf: { population: 14.07, economicLean: 0.1, socialLean: 1.4, turnout: 78 },
      junge_grossstadt: { population: 4.29, economicLean: -1.7, socialLean: -0.9, turnout: 64 },
      protest_waehler_ost: { population: 11.67, economicLean: -1.2, socialLean: 0.7, turnout: 67 },
      mittelstand_selbstaendige: { population: 6.88, economicLean: -0.7, socialLean: 0.6, turnout: 79 },
    },
  },
];
