import type { StateDemographicsSeed } from "./usStateDemographics1953.js";
/**
 * Japan region demographics for 1991. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateRosters.ts
 * Sources:
 * - src/lib/seeds/international/jp.ts getJpModel("1991") via getCountryLayer1Model
 * - src/lib/seeds/international/derive.ts buildModelRegionDemographics (the path admin/seed/seedJP.ts runs)
 */
export const JP_DEMOGRAPHICS_1991: StateDemographicsSeed[] = [
  {
    stateId: "HOK",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 11.46, economicLean: 0.3, socialLean: 0.3, turnout: 63 },
      urban_progressive: { population: 8.69, economicLean: -1.6, socialLean: -2.6, turnout: 57 },
      rural_traditionalist: { population: 11.38, economicLean: 2.6, socialLean: 3.6, turnout: 69 },
      young_urban: { population: 5.11, economicLean: -2.4, socialLean: -3, turnout: 34 },
      retiree: { population: 11.06, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 10.66, economicLean: -1, socialLean: -1.5, turnout: 56 },
      small_business: { population: 10.39, economicLean: 0.5, socialLean: 0.6, turnout: 56 },
      komeito_faithful: { population: 14.16, economicLean: -0.8, socialLean: -0.9, turnout: 65 },
      reform_populist: { population: 8.78, economicLean: -1.1, socialLean: -1.4, turnout: 47 },
      working_mothers: { population: 8.31, economicLean: 0, socialLean: -0.3, turnout: 52 },
    },
  },
  {
    stateId: "TOH",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 12.01, economicLean: 0.4, socialLean: 0.4, turnout: 63 },
      urban_progressive: { population: 7.18, economicLean: -1.5, socialLean: -2.5, turnout: 57 },
      rural_traditionalist: { population: 14, economicLean: 2.6, socialLean: 3.6, turnout: 69 },
      young_urban: { population: 4.16, economicLean: -2.4, socialLean: -3, turnout: 34 },
      retiree: { population: 11.99, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 9.79, economicLean: -0.8, socialLean: -1.3, turnout: 56 },
      small_business: { population: 11.21, economicLean: 0.5, socialLean: 0.6, turnout: 56 },
      komeito_faithful: { population: 13.07, economicLean: -0.4, socialLean: -0.5, turnout: 65 },
      reform_populist: { population: 7.84, economicLean: -0.8, socialLean: -1.1, turnout: 47 },
      working_mothers: { population: 8.74, economicLean: 0.1, socialLean: -0.2, turnout: 52 },
    },
  },
  {
    stateId: "KAN",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 10.09, economicLean: 0.2, socialLean: 0, turnout: 63 },
      urban_progressive: { population: 12.21, economicLean: -1.8, socialLean: -2.7, turnout: 57 },
      rural_traditionalist: { population: 5.27, economicLean: 1.9, socialLean: 3.3, turnout: 69 },
      young_urban: { population: 7.34, economicLean: -2.5, socialLean: -3.1, turnout: 34 },
      retiree: { population: 9.04, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 12.64, economicLean: -1.4, socialLean: -1.9, turnout: 56 },
      small_business: { population: 8.2, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      komeito_faithful: { population: 17.1, economicLean: -1.3, socialLean: -1.6, turnout: 65 },
      reform_populist: { population: 11.02, economicLean: -1.6, socialLean: -2, turnout: 47 },
      working_mothers: { population: 7.09, economicLean: -0.1, socialLean: -0.5, turnout: 52 },
    },
  },
  {
    stateId: "CHU",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 11.26, economicLean: 0.3, socialLean: 0.2, turnout: 63 },
      urban_progressive: { population: 9.57, economicLean: -1.7, socialLean: -2.6, turnout: 57 },
      rural_traditionalist: { population: 8.23, economicLean: 2.3, socialLean: 3.5, turnout: 69 },
      young_urban: { population: 5.76, economicLean: -2.4, socialLean: -3, turnout: 34 },
      retiree: { population: 10.81, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 11.27, economicLean: -1.1, socialLean: -1.6, turnout: 56 },
      small_business: { population: 10.19, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      komeito_faithful: { population: 15.16, economicLean: -1, socialLean: -1.2, turnout: 65 },
      reform_populist: { population: 9.47, economicLean: -1.3, socialLean: -1.6, turnout: 47 },
      working_mothers: { population: 8.28, economicLean: 0, socialLean: -0.3, turnout: 52 },
    },
  },
  {
    stateId: "KNS",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 10.57, economicLean: 0.2, socialLean: 0.1, turnout: 63 },
      urban_progressive: { population: 10.98, economicLean: -1.8, socialLean: -2.7, turnout: 57 },
      rural_traditionalist: { population: 6.29, economicLean: 2, socialLean: 3.3, turnout: 69 },
      young_urban: { population: 6.65, economicLean: -2.5, socialLean: -3.1, turnout: 34 },
      retiree: { population: 9.8, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 12.03, economicLean: -1.3, socialLean: -1.8, turnout: 56 },
      small_business: { population: 9.13, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      komeito_faithful: { population: 16.51, economicLean: -1.2, socialLean: -1.4, turnout: 65 },
      reform_populist: { population: 10.5, economicLean: -1.5, socialLean: -1.8, turnout: 47 },
      working_mothers: { population: 7.54, economicLean: -0.1, socialLean: -0.4, turnout: 52 },
    },
  },
  {
    stateId: "CGK",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 11.47, economicLean: 0.4, socialLean: 0.3, turnout: 63 },
      urban_progressive: { population: 8.44, economicLean: -1.7, socialLean: -2.6, turnout: 57 },
      rural_traditionalist: { population: 10.5, economicLean: 2.5, socialLean: 3.6, turnout: 69 },
      young_urban: { population: 5.1, economicLean: -2.4, socialLean: -3, turnout: 34 },
      retiree: { population: 11.42, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 10.62, economicLean: -1, socialLean: -1.5, turnout: 56 },
      small_business: { population: 10.63, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      komeito_faithful: { population: 14.57, economicLean: -0.8, socialLean: -0.9, turnout: 65 },
      reform_populist: { population: 8.92, economicLean: -1.1, socialLean: -1.5, turnout: 47 },
      working_mothers: { population: 8.32, economicLean: 0.1, socialLean: -0.2, turnout: 52 },
    },
  },
  {
    stateId: "SHI",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 11.87, economicLean: 0.4, socialLean: 0.3, turnout: 63 },
      urban_progressive: { population: 7.58, economicLean: -1.6, socialLean: -2.6, turnout: 57 },
      rural_traditionalist: { population: 12.44, economicLean: 2.6, socialLean: 3.6, turnout: 69 },
      young_urban: { population: 4.51, economicLean: -2.4, socialLean: -3, turnout: 34 },
      retiree: { population: 12.03, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 10.12, economicLean: -0.9, socialLean: -1.4, turnout: 56 },
      small_business: { population: 11.02, economicLean: 0.5, socialLean: 0.6, turnout: 56 },
      komeito_faithful: { population: 13.74, economicLean: -0.6, socialLean: -0.7, turnout: 65 },
      reform_populist: { population: 8.18, economicLean: -1, socialLean: -1.3, turnout: 47 },
      working_mothers: { population: 8.51, economicLean: 0.1, socialLean: -0.2, turnout: 52 },
    },
  },
  {
    stateId: "KYU",
    categoryWeights: {"jp_voterGroups":100},
    groups: {
      salaryman_conservative: { population: 11.28, economicLean: 0.3, socialLean: 0.3, turnout: 63 },
      urban_progressive: { population: 8.63, economicLean: -1.7, socialLean: -2.6, turnout: 57 },
      rural_traditionalist: { population: 10.06, economicLean: 2.4, socialLean: 3.5, turnout: 69 },
      young_urban: { population: 5.35, economicLean: -2.4, socialLean: -3, turnout: 34 },
      retiree: { population: 11.37, economicLean: 1.6, socialLean: 1.9, turnout: 73 },
      public_sector: { population: 10.7, economicLean: -1.1, socialLean: -1.6, turnout: 56 },
      small_business: { population: 10.48, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      komeito_faithful: { population: 14.73, economicLean: -0.9, socialLean: -1, turnout: 65 },
      reform_populist: { population: 9.12, economicLean: -1.2, socialLean: -1.5, turnout: 47 },
      working_mothers: { population: 8.28, economicLean: 0, socialLean: -0.2, turnout: 52 },
    },
  },
];
