/**
 * UK Demographics for 1953 — derived from mainline Layer 1 census shares via Layer1 model.
 *
 * Sources (no invented numbers):
 * - Census: src/lib/seeds/uk/ukRegionCensusData1953.ts (1951 Census, 12 regions)
 * - Positions: src/lib/seeds/international/uk.ts POSITIONS_1953 (post-war class politics)
 * - Composition/turnout/categories: src/lib/seeds/international/uk.ts (UK_GROUP_IDS, COMPOSITION, TURNOUT_RATES) + src/lib/seeds/uk/ukDemographicCategories.ts
 * - Derivation: src/lib/seeds/international/derive.ts deriveCountryGroupPopulations / deriveCountryGroupLean / deriveCountryGroupTurnout (census × positions × composition, clamped -5..5, normalized to 100)
 * Populations sum to 100 per region (rounded to 2dp, largest bucket absorbs rounding). Turnout per group derived from turnoutRates × civicMultiplier, clamped 25-85.
 */
export const UK_DEMOGRAPHICS_1953 = [
  {
    stateId: "LON",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 12.43, economicLean: -3.3, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 8.55, economicLean: -3.3, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 5.16, economicLean: 1.4, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 9.52, economicLean: -3.6, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 9.03, economicLean: -0.6, socialLean: 0.7, turnout: 70 },
      retirees: { population: 8.03, economicLean: 0.0, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 12.19, economicLean: -2.1, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 7.56, economicLean: -0.5, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 11.88, economicLean: -1.4, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 7.34, economicLean: -2.4, socialLean: 0.4, turnout: 58 },
      small_business: { population: 5.1, economicLean: 1.8, socialLean: 0.8, turnout: 69 },
      new_britons: { population: 3.21, economicLean: -4.0, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "SEE",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 10.06, economicLean: -3.0, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 4.44, economicLean: -2.9, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 9.54, economicLean: 1.6, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 5.24, economicLean: -3.4, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 12.1, economicLean: -0.1, socialLean: 0.8, turnout: 70 },
      retirees: { population: 9.99, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 9.04, economicLean: -1.5, socialLean: 0.6, turnout: 68 },
      moderate_centrists: { population: 9.58, economicLean: -0.1, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.42, economicLean: -1.0, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 4.99, economicLean: -1.8, socialLean: 0.4, turnout: 58 },
      small_business: { population: 9.11, economicLean: 1.9, socialLean: 0.8, turnout: 69 },
      new_britons: { population: 1.49, economicLean: -4.1, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "SWE",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 10.89, economicLean: -3.0, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 3.42, economicLean: -2.7, socialLean: 0.3, turnout: 62 },
      suburban_homeowners: { population: 8.24, economicLean: 1.4, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 4.6, economicLean: -3.4, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 16.27, economicLean: 0.2, socialLean: 0.8, turnout: 70 },
      retirees: { population: 10.56, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 8.49, economicLean: -1.3, socialLean: 0.6, turnout: 68 },
      moderate_centrists: { population: 9.16, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.99, economicLean: -1.2, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 4.46, economicLean: -1.6, socialLean: 0.4, turnout: 58 },
      small_business: { population: 7.66, economicLean: 1.6, socialLean: 0.8, turnout: 69 },
      new_britons: { population: 1.26, economicLean: -4.2, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "EAE",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 10.47, economicLean: -3.0, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 3.7, economicLean: -2.8, socialLean: 0.3, turnout: 62 },
      suburban_homeowners: { population: 8.84, economicLean: 1.5, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 4.76, economicLean: -3.4, socialLean: 0.3, turnout: 45 },
      rural_traditionalists: { population: 14.7, economicLean: 0.1, socialLean: 0.8, turnout: 70 },
      retirees: { population: 10.37, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 8.64, economicLean: -1.3, socialLean: 0.6, turnout: 68 },
      moderate_centrists: { population: 9.42, economicLean: -0.1, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.83, economicLean: -1.1, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 4.61, economicLean: -1.7, socialLean: 0.4, turnout: 58 },
      small_business: { population: 8.36, economicLean: 1.8, socialLean: 0.8, turnout: 69 },
      new_britons: { population: 1.3, economicLean: -4.1, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "EMI",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 11.07, economicLean: -3.1, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 4.0, economicLean: -2.8, socialLean: 0.3, turnout: 62 },
      suburban_homeowners: { population: 8.13, economicLean: 1.3, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 5.27, economicLean: -3.4, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 14.42, economicLean: 0.1, socialLean: 0.8, turnout: 70 },
      retirees: { population: 10.13, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 8.89, economicLean: -1.4, socialLean: 0.6, turnout: 68 },
      moderate_centrists: { population: 9.34, economicLean: -0.1, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.92, economicLean: -1.1, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 4.81, economicLean: -1.8, socialLean: 0.4, turnout: 58 },
      small_business: { population: 7.51, economicLean: 1.5, socialLean: 0.8, turnout: 69 },
      new_britons: { population: 1.51, economicLean: -4.1, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "WMI",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 11.95, economicLean: -3.2, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 5.77, economicLean: -3.3, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 7.14, economicLean: 1.3, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 7.09, economicLean: -3.6, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 11.03, economicLean: -0.3, socialLean: 0.8, turnout: 70 },
      retirees: { population: 9.36, economicLean: 0.1, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 10.16, economicLean: -1.8, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 8.75, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.12, economicLean: -1.3, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 5.68, economicLean: -2.3, socialLean: 0.4, turnout: 58 },
      small_business: { population: 6.61, economicLean: 1.6, socialLean: 0.8, turnout: 69 },
      new_britons: { population: 2.34, economicLean: -4.0, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "YHU",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 12.66, economicLean: -3.2, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 5.35, economicLean: -3.2, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 6.86, economicLean: 1.1, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 7.03, economicLean: -3.6, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 12.38, economicLean: -0.2, socialLean: 0.8, turnout: 70 },
      retirees: { population: 9.41, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 9.56, economicLean: -1.8, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 8.37, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.67, economicLean: -1.3, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 5.36, economicLean: -2.2, socialLean: 0.4, turnout: 58 },
      small_business: { population: 6.14, economicLean: 1.3, socialLean: 0.7, turnout: 69 },
      new_britons: { population: 2.21, economicLean: -4.1, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "NWE",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 12.89, economicLean: -3.3, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 6.06, economicLean: -3.3, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 6.52, economicLean: 1.1, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 7.74, economicLean: -3.6, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 11.01, economicLean: -0.4, socialLean: 0.8, turnout: 70 },
      retirees: { population: 9.01, economicLean: 0.1, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 10.09, economicLean: -1.9, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 8.21, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.36, economicLean: -1.3, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 5.77, economicLean: -2.3, socialLean: 0.4, turnout: 58 },
      small_business: { population: 5.87, economicLean: 1.3, socialLean: 0.7, turnout: 69 },
      new_britons: { population: 2.47, economicLean: -4.1, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "NEE",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 13.66, economicLean: -3.3, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 5.95, economicLean: -3.3, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 6.23, economicLean: 0.9, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 7.9, economicLean: -3.6, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 11.55, economicLean: -0.3, socialLean: 0.8, turnout: 70 },
      retirees: { population: 8.83, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 9.73, economicLean: -1.9, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 7.74, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.88, economicLean: -1.3, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 5.65, economicLean: -2.3, socialLean: 0.4, turnout: 58 },
      small_business: { population: 5.42, economicLean: 1.1, socialLean: 0.7, turnout: 69 },
      new_britons: { population: 2.46, economicLean: -4.2, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "SCO",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 12.55, economicLean: -3.3, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 5.82, economicLean: -3.1, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 6.64, economicLean: 1.1, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 7.41, economicLean: -3.6, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 12.3, economicLean: -0.2, socialLean: 0.8, turnout: 70 },
      retirees: { population: 8.95, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 9.81, economicLean: -1.8, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 8.23, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.3, economicLean: -1.2, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 5.75, economicLean: -2.1, socialLean: 0.4, turnout: 58 },
      small_business: { population: 6.0, economicLean: 1.3, socialLean: 0.7, turnout: 69 },
      new_britons: { population: 2.24, economicLean: -4.2, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "WAL",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 12.96, economicLean: -3.2, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 4.76, economicLean: -3.2, socialLean: 0.4, turnout: 62 },
      suburban_homeowners: { population: 6.96, economicLean: 1.0, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 6.62, economicLean: -3.6, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 13.55, economicLean: -0.1, socialLean: 0.8, turnout: 70 },
      retirees: { population: 9.67, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 8.96, economicLean: -1.7, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 8.24, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 15.17, economicLean: -1.3, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 4.98, economicLean: -2.1, socialLean: 0.4, turnout: 58 },
      small_business: { population: 6.1, economicLean: 1.2, socialLean: 0.7, turnout: 69 },
      new_britons: { population: 2.03, economicLean: -4.2, socialLean: 0.5, turnout: 41 },
    },
  },
  {
    stateId: "NIR",
    categoryWeights: { uk_voterGroups: 100 },
    groups: {
      post_industrial_workers: { population: 12.63, economicLean: -3.3, socialLean: 0.6, turnout: 52 },
      urban_progressives: { population: 4.81, economicLean: -3.0, socialLean: 0.3, turnout: 62 },
      suburban_homeowners: { population: 6.6, economicLean: 1.1, socialLean: 0.8, turnout: 70 },
      young_renters: { population: 6.86, economicLean: -3.5, socialLean: 0.4, turnout: 45 },
      rural_traditionalists: { population: 14.69, economicLean: 0.0, socialLean: 0.8, turnout: 70 },
      retirees: { population: 8.96, economicLean: 0.2, socialLean: 0.9, turnout: 77 },
      public_sector: { population: 8.98, economicLean: -1.7, socialLean: 0.5, turnout: 68 },
      moderate_centrists: { population: 8.39, economicLean: -0.2, socialLean: 0.6, turnout: 66 },
      populist_right: { population: 14.94, economicLean: -1.3, socialLean: 0.7, turnout: 54 },
      green_activists: { population: 5.22, economicLean: -2.1, socialLean: 0.4, turnout: 58 },
      small_business: { population: 5.98, economicLean: 1.3, socialLean: 0.7, turnout: 69 },
      new_britons: { population: 1.94, economicLean: -4.2, socialLean: 0.5, turnout: 41 },
    },
  },
];
