import type { StateDemographicsSeed } from "./usStateDemographics1953.js";
/**
 * UK region demographics for 1979. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/uk/ukRegionDemographics1979.ts (static per-region groups, the bundle admin/seed/seedUK.ts seedUKDemographics uses for 1979-default)
 */
export const UK_DEMOGRAPHICS_1979: StateDemographicsSeed[] = [
  {
    stateId: "LON",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 16, economicLean: -3, socialLean: 1, turnout: 70 },
      urban_progressives: { population: 9, economicLean: -4, socialLean: -2, turnout: 76 },
      suburban_homeowners: { population: 8, economicLean: 2, socialLean: 2, turnout: 76 },
      young_renters: { population: 14, economicLean: -2, socialLean: -2, turnout: 64 },
      rural_traditionalists: { population: 1, economicLean: 3, socialLean: 4, turnout: 76 },
      retirees: { population: 8, economicLean: 0, socialLean: 3, turnout: 80 },
      public_sector: { population: 12, economicLean: -4, socialLean: -1, turnout: 74 },
      moderate_centrists: { population: 10, economicLean: 0, socialLean: -1, turnout: 73 },
      populist_right: { population: 3, economicLean: 0, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 8, economicLean: 3, socialLean: 2, turnout: 76 },
      new_britons: { population: 10, economicLean: -3, socialLean: 1, turnout: 55 },
    },
  },
  {
    stateId: "SEE",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 12, economicLean: -3, socialLean: 2, turnout: 70 },
      urban_progressives: { population: 3, economicLean: -4, socialLean: -2, turnout: 75 },
      suburban_homeowners: { population: 17, economicLean: 3, socialLean: 2, turnout: 80 },
      young_renters: { population: 8, economicLean: -1, socialLean: -2, turnout: 64 },
      rural_traditionalists: { population: 16, economicLean: 3, socialLean: 4, turnout: 79 },
      retirees: { population: 12, economicLean: 1, socialLean: 3, turnout: 81 },
      public_sector: { population: 8, economicLean: -3, socialLean: -1, turnout: 74 },
      moderate_centrists: { population: 13, economicLean: 0, socialLean: -1, turnout: 75 },
      populist_right: { population: 1, economicLean: 1, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 8, economicLean: 3, socialLean: 2, turnout: 78 },
      new_britons: { population: 1, economicLean: -3, socialLean: 1, turnout: 52 },
    },
  },
  {
    stateId: "SWE",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 10, economicLean: -3, socialLean: 2, turnout: 70 },
      urban_progressives: { population: 3, economicLean: -4, socialLean: -2, turnout: 74 },
      suburban_homeowners: { population: 13, economicLean: 3, socialLean: 2, turnout: 79 },
      young_renters: { population: 7, economicLean: -1, socialLean: -2, turnout: 62 },
      rural_traditionalists: { population: 19, economicLean: 3, socialLean: 4, turnout: 79 },
      retirees: { population: 14, economicLean: 1, socialLean: 3, turnout: 82 },
      public_sector: { population: 7, economicLean: -3, socialLean: -1, turnout: 73 },
      moderate_centrists: { population: 16, economicLean: 0, socialLean: -1, turnout: 76 },
      populist_right: { population: 1, economicLean: 1, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 8, economicLean: 3, socialLean: 2, turnout: 78 },
      new_britons: { population: 1, economicLean: -3, socialLean: 1, turnout: 50 },
    },
  },
  {
    stateId: "EAE",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 13, economicLean: -3, socialLean: 2, turnout: 70 },
      urban_progressives: { population: 3, economicLean: -4, socialLean: -2, turnout: 74 },
      suburban_homeowners: { population: 14, economicLean: 3, socialLean: 2, turnout: 79 },
      young_renters: { population: 7, economicLean: -1, socialLean: -2, turnout: 62 },
      rural_traditionalists: { population: 20, economicLean: 3, socialLean: 4, turnout: 78 },
      retirees: { population: 12, economicLean: 1, socialLean: 3, turnout: 81 },
      public_sector: { population: 7, economicLean: -3, socialLean: -1, turnout: 73 },
      moderate_centrists: { population: 12, economicLean: 0, socialLean: -1, turnout: 74 },
      populist_right: { population: 1, economicLean: 1, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 9, economicLean: 3, socialLean: 2, turnout: 77 },
      new_britons: { population: 1, economicLean: -3, socialLean: 1, turnout: 50 },
    },
  },
  {
    stateId: "EMI",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 25, economicLean: -3, socialLean: 2, turnout: 72 },
      urban_progressives: { population: 3, economicLean: -4, socialLean: -2, turnout: 73 },
      suburban_homeowners: { population: 11, economicLean: 3, socialLean: 2, turnout: 78 },
      young_renters: { population: 7, economicLean: -1, socialLean: -2, turnout: 62 },
      rural_traditionalists: { population: 15, economicLean: 3, socialLean: 4, turnout: 78 },
      retirees: { population: 9, economicLean: 1, socialLean: 3, turnout: 80 },
      public_sector: { population: 8, economicLean: -3, socialLean: -1, turnout: 73 },
      moderate_centrists: { population: 9, economicLean: 0, socialLean: -1, turnout: 73 },
      populist_right: { population: 2, economicLean: 0, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 6, economicLean: 3, socialLean: 2, turnout: 76 },
      new_britons: { population: 4, economicLean: -3, socialLean: 1, turnout: 54 },
    },
  },
  {
    stateId: "WMI",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 27, economicLean: -3, socialLean: 2, turnout: 71 },
      urban_progressives: { population: 4, economicLean: -4, socialLean: -2, turnout: 73 },
      suburban_homeowners: { population: 10, economicLean: 3, socialLean: 2, turnout: 78 },
      young_renters: { population: 8, economicLean: -2, socialLean: -2, turnout: 62 },
      rural_traditionalists: { population: 9, economicLean: 3, socialLean: 4, turnout: 78 },
      retirees: { population: 8, economicLean: 1, socialLean: 3, turnout: 80 },
      public_sector: { population: 8, economicLean: -4, socialLean: -1, turnout: 73 },
      moderate_centrists: { population: 8, economicLean: 0, socialLean: -1, turnout: 72 },
      populist_right: { population: 3, economicLean: 0, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 6, economicLean: 3, socialLean: 2, turnout: 75 },
      new_britons: { population: 8, economicLean: -3, socialLean: 1, turnout: 54 },
    },
  },
  {
    stateId: "YHU",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 29, economicLean: -4, socialLean: 2, turnout: 72 },
      urban_progressives: { population: 4, economicLean: -4, socialLean: -2, turnout: 73 },
      suburban_homeowners: { population: 8, economicLean: 2, socialLean: 2, turnout: 77 },
      young_renters: { population: 8, economicLean: -2, socialLean: -2, turnout: 62 },
      rural_traditionalists: { population: 11, economicLean: 3, socialLean: 4, turnout: 78 },
      retirees: { population: 9, economicLean: 0, socialLean: 3, turnout: 80 },
      public_sector: { population: 9, economicLean: -4, socialLean: -1, turnout: 73 },
      moderate_centrists: { population: 8, economicLean: 0, socialLean: -1, turnout: 72 },
      populist_right: { population: 2, economicLean: 0, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 5, economicLean: 3, socialLean: 2, turnout: 75 },
      new_britons: { population: 6, economicLean: -3, socialLean: 1, turnout: 53 },
    },
  },
  {
    stateId: "NWE",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 30, economicLean: -4, socialLean: 2, turnout: 72 },
      urban_progressives: { population: 5, economicLean: -4, socialLean: -2, turnout: 73 },
      suburban_homeowners: { population: 8, economicLean: 2, socialLean: 2, turnout: 77 },
      young_renters: { population: 9, economicLean: -2, socialLean: -2, turnout: 62 },
      rural_traditionalists: { population: 7, economicLean: 3, socialLean: 4, turnout: 77 },
      retirees: { population: 9, economicLean: 0, socialLean: 3, turnout: 80 },
      public_sector: { population: 9, economicLean: -4, socialLean: -1, turnout: 73 },
      moderate_centrists: { population: 8, economicLean: 0, socialLean: -1, turnout: 72 },
      populist_right: { population: 2, economicLean: 0, socialLean: 5, turnout: 58 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 5, economicLean: 3, socialLean: 2, turnout: 74 },
      new_britons: { population: 7, economicLean: -3, socialLean: 1, turnout: 53 },
    },
  },
  {
    stateId: "NEE",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 38, economicLean: -4, socialLean: 2, turnout: 72 },
      urban_progressives: { population: 4, economicLean: -4, socialLean: -2, turnout: 72 },
      suburban_homeowners: { population: 6, economicLean: 2, socialLean: 2, turnout: 76 },
      young_renters: { population: 8, economicLean: -2, socialLean: -2, turnout: 61 },
      rural_traditionalists: { population: 7, economicLean: 3, socialLean: 4, turnout: 77 },
      retirees: { population: 10, economicLean: -1, socialLean: 3, turnout: 79 },
      public_sector: { population: 12, economicLean: -4, socialLean: -1, turnout: 73 },
      moderate_centrists: { population: 7, economicLean: 0, socialLean: -1, turnout: 71 },
      populist_right: { population: 1, economicLean: 0, socialLean: 5, turnout: 56 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 5, economicLean: 3, socialLean: 2, turnout: 74 },
      new_britons: { population: 1, economicLean: -3, socialLean: 1, turnout: 50 },
    },
  },
  {
    stateId: "SCO",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 28, economicLean: -4, socialLean: 1, turnout: 74 },
      urban_progressives: { population: 6, economicLean: -4, socialLean: -2, turnout: 74 },
      suburban_homeowners: { population: 7, economicLean: 2, socialLean: 2, turnout: 76 },
      young_renters: { population: 10, economicLean: -2, socialLean: -2, turnout: 64 },
      rural_traditionalists: { population: 11, economicLean: 3, socialLean: 4, turnout: 76 },
      retirees: { population: 10, economicLean: 0, socialLean: 3, turnout: 79 },
      public_sector: { population: 11, economicLean: -4, socialLean: -1, turnout: 74 },
      moderate_centrists: { population: 8, economicLean: 0, socialLean: -1, turnout: 72 },
      populist_right: { population: 1, economicLean: 1, socialLean: 4, turnout: 56 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 5, economicLean: 3, socialLean: 2, turnout: 74 },
      new_britons: { population: 2, economicLean: -3, socialLean: 1, turnout: 50 },
    },
  },
  {
    stateId: "WAL",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 30, economicLean: -4, socialLean: 1, turnout: 74 },
      urban_progressives: { population: 4, economicLean: -4, socialLean: -2, turnout: 72 },
      suburban_homeowners: { population: 6, economicLean: 2, socialLean: 2, turnout: 76 },
      young_renters: { population: 7, economicLean: -2, socialLean: -2, turnout: 62 },
      rural_traditionalists: { population: 15, economicLean: 2, socialLean: 4, turnout: 78 },
      retirees: { population: 10, economicLean: 0, socialLean: 3, turnout: 79 },
      public_sector: { population: 15, economicLean: -4, socialLean: -1, turnout: 74 },
      moderate_centrists: { population: 5, economicLean: 0, socialLean: -1, turnout: 71 },
      populist_right: { population: 1, economicLean: 0, socialLean: 5, turnout: 56 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 60 },
      small_business: { population: 5, economicLean: 3, socialLean: 2, turnout: 74 },
      new_britons: { population: 1, economicLean: -3, socialLean: 1, turnout: 48 },
    },
  },
  {
    stateId: "NIR",
    categoryWeights: {"uk_voterGroups":100},
    groups: {
      post_industrial_workers: { population: 22, economicLean: -3, socialLean: 3, turnout: 70 },
      urban_progressives: { population: 4, economicLean: -3, socialLean: -2, turnout: 66 },
      suburban_homeowners: { population: 4, economicLean: 2, socialLean: 3, turnout: 70 },
      young_renters: { population: 8, economicLean: -2, socialLean: 0, turnout: 60 },
      rural_traditionalists: { population: 12, economicLean: 2, socialLean: 5, turnout: 74 },
      retirees: { population: 7, economicLean: 0, socialLean: 4, turnout: 76 },
      public_sector: { population: 9, economicLean: -3, socialLean: 0, turnout: 70 },
      moderate_centrists: { population: 6, economicLean: 0, socialLean: -1, turnout: 66 },
      populist_right: { population: 24, economicLean: 1, socialLean: 5, turnout: 76 },
      green_activists: { population: 1, economicLean: -4, socialLean: -4, turnout: 58 },
      small_business: { population: 2, economicLean: 3, socialLean: 3, turnout: 70 },
      new_britons: { population: 1, economicLean: -3, socialLean: 1, turnout: 46 },
    },
  },
];
