import type { StateDemographicsSeed } from "./usStateDemographics1953.js";
/**
 * US state demographics for 2019. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/stateCensusData.ts (mainline's 2019-default census bundle)
 * - src/lib/seeds/demographicCategories.ts ERA_COMPOSITIONS["2019"], ERA_TURNOUT_RATES["2019"]
 * - src/lib/seeds/stateDemographicsPure.ts
 *
 * Derived by mainline's own Layer-1 pipeline (stateDemographics.ts generateStateDemographics via the
 * generateStateDemographicsForTest seam) with that era's ERA_COMPOSITIONS / ERA_TURNOUT_RATES, legacy
 * positions path (layer1Positions off, no STATE_POSITION_OVERRIDES folded) — the same choice as
 * usStateDemographics1953.ts. DC excluded. Populations sum to 100 per state.
 */
export const US_STATE_DEMOGRAPHICS_2019: StateDemographicsSeed[] = [
  {
    stateId: "AK",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.04, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 10.81, economicLean: 4.3, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.83, economicLean: 4.7, socialLean: 4.9, turnout: 65 },
      union_trades: { population: 7.65, economicLean: -2.6, socialLean: -0.1, turnout: 52 },
      soccer_moms: { population: 14.95, economicLean: -0.4, socialLean: 0.1, turnout: 59 },
      college_liberals: { population: 6.39, economicLean: -3.9, socialLean: -4.4, turnout: 66 },
      small_business: { population: 10.46, economicLean: 4.2, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 7.09, economicLean: -2.4, socialLean: -2.4, turnout: 65 },
      retirees: { population: 8.2, economicLean: 1.9, socialLean: 2.9, turnout: 70 },
      libertarians: { population: 7.87, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 2.36, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.36, economicLean: -2.4, socialLean: -3.9, turnout: 69 },
    },
  },
  {
    stateId: "AL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.42, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 20.17, economicLean: 5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.95, economicLean: 5, socialLean: 5, turnout: 65 },
      union_trades: { population: 9.95, economicLean: -2.3, socialLean: 1, turnout: 52 },
      soccer_moms: { population: 12.78, economicLean: 1, socialLean: 1.5, turnout: 59 },
      college_liberals: { population: 4.82, economicLean: -2.5, socialLean: -3, turnout: 66 },
      small_business: { population: 7.94, economicLean: 4, socialLean: 2.7, turnout: 68 },
      public_sector: { population: 6.22, economicLean: -1, socialLean: -1, turnout: 65 },
      retirees: { population: 8.68, economicLean: 2.7, socialLean: 3.7, turnout: 71 },
      libertarians: { population: 4.69, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.7, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 4.69, economicLean: -1, socialLean: -2.5, turnout: 68 },
    },
  },
  {
    stateId: "AR",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.39, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 19.46, economicLean: 5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.98, economicLean: 5, socialLean: 5, turnout: 65 },
      union_trades: { population: 9.42, economicLean: -2.3, socialLean: 0.9, turnout: 52 },
      soccer_moms: { population: 13.16, economicLean: 0.9, socialLean: 1.4, turnout: 59 },
      college_liberals: { population: 4.86, economicLean: -2.6, socialLean: -3.1, turnout: 66 },
      small_business: { population: 7.92, economicLean: 4, socialLean: 2.6, turnout: 68 },
      public_sector: { population: 5.81, economicLean: -1.1, socialLean: -1.1, turnout: 65 },
      retirees: { population: 8.98, economicLean: 2.6, socialLean: 3.6, turnout: 71 },
      libertarians: { population: 5.29, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.03, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 4.69, economicLean: -1.1, socialLean: -2.6, turnout: 68 },
    },
  },
  {
    stateId: "AZ",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.58, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 9.32, economicLean: 4, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 9.89, economicLean: 3.8, socialLean: 3.8, turnout: 65 },
      union_trades: { population: 8.37, economicLean: -3.2, socialLean: -0.6, turnout: 52 },
      soccer_moms: { population: 14.28, economicLean: -1.1, socialLean: -0.6, turnout: 59 },
      college_liberals: { population: 7.33, economicLean: -4.6, socialLean: -5, turnout: 66 },
      small_business: { population: 9.59, economicLean: 3.9, socialLean: 1.9, turnout: 68 },
      public_sector: { population: 7.69, economicLean: -3.1, socialLean: -3.1, turnout: 65 },
      retirees: { population: 9.13, economicLean: 0.8, socialLean: 1.8, turnout: 71 },
      libertarians: { population: 6.63, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 4.31, economicLean: -3, socialLean: -2, turnout: 41 },
      secular_professionals: { population: 6.89, economicLean: -3.1, socialLean: -4.6, turnout: 69 },
    },
  },
  {
    stateId: "CA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.94, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 7.09, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 7.49, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 7.97, economicLean: -3.9, socialLean: -1.4, turnout: 52 },
      soccer_moms: { population: 14.12, economicLean: -2.2, socialLean: -1.7, turnout: 59 },
      college_liberals: { population: 10, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 8.92, economicLean: 3.3, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.76, economicLean: -4.2, socialLean: -4.2, turnout: 65 },
      retirees: { population: 8.3, economicLean: -0.5, socialLean: 0.5, turnout: 70 },
      libertarians: { population: 4.39, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 6.3, economicLean: -3, socialLean: -2, turnout: 42 },
      secular_professionals: { population: 8.7, economicLean: -4.2, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "CO",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.46, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 8.66, economicLean: 3.5, socialLean: 4.6, turnout: 75 },
      rural_traditionalists: { population: 9.25, economicLean: 3, socialLean: 2.7, turnout: 65 },
      union_trades: { population: 7.19, economicLean: -3.6, socialLean: -1.2, turnout: 52 },
      soccer_moms: { population: 14.34, economicLean: -2, socialLean: -1.5, turnout: 59 },
      college_liberals: { population: 9.75, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 10.11, economicLean: 3.6, socialLean: 1.5, turnout: 68 },
      public_sector: { population: 8.43, economicLean: -4, socialLean: -4, turnout: 65 },
      retirees: { population: 8.43, economicLean: -0.3, socialLean: 0.7, turnout: 70 },
      libertarians: { population: 6.81, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 2.73, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 8.85, economicLean: -4, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "CT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.5, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 7.56, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 8.5, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 8.13, economicLean: -4, socialLean: -1.4, turnout: 52 },
      soccer_moms: { population: 14.21, economicLean: -2.2, socialLean: -1.7, turnout: 59 },
      college_liberals: { population: 9.77, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 10.32, economicLean: 3.3, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.21, economicLean: -4.2, socialLean: -4.2, turnout: 65 },
      retirees: { population: 9.83, economicLean: -0.5, socialLean: 0.5, turnout: 72 },
      libertarians: { population: 5.52, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 2.27, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 9.19, economicLean: -4.2, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "DE",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.13, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.41, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 8.71, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 9.49, economicLean: -3.9, socialLean: -1.4, turnout: 52 },
      soccer_moms: { population: 14.27, economicLean: -2.2, socialLean: -1.7, turnout: 59 },
      college_liberals: { population: 9.66, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.6, economicLean: 3.3, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.51, economicLean: -4.2, socialLean: -4.2, turnout: 65 },
      retirees: { population: 9.74, economicLean: -0.5, socialLean: 0.5, turnout: 72 },
      libertarians: { population: 5.4, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.49, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 8.59, economicLean: -4.2, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "FL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.23, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 11.7, economicLean: 4.2, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.65, economicLean: 4.1, socialLean: 4.2, turnout: 65 },
      union_trades: { population: 8.94, economicLean: -3, socialLean: -0.3, turnout: 52 },
      soccer_moms: { population: 13.25, economicLean: -0.8, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 7.08, economicLean: -4.3, socialLean: -4.8, turnout: 66 },
      small_business: { population: 9.3, economicLean: 3.8, socialLean: 2.1, turnout: 68 },
      public_sector: { population: 7.64, economicLean: -2.8, socialLean: -2.8, turnout: 65 },
      retirees: { population: 9.53, economicLean: 1.2, socialLean: 2.2, turnout: 72 },
      libertarians: { population: 5.62, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 3.23, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 6.82, economicLean: -2.8, socialLean: -4.3, turnout: 69 },
    },
  },
  {
    stateId: "GA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.8, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 11.13, economicLean: 4.3, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 9.98, economicLean: 3.9, socialLean: 3.9, turnout: 65 },
      union_trades: { population: 10.43, economicLean: -3.3, socialLean: -0.5, turnout: 52 },
      soccer_moms: { population: 14.41, economicLean: -1, socialLean: -0.5, turnout: 59 },
      college_liberals: { population: 7.3, economicLean: -4.5, socialLean: -5, turnout: 66 },
      small_business: { population: 9, economicLean: 3.6, socialLean: 1.9, turnout: 68 },
      public_sector: { population: 9.03, economicLean: -3, socialLean: -3, turnout: 65 },
      retirees: { population: 8.53, economicLean: 0.9, socialLean: 1.9, turnout: 70 },
      libertarians: { population: 4.99, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.54, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 6.86, economicLean: -3, socialLean: -4.5, turnout: 69 },
    },
  },
  {
    stateId: "HI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 7.17, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 5.95, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 6.88, economicLean: 2.8, socialLean: 2.6, turnout: 65 },
      union_trades: { population: 7.4, economicLean: -3.8, socialLean: -1.3, turnout: 52 },
      soccer_moms: { population: 15.22, economicLean: -2.1, socialLean: -1.6, turnout: 59 },
      college_liberals: { population: 9.88, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.21, economicLean: 3.4, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 10.65, economicLean: -4.1, socialLean: -4.1, turnout: 65 },
      retirees: { population: 8.72, economicLean: -0.5, socialLean: 0.5, turnout: 71 },
      libertarians: { population: 3.38, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 6.61, economicLean: -3, socialLean: -2, turnout: 41 },
      secular_professionals: { population: 8.93, economicLean: -4.1, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "IA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.57, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 12.38, economicLean: 4.3, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.99, economicLean: 4.4, socialLean: 4.5, turnout: 65 },
      union_trades: { population: 8.08, economicLean: -2.8, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 14.44, economicLean: -0.6, socialLean: -0.1, turnout: 59 },
      college_liberals: { population: 6.98, economicLean: -4.1, socialLean: -4.6, turnout: 66 },
      small_business: { population: 9.79, economicLean: 4, socialLean: 2.2, turnout: 68 },
      public_sector: { population: 6.56, economicLean: -2.6, socialLean: -2.6, turnout: 65 },
      retirees: { population: 9.95, economicLean: 1.5, socialLean: 2.5, turnout: 72 },
      libertarians: { population: 6.73, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.91, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.62, economicLean: -2.6, socialLean: -4.1, turnout: 68 },
    },
  },
  {
    stateId: "ID",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.89, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 12.13, economicLean: 4.4, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.54, economicLean: 4.8, socialLean: 5, turnout: 65 },
      union_trades: { population: 8.01, economicLean: -2.6, socialLean: 0, turnout: 52 },
      soccer_moms: { population: 14.47, economicLean: -0.3, socialLean: 0.2, turnout: 59 },
      college_liberals: { population: 6.11, economicLean: -3.8, socialLean: -4.3, turnout: 66 },
      small_business: { population: 9.85, economicLean: 4.3, socialLean: 2.4, turnout: 68 },
      public_sector: { population: 6.05, economicLean: -2.3, socialLean: -2.3, turnout: 65 },
      retirees: { population: 9.22, economicLean: 2, socialLean: 3, turnout: 71 },
      libertarians: { population: 8.26, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.56, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 5.91, economicLean: -2.3, socialLean: -3.8, turnout: 68 },
    },
  },
  {
    stateId: "IL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.12, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.8, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 8.55, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 8.76, economicLean: -3.9, socialLean: -1.3, turnout: 52 },
      soccer_moms: { population: 14.36, economicLean: -2.1, socialLean: -1.6, turnout: 59 },
      college_liberals: { population: 9.65, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.55, economicLean: 3.3, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.37, economicLean: -4.1, socialLean: -4.1, turnout: 65 },
      retirees: { population: 9.32, economicLean: -0.5, socialLean: 0.5, turnout: 71 },
      libertarians: { population: 5.35, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 2.51, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 8.66, economicLean: -4.1, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "IN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.12, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 13.12, economicLean: 4.5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.74, economicLean: 4.4, socialLean: 4.6, turnout: 65 },
      union_trades: { population: 8.99, economicLean: -2.9, socialLean: -0.1, turnout: 52 },
      soccer_moms: { population: 14.46, economicLean: -0.4, socialLean: 0.1, turnout: 59 },
      college_liberals: { population: 6.29, economicLean: -3.9, socialLean: -4.4, turnout: 66 },
      small_business: { population: 9.44, economicLean: 4, socialLean: 2.2, turnout: 68 },
      public_sector: { population: 6.61, economicLean: -2.4, socialLean: -2.4, turnout: 65 },
      retirees: { population: 9.55, economicLean: 1.6, socialLean: 2.6, turnout: 71 },
      libertarians: { population: 6.58, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.99, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.12, economicLean: -2.4, socialLean: -3.9, turnout: 68 },
    },
  },
  {
    stateId: "KS",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.91, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 13.74, economicLean: 4.6, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.39, economicLean: 4.5, socialLean: 4.7, turnout: 65 },
      union_trades: { population: 8.13, economicLean: -2.8, socialLean: 0.1, turnout: 52 },
      soccer_moms: { population: 14.3, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.4, economicLean: -3.7, socialLean: -4.2, turnout: 66 },
      small_business: { population: 9.6, economicLean: 4, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 6.7, economicLean: -2.2, socialLean: -2.2, turnout: 65 },
      retirees: { population: 9.15, economicLean: 1.7, socialLean: 2.7, turnout: 71 },
      libertarians: { population: 6.75, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.66, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 6.26, economicLean: -2.2, socialLean: -3.7, turnout: 69 },
    },
  },
  {
    stateId: "KY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.23, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 15.47, economicLean: 4.8, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.34, economicLean: 4.7, socialLean: 4.9, turnout: 65 },
      union_trades: { population: 9.12, economicLean: -2.7, socialLean: 0.3, turnout: 52 },
      soccer_moms: { population: 13.85, economicLean: 0, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 5.91, economicLean: -3.5, socialLean: -4, turnout: 66 },
      small_business: { population: 9.04, economicLean: 4, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 5.98, economicLean: -2, socialLean: -2, turnout: 65 },
      retirees: { population: 9.53, economicLean: 1.9, socialLean: 2.9, turnout: 71 },
      libertarians: { population: 6.27, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.63, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.62, economicLean: -2, socialLean: -3.5, turnout: 68 },
    },
  },
  {
    stateId: "LA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 7.13, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 15.99, economicLean: 4.9, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.01, economicLean: 4.5, socialLean: 4.6, turnout: 65 },
      union_trades: { population: 10.98, economicLean: -2.9, socialLean: 0.2, turnout: 52 },
      soccer_moms: { population: 13.64, economicLean: 0, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 5.66, economicLean: -3.5, socialLean: -4, turnout: 66 },
      small_business: { population: 8.3, economicLean: 3.9, socialLean: 2.2, turnout: 68 },
      public_sector: { population: 7.42, economicLean: -2, socialLean: -2, turnout: 65 },
      retirees: { population: 8.63, economicLean: 1.6, socialLean: 2.6, turnout: 70 },
      libertarians: { population: 5.08, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.87, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.3, economicLean: -2, socialLean: -3.5, turnout: 68 },
    },
  },
  {
    stateId: "MA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.39, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.38, economicLean: 3.5, socialLean: 4.6, turnout: 75 },
      rural_traditionalists: { population: 8.72, economicLean: 2.7, socialLean: 2.4, turnout: 65 },
      union_trades: { population: 7.75, economicLean: -3.9, socialLean: -1.5, turnout: 52 },
      soccer_moms: { population: 14.14, economicLean: -2.3, socialLean: -1.8, turnout: 59 },
      college_liberals: { population: 10.3, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 10.54, economicLean: 3.2, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.09, economicLean: -4.3, socialLean: -4.3, turnout: 65 },
      retirees: { population: 9.56, economicLean: -0.6, socialLean: 0.4, turnout: 71 },
      libertarians: { population: 5.34, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.88, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 9.91, economicLean: -4.3, socialLean: -5, turnout: 70 },
    },
  },
  {
    stateId: "MD",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.88, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.7, economicLean: 3.7, socialLean: 4.8, turnout: 75 },
      rural_traditionalists: { population: 7.82, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 9.26, economicLean: -4, socialLean: -1.3, turnout: 52 },
      soccer_moms: { population: 14.37, economicLean: -2.1, socialLean: -1.6, turnout: 59 },
      college_liberals: { population: 9.96, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.84, economicLean: 3.2, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 10.7, economicLean: -4.1, socialLean: -4.1, turnout: 65 },
      retirees: { population: 8.71, economicLean: -0.5, socialLean: 0.5, turnout: 70 },
      libertarians: { population: 4.5, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.9, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 9.36, economicLean: -4.1, socialLean: -5, turnout: 70 },
    },
  },
  {
    stateId: "ME",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.43, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 9.06, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 10.46, economicLean: 3.1, socialLean: 2.9, turnout: 65 },
      union_trades: { population: 8.38, economicLean: -3.6, socialLean: -1.2, turnout: 52 },
      soccer_moms: { population: 14.24, economicLean: -1.9, socialLean: -1.4, turnout: 59 },
      college_liberals: { population: 9, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.91, economicLean: 3.6, socialLean: 1.6, turnout: 68 },
      public_sector: { population: 7.32, economicLean: -3.9, socialLean: -3.9, turnout: 65 },
      retirees: { population: 10.79, economicLean: -0.1, socialLean: 0.9, turnout: 73 },
      libertarians: { population: 7.02, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.36, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 8.02, economicLean: -3.9, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "MI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.07, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 10.57, economicLean: 4.1, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.81, economicLean: 3.8, socialLean: 3.8, turnout: 65 },
      union_trades: { population: 9.15, economicLean: -3.3, socialLean: -0.6, turnout: 52 },
      soccer_moms: { population: 14.27, economicLean: -1.2, socialLean: -0.7, turnout: 59 },
      college_liberals: { population: 7.66, economicLean: -4.7, socialLean: -5, turnout: 66 },
      small_business: { population: 9.72, economicLean: 3.7, socialLean: 1.9, turnout: 68 },
      public_sector: { population: 7.6, economicLean: -3.2, socialLean: -3.2, turnout: 65 },
      retirees: { population: 9.83, economicLean: 0.8, socialLean: 1.8, turnout: 71 },
      libertarians: { population: 6.17, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.95, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 7.22, economicLean: -3.2, socialLean: -4.7, turnout: 69 },
    },
  },
  {
    stateId: "MN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.38, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 9.4, economicLean: 3.8, socialLean: 4.8, turnout: 75 },
      rural_traditionalists: { population: 10.06, economicLean: 3.3, socialLean: 3.2, turnout: 65 },
      union_trades: { population: 7.87, economicLean: -3.6, socialLean: -1, turnout: 52 },
      soccer_moms: { population: 15, economicLean: -1.7, socialLean: -1.2, turnout: 59 },
      college_liberals: { population: 8.99, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.99, economicLean: 3.6, socialLean: 1.7, turnout: 68 },
      public_sector: { population: 8.19, economicLean: -3.7, socialLean: -3.7, turnout: 65 },
      retirees: { population: 9.48, economicLean: 0.1, socialLean: 1.2, turnout: 71 },
      libertarians: { population: 6.29, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.13, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 8.22, economicLean: -3.7, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "MO",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.98, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 13.84, economicLean: 4.6, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.69, economicLean: 4.5, socialLean: 4.6, turnout: 65 },
      union_trades: { population: 8.93, economicLean: -2.8, socialLean: 0, turnout: 52 },
      soccer_moms: { population: 14.21, economicLean: -0.3, socialLean: 0.2, turnout: 59 },
      college_liberals: { population: 6.34, economicLean: -3.8, socialLean: -4.3, turnout: 66 },
      small_business: { population: 9.35, economicLean: 4, socialLean: 2.2, turnout: 68 },
      public_sector: { population: 6.71, economicLean: -2.3, socialLean: -2.3, turnout: 65 },
      retirees: { population: 9.63, economicLean: 1.6, socialLean: 2.6, turnout: 71 },
      libertarians: { population: 6.52, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.75, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.06, economicLean: -2.3, socialLean: -3.8, turnout: 68 },
    },
  },
  {
    stateId: "MS",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 7.48, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 17.65, economicLean: 5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.12, economicLean: 4.6, socialLean: 4.8, turnout: 65 },
      union_trades: { population: 11.69, economicLean: -2.8, socialLean: 0.4, turnout: 52 },
      soccer_moms: { population: 13.12, economicLean: 0.2, socialLean: 0.7, turnout: 59 },
      college_liberals: { population: 5.24, economicLean: -3.3, socialLean: -3.8, turnout: 66 },
      small_business: { population: 7.75, economicLean: 3.9, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 7.25, economicLean: -1.8, socialLean: -1.8, turnout: 65 },
      retirees: { population: 8.7, economicLean: 1.8, socialLean: 2.8, turnout: 71 },
      libertarians: { population: 4.6, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.51, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 4.9, economicLean: -1.8, socialLean: -3.3, turnout: 68 },
    },
  },
  {
    stateId: "MT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.38, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 11.45, economicLean: 4.2, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.37, economicLean: 4.6, socialLean: 4.8, turnout: 65 },
      union_trades: { population: 7.84, economicLean: -2.7, socialLean: -0.1, turnout: 52 },
      soccer_moms: { population: 14.28, economicLean: -0.5, socialLean: 0, turnout: 59 },
      college_liberals: { population: 6.72, economicLean: -4, socialLean: -4.5, turnout: 66 },
      small_business: { population: 10.16, economicLean: 4.2, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 6.29, economicLean: -2.5, socialLean: -2.5, turnout: 65 },
      retirees: { population: 9.96, economicLean: 1.8, socialLean: 2.8, turnout: 72 },
      libertarians: { population: 8.38, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.83, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.35, economicLean: -2.5, socialLean: -4, turnout: 69 },
    },
  },
  {
    stateId: "NC",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.35, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 11.4, economicLean: 4.3, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.78, economicLean: 4.1, socialLean: 4.1, turnout: 65 },
      union_trades: { population: 9.58, economicLean: -3.1, socialLean: -0.3, turnout: 52 },
      soccer_moms: { population: 14.22, economicLean: -0.8, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 7.13, economicLean: -4.3, socialLean: -4.8, turnout: 66 },
      small_business: { population: 9.39, economicLean: 3.8, socialLean: 2, turnout: 68 },
      public_sector: { population: 8.03, economicLean: -2.8, socialLean: -2.8, turnout: 65 },
      retirees: { population: 9.14, economicLean: 1.1, socialLean: 2.1, turnout: 71 },
      libertarians: { population: 5.71, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.5, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.79, economicLean: -2.8, socialLean: -4.3, turnout: 69 },
    },
  },
  {
    stateId: "ND",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.52, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 13.16, economicLean: 4.5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.29, economicLean: 4.8, socialLean: 5, turnout: 65 },
      union_trades: { population: 7.74, economicLean: -2.6, socialLean: 0.1, turnout: 52 },
      soccer_moms: { population: 14.9, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.32, economicLean: -3.7, socialLean: -4.2, turnout: 66 },
      small_business: { population: 9.92, economicLean: 4.2, socialLean: 2.4, turnout: 68 },
      public_sector: { population: 6.44, economicLean: -2.2, socialLean: -2.2, turnout: 65 },
      retirees: { population: 9.37, economicLean: 2, socialLean: 3, turnout: 71 },
      libertarians: { population: 7.37, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.86, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.1, economicLean: -2.2, socialLean: -3.7, turnout: 68 },
    },
  },
  {
    stateId: "NE",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.75, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 13.07, economicLean: 4.5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.74, economicLean: 4.6, socialLean: 4.8, turnout: 65 },
      union_trades: { population: 8, economicLean: -2.7, socialLean: 0.1, turnout: 52 },
      soccer_moms: { population: 14.67, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.39, economicLean: -3.7, socialLean: -4.2, turnout: 66 },
      small_business: { population: 9.74, economicLean: 4.1, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 6.64, economicLean: -2.2, socialLean: -2.2, turnout: 65 },
      retirees: { population: 9.3, economicLean: 1.8, socialLean: 2.8, turnout: 71 },
      libertarians: { population: 6.91, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.52, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 6.28, economicLean: -2.2, socialLean: -3.7, turnout: 69 },
    },
  },
  {
    stateId: "NH",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 4.82, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 8.49, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 10.21, economicLean: 3.3, socialLean: 3.1, turnout: 65 },
      union_trades: { population: 7.43, economicLean: -3.6, socialLean: -1.1, turnout: 52 },
      soccer_moms: { population: 14.4, economicLean: -1.8, socialLean: -1.3, turnout: 59 },
      college_liberals: { population: 8.97, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 11.15, economicLean: 3.7, socialLean: 1.6, turnout: 68 },
      public_sector: { population: 7.54, economicLean: -3.8, socialLean: -3.8, turnout: 65 },
      retirees: { population: 10.21, economicLean: 0.1, socialLean: 1.1, turnout: 72 },
      libertarians: { population: 7.59, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.65, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 8.54, economicLean: -3.8, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "NJ",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.74, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 6.99, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 8.04, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 8.14, economicLean: -3.9, socialLean: -1.4, turnout: 52 },
      soccer_moms: { population: 14.02, economicLean: -2.2, socialLean: -1.7, turnout: 59 },
      college_liberals: { population: 9.89, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 10.42, economicLean: 3.3, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.73, economicLean: -4.2, socialLean: -4.2, turnout: 65 },
      retirees: { population: 9.22, economicLean: -0.5, socialLean: 0.5, turnout: 71 },
      libertarians: { population: 5.08, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 3.23, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 9.52, economicLean: -4.2, socialLean: -5, turnout: 70 },
    },
  },
  {
    stateId: "NM",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 7.25, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.98, economicLean: 3.7, socialLean: 4.8, turnout: 75 },
      rural_traditionalists: { population: 7.86, economicLean: 2.8, socialLean: 2.6, turnout: 65 },
      union_trades: { population: 8.28, economicLean: -3.8, socialLean: -1.2, turnout: 52 },
      soccer_moms: { population: 13.62, economicLean: -2, socialLean: -1.5, turnout: 59 },
      college_liberals: { population: 9.33, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 8.44, economicLean: 3.4, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.11, economicLean: -4, socialLean: -4, turnout: 65 },
      retirees: { population: 8.69, economicLean: -0.5, socialLean: 0.5, turnout: 71 },
      libertarians: { population: 4.74, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 6.77, economicLean: -3, socialLean: -2, turnout: 41 },
      secular_professionals: { population: 7.92, economicLean: -4, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "NV",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.92, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 8.69, economicLean: 4.1, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.04, economicLean: 4, socialLean: 4.1, turnout: 65 },
      union_trades: { population: 8.95, economicLean: -3.1, socialLean: -0.5, turnout: 52 },
      soccer_moms: { population: 14.58, economicLean: -1, socialLean: -0.5, turnout: 59 },
      college_liberals: { population: 6.72, economicLean: -4.5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.81, economicLean: 4, socialLean: 2, turnout: 68 },
      public_sector: { population: 7.78, economicLean: -3, socialLean: -3, turnout: 65 },
      retirees: { population: 8.78, economicLean: 1.1, socialLean: 2.1, turnout: 70 },
      libertarians: { population: 6.91, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 4.44, economicLean: -3, socialLean: -2, turnout: 41 },
      secular_professionals: { population: 6.38, economicLean: -3, socialLean: -4.5, turnout: 68 },
    },
  },
  {
    stateId: "NY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.36, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.51, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 8.36, economicLean: 2.9, socialLean: 2.6, turnout: 65 },
      union_trades: { population: 9.04, economicLean: -3.9, socialLean: -1.3, turnout: 52 },
      soccer_moms: { population: 13.97, economicLean: -2.1, socialLean: -1.6, turnout: 59 },
      college_liberals: { population: 9.73, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.64, economicLean: 3.3, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.55, economicLean: -4.1, socialLean: -4.1, turnout: 65 },
      retirees: { population: 9.04, economicLean: -0.4, socialLean: 0.6, turnout: 71 },
      libertarians: { population: 4.72, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 2.94, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 9.14, economicLean: -4.1, socialLean: -5, turnout: 70 },
    },
  },
  {
    stateId: "OH",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.97, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 12.22, economicLean: 4.3, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.9, economicLean: 4.4, socialLean: 4.5, turnout: 65 },
      union_trades: { population: 9.05, economicLean: -2.9, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 14.31, economicLean: -0.6, socialLean: -0.1, turnout: 59 },
      college_liberals: { population: 6.8, economicLean: -4.1, socialLean: -4.6, turnout: 66 },
      small_business: { population: 9.47, economicLean: 3.9, socialLean: 2.2, turnout: 68 },
      public_sector: { population: 6.92, economicLean: -2.6, socialLean: -2.6, turnout: 65 },
      retirees: { population: 9.74, economicLean: 1.5, socialLean: 2.5, turnout: 71 },
      libertarians: { population: 6.54, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.7, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 6.38, economicLean: -2.6, socialLean: -4.1, turnout: 68 },
    },
  },
  {
    stateId: "OK",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.56, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 15.96, economicLean: 4.9, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.67, economicLean: 4.7, socialLean: 4.9, turnout: 65 },
      union_trades: { population: 8.75, economicLean: -2.7, socialLean: 0.3, turnout: 52 },
      soccer_moms: { population: 13.83, economicLean: 0.1, socialLean: 0.6, turnout: 59 },
      college_liberals: { population: 5.62, economicLean: -3.4, socialLean: -3.9, turnout: 66 },
      small_business: { population: 8.86, economicLean: 4, socialLean: 2.4, turnout: 68 },
      public_sector: { population: 6.37, economicLean: -1.9, socialLean: -1.9, turnout: 65 },
      retirees: { population: 8.83, economicLean: 1.9, socialLean: 2.9, turnout: 71 },
      libertarians: { population: 6.01, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.99, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.56, economicLean: -1.9, socialLean: -3.4, turnout: 68 },
    },
  },
  {
    stateId: "OR",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.74, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.87, economicLean: 3.4, socialLean: 4.6, turnout: 75 },
      rural_traditionalists: { population: 9.16, economicLean: 2.7, socialLean: 2.4, turnout: 65 },
      union_trades: { population: 7.83, economicLean: -3.9, socialLean: -1.5, turnout: 52 },
      soccer_moms: { population: 14.47, economicLean: -2.3, socialLean: -1.8, turnout: 59 },
      college_liberals: { population: 9.87, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.85, economicLean: 3.4, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 8.37, economicLean: -4.3, socialLean: -4.3, turnout: 65 },
      retirees: { population: 9.37, economicLean: -0.6, socialLean: 0.4, turnout: 71 },
      libertarians: { population: 6.83, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.98, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 8.67, economicLean: -4.3, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "PA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.84, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 10.67, economicLean: 4.2, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.76, economicLean: 3.9, socialLean: 3.9, turnout: 65 },
      union_trades: { population: 8.9, economicLean: -3.2, socialLean: -0.5, turnout: 52 },
      soccer_moms: { population: 14.47, economicLean: -1, socialLean: -0.5, turnout: 59 },
      college_liberals: { population: 7.37, economicLean: -4.5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.79, economicLean: 3.8, socialLean: 2, turnout: 68 },
      public_sector: { population: 7.53, economicLean: -3, socialLean: -3, turnout: 65 },
      retirees: { population: 10.24, economicLean: 0.9, socialLean: 1.9, turnout: 72 },
      libertarians: { population: 6.25, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.15, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 7.04, economicLean: -3, socialLean: -4.5, turnout: 69 },
    },
  },
  {
    stateId: "RI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.97, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.44, economicLean: 3.5, socialLean: 4.6, turnout: 75 },
      rural_traditionalists: { population: 8.91, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 8.42, economicLean: -3.9, socialLean: -1.4, turnout: 52 },
      soccer_moms: { population: 14.54, economicLean: -2.2, socialLean: -1.7, turnout: 59 },
      college_liberals: { population: 9.77, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.86, economicLean: 3.3, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 8.77, economicLean: -4.2, socialLean: -4.2, turnout: 65 },
      retirees: { population: 9.64, economicLean: -0.5, socialLean: 0.5, turnout: 71 },
      libertarians: { population: 5.76, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 2.12, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 8.81, economicLean: -4.2, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "SC",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.46, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 14.38, economicLean: 4.7, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.22, economicLean: 4.5, socialLean: 4.7, turnout: 65 },
      union_trades: { population: 10.06, economicLean: -2.8, socialLean: 0.1, turnout: 52 },
      soccer_moms: { population: 13.89, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.01, economicLean: -3.7, socialLean: -4.2, turnout: 66 },
      small_business: { population: 8.97, economicLean: 3.9, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 7.48, economicLean: -2.2, socialLean: -2.2, turnout: 65 },
      retirees: { population: 9.2, economicLean: 1.7, socialLean: 2.7, turnout: 71 },
      libertarians: { population: 5.66, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.91, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.76, economicLean: -2.2, socialLean: -3.7, turnout: 68 },
    },
  },
  {
    stateId: "SD",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.74, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 13.14, economicLean: 4.5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.35, economicLean: 4.8, socialLean: 5, turnout: 65 },
      union_trades: { population: 8.08, economicLean: -2.6, socialLean: 0.1, turnout: 52 },
      soccer_moms: { population: 14.55, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.2, economicLean: -3.7, socialLean: -4.2, turnout: 66 },
      small_business: { population: 9.7, economicLean: 4.2, socialLean: 2.4, turnout: 68 },
      public_sector: { population: 6.25, economicLean: -2.2, socialLean: -2.2, turnout: 65 },
      retirees: { population: 9.73, economicLean: 2, socialLean: 3, turnout: 71 },
      libertarians: { population: 7.34, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.92, economicLean: -2.2, socialLean: -3.7, turnout: 68 },
    },
  },
  {
    stateId: "TN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.19, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 15.32, economicLean: 4.8, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 11.59, economicLean: 4.6, socialLean: 4.8, turnout: 65 },
      union_trades: { population: 9.32, economicLean: -2.8, socialLean: 0.2, turnout: 52 },
      soccer_moms: { population: 13.95, economicLean: 0, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 6, economicLean: -3.5, socialLean: -4, turnout: 66 },
      small_business: { population: 9.12, economicLean: 4, socialLean: 2.3, turnout: 68 },
      public_sector: { population: 6.73, economicLean: -2, socialLean: -2, turnout: 65 },
      retirees: { population: 9.17, economicLean: 1.8, socialLean: 2.8, turnout: 71 },
      libertarians: { population: 5.95, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.87, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.79, economicLean: -2, socialLean: -3.5, turnout: 68 },
    },
  },
  {
    stateId: "TX",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 7.07, economicLean: -4, socialLean: -4, turnout: 42 },
      evangelicals: { population: 12.33, economicLean: 4.5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.02, economicLean: 4.3, socialLean: 4.4, turnout: 65 },
      union_trades: { population: 8.77, economicLean: -3, socialLean: -0.1, turnout: 52 },
      soccer_moms: { population: 13.96, economicLean: -0.5, socialLean: 0, turnout: 59 },
      college_liberals: { population: 6.1, economicLean: -4, socialLean: -4.5, turnout: 66 },
      small_business: { population: 8.95, economicLean: 4, socialLean: 2.1, turnout: 68 },
      public_sector: { population: 7.78, economicLean: -2.5, socialLean: -2.5, turnout: 65 },
      retirees: { population: 7.93, economicLean: 1.4, socialLean: 2.4, turnout: 70 },
      libertarians: { population: 6, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 5.23, economicLean: -3, socialLean: -2, turnout: 41 },
      secular_professionals: { population: 5.85, economicLean: -2.5, socialLean: -4, turnout: 68 },
    },
  },
  {
    stateId: "UT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.53, economicLean: -4, socialLean: -4, turnout: 40 },
      evangelicals: { population: 17.51, economicLean: 5, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.36, economicLean: 4.4, socialLean: 4.5, turnout: 65 },
      union_trades: { population: 7.07, economicLean: -2.7, socialLean: 0.4, turnout: 52 },
      soccer_moms: { population: 14.66, economicLean: 0.2, socialLean: 0.7, turnout: 59 },
      college_liberals: { population: 6.16, economicLean: -3.3, socialLean: -3.8, turnout: 66 },
      small_business: { population: 9.52, economicLean: 4.1, socialLean: 2.2, turnout: 68 },
      public_sector: { population: 6.42, economicLean: -1.8, socialLean: -1.8, turnout: 65 },
      retirees: { population: 8.2, economicLean: 1.5, socialLean: 2.5, turnout: 70 },
      libertarians: { population: 6.64, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.81, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 6.14, economicLean: -1.8, socialLean: -3.3, turnout: 69 },
    },
  },
  {
    stateId: "VA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.42, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 8.76, economicLean: 3.6, socialLean: 4.7, turnout: 75 },
      rural_traditionalists: { population: 8.92, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 8.17, economicLean: -4, socialLean: -1.4, turnout: 52 },
      soccer_moms: { population: 13.83, economicLean: -2.2, socialLean: -1.7, turnout: 59 },
      college_liberals: { population: 10.13, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 9.91, economicLean: 3.2, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 9.7, economicLean: -4.2, socialLean: -4.2, turnout: 65 },
      retirees: { population: 8.61, economicLean: -0.5, socialLean: 0.5, turnout: 70 },
      libertarians: { population: 5.47, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.69, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 9.39, economicLean: -4.2, socialLean: -5, turnout: 70 },
    },
  },
  {
    stateId: "VT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.18, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 8.2, economicLean: 3.4, socialLean: 4.5, turnout: 75 },
      rural_traditionalists: { population: 9.87, economicLean: 2.7, socialLean: 2.3, turnout: 65 },
      union_trades: { population: 7.8, economicLean: -3.9, socialLean: -1.5, turnout: 52 },
      soccer_moms: { population: 14.28, economicLean: -2.4, socialLean: -1.9, turnout: 59 },
      college_liberals: { population: 10.21, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 10.01, economicLean: 3.3, socialLean: 1.3, turnout: 68 },
      public_sector: { population: 8.07, economicLean: -4.4, socialLean: -4.4, turnout: 65 },
      retirees: { population: 10.25, economicLean: -0.7, socialLean: 0.3, turnout: 72 },
      libertarians: { population: 6.65, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.42, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 9.06, economicLean: -4.4, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "WA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.44, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 7.98, economicLean: 3.5, socialLean: 4.6, turnout: 75 },
      rural_traditionalists: { population: 8.83, economicLean: 2.8, socialLean: 2.5, turnout: 65 },
      union_trades: { population: 7.36, economicLean: -3.9, socialLean: -1.4, turnout: 52 },
      soccer_moms: { population: 14.67, economicLean: -2.2, socialLean: -1.7, turnout: 59 },
      college_liberals: { population: 10.08, economicLean: -5, socialLean: -5, turnout: 66 },
      small_business: { population: 10.09, economicLean: 3.4, socialLean: 1.4, turnout: 68 },
      public_sector: { population: 8.85, economicLean: -4.2, socialLean: -4.2, turnout: 65 },
      retirees: { population: 8.97, economicLean: -0.5, socialLean: 0.5, turnout: 70 },
      libertarians: { population: 6.24, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 2.38, economicLean: -3, socialLean: -2, turnout: 40 },
      secular_professionals: { population: 9.12, economicLean: -4.2, socialLean: -5, turnout: 69 },
    },
  },
  {
    stateId: "WI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.54, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 10.71, economicLean: 4, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 10.71, economicLean: 3.8, socialLean: 3.7, turnout: 65 },
      union_trades: { population: 8.22, economicLean: -3.3, socialLean: -0.6, turnout: 52 },
      soccer_moms: { population: 14.7, economicLean: -1.2, socialLean: -0.7, turnout: 59 },
      college_liberals: { population: 7.87, economicLean: -4.7, socialLean: -5, turnout: 66 },
      small_business: { population: 9.89, economicLean: 3.8, socialLean: 1.9, turnout: 68 },
      public_sector: { population: 7.47, economicLean: -3.2, socialLean: -3.2, turnout: 65 },
      retirees: { population: 9.87, economicLean: 0.7, socialLean: 1.7, turnout: 71 },
      libertarians: { population: 6.68, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.04, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 7.3, economicLean: -3.2, socialLean: -4.7, turnout: 69 },
    },
  },
  {
    stateId: "WV",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 6.36, economicLean: -4, socialLean: -4, turnout: 44 },
      evangelicals: { population: 14.87, economicLean: 4.7, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 13.34, economicLean: 4.9, socialLean: 5, turnout: 65 },
      union_trades: { population: 9.44, economicLean: -2.5, socialLean: 0.3, turnout: 52 },
      soccer_moms: { population: 13.47, economicLean: 0.1, socialLean: 0.6, turnout: 59 },
      college_liberals: { population: 5.65, economicLean: -3.4, socialLean: -3.9, turnout: 66 },
      small_business: { population: 9.05, economicLean: 4, socialLean: 2.5, turnout: 68 },
      public_sector: { population: 5.24, economicLean: -1.9, socialLean: -1.9, turnout: 65 },
      retirees: { population: 10.26, economicLean: 2.2, socialLean: 3.2, turnout: 72 },
      libertarians: { population: 6.53, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 0.31, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.48, economicLean: -1.9, socialLean: -3.4, turnout: 68 },
    },
  },
  {
    stateId: "WY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 5.56, economicLean: -4, socialLean: -4, turnout: 43 },
      evangelicals: { population: 12.11, economicLean: 4.4, socialLean: 5, turnout: 75 },
      rural_traditionalists: { population: 12.95, economicLean: 5, socialLean: 5, turnout: 65 },
      union_trades: { population: 7.84, economicLean: -2.5, socialLean: 0.1, turnout: 52 },
      soccer_moms: { population: 14.64, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 5.9, economicLean: -3.7, socialLean: -4.2, turnout: 66 },
      small_business: { population: 10.09, economicLean: 4.4, socialLean: 2.5, turnout: 68 },
      public_sector: { population: 6, economicLean: -2.2, socialLean: -2.2, turnout: 65 },
      retirees: { population: 9.31, economicLean: 2.3, socialLean: 3.3, turnout: 71 },
      libertarians: { population: 8.6, economicLean: 5, socialLean: 1, turnout: 64 },
      new_immigrants: { population: 1.26, economicLean: -3, socialLean: -2, turnout: 39 },
      secular_professionals: { population: 5.77, economicLean: -2.2, socialLean: -3.7, turnout: 68 },
    },
  },
];
