/**
 * US State Demographics for 1953 — derived from mainline Layer 1 census shares.
 *
 * Sources (no invented numbers):
 * - CENSUS_SHARES_1950 per-state race/education/wealth/age: src/lib/seeds/stateCensusData1953.ts CENSUS_SHARES_1950
 * - Ideology shares per-state: src/lib/seeds/stateCensusData1979.ts stateCensusData1979[].ideology (reused verbatim for 1953 as in mainline stateCensusData1953.ts: ideology: stateCensusData1979[stateId].ideology)
 * - Turnout rates per era: src/lib/seeds/demographicCategories.ts ERA_TURNOUT_RATES["1953"] (race/age/education/wealth/ideology baselines)
 * - Voter group composition weights: src/lib/seeds/demographicCategories.ts ERA_COMPOSITIONS["1953"].voterGroupComposition
 * - Default leans per group: src/lib/seeds/demographicCategories.ts ERA_COMPOSITIONS["1953"].defaultLeans
 * - Default turnouts per group: src/lib/seeds/demographicCategories.ts ERA_COMPOSITIONS["1953"].defaultTurnouts
 * - Derivation: src/lib/seeds/stateDemographicsPure.ts deriveGroupPopulations (turnout-weighted voter share, normalized to 100)
 *
 * State position overrides (STATE_POSITION_OVERRIDES["1953"]) are NOT folded here; leans are era-default. Future work may apply them via deriveGroupLeanFromLayer1.
 * Populations sum to 100 per state (rounded to 2dp, largest bucket absorbs rounding).
 * AK/HI absent (territories in 1953, houseSeats 0); DC excluded (non-state).
 */
export interface StateDemographicsSeed {
  stateId: string;
  categoryWeights: Record<string, number>;
  groups: Record<string, { population: number; economicLean: number; socialLean: number; turnout: number }>;
}

export const US_STATE_DEMOGRAPHICS_1953: StateDemographicsSeed[] = [
  {
    stateId: "AL",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 12.63, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 16.28, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 14.0, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.59, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 15.31, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 3.79, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 7.92, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.23, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.05, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 4.68, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.98, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.54, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "AR",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 12.19, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 15.81, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.84, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.27, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 14.92, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 3.94, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.18, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.11, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.92, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.43, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.99, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.4, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "AZ",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 11.42, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.52, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.03, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.05, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.82, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.77, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.99, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.0, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.64, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.66, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.84, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.26, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "CA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.6, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.56, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 9.97, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.35, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.39, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.77, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.62, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 4.14, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.09, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.58, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.86, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 4.07, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "CO",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.65, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.37, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.09, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.53, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.09, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.84, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.35, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.83, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.76, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.7, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.84, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.95, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "CT",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 9.29, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 8.81, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 9.88, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.35, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.15, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 7.18, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 11.77, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 4.27, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.38, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.34, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.02, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 4.56, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "DE",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.69, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.82, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 10.47, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.69, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.01, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.3, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.42, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.46, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.86, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.06, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.61, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 3.61, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "FL",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.94, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 11.89, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.04, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.35, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.13, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.98, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.45, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.28, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 13.12, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.22, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.18, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.42, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "GA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 12.66, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 15.73, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.0, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.7, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 15.44, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.1, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.44, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.54, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.56, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.16, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.77, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.9, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "IA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.31, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 12.01, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.27, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.5, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.31, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.46, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.74, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.08, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.75, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.82, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.63, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.12, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "ID",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.62, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 13.06, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 14.86, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 5.84, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.7, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.59, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.58, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.17, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.22, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 8.1, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.88, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.38, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "IL",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.26, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.28, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 10.57, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.32, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.13, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.46, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.49, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.66, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.67, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.18, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.34, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 3.64, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "IN",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.3, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 13.09, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.9, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.27, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.79, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.12, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.73, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.8, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.92, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.63, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.42, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.03, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "KS",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.42, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 12.43, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.12, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.19, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.47, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.0, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.77, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.59, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.25, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.3, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.68, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.78, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "KY",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 11.73, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 15.2, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.9, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.88, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 15.07, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.52, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.62, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.33, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.5, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.02, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.73, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.5, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "LA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 13.05, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 14.35, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.26, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 8.05, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 15.47, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.3, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.29, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.88, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.6, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 4.72, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.9, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.13, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "MA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 9.68, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 8.8, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 9.21, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.8, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.28, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 7.65, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.64, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 4.86, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.06, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.33, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.29, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 4.4, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "MD",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.65, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.61, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 9.57, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 8.04, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.98, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.65, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.53, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 4.08, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.36, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.91, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.46, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 4.16, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "ME",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.89, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.75, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.89, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.24, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.31, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.92, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.68, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.64, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.93, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.2, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.23, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.32, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "MI",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.35, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.72, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.33, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.17, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.44, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.19, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.22, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.27, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.49, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.25, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.29, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 3.28, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "MN",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.09, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.43, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.12, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.3, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.0, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.58, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.75, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.7, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.68, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.66, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.42, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 3.27, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "MO",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.66, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 13.13, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.6, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.8, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.57, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.2, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.35, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.08, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.14, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.43, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.92, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.12, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "MS",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 14.32, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 16.12, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.97, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 8.8, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 14.45, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 3.63, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 7.16, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.54, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.51, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 4.18, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 4.67, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.65, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "MT",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.61, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.58, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 14.81, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.25, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.83, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.13, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.62, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.83, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.7, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.84, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.04, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.76, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "NC",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 12.28, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 15.24, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.77, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.61, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.15, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.46, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.14, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.83, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.96, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.01, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.64, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.91, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "ND",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.85, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 11.62, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.52, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.35, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.42, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.12, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.38, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.72, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.25, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.11, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.87, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.79, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "NE",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.39, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 12.3, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.1, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.13, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.45, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.1, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.78, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.58, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.61, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.12, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.67, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.77, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "NH",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.2, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.43, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.91, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.57, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.23, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.8, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.96, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.44, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.15, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 8.21, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.48, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.62, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "NJ",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 9.9, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.06, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 9.81, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.51, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.39, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.8, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 11.52, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.94, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.24, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.27, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.23, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 4.33, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "NM",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 13.83, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.18, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.45, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.88, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.53, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.24, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.49, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.23, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.89, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.71, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 5.81, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.76, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "NV",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.49, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.07, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.47, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.23, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.43, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.21, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 11.04, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.9, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.52, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 8.65, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.69, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.3, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "NY",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.38, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 8.78, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 9.52, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 8.19, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 15.64, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 7.44, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.21, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 4.85, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.8, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.08, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.8, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 4.31, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "OH",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.25, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 11.48, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.86, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.8, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.77, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.8, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.97, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.69, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.01, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.31, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.3, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.76, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "OK",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.51, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 15.42, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.79, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.07, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.39, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.53, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.19, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.27, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.74, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.58, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.95, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.56, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "OR",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.08, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.35, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.9, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.01, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.01, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.31, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.72, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.28, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.75, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.25, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.57, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.77, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "PA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.34, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.41, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.8, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.2, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.9, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 5.99, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.84, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.97, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.76, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.28, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.66, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.85, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "RI",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.4, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 8.98, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 9.84, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.88, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.47, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 7.02, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.96, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 4.13, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.62, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.46, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.73, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 3.51, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "SC",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 13.54, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 15.67, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.08, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 8.26, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 15.64, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 3.83, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 7.71, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.52, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.35, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 4.5, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 4.1, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.8, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "SD",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 11.11, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 12.15, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.83, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.3, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.78, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.84, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.29, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.44, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.38, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.01, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.25, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.62, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "TN",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 11.61, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 16.19, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.51, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.96, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 15.41, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.38, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.47, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.43, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.26, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.65, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.52, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.61, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "TX",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 11.91, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 13.9, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.31, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 6.43, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.62, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.45, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.21, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.69, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.65, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.11, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.66, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.06, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "UT",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.91, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 15.83, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.72, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 5.63, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.28, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.89, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.47, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.33, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.23, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.56, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.49, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.66, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "VA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 11.4, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 13.42, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 12.4, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.3, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.78, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.94, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.51, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 2.2, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.93, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.61, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.93, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.58, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "VT",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.83, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 9.29, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.31, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.57, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 16.47, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.56, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.42, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.52, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.07, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 7.11, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.03, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 2.82, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "WA",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.1, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.01, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.26, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.11, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.13, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.59, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.85, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.61, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.67, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.91, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.5, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 3.26, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "WI",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 9.89, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 10.48, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 11.61, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.02, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.62, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 6.4, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 9.65, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 3.44, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 11.96, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 6.69, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.21, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 3.03, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "WV",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 11.52, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 14.27, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 13.31, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 7.24, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 14.69, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.98, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 8.45, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.87, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 12.3, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 5.76, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 3.85, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.76, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
  {
    stateId: "WY",
    categoryWeights: { voterGroups: 100 },
    groups: {
      young_renters: { population: 10.23, economicLean: -1.5, socialLean: -1.5, turnout: 36 },
      evangelicals: { population: 11.42, economicLean: 2.0, socialLean: 3.5, turnout: 55 },
      rural_traditionalists: { population: 15.3, economicLean: 2.5, socialLean: 3.0, turnout: 60 },
      union_trades: { population: 5.49, economicLean: -4.5, socialLean: -0.5, turnout: 67 },
      soccer_moms: { population: 17.34, economicLean: 0.5, socialLean: 0.5, turnout: 56 },
      college_liberals: { population: 4.74, economicLean: -3.5, socialLean: -3.0, turnout: 58 },
      small_business: { population: 10.68, economicLean: 4.0, socialLean: 1.5, turnout: 66 },
      public_sector: { population: 1.34, economicLean: -3.5, socialLean: -2.0, turnout: 62 },
      retirees: { population: 10.46, economicLean: 0.0, socialLean: 0.5, turnout: 60 },
      libertarians: { population: 8.72, economicLean: 4.5, socialLean: 0.0, turnout: 60 },
      new_immigrants: { population: 2.42, economicLean: -2.5, socialLean: -2.0, turnout: 28 },
      secular_professionals: { population: 1.86, economicLean: -2.0, socialLean: -2.5, turnout: 60 }
    },
  },
];
