import type { StateDemographicsSeed } from "./usStateDemographics1953.js";
/**
 * US state demographics for 1979. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/stateCensusData1979.ts (per-state race/age/education/wealth/ideology shares)
 * - src/lib/seeds/demographicCategories.ts ERA_COMPOSITIONS["1979"], ERA_TURNOUT_RATES["1979"]
 * - src/lib/seeds/stateDemographicsPure.ts deriveGroupPopulations / deriveGroupTurnout
 *
 * Derived by mainline's own Layer-1 pipeline (stateDemographics.ts generateStateDemographics via the
 * generateStateDemographicsForTest seam) with that era's ERA_COMPOSITIONS / ERA_TURNOUT_RATES, legacy
 * positions path (layer1Positions off, no STATE_POSITION_OVERRIDES folded) — the same choice as
 * usStateDemographics1953.ts. DC excluded. Populations sum to 100 per state.
 */
export const US_STATE_DEMOGRAPHICS_1979: StateDemographicsSeed[] = [
  {
    stateId: "AK",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.88, economicLean: -3, socialLean: -2.5, turnout: 38 },
      evangelicals: { population: 10.8, economicLean: 4.2, socialLean: 4.7, turnout: 68 },
      rural_traditionalists: { population: 15, economicLean: 4.5, socialLean: 4.8, turnout: 67 },
      union_trades: { population: 5.19, economicLean: -3.6, socialLean: 0.4, turnout: 55 },
      soccer_moms: { population: 15.97, economicLean: 0.6, socialLean: 0.6, turnout: 59 },
      college_liberals: { population: 6.47, economicLean: -3.4, socialLean: -3.4, turnout: 63 },
      small_business: { population: 11.91, economicLean: 4.2, socialLean: 2, turnout: 64 },
      public_sector: { population: 2.78, economicLean: -2.9, socialLean: -1.9, turnout: 65 },
      retirees: { population: 8.13, economicLean: 1.8, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 7.71, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.54, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.62, economicLean: -1.9, socialLean: -2.9, turnout: 64 },
    },
  },
  {
    stateId: "AL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.27, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 18.29, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 14.49, economicLean: 4.8, socialLean: 5, turnout: 67 },
      union_trades: { population: 8.12, economicLean: -3.3, socialLean: 1.3, turnout: 55 },
      soccer_moms: { population: 15.03, economicLean: 1.7, socialLean: 1.7, turnout: 59 },
      college_liberals: { population: 4.42, economicLean: -2.3, socialLean: -2.3, turnout: 63 },
      small_business: { population: 8.6, economicLean: 4, socialLean: 2.1, turnout: 64 },
      public_sector: { population: 1.5, economicLean: -1.8, socialLean: -0.8, turnout: 65 },
      retirees: { population: 10.11, economicLean: 2.1, socialLean: 3.1, turnout: 70 },
      libertarians: { population: 4.75, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.09, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.32, economicLean: -0.8, socialLean: -1.8, turnout: 63 },
    },
  },
  {
    stateId: "AR",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 17.76, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 14.38, economicLean: 4.7, socialLean: 5, turnout: 67 },
      union_trades: { population: 7.34, economicLean: -3.4, socialLean: 1.1, turnout: 55 },
      soccer_moms: { population: 14.85, economicLean: 1.5, socialLean: 1.5, turnout: 59 },
      college_liberals: { population: 4.59, economicLean: -2.5, socialLean: -2.5, turnout: 63 },
      small_business: { population: 8.92, economicLean: 4, socialLean: 2.1, turnout: 64 },
      public_sector: { population: 1.43, economicLean: -2, socialLean: -1, turnout: 65 },
      retirees: { population: 11.07, economicLean: 2, socialLean: 3, turnout: 70 },
      libertarians: { population: 5.49, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.09, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.08, economicLean: -1, socialLean: -2, turnout: 63 },
    },
  },
  {
    stateId: "AZ",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.32, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 11.13, economicLean: 4.3, socialLean: 4.7, turnout: 68 },
      rural_traditionalists: { population: 13.25, economicLean: 4.3, socialLean: 4.5, turnout: 67 },
      union_trades: { population: 5.52, economicLean: -3.6, socialLean: 0.5, turnout: 55 },
      soccer_moms: { population: 16.22, economicLean: 0.6, socialLean: 0.6, turnout: 59 },
      college_liberals: { population: 5.97, economicLean: -3.4, socialLean: -3.4, turnout: 63 },
      small_business: { population: 10.85, economicLean: 4.2, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 2.46, economicLean: -2.9, socialLean: -1.9, turnout: 65 },
      retirees: { population: 10.64, economicLean: 1.5, socialLean: 2.5, turnout: 70 },
      libertarians: { population: 7.58, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 1.37, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.69, economicLean: -1.9, socialLean: -2.9, turnout: 64 },
    },
  },
  {
    stateId: "CA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.23, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 9.01, economicLean: 4, socialLean: 4.5, turnout: 68 },
      rural_traditionalists: { population: 9.08, economicLean: 3.2, socialLean: 3.2, turnout: 67 },
      union_trades: { population: 6.92, economicLean: -4.3, socialLean: -0.2, turnout: 55 },
      soccer_moms: { population: 15.94, economicLean: -0.3, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 8.23, economicLean: -4.3, socialLean: -4.3, turnout: 63 },
      small_business: { population: 10.99, economicLean: 3.7, socialLean: 1.4, turnout: 64 },
      public_sector: { population: 4.97, economicLean: -3.8, socialLean: -2.8, turnout: 65 },
      retirees: { population: 9.73, economicLean: 0.1, socialLean: 1.2, turnout: 70 },
      libertarians: { population: 5.8, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 1.77, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 6.33, economicLean: -2.8, socialLean: -3.8, turnout: 64 },
    },
  },
  {
    stateId: "CO",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.58, economicLean: -3, socialLean: -2.5, turnout: 39 },
      evangelicals: { population: 10.42, economicLean: 4.1, socialLean: 4.6, turnout: 68 },
      rural_traditionalists: { population: 11.84, economicLean: 3.8, socialLean: 3.9, turnout: 67 },
      union_trades: { population: 5.94, economicLean: -3.9, socialLean: 0.1, turnout: 55 },
      soccer_moms: { population: 16.44, economicLean: 0.1, socialLean: 0.1, turnout: 59 },
      college_liberals: { population: 7.58, economicLean: -3.9, socialLean: -3.9, turnout: 63 },
      small_business: { population: 10.91, economicLean: 4, socialLean: 1.6, turnout: 64 },
      public_sector: { population: 3.53, economicLean: -3.4, socialLean: -2.4, turnout: 65 },
      retirees: { population: 9.63, economicLean: 0.9, socialLean: 1.9, turnout: 70 },
      libertarians: { population: 7.33, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.96, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.84, economicLean: -2.4, socialLean: -3.4, turnout: 64 },
    },
  },
  {
    stateId: "CT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.48, economicLean: -3, socialLean: -2.5, turnout: 42 },
      evangelicals: { population: 8.41, economicLean: 3.9, socialLean: 4.4, turnout: 68 },
      rural_traditionalists: { population: 9.42, economicLean: 3.1, socialLean: 3.1, turnout: 67 },
      union_trades: { population: 6.99, economicLean: -4.4, socialLean: -0.3, turnout: 55 },
      soccer_moms: { population: 15.82, economicLean: -0.4, socialLean: -0.4, turnout: 59 },
      college_liberals: { population: 8.57, economicLean: -4.4, socialLean: -4.4, turnout: 63 },
      small_business: { population: 12.35, economicLean: 3.6, socialLean: 1.3, turnout: 64 },
      public_sector: { population: 5.06, economicLean: -3.9, socialLean: -2.9, turnout: 65 },
      retirees: { population: 11.23, economicLean: 0, socialLean: 1.1, turnout: 70 },
      libertarians: { population: 5.89, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.34, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 6.44, economicLean: -2.9, socialLean: -3.9, turnout: 64 },
    },
  },
  {
    stateId: "DE",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.88, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 9.95, economicLean: 4.1, socialLean: 4.6, turnout: 68 },
      rural_traditionalists: { population: 10.27, economicLean: 3.5, socialLean: 3.5, turnout: 67 },
      union_trades: { population: 7.96, economicLean: -4.1, socialLean: 0, turnout: 55 },
      soccer_moms: { population: 16.61, economicLean: 0, socialLean: 0, turnout: 59 },
      college_liberals: { population: 7.48, economicLean: -4, socialLean: -4, turnout: 63 },
      small_business: { population: 11, economicLean: 3.7, socialLean: 1.5, turnout: 64 },
      public_sector: { population: 4.14, economicLean: -3.5, socialLean: -2.5, turnout: 65 },
      retirees: { population: 10.74, economicLean: 0.5, socialLean: 1.5, turnout: 70 },
      libertarians: { population: 5.74, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.2, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 5.02, economicLean: -2.5, socialLean: -3.5, turnout: 64 },
    },
  },
  {
    stateId: "FL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.92, economicLean: -3, socialLean: -2.5, turnout: 42 },
      evangelicals: { population: 12.85, economicLean: 4.5, socialLean: 4.9, turnout: 68 },
      rural_traditionalists: { population: 12.24, economicLean: 4.1, socialLean: 4.3, turnout: 67 },
      union_trades: { population: 7.11, economicLean: -3.7, socialLean: 0.6, turnout: 55 },
      soccer_moms: { population: 15.59, economicLean: 0.8, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.88, economicLean: -3.2, socialLean: -3.2, turnout: 63 },
      small_business: { population: 10.17, economicLean: 4, socialLean: 1.8, turnout: 64 },
      public_sector: { population: 2.68, economicLean: -2.7, socialLean: -1.7, turnout: 65 },
      retirees: { population: 12.14, economicLean: 1.3, socialLean: 2.3, turnout: 70 },
      libertarians: { population: 6.11, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.74, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.58, economicLean: -1.7, socialLean: -2.7, turnout: 63 },
    },
  },
  {
    stateId: "GA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.28, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 17.45, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.22, economicLean: 4.5, socialLean: 4.8, turnout: 67 },
      union_trades: { population: 8.41, economicLean: -3.5, socialLean: 1.1, turnout: 55 },
      soccer_moms: { population: 15.11, economicLean: 1.4, socialLean: 1.4, turnout: 59 },
      college_liberals: { population: 4.95, economicLean: -2.6, socialLean: -2.6, turnout: 63 },
      small_business: { population: 9.01, economicLean: 4, socialLean: 2, turnout: 64 },
      public_sector: { population: 1.95, economicLean: -2.1, socialLean: -1.1, turnout: 65 },
      retirees: { population: 9.54, economicLean: 1.8, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 5.05, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.92, economicLean: -1.1, socialLean: -2.1, turnout: 63 },
    },
  },
  {
    stateId: "HI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 13.82, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 6.1, economicLean: 3.9, socialLean: 4.4, turnout: 68 },
      rural_traditionalists: { population: 6.56, economicLean: 3.1, socialLean: 3, turnout: 67 },
      union_trades: { population: 6.1, economicLean: -4.3, socialLean: -0.3, turnout: 55 },
      soccer_moms: { population: 18.28, economicLean: -0.4, socialLean: -0.4, turnout: 59 },
      college_liberals: { population: 8.77, economicLean: -4.4, socialLean: -4.4, turnout: 63 },
      small_business: { population: 10.05, economicLean: 3.6, socialLean: 1.3, turnout: 64 },
      public_sector: { population: 6.64, economicLean: -3.9, socialLean: -2.9, turnout: 65 },
      retirees: { population: 9.02, economicLean: -0.1, socialLean: 1, turnout: 70 },
      libertarians: { population: 3.33, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 3.67, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 7.67, economicLean: -2.9, socialLean: -3.9, turnout: 64 },
    },
  },
  {
    stateId: "IA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.7, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 12.76, economicLean: 4.4, socialLean: 4.8, turnout: 68 },
      rural_traditionalists: { population: 12.44, economicLean: 4, socialLean: 4.1, turnout: 67 },
      union_trades: { population: 5.9, economicLean: -3.8, socialLean: 0.4, turnout: 55 },
      soccer_moms: { population: 17.03, economicLean: 0.5, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 6.3, economicLean: -3.5, socialLean: -3.5, turnout: 63 },
      small_business: { population: 10.45, economicLean: 3.9, socialLean: 1.7, turnout: 64 },
      public_sector: { population: 2.51, economicLean: -3, socialLean: -2, turnout: 65 },
      retirees: { population: 11.93, economicLean: 1.1, socialLean: 2.1, turnout: 70 },
      libertarians: { population: 6.68, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.18, economicLean: -2, socialLean: -3, turnout: 63 },
    },
  },
  {
    stateId: "ID",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.96, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 14, economicLean: 4.6, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 15.19, economicLean: 4.7, socialLean: 5, turnout: 67 },
      union_trades: { population: 5.2, economicLean: -3.4, socialLean: 0.8, turnout: 55 },
      soccer_moms: { population: 16.24, economicLean: 1, socialLean: 1, turnout: 59 },
      college_liberals: { population: 5.45, economicLean: -3, socialLean: -3, turnout: 63 },
      small_business: { population: 10.32, economicLean: 4.2, socialLean: 2.1, turnout: 64 },
      public_sector: { population: 1.56, economicLean: -2.5, socialLean: -1.5, turnout: 65 },
      retirees: { population: 10.33, economicLean: 2, socialLean: 3, turnout: 70 },
      libertarians: { population: 7.96, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.34, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.45, economicLean: -1.5, socialLean: -2.5, turnout: 63 },
    },
  },
  {
    stateId: "IL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.07, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 10.15, economicLean: 4.2, socialLean: 4.6, turnout: 68 },
      rural_traditionalists: { population: 10.03, economicLean: 3.5, socialLean: 3.5, turnout: 67 },
      union_trades: { population: 7.89, economicLean: -4.2, socialLean: 0, turnout: 55 },
      soccer_moms: { population: 16.44, economicLean: 0, socialLean: 0, turnout: 59 },
      college_liberals: { population: 7.48, economicLean: -4, socialLean: -4, turnout: 63 },
      small_business: { population: 10.75, economicLean: 3.7, socialLean: 1.5, turnout: 64 },
      public_sector: { population: 4.42, economicLean: -3.5, socialLean: -2.5, turnout: 65 },
      retirees: { population: 10.49, economicLean: 0.5, socialLean: 1.5, turnout: 70 },
      libertarians: { population: 5.57, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.52, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 5.18, economicLean: -2.5, socialLean: -3.5, turnout: 64 },
    },
  },
  {
    stateId: "IN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.18, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 14.02, economicLean: 4.6, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.01, economicLean: 4.2, socialLean: 4.4, turnout: 67 },
      union_trades: { population: 6.37, economicLean: -3.6, socialLean: 0.7, turnout: 55 },
      soccer_moms: { population: 17.08, economicLean: 0.9, socialLean: 0.9, turnout: 59 },
      college_liberals: { population: 5.62, economicLean: -3.1, socialLean: -3.1, turnout: 63 },
      small_business: { population: 10.17, economicLean: 4, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 2.15, economicLean: -2.6, socialLean: -1.6, turnout: 65 },
      retirees: { population: 10.97, economicLean: 1.4, socialLean: 2.4, turnout: 70 },
      libertarians: { population: 6.37, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.92, economicLean: -1.6, socialLean: -2.6, turnout: 63 },
    },
  },
  {
    stateId: "KS",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.7, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 13.21, economicLean: 4.5, socialLean: 4.9, turnout: 68 },
      rural_traditionalists: { population: 13.27, economicLean: 4.3, socialLean: 4.5, turnout: 67 },
      union_trades: { population: 5.88, economicLean: -3.6, socialLean: 0.6, turnout: 55 },
      soccer_moms: { population: 17.06, economicLean: 0.8, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.8, economicLean: -3.2, socialLean: -3.2, turnout: 63 },
      small_business: { population: 10.46, economicLean: 4.1, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 2.02, economicLean: -2.7, socialLean: -1.7, turnout: 65 },
      retirees: { population: 11.37, economicLean: 1.5, socialLean: 2.5, turnout: 70 },
      libertarians: { population: 7.11, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.27, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.86, economicLean: -1.7, socialLean: -2.7, turnout: 63 },
    },
  },
  {
    stateId: "KY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.05, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 16.94, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 14.37, economicLean: 4.6, socialLean: 4.9, turnout: 67 },
      union_trades: { population: 6.68, economicLean: -3.5, socialLean: 1, turnout: 55 },
      soccer_moms: { population: 15.18, economicLean: 1.3, socialLean: 1.3, turnout: 59 },
      college_liberals: { population: 4.97, economicLean: -2.7, socialLean: -2.7, turnout: 63 },
      small_business: { population: 9.27, economicLean: 4, socialLean: 2, turnout: 64 },
      public_sector: { population: 1.66, economicLean: -2.2, socialLean: -1.2, turnout: 65 },
      retirees: { population: 10.71, economicLean: 1.9, socialLean: 2.9, turnout: 70 },
      libertarians: { population: 5.91, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.07, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.19, economicLean: -1.2, socialLean: -2.2, turnout: 63 },
    },
  },
  {
    stateId: "LA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.87, economicLean: -3, socialLean: -2.5, turnout: 39 },
      evangelicals: { population: 15.95, economicLean: 4.9, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.61, economicLean: 4.5, socialLean: 4.8, turnout: 67 },
      union_trades: { population: 8.94, economicLean: -3.5, socialLean: 1, turnout: 55 },
      soccer_moms: { population: 15.22, economicLean: 1.3, socialLean: 1.3, turnout: 59 },
      college_liberals: { population: 4.88, economicLean: -2.7, socialLean: -2.7, turnout: 63 },
      small_business: { population: 8.91, economicLean: 3.9, socialLean: 2, turnout: 64 },
      public_sector: { population: 2.24, economicLean: -2.2, socialLean: -1.2, turnout: 65 },
      retirees: { population: 9.63, economicLean: 1.8, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 4.64, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.2, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.91, economicLean: -1.2, socialLean: -2.2, turnout: 63 },
    },
  },
  {
    stateId: "MA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.66, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 8.57, economicLean: 3.8, socialLean: 4.4, turnout: 68 },
      rural_traditionalists: { population: 8.84, economicLean: 2.9, socialLean: 2.7, turnout: 67 },
      union_trades: { population: 7.16, economicLean: -4.5, socialLean: -0.5, turnout: 55 },
      soccer_moms: { population: 15.93, economicLean: -0.6, socialLean: -0.6, turnout: 59 },
      college_liberals: { population: 9.31, economicLean: -4.6, socialLean: -4.6, turnout: 63 },
      small_business: { population: 11.18, economicLean: 3.5, socialLean: 1.2, turnout: 64 },
      public_sector: { population: 5.62, economicLean: -4.1, socialLean: -3.1, turnout: 65 },
      retirees: { population: 11.06, economicLean: -0.3, socialLean: 0.7, turnout: 70 },
      libertarians: { population: 6, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.19, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 6.46, economicLean: -3.1, socialLean: -4.1, turnout: 64 },
    },
  },
  {
    stateId: "MD",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.74, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 9.46, economicLean: 4.1, socialLean: 4.6, turnout: 68 },
      rural_traditionalists: { population: 9.02, economicLean: 3.3, socialLean: 3.2, turnout: 67 },
      union_trades: { population: 8.84, economicLean: -4.3, socialLean: -0.1, turnout: 55 },
      soccer_moms: { population: 16.45, economicLean: -0.2, socialLean: -0.2, turnout: 59 },
      college_liberals: { population: 8.03, economicLean: -4.2, socialLean: -4.2, turnout: 63 },
      small_business: { population: 10.96, economicLean: 3.6, socialLean: 1.4, turnout: 64 },
      public_sector: { population: 4.95, economicLean: -3.7, socialLean: -2.7, turnout: 65 },
      retirees: { population: 10.09, economicLean: 0.2, socialLean: 1.2, turnout: 70 },
      libertarians: { population: 5.38, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.14, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 5.93, economicLean: -2.7, socialLean: -3.7, turnout: 64 },
    },
  },
  {
    stateId: "ME",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.31, economicLean: -3, socialLean: -2.5, turnout: 42 },
      evangelicals: { population: 9.96, economicLean: 4, socialLean: 4.5, turnout: 68 },
      rural_traditionalists: { population: 12.07, economicLean: 3.7, socialLean: 3.7, turnout: 67 },
      union_trades: { population: 6.57, economicLean: -4.1, socialLean: -0.1, turnout: 55 },
      soccer_moms: { population: 16.19, economicLean: -0.1, socialLean: -0.1, turnout: 59 },
      college_liberals: { population: 7.21, economicLean: -4.1, socialLean: -4.1, turnout: 63 },
      small_business: { population: 10.45, economicLean: 3.9, socialLean: 1.6, turnout: 64 },
      public_sector: { population: 3.1, economicLean: -3.6, socialLean: -2.6, turnout: 65 },
      retirees: { population: 12.1, economicLean: 0.7, socialLean: 1.7, turnout: 70 },
      libertarians: { population: 7.11, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.06, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.89, economicLean: -2.6, socialLean: -3.6, turnout: 63 },
    },
  },
  {
    stateId: "MI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.21, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 10.88, economicLean: 4.2, socialLean: 4.7, turnout: 68 },
      rural_traditionalists: { population: 11.09, economicLean: 3.7, socialLean: 3.7, turnout: 67 },
      union_trades: { population: 7.59, economicLean: -4.1, socialLean: 0.1, turnout: 55 },
      soccer_moms: { population: 16.79, economicLean: 0.1, socialLean: 0.1, turnout: 59 },
      college_liberals: { population: 7.02, economicLean: -3.9, socialLean: -3.9, turnout: 63 },
      small_business: { population: 10.57, economicLean: 3.7, socialLean: 1.6, turnout: 64 },
      public_sector: { population: 3.91, economicLean: -3.4, socialLean: -2.4, turnout: 65 },
      retirees: { population: 10.41, economicLean: 0.7, socialLean: 1.7, turnout: 70 },
      libertarians: { population: 5.81, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.2, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.52, economicLean: -2.4, socialLean: -3.4, turnout: 63 },
    },
  },
  {
    stateId: "MN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.12, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 10.71, economicLean: 4.1, socialLean: 4.6, turnout: 68 },
      rural_traditionalists: { population: 11.07, economicLean: 3.5, socialLean: 3.5, turnout: 67 },
      union_trades: { population: 6.5, economicLean: -4.3, socialLean: -0.1, turnout: 55 },
      soccer_moms: { population: 16.65, economicLean: -0.1, socialLean: -0.1, turnout: 59 },
      college_liberals: { population: 8.02, economicLean: -4.1, socialLean: -4.1, turnout: 63 },
      small_business: { population: 10.35, economicLean: 3.7, socialLean: 1.5, turnout: 64 },
      public_sector: { population: 4.46, economicLean: -3.6, socialLean: -2.6, turnout: 65 },
      retirees: { population: 10.8, economicLean: 0.5, socialLean: 1.5, turnout: 70 },
      libertarians: { population: 6.44, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.13, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.75, economicLean: -2.6, socialLean: -3.6, turnout: 64 },
    },
  },
  {
    stateId: "MO",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.04, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 14.17, economicLean: 4.6, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 12.75, economicLean: 4.2, socialLean: 4.4, turnout: 67 },
      union_trades: { population: 6.84, economicLean: -3.7, socialLean: 0.6, turnout: 55 },
      soccer_moms: { population: 16.24, economicLean: 0.8, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.84, economicLean: -3.2, socialLean: -3.2, turnout: 63 },
      small_business: { population: 9.98, economicLean: 3.9, socialLean: 1.8, turnout: 64 },
      public_sector: { population: 2.52, economicLean: -2.7, socialLean: -1.7, turnout: 65 },
      retirees: { population: 11.24, economicLean: 1.4, socialLean: 2.4, turnout: 70 },
      libertarians: { population: 6.21, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.05, economicLean: -1.7, socialLean: -2.7, turnout: 63 },
    },
  },
  {
    stateId: "MS",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 13.63, economicLean: -3, socialLean: -2.5, turnout: 39 },
      evangelicals: { population: 18.21, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.51, economicLean: 4.6, socialLean: 4.9, turnout: 67 },
      union_trades: { population: 9.78, economicLean: -3.5, socialLean: 1.2, turnout: 55 },
      soccer_moms: { population: 14.23, economicLean: 1.6, socialLean: 1.6, turnout: 59 },
      college_liberals: { population: 4.36, economicLean: -2.4, socialLean: -2.4, turnout: 63 },
      small_business: { population: 7.96, economicLean: 3.9, socialLean: 2.1, turnout: 64 },
      public_sector: { population: 1.83, economicLean: -1.9, socialLean: -0.9, turnout: 65 },
      retirees: { population: 9.62, economicLean: 1.9, socialLean: 2.9, turnout: 70 },
      libertarians: { population: 4.4, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.08, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.39, economicLean: -0.9, socialLean: -1.9, turnout: 63 },
    },
  },
  {
    stateId: "MT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.85, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 10.99, economicLean: 4.2, socialLean: 4.7, turnout: 68 },
      rural_traditionalists: { population: 15.21, economicLean: 4.5, socialLean: 4.8, turnout: 67 },
      union_trades: { population: 5.58, economicLean: -3.6, socialLean: 0.4, turnout: 55 },
      soccer_moms: { population: 16.47, economicLean: 0.5, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 6.32, economicLean: -3.5, socialLean: -3.5, turnout: 63 },
      small_business: { population: 10.4, economicLean: 4.1, socialLean: 2, turnout: 64 },
      public_sector: { population: 2.27, economicLean: -3, socialLean: -2, turnout: 65 },
      retirees: { population: 10.8, economicLean: 1.8, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 7.73, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.19, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.18, economicLean: -2, socialLean: -3, turnout: 63 },
    },
  },
  {
    stateId: "NC",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.14, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 16.94, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.06, economicLean: 4.4, socialLean: 4.6, turnout: 67 },
      union_trades: { population: 8.03, economicLean: -3.6, socialLean: 1, turnout: 55 },
      soccer_moms: { population: 15.89, economicLean: 1.3, socialLean: 1.3, turnout: 59 },
      college_liberals: { population: 5.16, economicLean: -2.7, socialLean: -2.7, turnout: 63 },
      small_business: { population: 8.73, economicLean: 3.9, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 2.19, economicLean: -2.2, socialLean: -1.2, turnout: 65 },
      retirees: { population: 10.01, economicLean: 1.6, socialLean: 2.6, turnout: 70 },
      libertarians: { population: 4.91, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.14, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.8, economicLean: -1.2, socialLean: -2.2, turnout: 63 },
    },
  },
  {
    stateId: "ND",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.24, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 12.28, economicLean: 4.4, socialLean: 4.8, turnout: 68 },
      rural_traditionalists: { population: 13.85, economicLean: 4.3, socialLean: 4.5, turnout: 67 },
      union_trades: { population: 5.71, economicLean: -3.7, socialLean: 0.5, turnout: 55 },
      soccer_moms: { population: 17.14, economicLean: 0.6, socialLean: 0.6, turnout: 59 },
      college_liberals: { population: 6.02, economicLean: -3.4, socialLean: -3.4, turnout: 63 },
      small_business: { population: 10.11, economicLean: 4, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 2.26, economicLean: -2.9, socialLean: -1.9, turnout: 65 },
      retirees: { population: 11.53, economicLean: 1.5, socialLean: 2.5, turnout: 70 },
      libertarians: { population: 6.98, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.14, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.75, economicLean: -1.9, socialLean: -2.9, turnout: 63 },
    },
  },
  {
    stateId: "NE",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.79, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 13.05, economicLean: 4.5, socialLean: 4.9, turnout: 68 },
      rural_traditionalists: { population: 13.29, economicLean: 4.3, socialLean: 4.5, turnout: 67 },
      union_trades: { population: 5.77, economicLean: -3.6, socialLean: 0.6, turnout: 55 },
      soccer_moms: { population: 17.09, economicLean: 0.8, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.87, economicLean: -3.2, socialLean: -3.2, turnout: 63 },
      small_business: { population: 10.47, economicLean: 4, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 1.99, economicLean: -2.7, socialLean: -1.7, turnout: 65 },
      retirees: { population: 11.79, economicLean: 1.5, socialLean: 2.5, turnout: 70 },
      libertarians: { population: 6.93, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.19, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.76, economicLean: -1.7, socialLean: -2.7, turnout: 63 },
    },
  },
  {
    stateId: "NH",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.21, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 9.43, economicLean: 4, socialLean: 4.5, turnout: 68 },
      rural_traditionalists: { population: 11.93, economicLean: 3.7, socialLean: 3.8, turnout: 67 },
      union_trades: { population: 5.82, economicLean: -4, socialLean: 0, turnout: 55 },
      soccer_moms: { population: 16.86, economicLean: 0, socialLean: 0, turnout: 59 },
      college_liberals: { population: 7.3, economicLean: -4, socialLean: -4, turnout: 63 },
      small_business: { population: 11.77, economicLean: 4, socialLean: 1.6, turnout: 64 },
      public_sector: { population: 3.03, economicLean: -3.5, socialLean: -2.5, turnout: 65 },
      retirees: { population: 11.2, economicLean: 0.8, socialLean: 1.8, turnout: 70 },
      libertarians: { population: 8.09, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.25, economicLean: -2.5, socialLean: -3.5, turnout: 64 },
    },
  },
  {
    stateId: "NJ",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.32, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 8.5, economicLean: 4, socialLean: 4.5, turnout: 68 },
      rural_traditionalists: { population: 9.11, economicLean: 3.2, socialLean: 3.2, turnout: 67 },
      union_trades: { population: 7.64, economicLean: -4.3, socialLean: -0.2, turnout: 55 },
      soccer_moms: { population: 16.06, economicLean: -0.3, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 8.11, economicLean: -4.3, socialLean: -4.3, turnout: 63 },
      small_business: { population: 12.04, economicLean: 3.6, socialLean: 1.4, turnout: 64 },
      public_sector: { population: 4.88, economicLean: -3.8, socialLean: -2.8, turnout: 65 },
      retirees: { population: 10.97, economicLean: 0.1, socialLean: 1.2, turnout: 70 },
      libertarians: { population: 5.63, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.6, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 6.13, economicLean: -2.8, socialLean: -3.8, turnout: 64 },
    },
  },
  {
    stateId: "NM",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 14, economicLean: -3, socialLean: -2.5, turnout: 39 },
      evangelicals: { population: 9.58, economicLean: 4.2, socialLean: 4.7, turnout: 68 },
      rural_traditionalists: { population: 11.54, economicLean: 4, socialLean: 4.1, turnout: 67 },
      union_trades: { population: 6.18, economicLean: -3.9, socialLean: 0.2, turnout: 55 },
      soccer_moms: { population: 16.13, economicLean: 0.3, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.47, economicLean: -3.7, socialLean: -3.7, turnout: 63 },
      small_business: { population: 9.2, economicLean: 3.9, socialLean: 1.7, turnout: 64 },
      public_sector: { population: 3.89, economicLean: -3.2, socialLean: -2.2, turnout: 65 },
      retirees: { population: 9.77, economicLean: 1.1, socialLean: 2.1, turnout: 70 },
      libertarians: { population: 5.44, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 3.47, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.34, economicLean: -2.2, socialLean: -3.2, turnout: 64 },
    },
  },
  {
    stateId: "NV",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.02, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 10.1, economicLean: 4.2, socialLean: 4.7, turnout: 68 },
      rural_traditionalists: { population: 12.42, economicLean: 4.1, socialLean: 4.3, turnout: 67 },
      union_trades: { population: 5.99, economicLean: -3.8, socialLean: 0.3, turnout: 55 },
      soccer_moms: { population: 17.08, economicLean: 0.4, socialLean: 0.4, turnout: 59 },
      college_liberals: { population: 6, economicLean: -3.6, socialLean: -3.6, turnout: 63 },
      small_business: { population: 11.92, economicLean: 4.2, socialLean: 1.8, turnout: 64 },
      public_sector: { population: 2.36, economicLean: -3.1, socialLean: -2.1, turnout: 65 },
      retirees: { population: 10.47, economicLean: 1.3, socialLean: 2.3, turnout: 70 },
      libertarians: { population: 8.44, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.6, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.58, economicLean: -2.1, socialLean: -3.1, turnout: 63 },
    },
  },
  {
    stateId: "NY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.97, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 8.13, economicLean: 3.9, socialLean: 4.4, turnout: 68 },
      rural_traditionalists: { population: 8.74, economicLean: 3.1, socialLean: 3, turnout: 67 },
      union_trades: { population: 8.48, economicLean: -4.5, socialLean: -0.4, turnout: 55 },
      soccer_moms: { population: 15.4, economicLean: -0.5, socialLean: -0.5, turnout: 59 },
      college_liberals: { population: 8.72, economicLean: -4.5, socialLean: -4.5, turnout: 63 },
      small_business: { population: 10.62, economicLean: 3.5, socialLean: 1.3, turnout: 64 },
      public_sector: { population: 5.86, economicLean: -4, socialLean: -3, turnout: 65 },
      retirees: { population: 10.59, economicLean: -0.1, socialLean: 1, turnout: 70 },
      libertarians: { population: 5.37, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.79, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 6.31, economicLean: -3, socialLean: -4, turnout: 64 },
    },
  },
  {
    stateId: "OH",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.07, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 11.97, economicLean: 4.4, socialLean: 4.8, turnout: 68 },
      rural_traditionalists: { population: 11.82, economicLean: 3.9, socialLean: 4, turnout: 67 },
      union_trades: { population: 7.01, economicLean: -3.9, socialLean: 0.3, turnout: 55 },
      soccer_moms: { population: 17.12, economicLean: 0.4, socialLean: 0.4, turnout: 59 },
      college_liberals: { population: 6.52, economicLean: -3.6, socialLean: -3.6, turnout: 63 },
      small_business: { population: 10.38, economicLean: 3.8, socialLean: 1.7, turnout: 64 },
      public_sector: { population: 3.21, economicLean: -3.1, socialLean: -2.1, turnout: 65 },
      retirees: { population: 11.04, economicLean: 1, socialLean: 2, turnout: 70 },
      libertarians: { population: 5.99, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.75, economicLean: -2.1, socialLean: -3.1, turnout: 63 },
    },
  },
  {
    stateId: "OK",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.03, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 17.01, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.98, economicLean: 4.6, socialLean: 4.9, turnout: 67 },
      union_trades: { population: 5.82, economicLean: -3.4, socialLean: 1.1, turnout: 55 },
      soccer_moms: { population: 16, economicLean: 1.4, socialLean: 1.4, turnout: 59 },
      college_liberals: { population: 4.99, economicLean: -2.6, socialLean: -2.6, turnout: 63 },
      small_business: { population: 9.75, economicLean: 4.1, socialLean: 2.1, turnout: 64 },
      public_sector: { population: 1.62, economicLean: -2.1, socialLean: -1.1, turnout: 65 },
      retirees: { population: 10.82, economicLean: 1.9, socialLean: 2.9, turnout: 70 },
      libertarians: { population: 6.25, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.3, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.44, economicLean: -1.1, socialLean: -2.1, turnout: 63 },
    },
  },
  {
    stateId: "OR",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.14, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 10.46, economicLean: 4, socialLean: 4.5, turnout: 68 },
      rural_traditionalists: { population: 11.77, economicLean: 3.5, socialLean: 3.6, turnout: 67 },
      union_trades: { population: 6.18, economicLean: -4.1, socialLean: -0.1, turnout: 55 },
      soccer_moms: { population: 16.49, economicLean: -0.2, socialLean: -0.2, turnout: 59 },
      college_liberals: { population: 8.06, economicLean: -4.2, socialLean: -4.2, turnout: 63 },
      small_business: { population: 10.26, economicLean: 3.8, socialLean: 1.5, turnout: 64 },
      public_sector: { population: 3.86, economicLean: -3.7, socialLean: -2.7, turnout: 65 },
      retirees: { population: 10.69, economicLean: 0.6, socialLean: 1.6, turnout: 70 },
      libertarians: { population: 6.96, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.32, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.82, economicLean: -2.7, socialLean: -3.7, turnout: 64 },
    },
  },
  {
    stateId: "PA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.83, economicLean: -3, socialLean: -2.5, turnout: 42 },
      evangelicals: { population: 10.74, economicLean: 4.2, socialLean: 4.7, turnout: 68 },
      rural_traditionalists: { population: 11.86, economicLean: 3.8, socialLean: 3.9, turnout: 67 },
      union_trades: { population: 7.17, economicLean: -4, socialLean: 0.2, turnout: 55 },
      soccer_moms: { population: 16.67, economicLean: 0.2, socialLean: 0.2, turnout: 59 },
      college_liberals: { population: 6.72, economicLean: -3.8, socialLean: -3.8, turnout: 63 },
      small_business: { population: 10.48, economicLean: 3.8, socialLean: 1.7, turnout: 64 },
      public_sector: { population: 3.52, economicLean: -3.3, socialLean: -2.3, turnout: 65 },
      retirees: { population: 11.85, economicLean: 0.9, socialLean: 1.9, turnout: 70 },
      libertarians: { population: 6.03, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.01, economicLean: -2.3, socialLean: -3.3, turnout: 63 },
    },
  },
  {
    stateId: "RI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.8, economicLean: -3, socialLean: -2.5, turnout: 41 },
      evangelicals: { population: 8.9, economicLean: 3.9, socialLean: 4.4, turnout: 68 },
      rural_traditionalists: { population: 9.66, economicLean: 3.1, socialLean: 3.1, turnout: 67 },
      union_trades: { population: 7.29, economicLean: -4.4, socialLean: -0.3, turnout: 55 },
      soccer_moms: { population: 16.35, economicLean: -0.4, socialLean: -0.4, turnout: 59 },
      college_liberals: { population: 8.24, economicLean: -4.4, socialLean: -4.4, turnout: 63 },
      small_business: { population: 10.63, economicLean: 3.6, socialLean: 1.3, turnout: 64 },
      public_sector: { population: 4.84, economicLean: -3.9, socialLean: -2.9, turnout: 65 },
      retirees: { population: 11.75, economicLean: 0, socialLean: 1.1, turnout: 70 },
      libertarians: { population: 6.23, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.2, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 5.11, economicLean: -2.9, socialLean: -3.9, turnout: 64 },
    },
  },
  {
    stateId: "SC",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.95, economicLean: -3, socialLean: -2.5, turnout: 39 },
      evangelicals: { population: 17.57, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.51, economicLean: 4.6, socialLean: 4.9, turnout: 67 },
      union_trades: { population: 8.95, economicLean: -3.4, socialLean: 1.1, turnout: 55 },
      soccer_moms: { population: 15.3, economicLean: 1.5, socialLean: 1.5, turnout: 59 },
      college_liberals: { population: 4.65, economicLean: -2.5, socialLean: -2.5, turnout: 63 },
      small_business: { population: 8.42, economicLean: 3.9, socialLean: 2, turnout: 64 },
      public_sector: { population: 1.91, economicLean: -2, socialLean: -1, turnout: 65 },
      retirees: { population: 9.48, economicLean: 1.9, socialLean: 2.9, turnout: 70 },
      libertarians: { population: 4.61, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.55, economicLean: -1, socialLean: -2, turnout: 63 },
    },
  },
  {
    stateId: "SD",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.58, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 12.98, economicLean: 4.5, socialLean: 4.9, turnout: 68 },
      rural_traditionalists: { population: 14.2, economicLean: 4.4, socialLean: 4.7, turnout: 67 },
      union_trades: { population: 5.69, economicLean: -3.6, socialLean: 0.6, turnout: 55 },
      soccer_moms: { population: 16.58, economicLean: 0.8, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.68, economicLean: -3.2, socialLean: -3.2, turnout: 63 },
      small_business: { population: 10.02, economicLean: 4, socialLean: 2, turnout: 64 },
      public_sector: { population: 1.92, economicLean: -2.7, socialLean: -1.7, turnout: 65 },
      retirees: { population: 11.68, economicLean: 1.7, socialLean: 2.7, turnout: 70 },
      libertarians: { population: 6.87, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.19, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.61, economicLean: -1.7, socialLean: -2.7, turnout: 63 },
    },
  },
  {
    stateId: "TN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.73, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 18.05, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.82, economicLean: 4.6, socialLean: 4.9, turnout: 67 },
      union_trades: { population: 7.24, economicLean: -3.5, socialLean: 1.1, turnout: 55 },
      soccer_moms: { population: 15.28, economicLean: 1.5, socialLean: 1.5, turnout: 59 },
      college_liberals: { population: 4.83, economicLean: -2.5, socialLean: -2.5, turnout: 63 },
      small_business: { population: 9.04, economicLean: 4, socialLean: 2, turnout: 64 },
      public_sector: { population: 1.75, economicLean: -2, socialLean: -1, turnout: 65 },
      retirees: { population: 10.32, economicLean: 1.9, socialLean: 2.9, turnout: 70 },
      libertarians: { population: 5.48, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.07, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.4, economicLean: -1, socialLean: -2, turnout: 63 },
    },
  },
  {
    stateId: "TX",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.27, economicLean: -3, socialLean: -2.5, turnout: 39 },
      evangelicals: { population: 15.1, economicLean: 4.8, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.36, economicLean: 4.5, socialLean: 4.8, turnout: 67 },
      union_trades: { population: 6.37, economicLean: -3.5, socialLean: 0.9, turnout: 55 },
      soccer_moms: { population: 16.03, economicLean: 1.2, socialLean: 1.2, turnout: 59 },
      college_liberals: { population: 4.97, economicLean: -2.8, socialLean: -2.8, turnout: 63 },
      small_business: { population: 9.74, economicLean: 4, socialLean: 2, turnout: 64 },
      public_sector: { population: 2.11, economicLean: -2.3, socialLean: -1.3, turnout: 65 },
      retirees: { population: 9.55, economicLean: 1.8, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 5.72, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 1.72, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.06, economicLean: -1.3, socialLean: -2.3, turnout: 63 },
    },
  },
  {
    stateId: "UT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.15, economicLean: -3, socialLean: -2.5, turnout: 36 },
      evangelicals: { population: 17.25, economicLean: 5, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 12.66, economicLean: 4.3, socialLean: 4.5, turnout: 67 },
      union_trades: { population: 5.02, economicLean: -3.5, socialLean: 1, turnout: 55 },
      soccer_moms: { population: 16.63, economicLean: 1.3, socialLean: 1.3, turnout: 59 },
      college_liberals: { population: 5.74, economicLean: -2.7, socialLean: -2.7, turnout: 63 },
      small_business: { population: 10.03, economicLean: 4.2, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 1.8, economicLean: -2.2, socialLean: -1.2, turnout: 65 },
      retirees: { population: 9.39, economicLean: 1.5, socialLean: 2.5, turnout: 70 },
      libertarians: { population: 7.28, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.35, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.7, economicLean: -1.2, socialLean: -2.2, turnout: 64 },
    },
  },
  {
    stateId: "VA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.17, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 14.56, economicLean: 4.7, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 12.51, economicLean: 4.2, socialLean: 4.4, turnout: 67 },
      union_trades: { population: 7.58, economicLean: -3.6, socialLean: 0.7, turnout: 55 },
      soccer_moms: { population: 16.1, economicLean: 1, socialLean: 1, turnout: 59 },
      college_liberals: { population: 6.03, economicLean: -3, socialLean: -3, turnout: 63 },
      small_business: { population: 10.06, economicLean: 3.9, socialLean: 1.8, turnout: 64 },
      public_sector: { population: 2.72, economicLean: -2.5, socialLean: -1.5, turnout: 65 },
      retirees: { population: 9.91, economicLean: 1.4, socialLean: 2.4, turnout: 70 },
      libertarians: { population: 5.45, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.79, economicLean: -1.5, socialLean: -2.5, turnout: 64 },
    },
  },
  {
    stateId: "VT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.85, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 9.3, economicLean: 3.8, socialLean: 4.4, turnout: 68 },
      rural_traditionalists: { population: 11.29, economicLean: 3.3, socialLean: 3.3, turnout: 67 },
      union_trades: { population: 6.75, economicLean: -4.3, socialLean: -0.3, turnout: 55 },
      soccer_moms: { population: 16.14, economicLean: -0.4, socialLean: -0.4, turnout: 59 },
      college_liberals: { population: 8.41, economicLean: -4.4, socialLean: -4.4, turnout: 63 },
      small_business: { population: 10.04, economicLean: 3.8, socialLean: 1.4, turnout: 64 },
      public_sector: { population: 4.15, economicLean: -3.9, socialLean: -2.9, turnout: 65 },
      retirees: { population: 11.19, economicLean: 0.3, socialLean: 1.3, turnout: 70 },
      libertarians: { population: 6.93, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.84, economicLean: -2.9, socialLean: -3.9, turnout: 64 },
    },
  },
  {
    stateId: "WA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.13, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 9.99, economicLean: 3.9, socialLean: 4.4, turnout: 68 },
      rural_traditionalists: { population: 11, economicLean: 3.4, socialLean: 3.4, turnout: 67 },
      union_trades: { population: 6.44, economicLean: -4.2, socialLean: -0.2, turnout: 55 },
      soccer_moms: { population: 16.58, economicLean: -0.2, socialLean: -0.2, turnout: 59 },
      college_liberals: { population: 8.4, economicLean: -4.2, socialLean: -4.2, turnout: 63 },
      small_business: { population: 10.33, economicLean: 3.8, socialLean: 1.4, turnout: 64 },
      public_sector: { population: 4.3, economicLean: -3.7, socialLean: -2.7, turnout: 65 },
      retirees: { population: 10.61, economicLean: 0.4, socialLean: 1.4, turnout: 70 },
      libertarians: { population: 6.55, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.36, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 5.31, economicLean: -2.7, socialLean: -3.7, turnout: 64 },
    },
  },
  {
    stateId: "WI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.52, economicLean: -3, socialLean: -2.5, turnout: 40 },
      evangelicals: { population: 10.72, economicLean: 4.2, socialLean: 4.6, turnout: 68 },
      rural_traditionalists: { population: 11.57, economicLean: 3.6, socialLean: 3.7, turnout: 67 },
      union_trades: { population: 6.72, economicLean: -4.2, socialLean: 0, turnout: 55 },
      soccer_moms: { population: 16.97, economicLean: 0, socialLean: 0, turnout: 59 },
      college_liberals: { population: 7.46, economicLean: -4, socialLean: -4, turnout: 63 },
      small_business: { population: 10.07, economicLean: 3.7, socialLean: 1.6, turnout: 64 },
      public_sector: { population: 4.08, economicLean: -3.5, socialLean: -2.5, turnout: 65 },
      retirees: { population: 11.08, economicLean: 0.7, socialLean: 1.7, turnout: 70 },
      libertarians: { population: 6.43, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.12, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 4.27, economicLean: -2.5, socialLean: -3.5, turnout: 63 },
    },
  },
  {
    stateId: "WV",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.86, economicLean: -3, socialLean: -2.5, turnout: 42 },
      evangelicals: { population: 15.94, economicLean: 4.8, socialLean: 5, turnout: 68 },
      rural_traditionalists: { population: 13.89, economicLean: 4.4, socialLean: 4.6, turnout: 67 },
      union_trades: { population: 6.73, economicLean: -3.7, socialLean: 0.8, turnout: 55 },
      soccer_moms: { population: 14.97, economicLean: 1, socialLean: 1, turnout: 59 },
      college_liberals: { population: 5.38, economicLean: -3, socialLean: -3, turnout: 63 },
      small_business: { population: 9.18, economicLean: 3.8, socialLean: 1.9, turnout: 64 },
      public_sector: { population: 2.21, economicLean: -2.5, socialLean: -1.5, turnout: 65 },
      retirees: { population: 11.61, economicLean: 1.6, socialLean: 2.6, turnout: 70 },
      libertarians: { population: 5.75, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.07, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 2.4, economicLean: -1.5, socialLean: -2.5, turnout: 63 },
    },
  },
  {
    stateId: "WY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.47, economicLean: -3, socialLean: -2.5, turnout: 39 },
      evangelicals: { population: 11.93, economicLean: 4.4, socialLean: 4.8, turnout: 68 },
      rural_traditionalists: { population: 15.59, economicLean: 4.8, socialLean: 5, turnout: 67 },
      union_trades: { population: 4.87, economicLean: -3.4, socialLean: 0.6, turnout: 55 },
      soccer_moms: { population: 16.75, economicLean: 0.8, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.62, economicLean: -3.2, socialLean: -3.2, turnout: 63 },
      small_business: { population: 11.5, economicLean: 4.3, socialLean: 2.1, turnout: 64 },
      public_sector: { population: 1.68, economicLean: -2.7, socialLean: -1.7, turnout: 65 },
      retirees: { population: 9.54, economicLean: 2.1, socialLean: 3.1, turnout: 70 },
      libertarians: { population: 8.58, economicLean: 5, socialLean: 0, turnout: 60 },
      new_immigrants: { population: 0.42, economicLean: -3, socialLean: -2, turnout: 30 },
      secular_professionals: { population: 3.04, economicLean: -1.7, socialLean: -2.7, turnout: 63 },
    },
  },
];
