import type { StateDemographicsSeed } from "./usStateDemographics1953.js";
/**
 * US state demographics for 1991. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/stateCensusData1991.ts
 * - src/lib/seeds/demographicCategories.ts ERA_COMPOSITIONS["1991"], ERA_TURNOUT_RATES["1991"]
 * - src/lib/seeds/stateDemographicsPure.ts
 *
 * Derived by mainline's own Layer-1 pipeline (stateDemographics.ts generateStateDemographics via the
 * generateStateDemographicsForTest seam) with that era's ERA_COMPOSITIONS / ERA_TURNOUT_RATES, legacy
 * positions path (layer1Positions off, no STATE_POSITION_OVERRIDES folded) — the same choice as
 * usStateDemographics1953.ts. DC excluded. Populations sum to 100 per state.
 */
export const US_STATE_DEMOGRAPHICS_1991: StateDemographicsSeed[] = [
  {
    stateId: "AK",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.29, economicLean: -3.5, socialLean: -3, turnout: 40 },
      evangelicals: { population: 11.86, economicLean: 3.8, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.67, economicLean: 4.5, socialLean: 4.8, turnout: 64 },
      union_trades: { population: 4.8, economicLean: -2.9, socialLean: 0.6, turnout: 52 },
      soccer_moms: { population: 16.78, economicLean: 0.3, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.79, economicLean: -3.2, socialLean: -3.2, turnout: 59 },
      small_business: { population: 12.09, economicLean: 4.4, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 1.96, economicLean: -2.2, socialLean: -1.7, turnout: 58 },
      retirees: { population: 9.06, economicLean: 1.8, socialLean: 3.3, turnout: 70 },
      libertarians: { population: 9.01, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.79, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.91, economicLean: -1.7, socialLean: -2.7, turnout: 62 },
    },
  },
  {
    stateId: "AL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.4, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 23.33, economicLean: 5, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 14.28, economicLean: 5, socialLean: 5, turnout: 64 },
      union_trades: { population: 7.34, economicLean: -2.7, socialLean: 1.8, turnout: 52 },
      soccer_moms: { population: 14.32, economicLean: 1.9, socialLean: 2.4, turnout: 59 },
      college_liberals: { population: 4.06, economicLean: -1.6, socialLean: -1.6, turnout: 59 },
      small_business: { population: 7.94, economicLean: 4, socialLean: 2.8, turnout: 65 },
      public_sector: { population: 1.31, economicLean: -0.6, socialLean: -0.1, turnout: 58 },
      retirees: { population: 10.31, economicLean: 2.5, socialLean: 4, turnout: 70 },
      libertarians: { population: 4.63, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.14, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 1.94, economicLean: -0.1, socialLean: -1.1, turnout: 62 },
    },
  },
  {
    stateId: "AR",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.42, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 22.75, economicLean: 5, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 14.24, economicLean: 5, socialLean: 5, turnout: 64 },
      union_trades: { population: 6.59, economicLean: -2.7, socialLean: 1.7, turnout: 52 },
      soccer_moms: { population: 14.24, economicLean: 1.7, socialLean: 2.2, turnout: 59 },
      college_liberals: { population: 4.09, economicLean: -1.8, socialLean: -1.8, turnout: 59 },
      small_business: { population: 8.25, economicLean: 4, socialLean: 2.7, turnout: 65 },
      public_sector: { population: 1.19, economicLean: -0.8, socialLean: -0.3, turnout: 58 },
      retirees: { population: 11.05, economicLean: 2.4, socialLean: 3.9, turnout: 70 },
      libertarians: { population: 5.32, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.14, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 1.73, economicLean: -0.3, socialLean: -1.3, turnout: 62 },
    },
  },
  {
    stateId: "AZ",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.75, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 12.47, economicLean: 3.9, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 11.74, economicLean: 4.1, socialLean: 4.3, turnout: 64 },
      union_trades: { population: 5.16, economicLean: -3.1, socialLean: 0.5, turnout: 52 },
      soccer_moms: { population: 16.04, economicLean: 0.2, socialLean: 0.7, turnout: 59 },
      college_liberals: { population: 5.67, economicLean: -3.3, socialLean: -3.3, turnout: 59 },
      small_business: { population: 10.78, economicLean: 4.2, socialLean: 2.3, turnout: 65 },
      public_sector: { population: 2.18, economicLean: -2.3, socialLean: -1.8, turnout: 58 },
      retirees: { population: 11.77, economicLean: 1.3, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 7.65, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 2.21, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.57, economicLean: -1.8, socialLean: -2.8, turnout: 62 },
    },
  },
  {
    stateId: "CA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.31, economicLean: -3.5, socialLean: -3, turnout: 41 },
      evangelicals: { population: 10.47, economicLean: 3.5, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 8.65, economicLean: 3.3, socialLean: 3.2, turnout: 64 },
      union_trades: { population: 6.16, economicLean: -3.6, socialLean: -0.1, turnout: 52 },
      soccer_moms: { population: 15.66, economicLean: -0.6, socialLean: -0.1, turnout: 59 },
      college_liberals: { population: 7.6, economicLean: -4.1, socialLean: -4.1, turnout: 59 },
      small_business: { population: 10.63, economicLean: 3.8, socialLean: 1.9, turnout: 65 },
      public_sector: { population: 4.15, economicLean: -3.1, socialLean: -2.6, turnout: 58 },
      retirees: { population: 10.12, economicLean: 0.2, socialLean: 1.7, turnout: 70 },
      libertarians: { population: 5.65, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 3.42, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 6.2, economicLean: -2.6, socialLean: -3.6, turnout: 62 },
    },
  },
  {
    stateId: "CO",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.7, economicLean: -3.5, socialLean: -3, turnout: 41 },
      evangelicals: { population: 12.01, economicLean: 3.6, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 10.85, economicLean: 3.6, socialLean: 3.6, turnout: 64 },
      union_trades: { population: 5.51, economicLean: -3.3, socialLean: 0.2, turnout: 52 },
      soccer_moms: { population: 16.39, economicLean: -0.3, socialLean: 0.2, turnout: 59 },
      college_liberals: { population: 7.58, economicLean: -3.8, socialLean: -3.8, turnout: 59 },
      small_business: { population: 10.82, economicLean: 4, socialLean: 2, turnout: 65 },
      public_sector: { population: 3.11, economicLean: -2.8, socialLean: -2.3, turnout: 58 },
      retirees: { population: 10.08, economicLean: 0.6, socialLean: 2.1, turnout: 70 },
      libertarians: { population: 7.35, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 1.42, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 5.18, economicLean: -2.3, socialLean: -3.3, turnout: 62 },
    },
  },
  {
    stateId: "CT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.23, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 9.13, economicLean: 3.3, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 9.46, economicLean: 3.2, socialLean: 3.1, turnout: 64 },
      union_trades: { population: 6.47, economicLean: -3.7, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 16.23, economicLean: -0.8, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 8.24, economicLean: -4.3, socialLean: -4.3, turnout: 59 },
      small_business: { population: 12.26, economicLean: 3.7, socialLean: 1.8, turnout: 65 },
      public_sector: { population: 4.04, economicLean: -3.3, socialLean: -2.8, turnout: 58 },
      retirees: { population: 11.89, economicLean: 0.1, socialLean: 1.6, turnout: 70 },
      libertarians: { population: 6.03, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.73, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 6.29, economicLean: -2.8, socialLean: -3.8, turnout: 62 },
    },
  },
  {
    stateId: "DE",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.25, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 10.81, economicLean: 3.6, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 10, economicLean: 3.5, socialLean: 3.5, turnout: 64 },
      union_trades: { population: 7.52, economicLean: -3.5, socialLean: 0, turnout: 52 },
      soccer_moms: { population: 16.51, economicLean: -0.5, socialLean: 0, turnout: 59 },
      college_liberals: { population: 7.18, economicLean: -4, socialLean: -4, turnout: 59 },
      small_business: { population: 11.2, economicLean: 3.8, socialLean: 2, turnout: 65 },
      public_sector: { population: 3.34, economicLean: -3, socialLean: -2.5, turnout: 58 },
      retirees: { population: 11.88, economicLean: 0.5, socialLean: 2, turnout: 70 },
      libertarians: { population: 5.89, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.29, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 5.12, economicLean: -2.5, socialLean: -3.5, turnout: 62 },
    },
  },
  {
    stateId: "FL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.82, economicLean: -3.5, socialLean: -3, turnout: 44 },
      evangelicals: { population: 13.64, economicLean: 4, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 11.8, economicLean: 4.1, socialLean: 4.3, turnout: 64 },
      union_trades: { population: 6.48, economicLean: -3.1, socialLean: 0.6, turnout: 52 },
      soccer_moms: { population: 15.19, economicLean: 0.3, socialLean: 0.8, turnout: 59 },
      college_liberals: { population: 5.75, economicLean: -3.2, socialLean: -3.2, turnout: 59 },
      small_business: { population: 10.21, economicLean: 4, socialLean: 2.3, turnout: 65 },
      public_sector: { population: 2.31, economicLean: -2.2, socialLean: -1.7, turnout: 58 },
      retirees: { population: 13.54, economicLean: 1.3, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 6.11, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 1.31, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.83, economicLean: -1.7, socialLean: -2.7, turnout: 62 },
    },
  },
  {
    stateId: "GA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.43, economicLean: -3.5, socialLean: -3, turnout: 41 },
      evangelicals: { population: 20.54, economicLean: 4.9, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.82, economicLean: 4.6, socialLean: 4.9, turnout: 64 },
      union_trades: { population: 7.72, economicLean: -2.9, socialLean: 1.3, turnout: 52 },
      soccer_moms: { population: 15.12, economicLean: 1.3, socialLean: 1.8, turnout: 59 },
      college_liberals: { population: 4.76, economicLean: -2.2, socialLean: -2.2, turnout: 59 },
      small_business: { population: 8.84, economicLean: 4, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.99, economicLean: -1.2, socialLean: -0.7, turnout: 58 },
      retirees: { population: 9.72, economicLean: 1.9, socialLean: 3.4, turnout: 70 },
      libertarians: { population: 4.99, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.25, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.83, economicLean: -0.7, socialLean: -1.7, turnout: 62 },
    },
  },
  {
    stateId: "HI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.76, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 7.63, economicLean: 3.4, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 6.3, economicLean: 3, socialLean: 2.9, turnout: 64 },
      union_trades: { population: 5.42, economicLean: -3.8, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 17.7, economicLean: -0.8, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 8.12, economicLean: -4.3, socialLean: -4.3, turnout: 59 },
      small_business: { population: 10.05, economicLean: 3.6, socialLean: 1.8, turnout: 65 },
      public_sector: { population: 5.63, economicLean: -3.3, socialLean: -2.8, turnout: 58 },
      retirees: { population: 10.69, economicLean: -0.1, socialLean: 1.4, turnout: 70 },
      libertarians: { population: 3.54, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 4.85, economicLean: -2.5, socialLean: -1.5, turnout: 31 },
      secular_professionals: { population: 7.31, economicLean: -2.8, socialLean: -3.8, turnout: 62 },
    },
  },
  {
    stateId: "IA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.77, economicLean: -3.5, socialLean: -3, turnout: 43 },
      evangelicals: { population: 14.18, economicLean: 4, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.63, economicLean: 4.1, socialLean: 4.3, turnout: 64 },
      union_trades: { population: 5.53, economicLean: -3.2, socialLean: 0.5, turnout: 52 },
      soccer_moms: { population: 16.66, economicLean: 0.2, socialLean: 0.7, turnout: 59 },
      college_liberals: { population: 6.05, economicLean: -3.3, socialLean: -3.3, turnout: 59 },
      small_business: { population: 10.22, economicLean: 4, socialLean: 2.3, turnout: 65 },
      public_sector: { population: 2.17, economicLean: -2.3, socialLean: -1.8, turnout: 58 },
      retirees: { population: 12.57, economicLean: 1.3, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 6.97, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.17, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.09, economicLean: -1.8, socialLean: -2.8, turnout: 62 },
    },
  },
  {
    stateId: "ID",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.08, economicLean: -3.5, socialLean: -3, turnout: 41 },
      evangelicals: { population: 15.49, economicLean: 4.2, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 14.28, economicLean: 4.7, socialLean: 5, turnout: 64 },
      union_trades: { population: 4.8, economicLean: -2.9, socialLean: 0.9, turnout: 52 },
      soccer_moms: { population: 15.6, economicLean: 0.7, socialLean: 1.2, turnout: 59 },
      college_liberals: { population: 5.19, economicLean: -2.8, socialLean: -2.8, turnout: 59 },
      small_business: { population: 10.6, economicLean: 4.4, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.38, economicLean: -1.8, socialLean: -1.3, turnout: 58 },
      retirees: { population: 10.91, economicLean: 2, socialLean: 3.5, turnout: 70 },
      libertarians: { population: 8.54, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.55, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.57, economicLean: -1.3, socialLean: -2.3, turnout: 62 },
    },
  },
  {
    stateId: "IL",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.5, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 11.36, economicLean: 3.7, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 10.11, economicLean: 3.5, socialLean: 3.6, turnout: 64 },
      union_trades: { population: 7.42, economicLean: -3.5, socialLean: 0.1, turnout: 52 },
      soccer_moms: { population: 16.09, economicLean: -0.3, socialLean: 0.2, turnout: 59 },
      college_liberals: { population: 7.02, economicLean: -3.8, socialLean: -3.8, turnout: 59 },
      small_business: { population: 10.74, economicLean: 3.8, socialLean: 2, turnout: 65 },
      public_sector: { population: 3.59, economicLean: -2.8, socialLean: -2.3, turnout: 58 },
      retirees: { population: 11.32, economicLean: 0.6, socialLean: 2.1, turnout: 70 },
      libertarians: { population: 6, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.95, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 4.91, economicLean: -2.3, socialLean: -3.3, turnout: 62 },
    },
  },
  {
    stateId: "IN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.13, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 16.62, economicLean: 4.3, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.2, economicLean: 4.4, socialLean: 4.7, turnout: 64 },
      union_trades: { population: 5.96, economicLean: -3, socialLean: 0.9, turnout: 52 },
      soccer_moms: { population: 16.16, economicLean: 0.7, socialLean: 1.2, turnout: 59 },
      college_liberals: { population: 5.3, economicLean: -2.8, socialLean: -2.8, turnout: 59 },
      small_business: { population: 9.83, economicLean: 4, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 1.86, economicLean: -1.8, socialLean: -1.3, turnout: 58 },
      retirees: { population: 11.42, economicLean: 1.7, socialLean: 3.2, turnout: 70 },
      libertarians: { population: 6.6, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.25, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.68, economicLean: -1.3, socialLean: -2.3, turnout: 62 },
    },
  },
  {
    stateId: "KS",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.62, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 16.4, economicLean: 4.3, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.57, economicLean: 4.3, socialLean: 4.6, turnout: 64 },
      union_trades: { population: 5.54, economicLean: -3.1, socialLean: 0.9, turnout: 52 },
      soccer_moms: { population: 15.93, economicLean: 0.7, socialLean: 1.2, turnout: 59 },
      college_liberals: { population: 5.55, economicLean: -2.8, socialLean: -2.8, turnout: 59 },
      small_business: { population: 10.28, economicLean: 4.1, socialLean: 2.4, turnout: 65 },
      public_sector: { population: 2.03, economicLean: -1.8, socialLean: -1.3, turnout: 58 },
      retirees: { population: 11.44, economicLean: 1.6, socialLean: 3.1, turnout: 70 },
      libertarians: { population: 7.17, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.45, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.01, economicLean: -1.3, socialLean: -2.3, turnout: 62 },
    },
  },
  {
    stateId: "KY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.47, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 19.53, economicLean: 4.7, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.98, economicLean: 4.7, socialLean: 5, turnout: 64 },
      union_trades: { population: 5.97, economicLean: -2.9, socialLean: 1.2, turnout: 52 },
      soccer_moms: { population: 15.01, economicLean: 1.1, socialLean: 1.6, turnout: 59 },
      college_liberals: { population: 4.78, economicLean: -2.4, socialLean: -2.4, turnout: 59 },
      small_business: { population: 9.13, economicLean: 4, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.49, economicLean: -1.4, socialLean: -0.9, turnout: 58 },
      retirees: { population: 11.16, economicLean: 2, socialLean: 3.5, turnout: 70 },
      libertarians: { population: 6.16, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.14, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.18, economicLean: -0.9, socialLean: -1.9, turnout: 62 },
    },
  },
  {
    stateId: "LA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.49, economicLean: -3.5, socialLean: -3, turnout: 41 },
      evangelicals: { population: 19.94, economicLean: 4.8, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.89, economicLean: 4.6, socialLean: 4.9, turnout: 64 },
      union_trades: { population: 8.68, economicLean: -2.9, socialLean: 1.3, turnout: 52 },
      soccer_moms: { population: 14.65, economicLean: 1.2, socialLean: 1.7, turnout: 59 },
      college_liberals: { population: 4.55, economicLean: -2.3, socialLean: -2.3, turnout: 59 },
      small_business: { population: 8.19, economicLean: 4, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.93, economicLean: -1.3, socialLean: -0.8, turnout: 58 },
      retirees: { population: 10.03, economicLean: 1.9, socialLean: 3.4, turnout: 70 },
      libertarians: { population: 4.92, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.25, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.47, economicLean: -0.8, socialLean: -1.8, turnout: 62 },
    },
  },
  {
    stateId: "MA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.51, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 8.39, economicLean: 3.2, socialLean: 4.8, turnout: 72 },
      rural_traditionalists: { population: 8.92, economicLean: 2.9, socialLean: 2.8, turnout: 64 },
      union_trades: { population: 6.74, economicLean: -3.9, socialLean: -0.4, turnout: 52 },
      soccer_moms: { population: 16.01, economicLean: -1.1, socialLean: -0.6, turnout: 59 },
      college_liberals: { population: 8.9, economicLean: -4.6, socialLean: -4.6, turnout: 59 },
      small_business: { population: 11.69, economicLean: 3.6, socialLean: 1.7, turnout: 65 },
      public_sector: { population: 4.78, economicLean: -3.6, socialLean: -3.1, turnout: 58 },
      retirees: { population: 11.83, economicLean: -0.2, socialLean: 1.3, turnout: 70 },
      libertarians: { population: 6.15, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.62, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 6.47, economicLean: -3.1, socialLean: -4.1, turnout: 62 },
    },
  },
  {
    stateId: "MD",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.91, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 9.68, economicLean: 3.5, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 8.85, economicLean: 3.2, socialLean: 3.2, turnout: 64 },
      union_trades: { population: 8.59, economicLean: -3.7, socialLean: -0.1, turnout: 52 },
      soccer_moms: { population: 16.25, economicLean: -0.7, socialLean: -0.2, turnout: 59 },
      college_liberals: { population: 7.93, economicLean: -4.2, socialLean: -4.2, turnout: 59 },
      small_business: { population: 11.31, economicLean: 3.7, socialLean: 1.9, turnout: 65 },
      public_sector: { population: 4.43, economicLean: -3.2, socialLean: -2.7, turnout: 58 },
      retirees: { population: 10.92, economicLean: 0.1, socialLean: 1.7, turnout: 70 },
      libertarians: { population: 5.4, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.49, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 6.24, economicLean: -2.7, socialLean: -3.7, turnout: 62 },
    },
  },
  {
    stateId: "ME",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.94, economicLean: -3.5, socialLean: -3, turnout: 43 },
      evangelicals: { population: 10.17, economicLean: 3.3, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 11.61, economicLean: 3.5, socialLean: 3.6, turnout: 64 },
      union_trades: { population: 5.92, economicLean: -3.5, socialLean: -0.1, turnout: 52 },
      soccer_moms: { population: 16.45, economicLean: -0.7, socialLean: -0.2, turnout: 59 },
      college_liberals: { population: 7.48, economicLean: -4.2, socialLean: -4.2, turnout: 59 },
      small_business: { population: 11.06, economicLean: 4, socialLean: 2, turnout: 65 },
      public_sector: { population: 2.8, economicLean: -3.2, socialLean: -2.7, turnout: 58 },
      retirees: { population: 12.43, economicLean: 0.6, socialLean: 2.1, turnout: 70 },
      libertarians: { population: 7.52, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 4.48, economicLean: -2.7, socialLean: -3.7, turnout: 62 },
    },
  },
  {
    stateId: "MI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.58, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 12.9, economicLean: 3.9, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 11.95, economicLean: 3.9, socialLean: 4.1, turnout: 64 },
      union_trades: { population: 7.16, economicLean: -3.3, socialLean: 0.4, turnout: 52 },
      soccer_moms: { population: 16.2, economicLean: 0, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 6.3, economicLean: -3.5, socialLean: -3.5, turnout: 59 },
      small_business: { population: 10.28, economicLean: 3.9, socialLean: 2.2, turnout: 65 },
      public_sector: { population: 2.8, economicLean: -2.5, socialLean: -2, turnout: 58 },
      retirees: { population: 11.36, economicLean: 1.1, socialLean: 2.6, turnout: 70 },
      libertarians: { population: 6.2, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.28, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.99, economicLean: -2, socialLean: -3, turnout: 62 },
    },
  },
  {
    stateId: "MN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.59, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 11.89, economicLean: 3.6, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 11.16, economicLean: 3.5, socialLean: 3.5, turnout: 64 },
      union_trades: { population: 6.01, economicLean: -3.6, socialLean: 0, turnout: 52 },
      soccer_moms: { population: 16.55, economicLean: -0.5, socialLean: 0, turnout: 59 },
      college_liberals: { population: 7.66, economicLean: -4, socialLean: -4, turnout: 59 },
      small_business: { population: 10.37, economicLean: 3.8, socialLean: 2, turnout: 65 },
      public_sector: { population: 3.64, economicLean: -3, socialLean: -2.5, turnout: 58 },
      retirees: { population: 11.66, economicLean: 0.5, socialLean: 2, turnout: 70 },
      libertarians: { population: 6.52, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.24, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 4.72, economicLean: -2.5, socialLean: -3.5, turnout: 62 },
    },
  },
  {
    stateId: "MO",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.04, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 16.47, economicLean: 4.3, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.61, economicLean: 4.3, socialLean: 4.5, turnout: 64 },
      union_trades: { population: 6.47, economicLean: -3.1, socialLean: 0.8, turnout: 52 },
      soccer_moms: { population: 15.62, economicLean: 0.6, socialLean: 1.1, turnout: 59 },
      college_liberals: { population: 5.52, economicLean: -2.9, socialLean: -2.9, turnout: 59 },
      small_business: { population: 9.88, economicLean: 4, socialLean: 2.4, turnout: 65 },
      public_sector: { population: 2.19, economicLean: -1.9, socialLean: -1.4, turnout: 58 },
      retirees: { population: 11.56, economicLean: 1.5, socialLean: 3, turnout: 70 },
      libertarians: { population: 6.5, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.99, economicLean: -1.4, socialLean: -2.4, turnout: 62 },
    },
  },
  {
    stateId: "MS",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.56, economicLean: -3.5, socialLean: -3, turnout: 41 },
      evangelicals: { population: 23.55, economicLean: 5, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.02, economicLean: 4.8, socialLean: 5, turnout: 64 },
      union_trades: { population: 8.91, economicLean: -2.8, socialLean: 1.7, turnout: 52 },
      soccer_moms: { population: 13.77, economicLean: 1.7, socialLean: 2.2, turnout: 59 },
      college_liberals: { population: 3.97, economicLean: -1.8, socialLean: -1.8, turnout: 59 },
      small_business: { population: 7.33, economicLean: 4, socialLean: 2.7, turnout: 65 },
      public_sector: { population: 1.59, economicLean: -0.8, socialLean: -0.3, turnout: 58 },
      retirees: { population: 9.88, economicLean: 2.2, socialLean: 3.7, turnout: 70 },
      libertarians: { population: 4.3, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 1.98, economicLean: -0.3, socialLean: -1.3, turnout: 62 },
    },
  },
  {
    stateId: "MT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.93, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 12.75, economicLean: 3.8, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 14.02, economicLean: 4.4, socialLean: 4.7, turnout: 64 },
      union_trades: { population: 5.2, economicLean: -3.1, socialLean: 0.5, turnout: 52 },
      soccer_moms: { population: 15.62, economicLean: 0.1, socialLean: 0.6, turnout: 59 },
      college_liberals: { population: 6.09, economicLean: -3.4, socialLean: -3.4, turnout: 59 },
      small_business: { population: 10.64, economicLean: 4.3, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 1.98, economicLean: -2.4, socialLean: -1.9, turnout: 58 },
      retirees: { population: 11.61, economicLean: 1.7, socialLean: 3.2, turnout: 70 },
      libertarians: { population: 8.64, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.34, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.18, economicLean: -1.9, socialLean: -2.9, turnout: 62 },
    },
  },
  {
    stateId: "NC",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.2, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 19.95, economicLean: 4.7, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.68, economicLean: 4.5, socialLean: 4.8, turnout: 64 },
      union_trades: { population: 7.26, economicLean: -3, socialLean: 1.2, turnout: 52 },
      soccer_moms: { population: 15.27, economicLean: 1.1, socialLean: 1.6, turnout: 59 },
      college_liberals: { population: 4.97, economicLean: -2.4, socialLean: -2.4, turnout: 59 },
      small_business: { population: 8.96, economicLean: 4, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 1.94, economicLean: -1.4, socialLean: -0.9, turnout: 58 },
      retirees: { population: 10.5, economicLean: 1.8, socialLean: 3.3, turnout: 70 },
      libertarians: { population: 5.22, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.17, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.87, economicLean: -0.9, socialLean: -1.9, turnout: 62 },
    },
  },
  {
    stateId: "ND",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 15.24, economicLean: 4.2, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.53, economicLean: 4.5, socialLean: 4.7, turnout: 64 },
      union_trades: { population: 5.17, economicLean: -3, socialLean: 0.8, turnout: 52 },
      soccer_moms: { population: 16.26, economicLean: 0.6, socialLean: 1.1, turnout: 59 },
      college_liberals: { population: 5.45, economicLean: -2.9, socialLean: -2.9, turnout: 59 },
      small_business: { population: 10.33, economicLean: 4.2, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 1.67, economicLean: -1.9, socialLean: -1.4, turnout: 58 },
      retirees: { population: 12.08, economicLean: 1.7, socialLean: 3.2, turnout: 70 },
      libertarians: { population: 7.53, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.2, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.55, economicLean: -1.4, socialLean: -2.4, turnout: 62 },
    },
  },
  {
    stateId: "NE",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.81, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 15.62, economicLean: 4.2, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.26, economicLean: 4.4, socialLean: 4.7, turnout: 64 },
      union_trades: { population: 5.4, economicLean: -3, socialLean: 0.8, turnout: 52 },
      soccer_moms: { population: 16.49, economicLean: 0.6, socialLean: 1.1, turnout: 59 },
      college_liberals: { population: 5.48, economicLean: -2.9, socialLean: -2.9, turnout: 59 },
      small_business: { population: 10.29, economicLean: 4.1, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 1.72, economicLean: -1.9, socialLean: -1.4, turnout: 58 },
      retirees: { population: 11.8, economicLean: 1.7, socialLean: 3.2, turnout: 70 },
      libertarians: { population: 7.15, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.25, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.73, economicLean: -1.4, socialLean: -2.4, turnout: 62 },
    },
  },
  {
    stateId: "NH",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 8.86, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 9.96, economicLean: 3.4, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 11.6, economicLean: 3.7, socialLean: 3.8, turnout: 64 },
      union_trades: { population: 5.19, economicLean: -3.4, socialLean: 0, turnout: 52 },
      soccer_moms: { population: 16.95, economicLean: -0.5, socialLean: 0, turnout: 59 },
      college_liberals: { population: 7.24, economicLean: -4, socialLean: -4, turnout: 59 },
      small_business: { population: 12.5, economicLean: 4.2, socialLean: 2.1, turnout: 65 },
      public_sector: { population: 2.67, economicLean: -3, socialLean: -2.5, turnout: 58 },
      retirees: { population: 11.44, economicLean: 0.8, socialLean: 2.3, turnout: 70 },
      libertarians: { population: 8.74, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 4.69, economicLean: -2.5, socialLean: -3.5, turnout: 62 },
    },
  },
  {
    stateId: "NJ",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.87, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 8.7, economicLean: 3.4, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 9.28, economicLean: 3.3, socialLean: 3.2, turnout: 64 },
      union_trades: { population: 7.1, economicLean: -3.6, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 16.2, economicLean: -0.7, socialLean: -0.2, turnout: 59 },
      college_liberals: { population: 7.9, economicLean: -4.2, socialLean: -4.2, turnout: 59 },
      small_business: { population: 12.08, economicLean: 3.7, socialLean: 1.9, turnout: 65 },
      public_sector: { population: 4.12, economicLean: -3.2, socialLean: -2.7, turnout: 58 },
      retirees: { population: 11.6, economicLean: 0.2, socialLean: 1.7, turnout: 70 },
      libertarians: { population: 5.7, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 1.25, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 6.19, economicLean: -2.7, socialLean: -3.7, turnout: 62 },
    },
  },
  {
    stateId: "NM",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 12.58, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 11.35, economicLean: 3.7, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 9.74, economicLean: 3.7, socialLean: 3.7, turnout: 64 },
      union_trades: { population: 5.71, economicLean: -3.4, socialLean: 0.2, turnout: 52 },
      soccer_moms: { population: 15.54, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.57, economicLean: -3.7, socialLean: -3.7, turnout: 59 },
      small_business: { population: 9.21, economicLean: 3.9, socialLean: 2.1, turnout: 65 },
      public_sector: { population: 3.6, economicLean: -2.7, socialLean: -2.2, turnout: 58 },
      retirees: { population: 10.81, economicLean: 0.7, socialLean: 2.2, turnout: 70 },
      libertarians: { population: 5.47, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 4.63, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 4.8, economicLean: -2.2, socialLean: -3.2, turnout: 62 },
    },
  },
  {
    stateId: "NV",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.69, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 11.04, economicLean: 3.7, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 11.9, economicLean: 4.1, socialLean: 4.3, turnout: 64 },
      union_trades: { population: 5.54, economicLean: -3.2, socialLean: 0.4, turnout: 52 },
      soccer_moms: { population: 16.85, economicLean: 0, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 5.5, economicLean: -3.5, socialLean: -3.5, turnout: 59 },
      small_business: { population: 12.08, economicLean: 4.3, socialLean: 2.3, turnout: 65 },
      public_sector: { population: 1.95, economicLean: -2.5, socialLean: -2, turnout: 58 },
      retirees: { population: 10.59, economicLean: 1.3, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 9.05, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 1.24, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.57, economicLean: -2, socialLean: -3, turnout: 62 },
    },
  },
  {
    stateId: "NY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.86, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 8.85, economicLean: 3.4, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 8.96, economicLean: 3.2, socialLean: 3.1, turnout: 64 },
      union_trades: { population: 7.82, economicLean: -3.8, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 15.57, economicLean: -0.8, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 7.98, economicLean: -4.3, socialLean: -4.3, turnout: 59 },
      small_business: { population: 10.9, economicLean: 3.6, socialLean: 1.8, turnout: 65 },
      public_sector: { population: 4.64, economicLean: -3.3, socialLean: -2.8, turnout: 58 },
      retirees: { population: 11.33, economicLean: 0.1, socialLean: 1.6, turnout: 70 },
      libertarians: { population: 5.47, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 1.55, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 6.07, economicLean: -2.8, socialLean: -3.8, turnout: 62 },
    },
  },
  {
    stateId: "OH",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.22, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 13.41, economicLean: 3.9, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.5, economicLean: 4.1, socialLean: 4.3, turnout: 64 },
      union_trades: { population: 6.67, economicLean: -3.2, socialLean: 0.5, turnout: 52 },
      soccer_moms: { population: 16.13, economicLean: 0.1, socialLean: 0.6, turnout: 59 },
      college_liberals: { population: 6.03, economicLean: -3.4, socialLean: -3.4, turnout: 59 },
      small_business: { population: 10.32, economicLean: 4, socialLean: 2.3, turnout: 65 },
      public_sector: { population: 2.47, economicLean: -2.4, socialLean: -1.9, turnout: 58 },
      retirees: { population: 11.87, economicLean: 1.3, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 6.67, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.55, economicLean: -1.9, socialLean: -2.9, turnout: 62 },
    },
  },
  {
    stateId: "OK",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.2, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 21.49, economicLean: 4.9, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.4, economicLean: 4.7, socialLean: 5, turnout: 64 },
      union_trades: { population: 5.47, economicLean: -2.8, socialLean: 1.5, turnout: 52 },
      soccer_moms: { population: 14.8, economicLean: 1.5, socialLean: 2, turnout: 59 },
      college_liberals: { population: 4.6, economicLean: -2, socialLean: -2, turnout: 59 },
      small_business: { population: 8.96, economicLean: 4.1, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.39, economicLean: -1, socialLean: -0.5, turnout: 58 },
      retirees: { population: 10.92, economicLean: 2.1, socialLean: 3.6, turnout: 70 },
      libertarians: { population: 6.05, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.47, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.25, economicLean: -0.5, socialLean: -1.5, turnout: 62 },
    },
  },
  {
    stateId: "OR",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.75, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 10.82, economicLean: 3.3, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 10.95, economicLean: 3.3, socialLean: 3.3, turnout: 64 },
      union_trades: { population: 5.97, economicLean: -3.6, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 15.95, economicLean: -0.7, socialLean: -0.2, turnout: 59 },
      college_liberals: { population: 7.97, economicLean: -4.2, socialLean: -4.2, turnout: 59 },
      small_business: { population: 10.63, economicLean: 3.9, socialLean: 1.9, turnout: 65 },
      public_sector: { population: 3.33, economicLean: -3.2, socialLean: -2.7, turnout: 58 },
      retirees: { population: 11.56, economicLean: 0.3, socialLean: 1.8, turnout: 70 },
      libertarians: { population: 7.41, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.51, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 5.14, economicLean: -2.7, socialLean: -3.7, turnout: 62 },
    },
  },
  {
    stateId: "PA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.83, economicLean: -3.5, socialLean: -3, turnout: 43 },
      evangelicals: { population: 12.25, economicLean: 3.8, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.66, economicLean: 4.1, socialLean: 4.2, turnout: 64 },
      union_trades: { population: 6.41, economicLean: -3.2, socialLean: 0.4, turnout: 52 },
      soccer_moms: { population: 16.16, economicLean: 0, socialLean: 0.5, turnout: 59 },
      college_liberals: { population: 6.32, economicLean: -3.5, socialLean: -3.5, turnout: 59 },
      small_business: { population: 10.68, economicLean: 3.9, socialLean: 2.3, turnout: 65 },
      public_sector: { population: 2.53, economicLean: -2.5, socialLean: -2, turnout: 58 },
      retirees: { population: 12.59, economicLean: 1.2, socialLean: 2.7, turnout: 70 },
      libertarians: { population: 6.42, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.25, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.88, economicLean: -2, socialLean: -3, turnout: 62 },
    },
  },
  {
    stateId: "RI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.27, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 8.67, economicLean: 3.3, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 9.67, economicLean: 3.1, socialLean: 3.1, turnout: 64 },
      union_trades: { population: 6.73, economicLean: -3.7, socialLean: -0.3, turnout: 52 },
      soccer_moms: { population: 16.62, economicLean: -0.9, socialLean: -0.4, turnout: 59 },
      college_liberals: { population: 8.08, economicLean: -4.4, socialLean: -4.4, turnout: 59 },
      small_business: { population: 11.04, economicLean: 3.7, socialLean: 1.8, turnout: 65 },
      public_sector: { population: 4.11, economicLean: -3.4, socialLean: -2.9, turnout: 58 },
      retirees: { population: 12.51, economicLean: 0, socialLean: 1.6, turnout: 70 },
      libertarians: { population: 6.35, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.63, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 5.33, economicLean: -2.9, socialLean: -3.9, turnout: 62 },
    },
  },
  {
    stateId: "SC",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.65, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 21.29, economicLean: 4.9, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.14, economicLean: 4.7, socialLean: 5, turnout: 64 },
      union_trades: { population: 8.03, economicLean: -2.8, socialLean: 1.5, turnout: 52 },
      soccer_moms: { population: 14.81, economicLean: 1.5, socialLean: 2, turnout: 59 },
      college_liberals: { population: 4.4, economicLean: -2, socialLean: -2, turnout: 59 },
      small_business: { population: 8.49, economicLean: 4, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.66, economicLean: -1, socialLean: -0.5, turnout: 58 },
      retirees: { population: 9.95, economicLean: 2.1, socialLean: 3.6, turnout: 70 },
      libertarians: { population: 4.89, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.54, economicLean: -0.5, socialLean: -1.5, turnout: 62 },
    },
  },
  {
    stateId: "SD",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.29, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 15.56, economicLean: 4.2, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.63, economicLean: 4.5, socialLean: 4.8, turnout: 64 },
      union_trades: { population: 5.29, economicLean: -3, socialLean: 0.8, turnout: 52 },
      soccer_moms: { population: 15.81, economicLean: 0.6, socialLean: 1.1, turnout: 59 },
      college_liberals: { population: 5.31, economicLean: -2.9, socialLean: -2.9, turnout: 59 },
      small_business: { population: 10.08, economicLean: 4.2, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 1.65, economicLean: -1.9, socialLean: -1.4, turnout: 58 },
      retirees: { population: 12.25, economicLean: 1.8, socialLean: 3.3, turnout: 70 },
      libertarians: { population: 7.43, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.22, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.48, economicLean: -1.4, socialLean: -2.4, turnout: 62 },
    },
  },
  {
    stateId: "TN",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.17, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 21.41, economicLean: 4.9, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 13.58, economicLean: 4.7, socialLean: 5, turnout: 64 },
      union_trades: { population: 6.57, economicLean: -2.9, socialLean: 1.4, turnout: 52 },
      soccer_moms: { population: 14.88, economicLean: 1.4, socialLean: 1.9, turnout: 59 },
      college_liberals: { population: 4.63, economicLean: -2.1, socialLean: -2.1, turnout: 59 },
      small_business: { population: 8.85, economicLean: 4, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.56, economicLean: -1.1, socialLean: -0.6, turnout: 58 },
      retirees: { population: 10.49, economicLean: 2.1, socialLean: 3.6, turnout: 70 },
      libertarians: { population: 5.39, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.14, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.34, economicLean: -0.6, socialLean: -1.6, turnout: 62 },
    },
  },
  {
    stateId: "TX",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 11.3, economicLean: -3.5, socialLean: -3, turnout: 41 },
      evangelicals: { population: 17.41, economicLean: 4.5, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12.15, economicLean: 4.5, socialLean: 4.7, turnout: 64 },
      union_trades: { population: 6.04, economicLean: -3, socialLean: 1.1, turnout: 52 },
      soccer_moms: { population: 15.2, economicLean: 0.9, socialLean: 1.4, turnout: 59 },
      college_liberals: { population: 4.91, economicLean: -2.6, socialLean: -2.6, turnout: 59 },
      small_business: { population: 9.31, economicLean: 4.1, socialLean: 2.5, turnout: 65 },
      public_sector: { population: 2.15, economicLean: -1.6, socialLean: -1.1, turnout: 58 },
      retirees: { population: 9.7, economicLean: 1.7, socialLean: 3.2, turnout: 70 },
      libertarians: { population: 5.85, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 2.82, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 3.15, economicLean: -1.1, socialLean: -2.1, turnout: 62 },
    },
  },
  {
    stateId: "UT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.19, economicLean: -3.5, socialLean: -3, turnout: 38 },
      evangelicals: { population: 21.08, economicLean: 4.8, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 11.8, economicLean: 4.3, socialLean: 4.5, turnout: 64 },
      union_trades: { population: 4.58, economicLean: -3, socialLean: 1.3, turnout: 52 },
      soccer_moms: { population: 16.14, economicLean: 1.2, socialLean: 1.7, turnout: 59 },
      college_liberals: { population: 5.25, economicLean: -2.3, socialLean: -2.3, turnout: 59 },
      small_business: { population: 9.76, economicLean: 4.2, socialLean: 2.4, turnout: 65 },
      public_sector: { population: 1.51, economicLean: -1.3, socialLean: -0.8, turnout: 58 },
      retirees: { population: 9.39, economicLean: 1.5, socialLean: 3, turnout: 70 },
      libertarians: { population: 7.12, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.58, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.6, economicLean: -0.8, socialLean: -1.8, turnout: 62 },
    },
  },
  {
    stateId: "VA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.8, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 15.28, economicLean: 4.2, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 11.96, economicLean: 4.1, socialLean: 4.3, turnout: 64 },
      union_trades: { population: 7.09, economicLean: -3.1, socialLean: 0.7, turnout: 52 },
      soccer_moms: { population: 15.83, economicLean: 0.5, socialLean: 1, turnout: 59 },
      college_liberals: { population: 6.16, economicLean: -3, socialLean: -3, turnout: 59 },
      small_business: { population: 10.44, economicLean: 3.9, socialLean: 2.3, turnout: 65 },
      public_sector: { population: 2.75, economicLean: -2, socialLean: -1.5, turnout: 58 },
      retirees: { population: 10.32, economicLean: 1.3, socialLean: 2.8, turnout: 70 },
      libertarians: { population: 5.77, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.41, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 4.19, economicLean: -1.5, socialLean: -2.5, turnout: 62 },
    },
  },
  {
    stateId: "VT",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.57, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 9.12, economicLean: 3.1, socialLean: 4.7, turnout: 72 },
      rural_traditionalists: { population: 10.51, economicLean: 3.1, socialLean: 3, turnout: 64 },
      union_trades: { population: 6.22, economicLean: -3.8, socialLean: -0.4, turnout: 52 },
      soccer_moms: { population: 16.47, economicLean: -1.1, socialLean: -0.6, turnout: 59 },
      college_liberals: { population: 8.71, economicLean: -4.6, socialLean: -4.6, turnout: 59 },
      small_business: { population: 10.78, economicLean: 3.8, socialLean: 1.8, turnout: 65 },
      public_sector: { population: 3.96, economicLean: -3.6, socialLean: -3.1, turnout: 58 },
      retirees: { population: 11.63, economicLean: 0, socialLean: 1.5, turnout: 70 },
      libertarians: { population: 7.38, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.15, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 5.5, economicLean: -3.1, socialLean: -4.1, turnout: 62 },
    },
  },
  {
    stateId: "WA",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.75, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 10.27, economicLean: 3.3, socialLean: 4.9, turnout: 72 },
      rural_traditionalists: { population: 10.61, economicLean: 3.3, socialLean: 3.2, turnout: 64 },
      union_trades: { population: 5.99, economicLean: -3.6, socialLean: -0.2, turnout: 52 },
      soccer_moms: { population: 16.27, economicLean: -0.8, socialLean: -0.3, turnout: 59 },
      college_liberals: { population: 8.26, economicLean: -4.3, socialLean: -4.3, turnout: 59 },
      small_business: { population: 10.84, economicLean: 3.8, socialLean: 1.9, turnout: 65 },
      public_sector: { population: 3.72, economicLean: -3.3, socialLean: -2.8, turnout: 58 },
      retirees: { population: 10.96, economicLean: 0.2, socialLean: 1.7, turnout: 70 },
      libertarians: { population: 6.97, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.64, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 5.71, economicLean: -2.8, socialLean: -3.8, turnout: 62 },
    },
  },
  {
    stateId: "WI",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.97, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 12.28, economicLean: 3.7, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 12, economicLean: 3.8, socialLean: 3.9, turnout: 64 },
      union_trades: { population: 6.14, economicLean: -3.4, socialLean: 0.2, turnout: 52 },
      soccer_moms: { population: 16.53, economicLean: -0.2, socialLean: 0.3, turnout: 59 },
      college_liberals: { population: 6.78, economicLean: -3.7, socialLean: -3.7, turnout: 59 },
      small_business: { population: 10.43, economicLean: 3.9, socialLean: 2.2, turnout: 65 },
      public_sector: { population: 3.01, economicLean: -2.7, socialLean: -2.2, turnout: 58 },
      retirees: { population: 11.72, economicLean: 0.9, socialLean: 2.4, turnout: 70 },
      libertarians: { population: 6.82, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.27, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 4.05, economicLean: -2.2, socialLean: -3.2, turnout: 62 },
    },
  },
  {
    stateId: "WV",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 10.78, economicLean: -3.5, socialLean: -3, turnout: 43 },
      evangelicals: { population: 17.62, economicLean: 4.5, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 14.72, economicLean: 4.7, socialLean: 5, turnout: 64 },
      union_trades: { population: 6.03, economicLean: -2.9, socialLean: 1.1, turnout: 52 },
      soccer_moms: { population: 14.67, economicLean: 0.9, socialLean: 1.4, turnout: 59 },
      college_liberals: { population: 4.88, economicLean: -2.6, socialLean: -2.6, turnout: 59 },
      small_business: { population: 9.08, economicLean: 4, socialLean: 2.6, turnout: 65 },
      public_sector: { population: 1.43, economicLean: -1.6, socialLean: -1.1, turnout: 58 },
      retirees: { population: 12.59, economicLean: 2.1, socialLean: 3.6, turnout: 70 },
      libertarians: { population: 6.16, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.1, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 1.95, economicLean: -1.1, socialLean: -2.1, turnout: 62 },
    },
  },
  {
    stateId: "WY",
    categoryWeights: {"voterGroups":100},
    groups: {
      young_renters: { population: 9.82, economicLean: -3.5, socialLean: -3, turnout: 42 },
      evangelicals: { population: 13.43, economicLean: 4, socialLean: 5, turnout: 72 },
      rural_traditionalists: { population: 14.93, economicLean: 4.8, socialLean: 5, turnout: 64 },
      union_trades: { population: 4.82, economicLean: -2.8, socialLean: 0.8, turnout: 52 },
      soccer_moms: { population: 16.05, economicLean: 0.5, socialLean: 1, turnout: 59 },
      college_liberals: { population: 5.25, economicLean: -3, socialLean: -3, turnout: 59 },
      small_business: { population: 10.93, economicLean: 4.4, socialLean: 2.7, turnout: 65 },
      public_sector: { population: 1.42, economicLean: -2, socialLean: -1.5, turnout: 58 },
      retirees: { population: 10.92, economicLean: 2.2, socialLean: 3.7, turnout: 70 },
      libertarians: { population: 9.2, economicLean: 5, socialLean: 1, turnout: 60 },
      new_immigrants: { population: 0.64, economicLean: -2.5, socialLean: -1.5, turnout: 30 },
      secular_professionals: { population: 2.59, economicLean: -1.5, socialLean: -2.5, turnout: 62 },
    },
  },
];
