import type { CatalogEntry } from "./catalog.js";
/**
 * CN legislation catalog. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateCatalogs.ts
 * Source: src/lib/seeds/cn/cnLegislationTypes.ts (62 types),
 * src/lib/politicalLegislation/marginAdapter.ts ADAPTER_TIER1 (target mapping),
 * src/lib/seeds/reference/budgets.ts policyDefaults (tax baselines). See the
 * generator header for the mapping rules and the PORT-STUB convention.
 */
export const CATALOG_CN: CatalogEntry[] = [
  {
    // source: cnLegislationTypes.ts cn_enterprise_income_tax; baselineRate from budget policyDefaults option cn_enterprise_income_tax_opt_5
    id: "cn_enterprise_income_tax",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Enterprise Income Tax Law",
    description: "Sets the headline enterprise income tax rate on corporate profits",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "domesticCorporateTax", minRate: 0, maxRate: 40, step: 2, baselineRate: 25 },
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.smallBusinessFormation","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.smallBusinessFormation,economic.manufacturingCompetitiveness,governance.budgetBalance",
  },
  {
    // source: cnLegislationTypes.ts cn_individual_income_tax; baselineRate from budget policyDefaults option cn_individual_income_tax_opt_5
    id: "cn_individual_income_tax",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Individual Income Tax Law",
    description: "Sets the top-bracket personal income tax rate",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "incomeTax", minRate: 0, maxRate: 50, step: 1, baselineRate: 35 },
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.povertyRate","weight":0.5},{"metricId":"society.socialMobility","weight":-0.6},{"metricId":"economic.gdpGrowth","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.povertyRate,economic.gdpGrowth",
  },
  {
    // source: cnLegislationTypes.ts cn_value_added_tax; baselineRate from budget policyDefaults option cn_value_added_tax_opt_5
    id: "cn_value_added_tax",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Value-Added Tax Law",
    description: "Sets the headline value-added tax rate",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "salesTax", minRate: 0, maxRate: 25, step: 2, baselineRate: 13 },
    targets: [{"metricId":"economic.costOfLiving","weight":-1},{"metricId":"economic.gdpGrowth","weight":-0.25},{"metricId":"economic.povertyRate","weight":-0.6},{"metricId":"economic.smallBusinessFormation","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.gdpGrowth,economic.povertyRate,economic.smallBusinessFormation",
  },
  {
    // source: cnLegislationTypes.ts cn_land_value_added_tax; baselineRate from budget policyDefaults option cn_land_value_added_tax_opt_5
    id: "cn_land_value_added_tax",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Land Value-Added Tax Law",
    description: "Sets the headline tax rate on capital gains from real-estate transactions",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "landValueAddedTax", minRate: 0, maxRate: 80, step: 5, baselineRate: 40 },
    targets: [{"metricId":"infrastructure.publicHousing","weight":1},{"metricId":"society.socialMobility","weight":-0.5},{"metricId":"social.wohnungsBauRate","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.wohnungsBauRate,governance.budgetBalance",
  },
  {
    // source: cnLegislationTypes.ts cn_urban_maintenance_construction_tax; baselineRate from budget policyDefaults option cn_urban_maintenance_construction_tax_opt_5
    id: "cn_urban_maintenance_construction_tax",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Urban Maintenance & Construction Tax Law",
    description: "Sets the surcharge rate on VAT funding municipal infrastructure",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "urbanMaintenanceTax", minRate: 0, maxRate: 15, step: 1, baselineRate: 7 },
    targets: [{"metricId":"infrastructure.highways","weight":1},{"metricId":"economic.costOfLiving","weight":0.3},{"metricId":"economic.gdpGrowth","weight":-0.2},{"metricId":"economic.ruralRevitalization","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.gdpGrowth,economic.ruralRevitalization",
  },
  {
    // source: cnLegislationTypes.ts cn_stamp_duty; baselineRate from budget policyDefaults option cn_stamp_duty_opt_5
    id: "cn_stamp_duty",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Stamp Duty Law",
    description: "Sets the documented-transaction tax rate on contracts and securities trades",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "stampDuty", minRate: 0, maxRate: 2, step: 0.009999999999999998, baselineRate: 0.05 },
    targets: [{"metricId":"economic.smallBusinessFormation","weight":1},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.gdpGrowth","weight":0.2},{"metricId":"society.socialMobility","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation,governance.budgetBalance,economic.gdpGrowth",
  },
  {
    // source: cnLegislationTypes.ts cn_social_insurance_contribution; baselineRate from budget policyDefaults option cn_social_insurance_contribution_opt_5
    id: "cn_social_insurance_contribution",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Social Insurance Contribution Law",
    description: "Sets the combined employer + employee social-insurance contribution rate",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "payrollTax", minRate: 0, maxRate: 45, step: 2, baselineRate: 28 },
    targets: [{"metricId":"governance.rentenStabilitaet","weight":-1},{"metricId":"economic.unemploymentRate","weight":0.4},{"metricId":"economic.medianIncome","weight":0.5},{"metricId":"economic.povertyRate","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.rentenStabilitaet,economic.unemploymentRate,economic.medianIncome,economic.povertyRate",
  },
  {
    // source: cnLegislationTypes.ts cn_customs_tariff; baselineRate from budget policyDefaults option cn_customs_tariff_opt_5
    id: "cn_customs_tariff",
    countryId: "CN",
    kind: "tax",
    title: "Statutory Customs Tariff Law",
    description: "Sets the average applied tariff rate on imports",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "tariffs", minRate: 0, maxRate: 25, step: 1, baselineRate: 7 },
    targets: [{"metricId":"economic.manufacturingCompetitiveness","weight":-1},{"metricId":"economic.tradeBalance","weight":-0.5},{"metricId":"economic.costOfLiving","weight":-0.4},{"metricId":"economic.gdpGrowth","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.manufacturingCompetitiveness,economic.tradeBalance,economic.costOfLiving,economic.gdpGrowth",
  },
  {
    // source: cnLegislationTypes.ts cn_provincial_resource_tax; baselineRate from budget policyDefaults option cn_provincial_resource_tax_opt_5
    id: "cn_provincial_resource_tax",
    countryId: "CN",
    kind: "tax",
    title: "Provincial Resource Tax Law",
    description: "Sets the provincial-level ad-valorem rate on natural-resource extraction",
    category: "tax",
    allowedScope: "both",
    taxPolicy: { scope: "state", taxType: "salesTax", minRate: 0, maxRate: 20, step: 1, baselineRate: 6 },
    targets: [{"metricId":"environment.stewardship","weight":-1},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.gdpGrowth,economic.manufacturingCompetitiveness",
  },
  {
    // source: seed
    id: "cn_medical_insurance",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Medical Insurance Law",
    description: "Sets central funding levels for China's three-tier medical insurance system",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.prevention","weight":1.6},{"metricId":"health.outcomes","weight":0.5},{"metricId":"economic.costOfLiving","weight":0.4},{"metricId":"economic.commonProsperityIndex","weight":0.5},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.commonProsperityIndex,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_elder_care",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Elder Care Services Law",
    description: "Sets central funding for China's elder-care system under the 9073 framework",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.socialInsurance","weight":1},{"metricId":"health.outcomes","weight":0.3},{"metricId":"society.integration","weight":0.3},{"metricId":"economic.commonProsperityIndex","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.commonProsperityIndex,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_mental_health",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Mental Health Services Law",
    description: "Sets the framework for mental-health-services delivery and stigma policy",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"healthcare.mentalHealthAccess","weight":1},{"metricId":"society.integration","weight":0.4},{"metricId":"governance.socialCreditCoverage","weight":-0.3},{"metricId":"health.prevention","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,governance.socialCreditCoverage,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_public_health",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Public Health Preparedness Law",
    description: "Sets the framework for CDC capacity and public-health emergency response",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.prevention","weight":1.4},{"metricId":"governance.socialCreditCoverage","weight":0.4},{"metricId":"economic.costOfLiving","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.socialCreditCoverage,economic.costOfLiving,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_education_funding",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Education Funding Law",
    description: "Sets central funding for compulsory and higher education programs",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"economic.commonProsperityIndex","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.commonProsperityIndex,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_gaokao_reform",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Gaokao Reform Law",
    description: "Sets the framework for college admissions criteria and the 高考 (Gaokao) system",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.academicPressure","weight":1},{"metricId":"society.socialMobility","weight":0.5},{"metricId":"social.hukouMobility","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/education.academicPressure,social.hukouMobility,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_academic_pressure_reform",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Academic Pressure Reform Law",
    description: "Sets the framework for student-burden reduction and tutoring-industry regulation",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.academicPressure","weight":1},{"metricId":"healthcare.mentalHealthAccess","weight":0.5},{"metricId":"population.birthRate","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/education.academicPressure,healthcare.mentalHealthAccess,population.birthRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_research_science",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Research and Science Law",
    description: "Sets central funding for state-led R&D and talent-attraction programs",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"economic.rdIntensity","weight":1},{"metricId":"economic.industrialPolicyExecution","weight":0.7},{"metricId":"economic.gdpGrowth","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.rdIntensity,economic.industrialPolicyExecution,economic.gdpGrowth,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_pension_system",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Pension System Law",
    description: "Sets the framework for China's three-pillar pension system",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"governance.rentenStabilitaet","weight":1},{"metricId":"health.socialInsurance","weight":0.5},{"metricId":"economic.commonProsperityIndex","weight":0.6},{"metricId":"governance.budgetBalance","weight":-0.7},{"metricId":"economic.laborParticipation","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.rentenStabilitaet,economic.commonProsperityIndex,governance.budgetBalance,economic.laborParticipation",
  },
  {
    // source: seed
    id: "cn_family_policy",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Family Policy Law",
    description: "Sets the framework for birth incentives and childcare-infrastructure programs",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"population.birthRate","weight":1},{"metricId":"society.womensOpportunity","weight":0.4},{"metricId":"economic.commonProsperityIndex","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.birthRate,economic.commonProsperityIndex,governance.budgetBalance",
  },
  {
    // source: seed
    id: "cn_gender_equality",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Gender Equality Law",
    description: "Sets the framework for workplace-discrimination and family-role policy",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"society.womensOpportunity","weight":1},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"economic.commonProsperityIndex","weight":0.3},{"metricId":"population.birthRate","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.commonProsperityIndex,population.birthRate",
  },
  {
    // source: seed
    id: "cn_common_prosperity",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Common Prosperity Law",
    description: "Sets the 共同富裕 (Common Prosperity) framework for wealth-redistribution and anti-monopoly enforcement",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"economic.commonProsperityIndex","weight":1},{"metricId":"society.socialMobility","weight":0.6},{"metricId":"economic.ruralRevitalization","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"economic.smallBusinessFormation","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.commonProsperityIndex,economic.ruralRevitalization,economic.manufacturingCompetitiveness,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "cn_pla_modernization",
    countryId: "CN",
    kind: "primary",
    title: "Statutory PLA Modernization Law",
    description: "Sets the framework for PLA modernization, force structure, and budget growth",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.taiwanStraitTension","weight":-1},{"metricId":"economic.industrialPolicyExecution","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.2},{"metricId":"economic.gdpGrowth","weight":-0.2},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.taiwanStraitTension,economic.industrialPolicyExecution,governance.budgetBalance,economic.manufacturingCompetitiveness,economic.gdpGrowth,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "cn_taiwan_strait_doctrine",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Taiwan Strait Doctrine Law",
    description: "Sets the framework for Taiwan Strait policy and unification doctrine",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.taiwanStraitTension","weight":-1},{"metricId":"governance.partyDiscipline","weight":0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"governance.beltAndRoadEngagement","weight":-0.2},{"metricId":"governance.militaryReadiness","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.taiwanStraitTension,governance.partyDiscipline,economic.manufacturingCompetitiveness,governance.beltAndRoadEngagement,governance.militaryReadiness",
  },
  {
    // source: seed
    id: "cn_cybersecurity",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Cybersecurity Law",
    description: "Sets the framework for data-security and tech-platform regulation",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.socialCreditCoverage","weight":1},{"metricId":"governance.partyDiscipline","weight":0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"governance.openness","weight":0.4},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.socialCreditCoverage,governance.partyDiscipline,economic.manufacturingCompetitiveness,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "cn_belt_and_road",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Belt and Road Initiative Law",
    description: "Sets central funding for the 一带一路 (Belt and Road) overseas-lending program",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"governance.beltAndRoadEngagement","weight":1},{"metricId":"economic.tradeBalance","weight":0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.6},{"metricId":"economic.industrialPolicyExecution","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.beltAndRoadEngagement,economic.tradeBalance,economic.manufacturingCompetitiveness,governance.budgetBalance,economic.industrialPolicyExecution",
  },
  {
    // source: seed
    id: "cn_us_china_relations",
    countryId: "CN",
    kind: "primary",
    title: "Statutory US-China Relations Law",
    description: "Sets the posture for US-China bilateral diplomatic and economic relations",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"economic.tradeBalance","weight":-0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.5},{"metricId":"economic.industrialPolicyExecution","weight":0.4},{"metricId":"governance.taiwanStraitTension","weight":-0.6},{"metricId":"governance.partyDiscipline","weight":0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.tradeBalance,economic.manufacturingCompetitiveness,economic.industrialPolicyExecution,governance.taiwanStraitTension,governance.partyDiscipline",
  },
  {
    // source: seed
    id: "cn_un_security_council_posture",
    countryId: "CN",
    kind: "primary",
    title: "Statutory UN Security Council Posture Law",
    description: "Sets China's posture and voting framework at the UN Security Council",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"governance.nationalPride","weight":0.5},{"metricId":"governance.partyDiscipline","weight":0.3},{"metricId":"governance.taiwanStraitTension","weight":0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.nationalPride,governance.partyDiscipline,governance.taiwanStraitTension,economic.manufacturingCompetitiveness",
  },
  {
    // source: seed
    id: "cn_ai_strategy",
    countryId: "CN",
    kind: "primary",
    title: "Statutory AI Strategy Law",
    description: "Sets the framework for state-led AI development and content regulation",
    category: "technology",
    allowedScope: "national",
    targets: [{"metricId":"economic.industrialPolicyExecution","weight":0.7},{"metricId":"economy.productivity","weight":0.5},{"metricId":"education.adultSkills","weight":0.4},{"metricId":"governance.socialCreditCoverage","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.industrialPolicyExecution,governance.socialCreditCoverage,economic.manufacturingCompetitiveness,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_semiconductor_strategy",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Semiconductor Strategy Law",
    description: "Sets the framework for semiconductor self-sufficiency and 大基金 (National IC Fund) capitalization",
    category: "technology",
    allowedScope: "national",
    targets: [{"metricId":"economic.industrialPolicyExecution","weight":0.8},{"metricId":"economic.manufacturingCompetitiveness","weight":0.6},{"metricId":"economic.tradeBalance","weight":0.4},{"metricId":"education.adultSkills","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.industrialPolicyExecution,economic.manufacturingCompetitiveness,economic.tradeBalance,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_public_security",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Public Security Law",
    description: "Sets the framework for 公安部 (Ministry of Public Security) authority and surveillance",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":0.7},{"metricId":"order.safety","weight":0.5},{"metricId":"governance.socialCreditCoverage","weight":0.6},{"metricId":"governance.partyDiscipline","weight":0.4},{"metricId":"governance.integrity","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.socialCreditCoverage,governance.partyDiscipline,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_criminal_justice",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Criminal Justice Law",
    description: "Sets the framework for sentencing severity, 严打 (strike-hard) campaigns, and due process",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"publicSafety.incarcerationRate","weight":-0.6},{"metricId":"order.safety","weight":0.8},{"metricId":"governance.integrity","weight":0.4},{"metricId":"governance.partyDiscipline","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/publicSafety.incarcerationRate,governance.partyDiscipline,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_internet_governance",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Internet Governance Law",
    description: "Sets the framework for 防火长城 (Great Firewall) scope and 网信办 (Cyberspace Administration) content moderation",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"governance.socialCreditCoverage","weight":1},{"metricId":"governance.partyDiscipline","weight":0.5},{"metricId":"governance.openness","weight":-0.5},{"metricId":"mediaInformation.mediaPolarization","weight":0.3},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"order.safety","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.socialCreditCoverage,governance.partyDiscipline,mediaInformation.mediaPolarization,economic.manufacturingCompetitiveness",
  },
  {
    // source: seed
    id: "cn_state_enterprises",
    countryId: "CN",
    kind: "primary",
    title: "Statutory State Enterprises Law",
    description: "Sets the framework for SOE ownership, governance, and 党的领导 (Party leadership)",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.industrialPolicyExecution","weight":0.7},{"metricId":"economic.smallBusinessFormation","weight":-0.6},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"society.socialMobility","weight":0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.industrialPolicyExecution,economic.smallBusinessFormation,economic.gdpGrowth,economic.manufacturingCompetitiveness",
  },
  {
    // source: seed
    id: "cn_industrial_strategy",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Industrial Strategy Law",
    description: "Sets the framework for industrial-policy targeting and Five-Year Plan priorities",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.industrialPolicyExecution","weight":1},{"metricId":"economic.manufacturingCompetitiveness","weight":0.5},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"economic.smallBusinessFormation","weight":-0.4},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.industrialPolicyExecution,economic.manufacturingCompetitiveness,economic.gdpGrowth,economic.smallBusinessFormation,governance.budgetBalance",
  },
  {
    // source: seed
    id: "cn_minimum_wage",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Minimum Wage Law",
    description: "Sets the federal minimum-wage floor and provincial-discretion framework",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.unemploymentRate","weight":0.5},{"metricId":"economic.povertyRate","weight":0.4},{"metricId":"economic.smallBusinessFormation","weight":-0.4},{"metricId":"economic.commonProsperityIndex","weight":0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.unemploymentRate,economic.povertyRate,economic.smallBusinessFormation,economic.commonProsperityIndex",
  },
  {
    // source: seed
    id: "cn_fiscal_stimulus",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Fiscal Stimulus Law",
    description: "Sets the framework for central-government cyclical stimulus and 专项债 (special bonds) issuance",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"governance.budgetBalance","weight":-0.7},{"metricId":"governance.debtToGdp","weight":-0.6},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"economic.costOfLiving","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,governance.budgetBalance,governance.debtToGdp,economic.manufacturingCompetitiveness,economic.costOfLiving,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_rail_transport",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Rail Transport Law",
    description: "Sets central funding for HSR network expansion and 中国国铁 (China Railway Corporation) operations",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.highways","weight":1},{"metricId":"infrastructure.transit","weight":0.6},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.eastWestRegionalGap","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,governance.budgetBalance,economic.eastWestRegionalGap,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_digital_infrastructure",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Digital Infrastructure Law",
    description: "Sets central funding for 5G, fiber, data centers, and 智慧城市 (smart city) programs",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.utilities","weight":1},{"metricId":"economic.industrialPolicyExecution","weight":0.4},{"metricId":"economic.eastWestRegionalGap","weight":0.4},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.industrialPolicyExecution,economic.eastWestRegionalGap,economic.gdpGrowth,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_housing",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Housing Policy Law",
    description: "Sets the framework for 保障房 (affordable housing) construction and 房住不炒 (houses are for living, not speculation) enforcement",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.publicHousing","weight":1},{"metricId":"social.wohnungsBauRate","weight":0.3},{"metricId":"economic.commonProsperityIndex","weight":0.5},{"metricId":"governance.budgetBalance","weight":-0.6},{"metricId":"economic.gdpGrowth","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.wohnungsBauRate,economic.commonProsperityIndex,governance.budgetBalance,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_renewable_energy_target",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Renewable Energy Target Law",
    description: "Sets central funding and targets for renewable-energy deployment and coal phaseout",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":2.4},{"metricId":"economic.industrialPolicyExecution","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.industrialPolicyExecution,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_nuclear_energy",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Nuclear Energy Law",
    description: "Sets the framework for commercial-nuclear fleet expansion and 华龙一号 deployment",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":1.2},{"metricId":"environment.energySecurity","weight":0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.manufacturingCompetitiveness,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_emissions_trading_scheme",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Emissions Trading Scheme Law",
    description: "Sets the framework for national ETS cap-tightening and sector coverage",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":1.4},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.4},{"metricId":"economic.industrialPolicyExecution","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.manufacturingCompetitiveness,economic.industrialPolicyExecution,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_climate_targets",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Climate Targets Law",
    description: "Sets the framework for 双碳 (Dual Carbon) emissions-peak and neutrality commitments",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.climateResilience","weight":1},{"metricId":"environment.stewardship","weight":1.3},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"governance.beltAndRoadEngagement","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.climateResilience,economic.manufacturingCompetitiveness,governance.beltAndRoadEngagement,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_hukou_reform",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Hukou Reform Law",
    description: "Sets the framework for 户口 (Hukou) registration and inter-region mobility",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"social.hukouMobility","weight":1},{"metricId":"economic.commonProsperityIndex","weight":0.5},{"metricId":"economic.eastWestRegionalGap","weight":0.3},{"metricId":"infrastructure.publicHousing","weight":0},{"metricId":"society.socialMobility","weight":0.5},{"metricId":"population.urbanizationRate","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.hukouMobility,economic.commonProsperityIndex,economic.eastWestRegionalGap,population.urbanizationRate",
  },
  {
    // source: seed
    id: "cn_skilled_immigration",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Foreign Talent Law",
    description: "Sets the framework for 千人计划 (Thousand Talents) talent attraction and foreign-expert visas",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"education.adultSkills","weight":0.7},{"metricId":"economic.industrialPolicyExecution","weight":0.5},{"metricId":"society.integration","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"governance.partyDiscipline","weight":-0.3},{"metricId":"population.migrationRate","weight":0.4},{"metricId":"infrastructure.publicHousing","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.industrialPolicyExecution,economic.manufacturingCompetitiveness,governance.partyDiscipline,population.migrationRate",
  },
  {
    // source: seed
    id: "cn_diaspora_engagement",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Diaspora Engagement Law",
    description: "Sets the framework for 华侨 (overseas Chinese) outreach and 统战部 (United Front Work Department) engagement",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"governance.nationalPride","weight":0.6},{"metricId":"governance.partyDiscipline","weight":0.3},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"society.integration","weight":0.4},{"metricId":"infrastructure.publicHousing","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.nationalPride,governance.partyDiscipline,economic.manufacturingCompetitiveness",
  },
  {
    // source: seed
    id: "cn_agricultural_subsidies",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Agricultural Subsidies Law",
    description: "Sets the framework for 三农 (three rural) farm subsidies and direct payments",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.ruralRevitalization","weight":1},{"metricId":"economic.commonProsperityIndex","weight":0.5},{"metricId":"economic.tradeBalance","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.eastWestRegionalGap","weight":0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.commonProsperityIndex,economic.tradeBalance,governance.budgetBalance,economic.eastWestRegionalGap",
  },
  {
    // source: seed
    id: "cn_food_security",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Food Security Law",
    description: "Sets the framework for grain self-sufficiency and 耕地红线 (arable-land) protection",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.tradeBalance","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"economic.industrialPolicyExecution","weight":0.3},{"metricId":"economic.costOfLiving","weight":0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.tradeBalance,economic.manufacturingCompetitiveness,economic.ruralRevitalization,economic.industrialPolicyExecution,economic.costOfLiving",
  },
  {
    // source: seed
    id: "cn_rural_revitalization",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Rural Revitalization Law",
    description: "Sets the framework for 乡村振兴 (rural revitalization) program scope and funding",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.ruralRevitalization","weight":1},{"metricId":"economic.commonProsperityIndex","weight":0.5},{"metricId":"economic.eastWestRegionalGap","weight":0.5},{"metricId":"economic.povertyRate","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.commonProsperityIndex,economic.eastWestRegionalGap,economic.povertyRate,governance.budgetBalance",
  },
  {
    // source: seed
    id: "cn_anticorruption_campaign",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Anti-Corruption Campaign Law",
    description: "Sets the framework for 中央纪委 (CCDI) campaign intensity and 双开 (dual expulsion) enforcement",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.partyDiscipline","weight":1},{"metricId":"governance.integrity","weight":1.1},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.partyDiscipline,economic.manufacturingCompetitiveness",
  },
  {
    // source: seed
    id: "cn_npc_reform",
    countryId: "CN",
    kind: "primary",
    title: "Statutory NPC Reform Law",
    description: "Sets the framework for NPC delegate-selection, committee authority, and transparency",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":0.6},{"metricId":"governance.integrity","weight":0.4},{"metricId":"governance.partyDiscipline","weight":-0.4},{"metricId":"governance.participation","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.partyDiscipline",
  },
  {
    // source: seed
    id: "cn_hk_macao_affairs",
    countryId: "CN",
    kind: "primary",
    title: "Statutory HK-Macao Affairs Law",
    description: "Sets the framework for 一国两制 (One Country, Two Systems) policy direction",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.taiwanStraitTension","weight":-0.6},{"metricId":"governance.partyDiscipline","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"governance.beltAndRoadEngagement","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.taiwanStraitTension,governance.partyDiscipline,economic.manufacturingCompetitiveness,governance.beltAndRoadEngagement",
  },
  {
    // source: seed
    id: "cn_state_media_funding",
    countryId: "CN",
    kind: "primary",
    title: "Statutory State Media Funding Law",
    description: "Sets central funding for CCTV, Xinhua, People's Daily, and CGTN",
    category: "mediaInformation",
    allowedScope: "national",
    targets: [{"metricId":"mediaInformation.stateMediaControl","weight":-0.7},{"metricId":"governance.partyDiscipline","weight":0.6},{"metricId":"governance.openness","weight":-0.5},{"metricId":"mediaInformation.mediaPolarization","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/mediaInformation.stateMediaControl,governance.partyDiscipline,mediaInformation.mediaPolarization,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_press_freedom",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Press Freedom Law",
    description: "Sets the framework for journalist rights and 国家保密法 (State Secrets Law) enforcement scope",
    category: "mediaInformation",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1},{"metricId":"governance.partyDiscipline","weight":-0.5},{"metricId":"governance.integrity","weight":0.8},{"metricId":"governance.nationalPride","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.partyDiscipline,governance.nationalPride",
  },
  {
    // source: seed
    id: "cn_provincial_education",
    countryId: "CN",
    kind: "primary",
    title: "Provincial Education Law",
    description: "Sets provincial-level K-12 funding and 高考 (Gaokao) preparation programs",
    category: "education",
    allowedScope: "both",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"economic.commonProsperityIndex","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.commonProsperityIndex,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_provincial_public_security",
    countryId: "CN",
    kind: "primary",
    title: "Provincial Public Security Law",
    description: "Sets provincial 公安厅 (PSB) operational scale and 维稳 (stability maintenance) capability",
    category: "law_justice",
    allowedScope: "both",
    targets: [{"metricId":"order.communityTrust","weight":0.7},{"metricId":"order.safety","weight":0.5},{"metricId":"governance.socialCreditCoverage","weight":0.5},{"metricId":"governance.partyDiscipline","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.socialCreditCoverage,governance.partyDiscipline,governance.budgetBalance",
  },
  {
    // source: seed
    id: "cn_provincial_economic_development",
    countryId: "CN",
    kind: "primary",
    title: "Provincial Economic Development Law",
    description: "Sets provincial industrial-policy scope and 经济特区 (SEZ) management",
    category: "economic",
    allowedScope: "both",
    targets: [{"metricId":"economic.gdpGrowth","weight":-0.6},{"metricId":"economic.industrialPolicyExecution","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":0.4},{"metricId":"economic.smallBusinessFormation","weight":-0.3},{"metricId":"economic.eastWestRegionalGap","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.industrialPolicyExecution,economic.manufacturingCompetitiveness,economic.smallBusinessFormation,economic.eastWestRegionalGap",
  },
  {
    // source: seed
    id: "cn_provincial_health_services",
    countryId: "CN",
    kind: "primary",
    title: "Provincial Health Services Law",
    description: "Sets provincial-hospital network funding and rural-urban equalization",
    category: "healthcare",
    allowedScope: "both",
    targets: [{"metricId":"health.outcomes","weight":0.7},{"metricId":"health.prevention","weight":1},{"metricId":"health.socialInsurance","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance",
  },
  {
    // source: seed
    id: "cn_provincial_culture_propaganda",
    countryId: "CN",
    kind: "primary",
    title: "Provincial Culture & Propaganda Law",
    description: "Sets provincial 统战部 (United Front) activity and cultural-content regulation",
    category: "mediaInformation",
    allowedScope: "both",
    targets: [{"metricId":"governance.partyDiscipline","weight":0.5},{"metricId":"governance.openness","weight":-0.4},{"metricId":"society.integration","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.partyDiscipline,governance.budgetBalance",
  },
  {
    // source: seed
    id: "cn_provincial_environmental_policy",
    countryId: "CN",
    kind: "primary",
    title: "Provincial Environmental Policy Law",
    description: "Sets provincial-level pollution control, ecological restoration, and environmental-enforcement funding",
    category: "environment",
    allowedScope: "both",
    targets: [{"metricId":"environment.urbanAir","weight":0.8},{"metricId":"environment.stewardship","weight":-1},{"metricId":"environment.climateResilience","weight":-0.6},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"governance.budgetBalance","weight":0.5},{"metricId":"economic.economicFreedom","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.climateResilience,economic.manufacturingCompetitiveness,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_provincial_infrastructure_investment",
    countryId: "CN",
    kind: "primary",
    title: "Provincial Infrastructure Investment Law",
    description: "Sets provincial-level capital investment in inter-city roads, bridges, water, sewage, and urban-renewal programs",
    category: "infrastructure",
    allowedScope: "both",
    targets: [{"metricId":"infrastructure.highways","weight":-0.8},{"metricId":"infrastructure.transit","weight":-0.5},{"metricId":"economic.gdpGrowth","weight":-0.4},{"metricId":"economic.eastWestRegionalGap","weight":-0.4},{"metricId":"governance.budgetBalance","weight":0.6},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.eastWestRegionalGap,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "cn_conscription",
    countryId: "CN",
    kind: "primary",
    title: "Statutory Military Service Law",
    description: "PLA recruitment, the nominal universal-service obligation, and mobilization readiness",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.militaryReadiness","weight":1},{"metricId":"governance.nationalPride","weight":0.4},{"metricId":"governance.civilLiberties","weight":-0.4},{"metricId":"economic.smallBusinessFormation","weight":0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.militaryReadiness,governance.nationalPride,governance.civilLiberties,economic.smallBusinessFormation",
  },
];
