import type { CatalogEntry } from "./catalog.js";
/**
 * DE legislation catalog. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateCatalogs.ts
 * Source: src/lib/seeds/de/deLegislationTypes.ts (60 types),
 * src/lib/politicalLegislation/marginAdapter.ts ADAPTER_TIER1 (target mapping),
 * src/lib/seeds/reference/budgets.ts policyDefaults (tax baselines). See the
 * generator header for the mapping rules and the PORT-STUB convention.
 */
export const CATALOG_DE: CatalogEntry[] = [
  {
    // source: seed; baselineRate from budget policyDefaults option de_income_tax_rate_opt_5
    id: "de_income_tax_rate",
    countryId: "DE",
    kind: "tax",
    title: "Statutory Income Tax Act",
    description: "Germany's top federal income tax rate on personal earnings",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "incomeTax", minRate: 0, maxRate: 65, step: 3, baselineRate: 42 },
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.povertyRate","weight":0.5},{"metricId":"economic.gdpGrowth","weight":0.4},{"metricId":"society.socialMobility","weight":-0.6}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.povertyRate,economic.gdpGrowth",
  },
  {
    // source: seed; baselineRate from budget policyDefaults option de_solidarity_surcharge_opt_5
    id: "de_solidarity_surcharge",
    countryId: "DE",
    kind: "tax",
    title: "Statutory Solidarity Surcharge Act",
    description: "Germany's Solidaritätszuschlag — a percentage surcharge on income tax owed",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "solidaritySurcharge", minRate: 0, maxRate: 10, step: 0.5, baselineRate: 5.5 },
    targets: [{"metricId":"economic.eastWestConvergence","weight":-1},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.medianIncome","weight":0.3},{"metricId":"society.socialMobility","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.eastWestConvergence,governance.budgetBalance,economic.medianIncome",
  },
  {
    // source: seed; baselineRate from budget policyDefaults option de_vat_rate_opt_5
    id: "de_vat_rate",
    countryId: "DE",
    kind: "tax",
    title: "Statutory VAT Act",
    description: "Germany's standard Mehrwertsteuer (VAT) rate on most goods and services",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "salesTax", minRate: 0, maxRate: 28, step: 1, baselineRate: 19 },
    targets: [{"metricId":"economic.costOfLiving","weight":-1},{"metricId":"economic.gdpGrowth","weight":-0.25},{"metricId":"economic.povertyRate","weight":-0.6},{"metricId":"economic.smallBusinessFormation","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.gdpGrowth,economic.povertyRate,economic.smallBusinessFormation",
  },
  {
    // source: seed; baselineRate from budget policyDefaults option de_domestic_corporate_tax_rate_opt_5
    id: "de_domestic_corporate_tax_rate",
    countryId: "DE",
    kind: "tax",
    title: "Statutory Corporate Tax Act",
    description: "Federal Körperschaftsteuer on German-headquartered corporations",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "domesticCorporateTax", minRate: 0, maxRate: 30, step: 2, baselineRate: 15 },
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.smallBusinessFormation","weight":0.5},{"metricId":"economic.mittelstandHealth","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.smallBusinessFormation,economic.mittelstandHealth,governance.budgetBalance",
  },
  {
    // source: seed; baselineRate from budget policyDefaults option de_foreign_corporate_tax_rate_opt_5
    id: "de_foreign_corporate_tax_rate",
    countryId: "DE",
    kind: "tax",
    title: "Foreign Corporate Parity Act",
    description: "Federal Körperschaftsteuer on foreign-headquartered corporations",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "foreignCorporateTax", minRate: 0, maxRate: 30, step: 2, baselineRate: 15 },
    targets: [{"metricId":"economic.manufacturingCompetitiveness","weight":-1},{"metricId":"economic.tradeBalance","weight":-0.4},{"metricId":"economic.gdpGrowth","weight":0.5},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.manufacturingCompetitiveness,economic.tradeBalance,economic.gdpGrowth,governance.budgetBalance",
  },
  {
    // source: seed; baselineRate from budget policyDefaults option de_payroll_social_insurance_opt_5
    id: "de_payroll_social_insurance",
    countryId: "DE",
    kind: "tax",
    title: "Statutory Social Insurance Act",
    description: "Combined employee+employer Sozialversicherungsbeiträge",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "payrollTax", minRate: 0, maxRate: 30, step: 2, baselineRate: 20 },
    targets: [{"metricId":"governance.rentenStabilitaet","weight":-1},{"metricId":"economic.unemploymentRate","weight":0.4},{"metricId":"economic.medianIncome","weight":0.5},{"metricId":"economic.povertyRate","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.rentenStabilitaet,economic.unemploymentRate,economic.medianIncome,economic.povertyRate",
  },
  {
    // source: seed; baselineRate from budget policyDefaults option de_customs_tariff_rate_opt_5
    id: "de_customs_tariff_rate",
    countryId: "DE",
    kind: "tax",
    title: "Statutory Tariff Act",
    description: "Germany's position on EU Common External Tariff levels",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "tariffs", minRate: 0, maxRate: 20, step: 1, baselineRate: 5 },
    targets: [{"metricId":"economic.manufacturingCompetitiveness","weight":-1},{"metricId":"economic.tradeBalance","weight":-0.5},{"metricId":"economic.costOfLiving","weight":-0.4},{"metricId":"governance.euCohesionScore","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.manufacturingCompetitiveness,economic.tradeBalance,economic.costOfLiving,governance.euCohesionScore",
  },
  {
    // source: seed; baselineRate from budget policyDefaults option de_trade_tax_opt_5
    id: "de_trade_tax",
    countryId: "DE",
    kind: "tax",
    title: "Statutory Hebesatz Act",
    description: "Land-level cap/floor on municipal Gewerbesteuer-Hebesätze",
    category: "tax",
    allowedScope: "both",
    taxPolicy: { scope: "state", taxType: "tradeTax", minRate: 200, maxRate: 600, step: 40, baselineRate: 400 },
    targets: [{"metricId":"economic.mittelstandHealth","weight":1},{"metricId":"economic.smallBusinessFormation","weight":0.4},{"metricId":"economic.gdpGrowth","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.mittelstandHealth,economic.smallBusinessFormation,economic.gdpGrowth,governance.budgetBalance",
  },
  {
    // source: seed
    id: "de_minimum_wage",
    countryId: "DE",
    kind: "primary",
    title: "Statutory Minimum Wage Act",
    description: "Germany's statutory minimum wage per hour, set by the Mindestlohnkommission on biennial review.",
    category: "labor",
    allowedScope: "national",
    targets: [{"metricId":"economic.povertyRate","weight":1},{"metricId":"economic.medianIncome","weight":0.5},{"metricId":"society.socialMobility","weight":0.6},{"metricId":"economic.unemploymentRate","weight":0.2},{"metricId":"economic.smallBusinessFormation","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.povertyRate,economic.medianIncome,economic.unemploymentRate,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "de_renewable_energy_target",
    countryId: "DE",
    kind: "primary",
    title: "Renewable Energy Targets Act",
    description: "Federal renewable-electricity share target plus EEG-Umlage management.",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":1},{"metricId":"economic.costOfLiving","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_immigration_policy",
    countryId: "DE",
    kind: "primary",
    title: "Skilled Immigration Framework Act",
    description: "The Fachkräfteeinwanderungsgesetz framework — Chancenkarte points system, qualifizierte Zuwanderung pathways, Vorrangprüfung, and Anerkennungsverfahren.",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"population.migrationRate","weight":1},{"metricId":"economic.gdpGrowth","weight":0.5},{"metricId":"economic.unemploymentRate","weight":0.4},{"metricId":"society.integration","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.1},{"metricId":"governance.borderSecurity","weight":-0.6}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.migrationRate,economic.gdpGrowth,economic.unemploymentRate,economic.economicFreedom,governance.borderSecurity",
  },
  {
    // source: seed
    id: "de_health_insurance",
    countryId: "DE",
    kind: "primary",
    title: "Health Insurance Structure Act",
    description: "Federal funding posture for the Gesetzliche Krankenversicherung (GKV) and the dual GKV/PKV system covering Germany's universal health insurance.",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.universalCare","weight":1},{"metricId":"economic.povertyRate","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.povertyRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_elder_care",
    countryId: "DE",
    kind: "primary",
    title: "Elder Care Framework Act",
    description: "Long-term care insurance (Pflegeversicherung, SGB XI), Pflegegrade assessment, nursing home funding, family caregiver support, and Pflegepersonal wages.",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.socialInsurance","weight":1},{"metricId":"health.outcomes","weight":0.3},{"metricId":"healthcare.mentalHealthAccess","weight":0.3},{"metricId":"society.integration","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_mental_health",
    countryId: "DE",
    kind: "primary",
    title: "Mental Health Care Act",
    description: "Psychotherapy access (KV-Bedarfsplanung wait times), psychiatric hospital capacity, suicide prevention, and workplace mental health.",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"healthcare.mentalHealthAccess","weight":1},{"metricId":"economy.workerSecurity","weight":0.4},{"metricId":"society.integration","weight":0.3},{"metricId":"health.prevention","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_public_health",
    countryId: "DE",
    kind: "primary",
    title: "Public Health Service Strengthening Act",
    description: "The Öffentlicher Gesundheitsdienst (ÖGD), Robert-Koch-Institut surveillance, vaccination programs, and pandemic preparedness.",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.prevention","weight":1},{"metricId":"environment.urbanAir","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_education_funding",
    countryId: "DE",
    kind: "primary",
    title: "Federal Education Funding Act",
    description: "The federal share of school funding (Bund-Länder-Kooperationsverbot caveat), Digitalpakt Schule infrastructure, BMBF grants, and Hochschulpakt.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_university_tuition",
    countryId: "DE",
    kind: "primary",
    title: "University Tuition and BAföG Act",
    description: "University tuition policy and the Bundesausbildungsförderungsgesetz (BAföG) student maintenance grant.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"society.socialMobility","weight":1},{"metricId":"education.adultSkills","weight":0.5},{"metricId":"education.universalSchooling","weight":0.4},{"metricId":"economic.medianIncome","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_academic_reform",
    countryId: "DE",
    kind: "primary",
    title: "Academic System Reform Act",
    description: "The Gymnasium/Realschule/Hauptschule debate, G8-vs-G9, Abiturnoten standardization, school stress, and curriculum reform.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.standards","weight":1},{"metricId":"society.socialMobility","weight":0.5},{"metricId":"education.academicPressure","weight":-0.4},{"metricId":"education.adultSkills","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/education.academicPressure,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_research_science",
    countryId: "DE",
    kind: "primary",
    title: "Research and Science Funding Act",
    description: "DFG, Max-Planck-Gesellschaft, Helmholtz-Gemeinschaft, Fraunhofer, Leibniz-Institute, and Exzellenzstrategie funding.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"economic.rdIntensity","weight":1},{"metricId":"economic.manufacturingCompetitiveness","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.rdIntensity,economic.manufacturingCompetitiveness,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_pension_system",
    countryId: "DE",
    kind: "primary",
    title: "Federal Pension System Act",
    description: "The Gesetzliche Rentenversicherung (GRV) — Rentenniveau, Beitragssatz balance, Doppelte Haltelinie, Riester-Rente, and Renteneintrittsalter debate.",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"governance.rentenStabilitaet","weight":1},{"metricId":"economic.povertyRate","weight":0.5},{"metricId":"economic.laborParticipation","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.rentenStabilitaet,economic.povertyRate,economic.laborParticipation,governance.budgetBalance",
  },
  {
    // source: seed
    id: "de_family_policy",
    countryId: "DE",
    kind: "primary",
    title: "Federal Family Policy Act",
    description: "Elterngeld, Kindergeld, Kita-Ausbau, Bundeselternzeit, Rechtsanspruch auf Kita-Platz, and family tax reforms (Ehegattensplitting).",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"population.birthRate","weight":1},{"metricId":"social.kitaCoverage","weight":0.5},{"metricId":"society.womensOpportunity","weight":0.5},{"metricId":"society.socialMobility","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.birthRate,social.kitaCoverage",
  },
  {
    // source: seed
    id: "de_unemployment_welfare",
    countryId: "DE",
    kind: "primary",
    title: "Bürgergeld and Unemployment Benefits Act",
    description: "Bürgergeld (successor to Hartz IV), Arbeitslosengeld II, Sanktionsregelungen, Hinzuverdienstgrenzen, and SGB II framework.",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"economic.povertyRate","weight":1},{"metricId":"society.socialMobility","weight":0.5},{"metricId":"society.integration","weight":0.3},{"metricId":"economic.laborParticipation","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.povertyRate,economic.laborParticipation",
  },
  {
    // source: seed
    id: "de_gender_equality",
    countryId: "DE",
    kind: "primary",
    title: "Federal Gender Equality Act",
    description: "Frauenquote (FüPoG), Entgelttransparenzgesetz, Gleichstellungsbeauftragte authority, and federal Gleichstellungspolitik.",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"society.womensOpportunity","weight":1},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.laborParticipation","weight":0.4},{"metricId":"social.kitaCoverage","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.laborParticipation,social.kitaCoverage",
  },
  {
    // source: seed
    id: "de_bundeswehr_funding",
    countryId: "DE",
    kind: "primary",
    title: "Bundeswehr Funding Act",
    description: "Overall Bundeswehr funding envelope — personnel, procurement, base maintenance, equipment modernization, and Sondervermögen authorization.",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":1},{"metricId":"economic.gdpGrowth","weight":0.2},{"metricId":"economic.manufacturingCompetitiveness","weight":-0.3},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.gdpGrowth,economic.manufacturingCompetitiveness,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "de_defense_posture",
    countryId: "DE",
    kind: "primary",
    title: "Defense Posture Act",
    description: "The mandate-and-scope dimension separated from funding. Article 87a Bundeswehr role, NATO collective defense, EU-Verteidigung leadership, overseas deployment authority, and arms exports.",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.bundeswehrReadiness","weight":-1},{"metricId":"society.integration","weight":0.5},{"metricId":"governance.euCohesionScore","weight":-0.5},{"metricId":"governance.militaryReadiness","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.bundeswehrReadiness,governance.euCohesionScore,governance.militaryReadiness",
  },
  {
    // source: seed
    id: "de_cybersecurity",
    countryId: "DE",
    kind: "primary",
    title: "IT Security Act",
    description: "The Bundesamt für Sicherheit in der Informationstechnik (BSI), Cyberagentur, KRITIS critical-infrastructure protection mandates, and federal IT-security policy.",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":1},{"metricId":"governance.openness","weight":0},{"metricId":"infrastructure.utilities","weight":0.2},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "de_eu_integration",
    countryId: "DE",
    kind: "primary",
    title: "European Integration Policy Act",
    description: "Germany's posture on EU integration depth — Eurobonds, fiscal union, EU defense cooperation, NextGenerationEU joint borrowing, social-policy harmonization.",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"governance.euCohesionScore","weight":1},{"metricId":"economic.manufacturingCompetitiveness","weight":0.2},{"metricId":"society.integration","weight":0.2},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.euCohesionScore,economic.manufacturingCompetitiveness,governance.budgetBalance",
  },
  {
    // source: seed
    id: "de_foreign_aid_diplomacy",
    countryId: "DE",
    kind: "primary",
    title: "Federal Foreign Aid and Diplomacy Act",
    description: "BMZ operations, Entwicklungshilfe, Auswärtiges Amt funding, Auslandsvertretungen, and the UN-target 0.7%-of-GNI commitment.",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":1},{"metricId":"governance.euCohesionScore","weight":0.8},{"metricId":"society.integration","weight":0.6},{"metricId":"governance.integrity","weight":0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,governance.euCohesionScore",
  },
  {
    // source: seed
    id: "de_trade_agreements",
    countryId: "DE",
    kind: "primary",
    title: "Federal Trade Agreements Position Act",
    description: "Germany's posture on EU trade agreements — CETA, TTIP, Mercosur, and pending China/ASEAN deals. Posture-only (EU competence).",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"economic.manufacturingCompetitiveness","weight":-1},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"society.integration","weight":-0.1},{"metricId":"environment.stewardship","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.manufacturingCompetitiveness,economic.gdpGrowth",
  },
  {
    // source: seed
    id: "de_robotics_ai",
    countryId: "DE",
    kind: "primary",
    title: "Federal AI and Robotics Strategy Act",
    description: "The KI-Strategie der Bundesregierung, BMBF KI-Forschung, Fraunhofer-Zentren für KI, robotics R&D funding, and Digitaler Zwilling Mittelstand.",
    category: "technology",
    allowedScope: "national",
    targets: [{"metricId":"economy.productivity","weight":1},{"metricId":"economic.rdIntensity","weight":0.4},{"metricId":"economic.productivityGrowth","weight":0.3},{"metricId":"economic.manufacturingCompetitiveness","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.rdIntensity,economic.productivityGrowth,economic.manufacturingCompetitiveness,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_digital_governance",
    countryId: "DE",
    kind: "primary",
    title: "Federal Digital Governance Act",
    description: "The Onlinezugangsgesetz (OZG), Digitale Identität, e-Government services, BMI digital-administration coordination, and Verwaltungsdigitalisierung.",
    category: "technology",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1},{"metricId":"governance.integrity","weight":0.3},{"metricId":"economic.productivityGrowth","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.productivityGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_policing_public_safety",
    countryId: "DE",
    kind: "primary",
    title: "Federal Policing and Public Safety Act",
    description: "Bundespolizei, BKA, federal coordination of Landespolizei, Zentralstelle für Sicherheitsfragen, and federal community-policing programs.",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":1},{"metricId":"order.safety","weight":-0.7},{"metricId":"governance.openness","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_criminal_justice",
    countryId: "DE",
    kind: "primary",
    title: "Federal Criminal Justice Reform Act",
    description: "Strafgesetzbuch reforms, federal sentencing guidelines, Strafvollzugsgesetz, drug policy (Cannabis), Sexualstrafrecht reforms, and Justizverstärkungs-Gesetzgebung.",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":1},{"metricId":"publicSafety.recidivismRate","weight":-0.4},{"metricId":"publicSafety.incarcerationRate","weight":-0.3},{"metricId":"governance.integrity","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/publicSafety.recidivismRate,publicSafety.incarcerationRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_constitutional_protection",
    countryId: "DE",
    kind: "primary",
    title: "Federal Constitutional Protection Act",
    description: "Bundesamt für Verfassungsschutz (BfV), Verfassungsschutzbehörden der Länder coordination, parliamentary G10-Kommission oversight, and the Inlandsnachrichtendienst framework.",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":-1},{"metricId":"governance.openness","weight":0.4},{"metricId":"governance.integrity","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_fiscal_stimulus_act",
    countryId: "DE",
    kind: "primary",
    title: "Federal Fiscal Stimulus Act",
    description: "The Schuldenbremse debate plus annual federal stimulus envelope. Article 109 GG limits structural deficit to 0.35% of GDP.",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"governance.budgetBalance","weight":-1},{"metricId":"governance.schuldenbremseHeadroom","weight":-1},{"metricId":"economic.unemploymentRate","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,governance.budgetBalance,governance.schuldenbremseHeadroom,economic.unemploymentRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_labor_reform",
    countryId: "DE",
    kind: "primary",
    title: "Labor Market Reform Act",
    description: "The Hartz-Gesetze legacy, Bürgergeld vs Arbeitslosengeld-II, Kündigungsschutz, Befristungs- und Zeitarbeitsregelungen, Mitbestimmung, and Tarifautonomie.",
    category: "labor",
    allowedScope: "national",
    targets: [{"metricId":"economy.workerSecurity","weight":1.5},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"economic.laborParticipation","weight":-0.2},{"metricId":"economic.smallBusinessFormation","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.laborParticipation,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "de_sme_mittelstand",
    countryId: "DE",
    kind: "primary",
    title: "Mittelstand Support Act",
    description: "Targeted federal support for Mittelstand firms — KfW-Kredite, Innovationsförderung, Unternehmensnachfolge support, and Mittelstand tax-relief.",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.mittelstandHealth","weight":1},{"metricId":"economic.smallBusinessFormation","weight":0.5},{"metricId":"economic.manufacturingCompetitiveness","weight":0.4},{"metricId":"economic.productivityGrowth","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.mittelstandHealth,economic.smallBusinessFormation,economic.manufacturingCompetitiveness,economic.productivityGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_rail_transport",
    countryId: "DE",
    kind: "primary",
    title: "Federal Rail Transport Act",
    description: "Deutsche Bahn AG funding, Bundesschienenwegeausbaugesetz infrastructure, Deutschland-Takt, regional rail subsidies, and DB privatization-vs-renationalization debate.",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.highways","weight":1},{"metricId":"environment.stewardship","weight":-0.4},{"metricId":"economic.ruralRevitalization","weight":0.3},{"metricId":"economic.gdpGrowth","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_digital_infrastructure",
    countryId: "DE",
    kind: "primary",
    title: "Digital Infrastructure Expansion Act",
    description: "Federal Glasfaser (FTTH) deployment, 5G rollout subsidies, Digitalpakt Schule infrastructure, Gigabit-Strategie, and rural broadband mandates.",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.utilities","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.3},{"metricId":"economic.rdIntensity","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.rdIntensity,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_housing",
    countryId: "DE",
    kind: "primary",
    title: "Federal Housing Construction Act",
    description: "Federal housing-construction support (Wohnungsbauförderung), Mietpreisbremse regulation, Sozialer Wohnungsbau funding, and Vergesellschaftung debate.",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"social.wohnungsBauRate","weight":1},{"metricId":"infrastructure.publicHousing","weight":0.9},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.wohnungsBauRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_nuclear_energy",
    countryId: "DE",
    kind: "primary",
    title: "Nuclear Energy Policy Act",
    description: "The Atomausstieg-vs-Atom-Renaissance question. Statutory baseline: phase-out completed, all reactors shut, Endlager search underway.",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.energySecurity","weight":1},{"metricId":"environment.stewardship","weight":0.7},{"metricId":"infrastructure.utilities","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_carbon_pricing",
    countryId: "DE",
    kind: "primary",
    title: "National Carbon Pricing Act",
    description: "The Brennstoffemissionshandelsgesetz (BEHG) — Germany's national CO2 trading system for transport and heating sectors, separate from the EU-ETS.",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":-0.5},{"metricId":"economic.costOfLiving","weight":0.4},{"metricId":"economic.mittelstandHealth","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.mittelstandHealth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_climate_targets",
    countryId: "DE",
    kind: "primary",
    title: "Federal Climate Protection Act",
    description: "The Klimaschutzgesetz framework — Klimaneutralität timeline, binding sector-specific emission limits, Klimasofortprogramm triggers.",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":-1},{"metricId":"environment.climateResilience","weight":0.4},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.climateResilience,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_asylum_policy",
    countryId: "DE",
    kind: "primary",
    title: "Federal Asylum Policy Act",
    description: "The Asylgesetz, AsylbLG, BAMF operations, Asylpaket framework, Geordnete-Rückkehr-Gesetz, Dublin-III compliance, and Artikel-16a protections.",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"population.migrationRate","weight":1},{"metricId":"society.integration","weight":0},{"metricId":"economic.povertyRate","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.1},{"metricId":"governance.borderSecurity","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.migrationRate,economic.povertyRate,economic.economicFreedom,governance.borderSecurity",
  },
  {
    // source: seed
    id: "de_integration_programs",
    countryId: "DE",
    kind: "primary",
    title: "Federal Integration Programs Act",
    description: "Integrationskurse, Sprachförderung, BAMF integration measures, Migrationsberatungsstellen, and Mehrgenerationenhaus funding.",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"society.integration","weight":1.5},{"metricId":"education.adultSkills","weight":0.3},{"metricId":"economic.unemploymentRate","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_agricultural_subsidies",
    countryId: "DE",
    kind: "primary",
    title: "Federal Agricultural Subsidies Act",
    description: "National share of EU GAP direct payments plus federal Bauernhilfen, Strukturförderung, and Förderung des ökologischen Landbaus.",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"economic.mittelstandHealth","weight":0.2},{"metricId":"environment.stewardship","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,economic.ruralRevitalization,economic.mittelstandHealth",
  },
  {
    // source: seed
    id: "de_food_security",
    countryId: "DE",
    kind: "primary",
    title: "Federal Food Security Act",
    description: "Bundesreserve Getreide, strategic food stockpiles, Notfallvorsorgegesetz frameworks, Versorgungssicherungsgesetz authorities, and BLE emergency mandates.",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.2},{"metricId":"society.integration","weight":0.2},{"metricId":"governance.budgetBalance","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,economic.ruralRevitalization,governance.budgetBalance",
  },
  {
    // source: seed
    id: "de_animal_welfare",
    countryId: "DE",
    kind: "primary",
    title: "Federal Animal Welfare Act",
    description: "The Tierschutzgesetz, Tierhaltungskennzeichnungsgesetz, Tiertransportregulierung, and Initiative Tierwohl framework.",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":-1},{"metricId":"economic.ruralRevitalization","weight":-0.5},{"metricId":"society.integration","weight":0.3},{"metricId":"environment.stewardship","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,economic.ruralRevitalization",
  },
  {
    // source: seed
    id: "de_grundgesetz_reform",
    countryId: "DE",
    kind: "primary",
    title: "Constitutional Federalism Reform Act",
    description: "Bund-Länder competence allocation, Kooperationsverbot, Länderfinanzausgleich reform, Bundesrat authority, and Föderalismusreform tradition.",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.localAutonomy","weight":1},{"metricId":"governance.openness","weight":0.2},{"metricId":"governance.budgetBalance","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance",
  },
  {
    // source: seed
    id: "de_electoral_reform",
    countryId: "DE",
    kind: "primary",
    title: "Federal Electoral Reform Act",
    description: "Bundestag size cap, Wahlkreis redistricting, voting age, Ausgleichsmandate algorithm, 5%-Sperrklausel, Direktwahl threshold, and Listenwahl proportionality.",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.participation","weight":1},{"metricId":"governance.integrity","weight":0.4},{"metricId":"governance.openness","weight":0.3},{"metricId":"mediaInformation.mediaPolarization","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/mediaInformation.mediaPolarization",
  },
  {
    // source: seed
    id: "de_government_ethics",
    countryId: "DE",
    kind: "primary",
    title: "Federal Government Ethics Act",
    description: "Lobbyregister, Karenzzeit, Verhaltensregeln für Abgeordnete, Abgeordnetengesetz transparency, Parteiengesetz disclosure, and Antikorruptionsbeauftragte authority.",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1},{"metricId":"governance.integrity","weight":0.4},{"metricId":"governance.participation","weight":0.2}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: seed
    id: "de_public_broadcasting",
    countryId: "DE",
    kind: "primary",
    title: "Federal Public Broadcasting Act",
    description: "Rundfunkbeitrag funding model, ARD / ZDF / Deutschlandradio subsidies, Medienstaatsvertrag, and recurring debate over public-broadcasting funding.",
    category: "mediaInformation",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1},{"metricId":"mediaInformation.mediaPolarization","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/mediaInformation.mediaPolarization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_press_freedom",
    countryId: "DE",
    kind: "primary",
    title: "Federal Press Freedom Act",
    description: "Whistleblower-Schutzgesetz, journalistic protections, Quellenschutz, Pressekodex enforcement, and Medienstaatsvertrag press-rights framework.",
    category: "mediaInformation",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1.4},{"metricId":"governance.nationalPride","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.nationalPride",
  },
  {
    // source: seed
    id: "de_land_education",
    countryId: "DE",
    kind: "primary",
    title: "Land Education Act",
    description: "Core Land competence under Kulturhoheit der Länder — K-12 schooling, Lehrerausbildung, school construction, curriculum (Bildungsplan), and Schulträgerschaft.",
    category: "education",
    allowedScope: "both",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_land_police",
    countryId: "DE",
    kind: "primary",
    title: "Land Police Act",
    description: "The Landespolizei funding envelope — Schutzpolizei, Kriminalpolizei, Bereitschaftspolizei, traffic policing, and Land-level coordination with BKA.",
    category: "law_justice",
    allowedScope: "both",
    targets: [{"metricId":"order.communityTrust","weight":1},{"metricId":"order.safety","weight":-0.7},{"metricId":"governance.openness","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_land_culture",
    countryId: "DE",
    kind: "primary",
    title: "Land Cultural Funding Act",
    description: "Land cultural budget — Landestheater, Museen, Landesoper, Bibliotheken, Konzerthäuser, Landesrundfunk-Anteil, Künstlerförderung, and Kulturhoheit programs.",
    category: "mediaInformation",
    allowedScope: "both",
    targets: [{"metricId":"governance.openness","weight":1},{"metricId":"society.integration","weight":0.67},{"metricId":"mediaInformation.mediaPolarization","weight":-0.33},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/mediaInformation.mediaPolarization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_land_economic_development",
    countryId: "DE",
    kind: "primary",
    title: "Land Economic Development Act",
    description: "Land-level Strukturpolitik — Landesinvestitionsbanken (LfA Bayern, NRW.Bank), Strukturhilfen, Land-level Innovationsförderung, and Wirtschaftsförderungsgesellschaften.",
    category: "economic",
    allowedScope: "both",
    targets: [{"metricId":"economic.mittelstandHealth","weight":1},{"metricId":"economic.smallBusinessFormation","weight":0.5},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.mittelstandHealth,economic.smallBusinessFormation,economic.ruralRevitalization,economic.manufacturingCompetitiveness,economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_land_health_services",
    countryId: "DE",
    kind: "primary",
    title: "Land Hospital Planning Act",
    description: "Krankenhausplanung as a Land competence — hospital network density, Versorgungsstufen, public-hospital ownership (Universitätskliniken, kommunale Krankenhäuser), Investitionskostenförderung.",
    category: "healthcare",
    allowedScope: "both",
    targets: [{"metricId":"health.prevention","weight":1},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "de_land_municipal_grants",
    countryId: "DE",
    kind: "primary",
    title: "Municipal Fiscal Equalization Act",
    description: "The Kommunaler Finanzausgleich — annual Land-to-Gemeinde transfers via Schlüsselzuweisungen formula, plus Land-level Zweckzuweisungen.",
    category: "governance",
    allowedScope: "both",
    targets: [{"metricId":"governance.localAutonomy","weight":1},{"metricId":"governance.participation","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance",
  },
  {
    // source: seed
    id: "de_wehrpflicht",
    countryId: "DE",
    kind: "primary",
    title: "Conscription and Recruitment Act",
    description: "The suspended conscription (_Wehrpflicht_) question, Bundeswehr recruitment, and reserve structure",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.militaryReadiness","weight":1},{"metricId":"governance.nationalPride","weight":0.4},{"metricId":"governance.civilLiberties","weight":-0.4},{"metricId":"economic.smallBusinessFormation","weight":0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.militaryReadiness,governance.nationalPride,governance.civilLiberties,economic.smallBusinessFormation",
  },
];
