import type { CatalogEntry } from "./catalog.js";
/**
 * JP legislation catalog. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateCatalogs.ts
 * Source: src/lib/seeds/jp/jpLegislationTypes.ts (63 types),
 * src/lib/politicalLegislation/marginAdapter.ts ADAPTER_TIER1 (target mapping),
 * src/lib/seeds/reference/budgets.ts policyDefaults (tax baselines). See the
 * generator header for the mapping rules and the PORT-STUB convention.
 */
export const CATALOG_JP: CatalogEntry[] = [
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_income_tax_rate",
    countryId: "JP",
    kind: "tax",
    title: "Income Tax Rate Act",
    description: "Sets Japan's national income tax rate on earned income",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "incomeTax", minRate: 0, maxRate: 50, step: 5, baselineRate: 25 },
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.povertyRate","weight":0.5},{"metricId":"economic.gdpGrowth","weight":0.4},{"metricId":"society.socialMobility","weight":-0.6}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.povertyRate,economic.gdpGrowth",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_domestic_corporation_tax",
    countryId: "JP",
    kind: "tax",
    title: "Domestic Corporation Tax Act",
    description: "Sets Japan's tax rate on profits of companies headquartered in Japan",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "domesticCorporateTax", minRate: 0, maxRate: 46, step: 4, baselineRate: 23 },
    targets: [{"metricId":"economic.smallBusinessFormation","weight":1},{"metricId":"economic.gdpGrowth","weight":0.5},{"metricId":"economic.unemploymentRate","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation,economic.gdpGrowth,economic.unemploymentRate",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_foreign_corporation_tax",
    countryId: "JP",
    kind: "tax",
    title: "Foreign Corporation Tax Act",
    description: "Sets Japan's tax rate on profits of companies headquartered outside Japan",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "foreignCorporateTax", minRate: 0, maxRate: 65, step: 6, baselineRate: 32 },
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.unemploymentRate","weight":0.2},{"metricId":"economic.smallBusinessFormation","weight":-0.3},{"metricId":"economic.costOfLiving","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.unemploymentRate,economic.smallBusinessFormation,economic.costOfLiving",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_social_insurance",
    countryId: "JP",
    kind: "tax",
    title: "Social Insurance Contribution Act",
    description: "Sets Japan's social insurance contribution rate (pension, health, employment, long-term care)",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "payrollTax", minRate: 0, maxRate: 30, step: 3, baselineRate: 15 },
    targets: [{"metricId":"society.integration","weight":1},{"metricId":"health.socialInsurance","weight":0.6},{"metricId":"healthcare.mentalHealthAccess","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_customs_tariff",
    countryId: "JP",
    kind: "tax",
    title: "Customs Tariff Act",
    description: "Sets Japan's import tariff rates on foreign goods",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "tariffs", minRate: 0, maxRate: 20, step: 0.5, baselineRate: 4 },
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.foodSecurity","weight":0.4},{"metricId":"economic.smallBusinessFormation","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.foodSecurity,economic.smallBusinessFormation",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_consumption_tax",
    countryId: "JP",
    kind: "tax",
    title: "Consumption Tax Act",
    description: "Sets Japan's consumption tax rate (equivalent to VAT)",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "salesTax", minRate: 0, maxRate: 25, step: 1, baselineRate: 10 },
    targets: [{"metricId":"economic.costOfLiving","weight":-1},{"metricId":"economic.gdpGrowth","weight":-0.25},{"metricId":"economic.povertyRate","weight":-0.4},{"metricId":"economic.foodSecurity","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.gdpGrowth,economic.povertyRate,economic.foodSecurity",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_resident_tax",
    countryId: "JP",
    kind: "tax",
    title: "Prefectural Resident Tax Act",
    description: "Sets the combined prefectural and municipal resident tax rate applied to income",
    category: "tax",
    allowedScope: "both",
    taxPolicy: { scope: "state", taxType: "residentTax", minRate: 0, maxRate: 20, step: 2, baselineRate: 10 },
    targets: [{"metricId":"governance.integrity","weight":1},{"metricId":"education.universalSchooling","weight":0.4},{"metricId":"order.safety","weight":0.3}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "jp_fixed_asset_tax",
    countryId: "JP",
    kind: "tax",
    title: "Fixed Asset Tax Act",
    description: "Sets the tax rate on land, buildings, and depreciable business assets",
    category: "tax",
    allowedScope: "both",
    taxPolicy: { scope: "state", taxType: "fixedAssetTax", minRate: 0, maxRate: 5, step: 0.2, baselineRate: 1.4 },
    targets: [{"metricId":"economic.costOfLiving","weight":1},{"metricId":"economic.smallBusinessFormation","weight":-0.3},{"metricId":"governance.integrity","weight":0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_national_health_insurance",
    countryId: "JP",
    kind: "primary",
    title: "National Health Insurance Act",
    description: "Controls overall funding for Japan's universal health insurance system (kokumin kenko hoken). The backbone of Japan's healthcare.",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.universalCare","weight":1},{"metricId":"economic.povertyRate","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.povertyRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_elder_care",
    countryId: "JP",
    kind: "primary",
    title: "Elder Care and Long-Term Services Act",
    description: "Japan's defining fiscal challenge — long-term care insurance (kaigo hoken), nursing homes, home care services, and support for the world's oldest population.",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.socialInsurance","weight":1},{"metricId":"health.outcomes","weight":0.3},{"metricId":"healthcare.mentalHealthAccess","weight":0.3},{"metricId":"society.integration","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_mental_health",
    countryId: "JP",
    kind: "primary",
    title: "Mental Health Services Act",
    description: "Mental health is a growing political priority — Japan has historically high suicide rates and significant stigma around seeking psychological help.",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"healthcare.mentalHealthAccess","weight":1},{"metricId":"education.academicPressure","weight":0.5},{"metricId":"economy.workerSecurity","weight":0.4},{"metricId":"order.safety","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,education.academicPressure,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_public_health",
    countryId: "JP",
    kind: "primary",
    title: "Public Health and Prevention Act",
    description: "Disease prevention, vaccination, health education, pandemic preparedness. Administered through national public health centers (hokenjo).",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.prevention","weight":1},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_health",
    countryId: "JP",
    kind: "primary",
    title: "Regional Health Services Act",
    description: "How the prefectural assembly allocates its health-related budget for local clinics, community health workers, health visitors, and local public health initiatives. Spending from the regional budget, not the national health insurance allocation.",
    category: "healthcare",
    allowedScope: "both",
    targets: [{"metricId":"health.prevention","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_education_funding",
    countryId: "JP",
    kind: "primary",
    title: "National Education Budget Act",
    description: "The overall national schools funding envelope distributed to prefectures. Covers K-12 compulsory education, teacher salaries, and school infrastructure.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"education.academicPressure","weight":0.3},{"metricId":"society.socialMobility","weight":0.7},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/education.academicPressure,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_university_tuition",
    countryId: "JP",
    kind: "primary",
    title: "University Tuition and Higher Education Act",
    description: "University tuition fees and student support. National university tuition is a significant debate, especially as birth rates decline and universities compete for shrinking cohorts.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"society.socialMobility","weight":0.9},{"metricId":"population.birthRate","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.birthRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_academic_reform",
    countryId: "JP",
    kind: "primary",
    title: "Academic Culture and Education Reform Act",
    description: "Japan's intense exam culture (juken), cram schools (juku), student mental health, and curriculum reform. A uniquely Japanese debate.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.academicPressure","weight":1},{"metricId":"healthcare.mentalHealthAccess","weight":0.5},{"metricId":"education.universalSchooling","weight":0.3},{"metricId":"society.womensOpportunity","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/education.academicPressure,healthcare.mentalHealthAccess,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_research_science",
    countryId: "JP",
    kind: "primary",
    title: "Research and Science Funding Act",
    description: "JSPS (Japan Society for the Promotion of Science), RIKEN, JAXA, university research grants, and industrial R&D.",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"economic.rdIntensity","weight":1},{"metricId":"economic.gdpGrowth","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.rdIntensity,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_education",
    countryId: "JP",
    kind: "primary",
    title: "Regional Education Services Act",
    description: "Prefectural education spending — early childhood education, school meals, educational support services, and special needs coordination funded from the regional budget.",
    category: "education",
    allowedScope: "both",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.ruralRevitalization","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_skills",
    countryId: "JP",
    kind: "primary",
    title: "Regional Skills and Vocational Training Act",
    description: "Vocational schools (senmon gakko), apprenticeships, adult retraining, and skills development — increasingly important as Japan faces labor shortages.",
    category: "education",
    allowedScope: "both",
    targets: [{"metricId":"economic.unemploymentRate","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.3},{"metricId":"economic.smallBusinessFormation","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,economic.ruralRevitalization,economic.smallBusinessFormation,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_article9_sdf",
    countryId: "JP",
    kind: "primary",
    title: "National Defense Posture Act",
    description: "The core debate: Article 9 constitutional pacifism vs. military normalization. Controls the Self-Defense Forces' mandate, scope of operations, and constitutional interpretation.",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":1},{"metricId":"society.integration","weight":-0.2},{"metricId":"governance.integrity","weight":0.4},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_defense_spending",
    countryId: "JP",
    kind: "primary",
    title: "Defense Budget Act",
    description: "Overall defense spending level — separate from the posture question. Controls procurement, personnel, base maintenance, and equipment modernization. Social axis represents pacifism ↔ militarism spectrum.",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":1},{"metricId":"economic.gdpGrowth","weight":-0.2},{"metricId":"economy.productivity","weight":0.3},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_cybersecurity",
    countryId: "JP",
    kind: "primary",
    title: "National Cybersecurity Act",
    description: "Cybersecurity infrastructure, digital defense, critical infrastructure protection, and information warfare capabilities.",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"order.communityTrust","weight":1},{"metricId":"economy.productivity","weight":0.3},{"metricId":"infrastructure.utilities","weight":0.4},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_fiscal_stimulus",
    countryId: "JP",
    kind: "primary",
    title: "Fiscal and Economic Stimulus Act",
    description: "Government spending stimulus — Japan's long history of fiscal stimulus packages to combat deflation and stagnation.",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.unemploymentRate","weight":0.5},{"metricId":"economic.medianIncome","weight":0.3},{"metricId":"economic.costOfLiving","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.unemploymentRate,economic.medianIncome,economic.costOfLiving,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_minimum_wage",
    countryId: "JP",
    kind: "primary",
    title: "Minimum Wage Act",
    description: "No annualCostPerCapita — cost borne by corporations. Uses minimumWageRate field (¥/hour).",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.povertyRate","weight":0.5},{"metricId":"economic.smallBusinessFormation","weight":-0.3},{"metricId":"society.socialMobility","weight":0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.povertyRate,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_labor_reform",
    countryId: "JP",
    kind: "primary",
    title: "Labor and Employment Reform Act",
    description: "Overtime regulation, non-regular worker protections, work-life balance mandates, and karoshi prevention. A defining Japanese workplace debate.",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economy.workerSecurity","weight":1},{"metricId":"healthcare.mentalHealthAccess","weight":0.4},{"metricId":"population.birthRate","weight":0.3},{"metricId":"society.womensOpportunity","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,population.birthRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_sme_support",
    countryId: "JP",
    kind: "primary",
    title: "Small and Medium Enterprise Support Act",
    description: "SME policy — Japan's economy is built on small and medium enterprises (99.7% of all businesses). Support programs, subsidies, and regulatory relief.",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.smallBusinessFormation","weight":1},{"metricId":"economic.unemploymentRate","weight":0.3},{"metricId":"economic.ruralRevitalization","weight":0.3},{"metricId":"economic.gdpGrowth","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation,economic.unemploymentRate,economic.ruralRevitalization,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_local_allocation_tax",
    countryId: "JP",
    kind: "primary",
    title: "Local Allocation Tax Act",
    description: "Controls the ¥/cap grant sent from the national government to prefectural regions via the Local Allocation Tax (chihou koufu zei). The primary mechanism for central-to-regional fiscal transfer. Feeds into regional budget pages.",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.ruralRevitalization","weight":1},{"metricId":"education.universalSchooling","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_economic_development",
    countryId: "JP",
    kind: "primary",
    title: "Regional Economic Development Act",
    description: "Prefectural economic development — business attraction, industrial parks, startup incubators, and regional economic strategy funded from the regional budget.",
    category: "economic",
    allowedScope: "both",
    targets: [{"metricId":"economic.unemploymentRate","weight":1},{"metricId":"economic.smallBusinessFormation","weight":0.4},{"metricId":"economic.ruralRevitalization","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,economic.smallBusinessFormation,economic.ruralRevitalization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_disaster_preparedness",
    countryId: "JP",
    kind: "primary",
    title: "Disaster Preparedness and Resilience Act",
    description: "Japan's existential infrastructure challenge — earthquake-proofing, tsunami barriers, flood control, early warning systems, and evacuation infrastructure.",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"environment.naturalDisasterPreparedness","weight":1},{"metricId":"health.prevention","weight":0.3},{"metricId":"economic.ruralRevitalization","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.naturalDisasterPreparedness,economic.ruralRevitalization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_rail_transport",
    countryId: "JP",
    kind: "primary",
    title: "Rail and Transportation Infrastructure Act",
    description: "Japan's rail network — shinkansen expansion, conventional rail maintenance, urban transit, and the debate over continued public investment vs. privatization.",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.highways","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"economic.gdpGrowth","weight":0.3},{"metricId":"environment.stewardship","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_digital_infrastructure",
    countryId: "JP",
    kind: "primary",
    title: "Digital Infrastructure and Connectivity Act",
    description: "Broadband expansion, 5G/6G rollout, government digitization, and My Number system modernization.",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.utilities","weight":1},{"metricId":"economy.productivity","weight":0.3},{"metricId":"economic.ruralRevitalization","weight":0.3},{"metricId":"economic.gdpGrowth","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_transport",
    countryId: "JP",
    kind: "primary",
    title: "Regional Transport Act",
    description: "Prefectural transport — local bus routes, regional rail subsidies, road maintenance, and cycling infrastructure funded from the regional budget.",
    category: "infrastructure",
    allowedScope: "both",
    targets: [{"metricId":"infrastructure.highways","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"economic.unemploymentRate","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.unemploymentRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_utilities",
    countryId: "JP",
    kind: "primary",
    title: "Regional Utilities and Public Works Act",
    description: "Water supply, sewage, waste management, and local public works funded from the regional budget.",
    category: "infrastructure",
    allowedScope: "both",
    targets: [{"metricId":"infrastructure.utilities","weight":1},{"metricId":"health.prevention","weight":0.3},{"metricId":"environment.naturalDisasterPreparedness","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.naturalDisasterPreparedness,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_nuclear_energy",
    countryId: "JP",
    kind: "primary",
    title: "Nuclear Energy Policy Act",
    description: "The post-Fukushima debate: restart reactors vs. phase out nuclear entirely. This debate cuts across traditional left/right lines — scored on economic axis only (transition costs vs. cheap baseload), social is null.",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.energySecurity","weight":1},{"metricId":"environment.stewardship","weight":0.4},{"metricId":"economic.costOfLiving","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_climate_emissions",
    countryId: "JP",
    kind: "primary",
    title: "Climate and Emissions Policy Act",
    description: "Carbon reduction targets, emissions trading, carbon pricing, and Japan's commitments under international climate agreements.",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":1},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"health.prevention","weight":0.3},{"metricId":"economic.foodSecurity","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.foodSecurity,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_renewable_energy",
    countryId: "JP",
    kind: "primary",
    title: "Renewable Energy Investment Act",
    description: "Solar, wind, geothermal, and hydroelectric investment. Japan has significant untapped geothermal potential and growing offshore wind capacity.",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":1},{"metricId":"environment.energySecurity","weight":0.2},{"metricId":"economic.costOfLiving","weight":0.3},{"metricId":"economic.gdpGrowth","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_environment",
    countryId: "JP",
    kind: "primary",
    title: "Regional Environment Act",
    description: "Prefectural environmental spending — local pollution control, nature conservation, parks, recycling programs, and environmental monitoring funded from the regional budget.",
    category: "environment",
    allowedScope: "both",
    targets: [{"metricId":"environment.urbanAir","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.2},{"metricId":"economic.foodSecurity","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.foodSecurity,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_family_policy",
    countryId: "JP",
    kind: "primary",
    title: "Family Policy and Birthrate Support Act",
    description: "Japan's most urgent social challenge — declining birthrate, childcare availability, parental leave, and financial incentives for family formation.",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"population.birthRate","weight":1},{"metricId":"society.womensOpportunity","weight":0.4},{"metricId":"economy.workerSecurity","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.birthRate",
  },
  {
    // source: seed
    id: "jp_pension",
    countryId: "JP",
    kind: "primary",
    title: "Pension & Retirement Age Act",
    description: "Kōsei Nenkin / Kokumin Nenkin public pension — replacement rate, contribution balance, and the pensionable-age (shikyū kaishi nenrei) debate.",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.povertyRate","weight":1},{"metricId":"economic.laborParticipation","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.povertyRate,economic.laborParticipation,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_gender_equality",
    countryId: "JP",
    kind: "primary",
    title: "Gender Equality and Women's Advancement Act",
    description: "Japan ranks notably low among developed nations for gender equality — workforce participation gap, political representation, pay equity, and workplace discrimination.",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"society.womensOpportunity","weight":1},{"metricId":"population.birthRate","weight":0.3},{"metricId":"economy.workerSecurity","weight":0.3},{"metricId":"economic.medianIncome","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.birthRate,economic.medianIncome",
  },
  {
    // source: seed
    id: "jp_work_culture_reform",
    countryId: "JP",
    kind: "primary",
    title: "Work Culture and Lifestyle Reform Act",
    description: "Karoshi prevention, mandatory vacation, remote work incentives, and the broader cultural shift away from overwork. Distinct from labor reform (which covers legal protections) — this is about culture change and lifestyle support.",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"economy.workerSecurity","weight":1},{"metricId":"healthcare.mentalHealthAccess","weight":0.4},{"metricId":"population.birthRate","weight":0.3},{"metricId":"society.womensOpportunity","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,population.birthRate",
  },
  {
    // source: seed
    id: "jp_regional_social_services",
    countryId: "JP",
    kind: "primary",
    title: "Regional Social Services Act",
    description: "Prefectural social services — community centers, childcare coordination, domestic violence support, disability services, and social welfare programs funded from the regional budget.",
    category: "social",
    allowedScope: "both",
    targets: [{"metricId":"society.integration","weight":1},{"metricId":"order.safety","weight":0.3},{"metricId":"healthcare.mentalHealthAccess","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess",
  },
  {
    // source: seed
    id: "jp_foreign_worker_policy",
    countryId: "JP",
    kind: "primary",
    title: "Foreign Worker and Immigration Policy Act",
    description: "The core immigration debate: how many foreign workers to admit, under what conditions, and with what path to residency.",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"society.integration","weight":1},{"metricId":"economic.unemploymentRate","weight":0.3},{"metricId":"population.migrationRate","weight":0.4},{"metricId":"economic.gdpGrowth","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,population.migrationRate,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_visa_residency",
    countryId: "JP",
    kind: "primary",
    title: "Visa and Residency Standards Act",
    description: "The legal framework for visa categories, residency requirements, and the path to permanent residency or citizenship.",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"society.integration","weight":1.3},{"metricId":"population.migrationRate","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.migrationRate,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_integration_programs",
    countryId: "JP",
    kind: "primary",
    title: "Immigrant Integration and Support Act",
    description: "How the government supports foreign residents already in Japan — language education, cultural programs, anti-discrimination enforcement, and community integration.",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"society.integration","weight":1.5},{"metricId":"order.safety","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_agricultural_subsidies",
    countryId: "JP",
    kind: "primary",
    title: "Agricultural Subsidies and Farming Support Act",
    description: "Farm subsidies, rice production support, agricultural cooperatives (JA), and the debate over protecting Japan's farming sector vs. market liberalization.",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.5},{"metricId":"economic.smallBusinessFormation","weight":0.3},{"metricId":"economic.gdpGrowth","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,economic.ruralRevitalization,economic.smallBusinessFormation,economic.gdpGrowth",
  },
  {
    // source: seed
    id: "jp_food_security",
    countryId: "JP",
    kind: "primary",
    title: "Food Security and Self-Sufficiency Act",
    description: "Japan's food self-sufficiency strategy — strategic grain reserves, domestic production targets, food supply chain resilience, and emergency food security planning.",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":1},{"metricId":"environment.naturalDisasterPreparedness","weight":0.3},{"metricId":"health.prevention","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,environment.naturalDisasterPreparedness",
  },
  {
    // source: seed
    id: "jp_rural_development",
    countryId: "JP",
    kind: "primary",
    title: "Rural Development and Revitalization Act",
    description: "The urban-rural divide — depopulating countryside, shuttered rural economies, and government programs to attract residents and investment back to rural Japan.",
    category: "agriculture",
    allowedScope: "national",
    targets: [{"metricId":"economic.ruralRevitalization","weight":1},{"metricId":"population.urbanizationRate","weight":-0.4},{"metricId":"infrastructure.highways","weight":0.3},{"metricId":"economic.unemploymentRate","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,population.urbanizationRate,economic.unemploymentRate",
  },
  {
    // source: seed
    id: "jp_regional_agriculture",
    countryId: "JP",
    kind: "primary",
    title: "Regional Agriculture Act",
    description: "Prefectural agricultural support — local farm extension services, regional crop promotion, farmers' markets, and agricultural land use planning funded from the regional budget.",
    category: "agriculture",
    allowedScope: "both",
    targets: [{"metricId":"economic.foodSecurity","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.3},{"metricId":"economic.smallBusinessFormation","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,economic.ruralRevitalization,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_constitutional_reform",
    countryId: "JP",
    kind: "primary",
    title: "Constitutional Reform Act",
    description: "The long-running debate over revising Japan's postwar constitution — covers emergency powers, human rights provisions, amendment thresholds, and the Emperor's role beyond just the Article 9 defense question.",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.integrity","weight":1},{"metricId":"society.integration","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: seed
    id: "jp_regional_autonomy",
    countryId: "JP",
    kind: "primary",
    title: "Regional Autonomy and Decentralization Act",
    description: "The balance of power between Tokyo and the prefectures — how much fiscal and regulatory authority to devolve to regional governments.",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"economic.ruralRevitalization","weight":1},{"metricId":"governance.openness","weight":0.4},{"metricId":"governance.integrity","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization",
  },
  {
    // source: seed
    id: "jp_electoral_reform",
    countryId: "JP",
    kind: "primary",
    title: "Electoral Reform Act",
    description: "Electoral system reform — the debate over FPTP vs. proportional representation, campaign finance, voting age, and political participation.",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.integrity","weight":1},{"metricId":"society.integration","weight":0.2}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: seed
    id: "jp_regional_governance",
    countryId: "JP",
    kind: "primary",
    title: "Regional Governance Act",
    description: "Prefectural governance — local government transparency, public participation mechanisms, and administrative efficiency funded from the regional budget.",
    category: "governance",
    allowedScope: "both",
    targets: [{"metricId":"governance.integrity","weight":1},{"metricId":"society.integration","weight":0.3},{"metricId":"governance.openness","weight":0.2}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: seed
    id: "jp_foreign_aid_diplomacy",
    countryId: "JP",
    kind: "primary",
    title: "Foreign Aid and Diplomacy Act",
    description: "Japan's ODA (Official Development Assistance) and diplomatic engagement — Japan is historically one of the world's largest aid donors, with a focus on Asia-Pacific development.",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"governance.integrity","weight":1},{"metricId":"society.integration","weight":0.2},{"metricId":"economic.gdpGrowth","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth",
  },
  {
    // source: seed
    id: "jp_trade_agreements",
    countryId: "JP",
    kind: "primary",
    title: "Trade Agreements and Economic Partnership Act",
    description: "Japan's trade policy framework — CPTPP, RCEP, bilateral EPAs, and the broader approach to free trade vs. protectionism. Separate from tariff rates — this is about the diplomatic framework.",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.foodSecurity","weight":-0.3},{"metricId":"economic.smallBusinessFormation","weight":0.2},{"metricId":"society.integration","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.foodSecurity,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_robotics_ai",
    countryId: "JP",
    kind: "primary",
    title: "Robotics and Artificial Intelligence Policy Act",
    description: "Japan's robotics leadership and the growing AI debate — regulation vs. promotion, automation in eldercare and agriculture, workforce displacement, and ethical AI frameworks.",
    category: "technology",
    allowedScope: "national",
    targets: [{"metricId":"economy.productivity","weight":1},{"metricId":"economic.unemploymentRate","weight":0.3},{"metricId":"health.socialInsurance","weight":0.3},{"metricId":"economic.gdpGrowth","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,economic.gdpGrowth,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_rd_investment",
    countryId: "JP",
    kind: "primary",
    title: "National R&D Investment Strategy Act",
    description: "Government R&D investment strategy — applied research, technology commercialization, innovation hubs, and public-private research partnerships. Distinct from basic science/JSPS/JAXA funding.",
    category: "technology",
    allowedScope: "national",
    targets: [{"metricId":"economic.rdIntensity","weight":1},{"metricId":"economic.gdpGrowth","weight":0.4},{"metricId":"economic.smallBusinessFormation","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.rdIntensity,economic.gdpGrowth,economic.smallBusinessFormation,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_digital_governance",
    countryId: "JP",
    kind: "primary",
    title: "Digital Governance and e-Government Act",
    description: "Government digitization — the Digital Agency's mission to modernize Japan's famously paper-heavy bureaucracy. My Number system, digital IDs, paperless administration, and government data platforms.",
    category: "technology",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.utilities","weight":1},{"metricId":"governance.openness","weight":0.3},{"metricId":"governance.integrity","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_policing_public_safety",
    countryId: "JP",
    kind: "primary",
    title: "Policing and Public Safety Act",
    description: "Police funding, the koban (police box) neighborhood system, surveillance infrastructure, organized crime enforcement, and the balance between public safety and civil liberties.",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"society.integration","weight":0.3},{"metricId":"healthcare.mentalHealthAccess","weight":-0.1},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_criminal_justice",
    countryId: "JP",
    kind: "primary",
    title: "Criminal Justice and Rehabilitation Act",
    description: "Prison system reform, rehabilitation vs. punishment, the death penalty debate, juvenile justice, and reintegration programs. Japan faces criticism over harsh detention conditions and the daiyo kangoku (substitute prison) system.",
    category: "law_justice",
    allowedScope: "national",
    targets: [{"metricId":"publicSafety.incarcerationRate","weight":1},{"metricId":"society.integration","weight":0.5},{"metricId":"healthcare.mentalHealthAccess","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/publicSafety.incarcerationRate,healthcare.mentalHealthAccess,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_regional_policing",
    countryId: "JP",
    kind: "primary",
    title: "Regional Policing Act",
    description: "Prefectural police funding — community safety programs, local koban staffing, traffic enforcement, and crime prevention initiatives funded from the regional budget.",
    category: "law_justice",
    allowedScope: "both",
    targets: [{"metricId":"society.integration","weight":0.2},{"metricId":"economic.ruralRevitalization","weight":0.1},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.economicFreedom",
  },
  {
    // source: seed
    id: "jp_jsdf_recruitment",
    countryId: "JP",
    kind: "primary",
    title: "JSDF Recruitment and Service Act",
    description: "Self-Defense Forces recruitment amid demographic decline - within the Article 9 framework",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.militaryReadiness","weight":1},{"metricId":"governance.nationalPride","weight":0.4},{"metricId":"governance.civilLiberties","weight":-0.4},{"metricId":"economic.smallBusinessFormation","weight":0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.militaryReadiness,governance.nationalPride,governance.civilLiberties,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "jp_media_press",
    countryId: "JP",
    kind: "primary",
    title: "Media and Press Freedom Act",
    description: "Press club (_kisha kurabu_) reform, NHK governance, broadcast neutrality rules, and journalist access",
    category: "mediaInformation",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1.3},{"metricId":"mediaInformation.stateMediaControl","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/mediaInformation.stateMediaControl",
  },
];
