import type { CatalogEntry } from "./catalog.js";
/**
 * BR legislation catalog. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateCatalogs.ts
 * Source: src/lib/seeds/br/brLegislationTypes.ts (14 types),
 * src/lib/politicalLegislation/marginAdapter.ts ADAPTER_TIER1 (target mapping),
 * src/lib/seeds/reference/budgets.ts policyDefaults (tax baselines). See the
 * generator header for the mapping rules and the PORT-STUB convention.
 */
export const CATALOG_BR: CatalogEntry[] = [
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "br_income_tax_rate",
    countryId: "BR",
    kind: "tax",
    title: "Imposto de Renda Statute",
    description: "Sets the top marginal personal income tax rate",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "incomeTax", minRate: 0, maxRate: 30, step: 5, baselineRate: 18 },
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"society.socialMobility","weight":-0.4},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,governance.budgetBalance",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "br_corporate_tax",
    countryId: "BR",
    kind: "tax",
    title: "Imposto de Renda sobre Pessoas Jurídicas Statute",
    description: "Sets the corporate income tax rate",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "domesticCorporateTax", minRate: 0, maxRate: 26, step: 5, baselineRate: 13 },
    targets: [{"metricId":"economic.economicFreedom","weight":1},{"metricId":"economic.smallBusinessFormation","weight":0.5},{"metricId":"governance.budgetBalance","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom,economic.smallBusinessFormation,governance.budgetBalance",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "br_ivc",
    countryId: "BR",
    kind: "tax",
    title: "Imposto sobre Vendas e Consignações Schedule",
    description: "Sets the cascading sales/turnover tax (IVC) rate",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "salesTax", minRate: 0, maxRate: 22, step: 5, baselineRate: 10 },
    targets: [{"metricId":"economic.costOfLiving","weight":0.6},{"metricId":"governance.budgetBalance","weight":-0.6}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,governance.budgetBalance",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "br_iap_contribution",
    countryId: "BR",
    kind: "tax",
    title: "Institutos de Aposentadoria e Pensões Contribution Statute",
    description: "Sets employer/employee social-insurance contributions (the IAP system)",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "payrollTax", minRate: 10, maxRate: 32, step: 10, baselineRate: 20 },
    targets: [{"metricId":"economic.economicFreedom","weight":1},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom,governance.budgetBalance",
  },
  {
    // source: seed; baselineRate = median authored option (no policyDefaults entry for this preset; PORT-STUB)
    id: "br_customs_tariff",
    countryId: "BR",
    kind: "tax",
    title: "Tarifa Aduaneira Statute",
    description: "Sets the external customs tariff",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "tariffs", minRate: 0, maxRate: 35, step: 17, baselineRate: 18 },
    targets: [{"metricId":"economic.tradeBalance","weight":0.5},{"metricId":"economic.costOfLiving","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.tradeBalance,economic.costOfLiving",
  },
  {
    // source: seed
    id: "br_state_enterprises",
    countryId: "BR",
    kind: "primary",
    title: "Empresa Estatal Statute",
    description: "Sets the balance of state vs private ownership of strategic industry",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.economicFreedom","weight":-0.9},{"metricId":"economic.smallBusinessFormation","weight":-0.6},{"metricId":"society.socialMobility","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "br_labor_law",
    countryId: "BR",
    kind: "primary",
    title: "Consolidação das Leis do Trabalho Statute",
    description: "Sets labor-market protection and union rights",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.economicFreedom","weight":-0.8},{"metricId":"economy.workerSecurity","weight":0.6}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.economicFreedom",
  },
  {
    // source: seed
    id: "br_social_security_benefits",
    countryId: "BR",
    kind: "primary",
    title: "IAP Pension & Social Insurance Benefits Act",
    description: "Sets the generosity of IAP pension and social-insurance benefits",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "br_public_health",
    countryId: "BR",
    kind: "primary",
    title: "Ministério da Saúde Funding Act",
    description: "Sets public-health service funding",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "br_education_funding",
    countryId: "BR",
    kind: "primary",
    title: "Ministério da Educação e Cultura Funding Act",
    description: "Sets public-education funding",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "br_defense_policy",
    countryId: "BR",
    kind: "primary",
    title: "Forças Armadas Funding Act",
    description: "Sets national defense funding",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "br_infrastructure_investment",
    countryId: "BR",
    kind: "primary",
    title: "SALTE Plan Investment Act",
    description: "Sets federal infrastructure and development-bank investment",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "br_general_administration",
    countryId: "BR",
    kind: "primary",
    title: "Administração Federal Act",
    description: "Sets general federal civil-administration funding",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: seed
    id: "br_state_grants",
    countryId: "BR",
    kind: "primary",
    title: "Auxílios aos Estados Act",
    description: "Sets discretionary federal aid/subventions to state governments",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
];
