import type { CatalogEntry } from "./catalog.js";
/**
 * IE legislation catalog. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateCatalogs.ts
 * Source: src/lib/seeds/ie/ieLegislationTypes.ts (58 types),
 * src/lib/politicalLegislation/marginAdapter.ts ADAPTER_TIER1 (target mapping),
 * src/lib/seeds/reference/budgets.ts policyDefaults (tax baselines). See the
 * generator header for the mapping rules and the PORT-STUB convention.
 */
export const CATALOG_IE: CatalogEntry[] = [
  {
    // source: ieLegislationTypes.ts ie_corporate_tax_rate; baselineRate from budget policyDefaults option ie_corporate_tax_rate_opt_3
    id: "ie_corporate_tax_rate",
    countryId: "IE",
    kind: "tax",
    title: "Statutory Corporation Tax Act",
    description: "Sets the headline rate of corporation tax on company profits",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "domesticCorporateTax", minRate: 0, maxRate: 33, step: 2, baselineRate: 12.5 },
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.unemploymentRate","weight":0.4},{"metricId":"society.socialMobility","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.unemploymentRate,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_foreign_corporate_tax_rate; baselineRate from budget policyDefaults option ie_foreign_corporate_tax_rate_opt_3
    id: "ie_foreign_corporate_tax_rate",
    countryId: "IE",
    kind: "tax",
    title: "Foreign Corporation Tax Act",
    description: "Sets the rate of corporation tax on foreign-headquartered corps operating in Ireland",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "foreignCorporateTax", minRate: 0, maxRate: 33, step: 2, baselineRate: 12.5 },
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.tradeBalance","weight":0.4},{"metricId":"economic.fdiPipelineStrength","weight":0.6},{"metricId":"economic.mncDependency","weight":-0.5},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.tradeBalance,economic.fdiPipelineStrength,economic.mncDependency,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_income_tax_rate; baselineRate from budget policyDefaults option ie_income_tax_rate_opt_5
    id: "ie_income_tax_rate",
    countryId: "IE",
    kind: "tax",
    title: "Statutory Income Tax Act",
    description: "Adjusts the higher rate of income tax on personal earnings",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "incomeTax", minRate: 0, maxRate: 55, step: 5, baselineRate: 30 },
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.povertyRate","weight":-0.5},{"metricId":"society.socialMobility","weight":-0.7},{"metricId":"economic.gdpGrowth","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.povertyRate,economic.gdpGrowth",
  },
  {
    // source: ieLegislationTypes.ts ie_usc; baselineRate from budget policyDefaults option ie_usc_opt_5
    id: "ie_usc",
    countryId: "IE",
    kind: "tax",
    title: "Universal Social Charge Act",
    description: "Adjusts the Universal Social Charge — a separate levy on gross income",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "universalSocialCharge", minRate: 0, maxRate: 20, step: 1, baselineRate: 8 },
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.povertyRate","weight":-0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"society.socialMobility","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.povertyRate,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_prsi; baselineRate from budget policyDefaults option ie_prsi_opt_5
    id: "ie_prsi",
    countryId: "IE",
    kind: "tax",
    title: "Pay-Related Social Insurance Act",
    description: "Sets PRSI rates funding the Social Insurance Fund",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "payrollTax", minRate: 0, maxRate: 26, step: 2, baselineRate: 11 },
    targets: [{"metricId":"economic.unemploymentRate","weight":1},{"metricId":"economic.medianIncome","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"society.socialMobility","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,economic.medianIncome,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_vat_rate; baselineRate from budget policyDefaults option ie_vat_rate_opt_5
    id: "ie_vat_rate",
    countryId: "IE",
    kind: "tax",
    title: "Statutory Value-Added Tax Act",
    description: "Sets the standard VAT rate on goods and services",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "salesTax", minRate: 0, maxRate: 35, step: 2, baselineRate: 21 },
    targets: [{"metricId":"economic.costOfLiving","weight":-1},{"metricId":"economic.gdpGrowth","weight":-0.25},{"metricId":"economic.povertyRate","weight":-0.6},{"metricId":"economic.smallBusinessFormation","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.costOfLiving,economic.gdpGrowth,economic.povertyRate,economic.smallBusinessFormation,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_customs_tariff_rate; baselineRate from budget policyDefaults option ie_customs_tariff_rate_opt_0
    id: "ie_customs_tariff_rate",
    countryId: "IE",
    kind: "tax",
    title: "Customs Tariff Act",
    description: "Sets customs duties on imports",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "tariffs", minRate: 0, maxRate: 50, step: 2, baselineRate: 0 },
    targets: [{"metricId":"economic.tradeBalance","weight":1},{"metricId":"economic.costOfLiving","weight":-0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":0.4},{"metricId":"economic.fdiPipelineStrength","weight":-0.5},{"metricId":"economic.mncDependency","weight":0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.tradeBalance,economic.costOfLiving,economic.manufacturingCompetitiveness,economic.fdiPipelineStrength,economic.mncDependency",
  },
  {
    // source: ieLegislationTypes.ts ie_local_property_tax; baselineRate from budget policyDefaults option ie_local_property_tax_opt_4
    id: "ie_local_property_tax",
    countryId: "IE",
    kind: "tax",
    title: "Local Property Tax Act",
    description: "Sets the rate of annual self-assessed Local Property Tax",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "propertyTax", minRate: 0, maxRate: 1, step: 0.03, baselineRate: 0.18 },
    targets: [{"metricId":"infrastructure.publicHousing","weight":-0.8},{"metricId":"social.vacantPropertyRate","weight":-0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"society.socialMobility","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.vacantPropertyRate,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_stamp_duty; baselineRate from budget policyDefaults option ie_stamp_duty_opt_3
    id: "ie_stamp_duty",
    countryId: "IE",
    kind: "tax",
    title: "Stamp Duty Act",
    description: "Sets the rate of stamp duty on property and share transactions",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "stampDuty", minRate: 0, maxRate: 20, step: 0.5, baselineRate: 2 },
    targets: [{"metricId":"economic.smallBusinessFormation","weight":0.5},{"metricId":"infrastructure.publicHousing","weight":-0.4},{"metricId":"social.vacantPropertyRate","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"social.rentalPressureIndex","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation,social.vacantPropertyRate,governance.budgetBalance,social.rentalPressureIndex",
  },
  {
    // source: ieLegislationTypes.ts ie_capital_gains_tax; baselineRate from budget policyDefaults option ie_capital_gains_tax_opt_5
    id: "ie_capital_gains_tax",
    countryId: "IE",
    kind: "tax",
    title: "Capital Gains Tax Act",
    description: "Sets the rate of capital gains tax on realised investment returns",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "capitalGainsTax", minRate: 0, maxRate: 55, step: 5, baselineRate: 25 },
    targets: [{"metricId":"economic.smallBusinessFormation","weight":0.6},{"metricId":"economic.fdiPipelineStrength","weight":0.3},{"metricId":"society.socialMobility","weight":-0.5},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation,economic.fdiPipelineStrength,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_excise_duty; baselineRate from budget policyDefaults option ie_excise_duty_opt_4
    id: "ie_excise_duty",
    countryId: "IE",
    kind: "tax",
    title: "Excise Duty Act",
    description: "Sets excise multiplier for alcohol, tobacco, and fuel duties (100 = baseline)",
    category: "tax",
    allowedScope: "national",
    taxPolicy: { scope: "federal", taxType: "exciseDuty", minRate: 0, maxRate: 300, step: 25, baselineRate: 100 },
    targets: [{"metricId":"environment.stewardship","weight":0.5},{"metricId":"environment.agriEmissionsShare","weight":0.2},{"metricId":"economic.costOfLiving","weight":-0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"society.socialMobility","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.agriEmissionsShare,economic.costOfLiving,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_housing_policy
    id: "ie_housing_policy",
    countryId: "IE",
    kind: "primary",
    title: "Housing Development and Tenure Act",
    description: "Sets national housing development targets, planning policy, and tenure mix",
    category: "housing",
    allowedScope: "both",
    targets: [{"metricId":"infrastructure.publicHousing","weight":1.6},{"metricId":"social.housingCompletionsRate","weight":0.7},{"metricId":"social.rentalPressureIndex","weight":0.5},{"metricId":"social.vacantPropertyRate","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.housingCompletionsRate,social.rentalPressureIndex,social.vacantPropertyRate,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_healthcare_policy
    id: "ie_healthcare_policy",
    countryId: "IE",
    kind: "primary",
    title: "Health Services Bill",
    description: "Governs the structure and funding of the Irish public health system",
    category: "healthcare",
    allowedScope: "both",
    targets: [{"metricId":"health.outcomes","weight":1},{"metricId":"health.prevention","weight":0.6},{"metricId":"healthcare.slaintecareProgress","weight":0.8},{"metricId":"healthcare.hseWaitingListMonths","weight":0.5},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.slaintecareProgress,healthcare.hseWaitingListMonths,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_public_health
    id: "ie_public_health",
    countryId: "IE",
    kind: "primary",
    title: "Public Health and Disease Prevention Act",
    description: "Funds HSE Health Protection, vaccination outreach, and public-health levies",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.prevention","weight":1.5},{"metricId":"health.outcomes","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_mental_health
    id: "ie_mental_health",
    countryId: "IE",
    kind: "primary",
    title: "Mental Health Services Act",
    description: "Funds community-based mental health teams and CAMHS",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"healthcare.mentalHealthAccess","weight":1},{"metricId":"health.outcomes","weight":0.3},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.mentalHealthAccess,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_elder_care
    id: "ie_elder_care",
    countryId: "IE",
    kind: "primary",
    title: "Fair Deal Reform Act",
    description: "Sets the Nursing Homes Support Scheme and statutory home-care framework",
    category: "healthcare",
    allowedScope: "national",
    targets: [{"metricId":"health.socialInsurance","weight":1},{"metricId":"health.outcomes","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.6},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_education_funding
    id: "ie_education_funding",
    countryId: "IE",
    kind: "primary",
    title: "Primary and Post-Primary Education Funding Act",
    description: "Sets per-pupil capitation, DEIS funding, and school-meals/transport programmes",
    category: "education",
    allowedScope: "both",
    targets: [{"metricId":"education.universalSchooling","weight":1},{"metricId":"society.socialMobility","weight":0.5},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_higher_education
    id: "ie_higher_education",
    countryId: "IE",
    kind: "primary",
    title: "Higher Education and SUSI Reform Act",
    description: "Sets the registration-fee + SUSI maintenance-grant framework for third-level",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.attainment","weight":1},{"metricId":"society.socialMobility","weight":0.8},{"metricId":"education.adultSkills","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_research_science
    id: "ie_research_science",
    countryId: "IE",
    kind: "primary",
    title: "Research and Science Funding Act",
    description: "Funds SFI, IRC, and disruptive-technologies research programmes",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.rdIntensity","weight":1},{"metricId":"economic.fdiPipelineStrength","weight":0.4},{"metricId":"economic.manufacturingCompetitiveness","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.rdIntensity,economic.fdiPipelineStrength,economic.manufacturingCompetitiveness,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_curriculum_reform
    id: "ie_curriculum_reform",
    countryId: "IE",
    kind: "primary",
    title: "Leaving Certificate Reform Act",
    description: "Sets the Senior Cycle assessment framework and exam-based vs continuous-assessment balance",
    category: "education",
    allowedScope: "national",
    targets: [{"metricId":"education.standards","weight":0.6},{"metricId":"education.academicPressure","weight":0.7},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"social.irishLanguageStrength","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/education.academicPressure,social.irishLanguageStrength,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_state_pensions
    id: "ie_state_pensions",
    countryId: "IE",
    kind: "primary",
    title: "Contributory State Pension Act",
    description: "Sets age qualification, indexation, and Total Contributions Approach for State Pension",
    category: "welfare",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":-1},{"metricId":"economic.povertyRate","weight":0.6},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.laborParticipation","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.povertyRate,economic.laborParticipation,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_unemployment_benefits
    id: "ie_unemployment_benefits",
    countryId: "IE",
    kind: "primary",
    title: "Jobseeker's Allowance Reform Act",
    description: "Sets JSA/JSB rates, eligibility, and Intreo activation requirements",
    category: "welfare",
    allowedScope: "national",
    targets: [{"metricId":"economic.unemploymentRate","weight":0.6},{"metricId":"economic.povertyRate","weight":0.7},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,economic.povertyRate,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_working_family_payment
    id: "ie_working_family_payment",
    countryId: "IE",
    kind: "primary",
    title: "Working Family Payment Act",
    description: "Sets means-tested in-work family benefit thresholds and per-child supplements",
    category: "welfare",
    allowedScope: "national",
    targets: [{"metricId":"economic.povertyRate","weight":1},{"metricId":"society.socialMobility","weight":0.5},{"metricId":"society.integration","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.unemploymentRate","weight":0.2},{"metricId":"population.birthRate","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.povertyRate,governance.budgetBalance,economic.unemploymentRate,population.birthRate,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_parental_leave
    id: "ie_parental_leave",
    countryId: "IE",
    kind: "primary",
    title: "Parent's Leave and Benefit Act",
    description: "Sets duration and rate of paid parent's leave",
    category: "welfare",
    allowedScope: "national",
    targets: [{"metricId":"society.womensOpportunity","weight":1},{"metricId":"population.birthRate","weight":0.4},{"metricId":"economy.workerSecurity","weight":0.4},{"metricId":"society.integration","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.2},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.birthRate,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_childcare_policy
    id: "ie_childcare_policy",
    countryId: "IE",
    kind: "primary",
    title: "National Childcare Scheme Act",
    description: "Sets NCS means-tested subsidies and AIM disability supports",
    category: "welfare",
    allowedScope: "national",
    targets: [{"metricId":"society.familyStability","weight":1},{"metricId":"population.birthRate","weight":0.4},{"metricId":"society.womensOpportunity","weight":0.5},{"metricId":"infrastructure.publicHousing","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.birthRate,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_gender_equality
    id: "ie_gender_equality",
    countryId: "IE",
    kind: "primary",
    title: "Gender Pay Gap and Equality Reform Act",
    description: "Sets pay-gap reporting thresholds and gender quotas",
    category: "social",
    allowedScope: "national",
    targets: [{"metricId":"society.womensOpportunity","weight":1},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"society.civicLife","weight":0.3},{"metricId":"society.integration","weight":0.3}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: ieLegislationTypes.ts ie_drug_policy
    id: "ie_drug_policy",
    countryId: "IE",
    kind: "primary",
    title: "Misuse of Drugs Reform Act",
    description: "Sets the framework for personal-use possession, supply offences, and harm reduction",
    category: "criminal_justice",
    allowedScope: "national",
    targets: [{"metricId":"publicSafety.recidivismRate","weight":0.7},{"metricId":"order.safety","weight":0.1},{"metricId":"healthcare.mentalHealthAccess","weight":0.4},{"metricId":"publicSafety.incarcerationRate","weight":0.6},{"metricId":"governance.budgetBalance","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/publicSafety.recidivismRate,healthcare.mentalHealthAccess,publicSafety.incarcerationRate,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_minimum_wage
    id: "ie_minimum_wage",
    countryId: "IE",
    kind: "primary",
    title: "National Minimum Wage Act",
    description: "Sets the national minimum hourly wage rate",
    category: "labour",
    allowedScope: "national",
    targets: [{"metricId":"economic.medianIncome","weight":1},{"metricId":"economic.povertyRate","weight":0.5},{"metricId":"economic.smallBusinessFormation","weight":-0.4},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"economic.unemploymentRate","weight":0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.povertyRate,economic.smallBusinessFormation,economic.unemploymentRate",
  },
  {
    // source: ieLegislationTypes.ts ie_workers_rights
    id: "ie_workers_rights",
    countryId: "IE",
    kind: "primary",
    title: "Workplace Relations Reform Act",
    description: "Sets workers' rights framework — sick pay, right to disconnect, collective bargaining",
    category: "labour",
    allowedScope: "national",
    targets: [{"metricId":"economy.workerSecurity","weight":1},{"metricId":"economic.medianIncome","weight":-0.3},{"metricId":"economic.productivityGrowth","weight":0.3},{"metricId":"economic.smallBusinessFormation","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.medianIncome,economic.productivityGrowth,economic.smallBusinessFormation",
  },
  {
    // source: ieLegislationTypes.ts ie_workforce_development
    id: "ie_workforce_development",
    countryId: "IE",
    kind: "primary",
    title: "Apprenticeship and Workforce Development Act",
    description: "Funds apprenticeships, SOLAS programmes, and lifelong learning",
    category: "education",
    allowedScope: "both",
    targets: [{"metricId":"education.adultSkills","weight":1},{"metricId":"economic.unemploymentRate","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.2}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.unemploymentRate,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_sme_support
    id: "ie_sme_support",
    countryId: "IE",
    kind: "primary",
    title: "Enterprise Ireland SME Strategy Act",
    description: "Funds Enterprise Ireland, IDA, and Local Enterprise Office programmes",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.smallBusinessFormation","weight":1},{"metricId":"economic.gdpGrowth","weight":-0.4},{"metricId":"economic.unemploymentRate","weight":0.4},{"metricId":"economic.mncDependency","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.smallBusinessFormation,economic.gdpGrowth,economic.unemploymentRate,economic.mncDependency,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_fiscal_stimulus
    id: "ie_fiscal_stimulus",
    countryId: "IE",
    kind: "primary",
    title: "National Development Plan Fiscal Stance Act",
    description: "Sets capital-spending envelope and EU Stability Pact navigation",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.gdpGrowth","weight":1},{"metricId":"economic.unemploymentRate","weight":0.4},{"metricId":"governance.budgetBalance","weight":-0.7},{"metricId":"governance.debtToGdp","weight":-0.5},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.gdpGrowth,economic.unemploymentRate,governance.budgetBalance,governance.debtToGdp,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_transport_rail
    id: "ie_transport_rail",
    countryId: "IE",
    kind: "primary",
    title: "National Transport Strategy Act",
    description: "Sets BusConnects, MetroLink, and rail investment trajectory",
    category: "infrastructure",
    allowedScope: "both",
    targets: [{"metricId":"infrastructure.transit","weight":1},{"metricId":"infrastructure.highways","weight":0.5},{"metricId":"environment.stewardship","weight":0.4},{"metricId":"infrastructure.publicHousing","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_digital_infrastructure
    id: "ie_digital_infrastructure",
    countryId: "IE",
    kind: "primary",
    title: "National Broadband Plan Act",
    description: "Sets NBP rollout trajectory and gigabit-society targets",
    category: "infrastructure",
    allowedScope: "national",
    targets: [{"metricId":"infrastructure.utilities","weight":1},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_regional_economic_development
    id: "ie_regional_economic_development",
    countryId: "IE",
    kind: "primary",
    title: "Regional Enterprise Development Strategy Act",
    description: "Funds Western Development Commission, Regional Enterprise Plans, balanced development",
    category: "economic",
    allowedScope: "both",
    targets: [{"metricId":"economic.ruralRevitalization","weight":1},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"population.urbanizationRate","weight":-0.4},{"metricId":"economic.gdpGrowth","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,population.urbanizationRate,economic.gdpGrowth,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_climate_policy
    id: "ie_climate_policy",
    countryId: "IE",
    kind: "primary",
    title: "Climate Action Bill",
    description: "Sets national carbon reduction targets and energy transition policies",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":1.5},{"metricId":"environment.agriEmissionsShare","weight":0.6},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"environment.climateResilience","weight":0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.agriEmissionsShare,economic.gdpGrowth,environment.climateResilience,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_renewable_energy_target
    id: "ie_renewable_energy_target",
    countryId: "IE",
    kind: "primary",
    title: "Offshore Wind and Renewable Energy Act",
    description: "Sets renewable-electricity targets, foreshore licensing, and ORESS auction structure",
    category: "environment",
    allowedScope: "national",
    targets: [{"metricId":"environment.stewardship","weight":1.5},{"metricId":"infrastructure.utilities","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_agricultural_subsidies
    id: "ie_agricultural_subsidies",
    countryId: "IE",
    kind: "primary",
    title: "Common Agricultural Policy Implementation Act",
    description: "Sets CAP Pillar 1 / Pillar 2 split and eco-scheme conditionality",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":-1},{"metricId":"economic.capDependency","weight":0.4},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"environment.agriEmissionsShare","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,economic.capDependency,economic.ruralRevitalization,environment.agriEmissionsShare,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_food_security
    id: "ie_food_security",
    countryId: "IE",
    kind: "primary",
    title: "Food Vision Strategy Act",
    description: "Sets the Food Vision 2030 framework for agri-food output and sustainability",
    category: "economic",
    allowedScope: "national",
    targets: [{"metricId":"economic.foodSecurity","weight":-1},{"metricId":"environment.agriEmissionsShare","weight":0.5},{"metricId":"economic.tradeBalance","weight":-0.4},{"metricId":"economic.ruralRevitalization","weight":-0.3},{"metricId":"economic.mncDependency","weight":0.2},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.foodSecurity,environment.agriEmissionsShare,economic.tradeBalance,economic.ruralRevitalization,economic.mncDependency,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_rural_development
    id: "ie_rural_development",
    countryId: "IE",
    kind: "primary",
    title: "LEADER and Rural Development Programme Act",
    description: "Funds LEADER community-led development, Town & Village Renewal, and Údarás na Gaeltachta",
    category: "economic",
    allowedScope: "both",
    targets: [{"metricId":"economic.ruralRevitalization","weight":1},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"social.irishLanguageStrength","weight":0.3},{"metricId":"population.urbanizationRate","weight":-0.4},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,social.irishLanguageStrength,population.urbanizationRate,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_peat_bog_policy
    id: "ie_peat_bog_policy",
    countryId: "IE",
    kind: "primary",
    title: "Peatlands Conservation and Restoration Act",
    description: "Sets Bord na Móna just-transition, rewetting, and turf-cutting framework",
    category: "environment",
    allowedScope: "both",
    targets: [{"metricId":"environment.conservation","weight":1},{"metricId":"environment.stewardship","weight":0.6},{"metricId":"environment.agriEmissionsShare","weight":0.3},{"metricId":"economic.ruralRevitalization","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/environment.agriEmissionsShare,economic.ruralRevitalization,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_defence_spending
    id: "ie_defence_spending",
    countryId: "IE",
    kind: "primary",
    title: "Defence Forces Spending Act",
    description: "Sets the Defence Forces Level of Ambition (LOA) framework and budget envelope",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.budgetBalance","weight":1},{"metricId":"governance.integrity","weight":0.3},{"metricId":"economic.gdpGrowth","weight":-0.3},{"metricId":"governance.unityReferendumSupport","weight":-0.2},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.gdpGrowth,governance.unityReferendumSupport,economic.smallBusinessFormation",
  },
  {
    // source: ieLegislationTypes.ts ie_neutrality_posture
    id: "ie_neutrality_posture",
    countryId: "IE",
    kind: "primary",
    title: "Constitutional Neutrality Doctrine Act",
    description: "Sets the framework for the triple-lock and EU CSDP / NATO posture",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.unityReferendumSupport","weight":0.4},{"metricId":"governance.openness","weight":-0.3},{"metricId":"society.integration","weight":-0.1},{"metricId":"governance.integrity","weight":0.3},{"metricId":"governance.militaryReadiness","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.unityReferendumSupport,governance.militaryReadiness",
  },
  {
    // source: ieLegislationTypes.ts ie_foreign_aid_diplomacy
    id: "ie_foreign_aid_diplomacy",
    countryId: "IE",
    kind: "primary",
    title: "Irish Aid and ODA Strategy Act",
    description: "Sets the framework for Official Development Assistance and multilateral engagement",
    category: "foreign_policy",
    allowedScope: "national",
    targets: [{"metricId":"governance.integrity","weight":-0.4},{"metricId":"governance.openness","weight":0.3},{"metricId":"society.integration","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_cybersecurity
    id: "ie_cybersecurity",
    countryId: "IE",
    kind: "primary",
    title: "National Cyber Security Centre Act",
    description: "Sets the framework for NCSC mandate, CNI designation, and NIS2 transposition",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":0.3},{"metricId":"health.prevention","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.smallBusinessFormation","weight":-0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.smallBusinessFormation",
  },
  {
    // source: ieLegislationTypes.ts ie_garda_policing
    id: "ie_garda_policing",
    countryId: "IE",
    kind: "primary",
    title: "An Garda Síochána Reform Act",
    description: "Sets the Garda Operating Model, oversight, and force-structure direction",
    category: "criminal_justice",
    allowedScope: "both",
    targets: [{"metricId":"order.safety","weight":-0.6},{"metricId":"order.policeStrength","weight":-0.5},{"metricId":"order.communityTrust","weight":0.5},{"metricId":"governance.integrity","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_criminal_justice
    id: "ie_criminal_justice",
    countryId: "IE",
    kind: "primary",
    title: "Criminal Justice and Special Criminal Court Reform Act",
    description: "Sets the framework for sentencing, bail, SCC scope, and Probation Service",
    category: "criminal_justice",
    allowedScope: "national",
    targets: [{"metricId":"publicSafety.recidivismRate","weight":1},{"metricId":"publicSafety.incarcerationRate","weight":0.5},{"metricId":"order.safety","weight":-0.3},{"metricId":"governance.integrity","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3},{"metricId":"economic.economicFreedom","weight":-0.15}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/publicSafety.recidivismRate,publicSafety.incarcerationRate,governance.budgetBalance,economic.economicFreedom",
  },
  {
    // source: ieLegislationTypes.ts ie_government_ethics
    id: "ie_government_ethics",
    countryId: "IE",
    kind: "primary",
    title: "Standards in Public Office Reform Act",
    description: "Sets SIPO scope, lobbying register enforcement, and post-employment cooling-off",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1},{"metricId":"governance.integrity","weight":0.5},{"metricId":"society.civicLife","weight":0.3}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: ieLegislationTypes.ts ie_electoral_reform
    id: "ie_electoral_reform",
    countryId: "IE",
    kind: "primary",
    title: "Electoral Commission and Seanad Reform Act",
    description: "Sets the framework for An Coimisiún Toghcháin remit and Seanad structure",
    category: "governance",
    allowedScope: "national",
    targets: [{"metricId":"governance.participation","weight":0.6},{"metricId":"society.civicLife","weight":0.5},{"metricId":"governance.integrity","weight":0.4},{"metricId":"governance.openness","weight":0.3}],
    status: "unavailable",
    blockingSystem: "legislation/effectDescriptor",
  },
  {
    // source: ieLegislationTypes.ts ie_immigration_asylum
    id: "ie_immigration_asylum",
    countryId: "IE",
    kind: "primary",
    title: "International Protection and IPAS Reform Act",
    description: "Sets the framework for asylum processing and Direct Provision replacement",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"population.migrationRate","weight":1},{"metricId":"governance.directProvisionLoad","weight":0.4},{"metricId":"society.integration","weight":0},{"metricId":"society.socialMobility","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.4},{"metricId":"governance.borderSecurity","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/population.migrationRate,governance.directProvisionLoad,governance.budgetBalance,governance.borderSecurity",
  },
  {
    // source: ieLegislationTypes.ts ie_work_visas
    id: "ie_work_visas",
    countryId: "IE",
    kind: "primary",
    title: "Critical Skills and Employment Permits Act",
    description: "Sets the framework for Critical Skills, General Employment Permit, and Stamp 4",
    category: "immigration",
    allowedScope: "national",
    targets: [{"metricId":"economic.fdiPipelineStrength","weight":0.7},{"metricId":"economic.unemploymentRate","weight":-0.4},{"metricId":"economic.mncDependency","weight":-0.4},{"metricId":"education.adultSkills","weight":0.4},{"metricId":"society.integration","weight":0.3},{"metricId":"population.migrationRate","weight":0.4},{"metricId":"infrastructure.publicHousing","weight":-0.4}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.fdiPipelineStrength,economic.unemploymentRate,economic.mncDependency,population.migrationRate",
  },
  {
    // source: ieLegislationTypes.ts ie_integration_programs
    id: "ie_integration_programs",
    countryId: "IE",
    kind: "primary",
    title: "New Communities Integration Strategy Act",
    description: "Sets the framework for ESOL, naturalisation, and Migrant Integration Strategy",
    category: "immigration",
    allowedScope: "both",
    targets: [{"metricId":"society.integration","weight":1.5},{"metricId":"society.socialMobility","weight":0.4},{"metricId":"social.irishLanguageStrength","weight":-0.2},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.irishLanguageStrength,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_regional_health
    id: "ie_regional_health",
    countryId: "IE",
    kind: "primary",
    title: "Regional Health Services Delivery Act",
    description: "Sets regional HSE network funding and community-health investment per RHA",
    category: "healthcare",
    allowedScope: "both",
    targets: [{"metricId":"health.outcomes","weight":1},{"metricId":"healthcare.hseWaitingListMonths","weight":0.4},{"metricId":"health.prevention","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/healthcare.hseWaitingListMonths,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_regional_housing
    id: "ie_regional_housing",
    countryId: "IE",
    kind: "primary",
    title: "Regional Housing Strategy Act",
    description: "Sets RSES housing targets, LDA activation, and AHB pipeline per region",
    category: "housing",
    allowedScope: "both",
    targets: [{"metricId":"social.housingCompletionsRate","weight":1},{"metricId":"infrastructure.publicHousing","weight":0.5},{"metricId":"social.vacantPropertyRate","weight":0.4},{"metricId":"social.rentalPressureIndex","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/social.housingCompletionsRate,social.vacantPropertyRate,social.rentalPressureIndex,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_regional_transport
    id: "ie_regional_transport",
    countryId: "IE",
    kind: "primary",
    title: "Regional Transport Infrastructure Act",
    description: "Sets Connecting Ireland rural mobility, regional rail, and LIS funding per region",
    category: "infrastructure",
    allowedScope: "both",
    targets: [{"metricId":"infrastructure.transit","weight":0.8},{"metricId":"infrastructure.highways","weight":0.4},{"metricId":"economic.ruralRevitalization","weight":0.5},{"metricId":"infrastructure.condition","weight":-0.3},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,governance.budgetBalance",
  },
  {
    // source: ieLegislationTypes.ts ie_regional_skills
    id: "ie_regional_skills",
    countryId: "IE",
    kind: "primary",
    title: "Regional Skills Forum Strategy Act",
    description: "Sets Regional Skills Fora, FET Strategy, and ETB capital programme per region",
    category: "education",
    allowedScope: "both",
    targets: [{"metricId":"education.adultSkills","weight":1.5},{"metricId":"economic.ruralRevitalization","weight":0.4},{"metricId":"economic.unemploymentRate","weight":0.3},{"metricId":"governance.budgetBalance","weight":-0.3}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/economic.ruralRevitalization,economic.unemploymentRate,governance.budgetBalance",
  },
  {
    // source: seed
    id: "ie_defence_recruitment",
    countryId: "IE",
    kind: "primary",
    title: "Defence Forces Recruitment Act",
    description: "Defence Forces recruitment, retention, and the reserve - within the neutrality tradition",
    category: "defense",
    allowedScope: "national",
    targets: [{"metricId":"governance.militaryReadiness","weight":1},{"metricId":"governance.nationalPride","weight":0.4},{"metricId":"governance.civilLiberties","weight":-0.4},{"metricId":"economic.smallBusinessFormation","weight":0.1}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/governance.militaryReadiness,governance.nationalPride,governance.civilLiberties,economic.smallBusinessFormation",
  },
  {
    // source: seed
    id: "ie_media_press",
    countryId: "IE",
    kind: "primary",
    title: "Media and Press Freedom Act",
    description: "Press regulation, public broadcaster governance, defamation reform, and media plurality",
    category: "mediaInformation",
    allowedScope: "national",
    targets: [{"metricId":"governance.openness","weight":1.3},{"metricId":"mediaInformation.stateMediaControl","weight":-0.5}],
    status: "unavailable",
    blockingSystem: "politicalMetrics/mediaInformation.stateMediaControl",
  },
];
