import type { StateDemographics as EngineStateDemographics } from "../electionEngine/types.js";

/** DC is a presidential electoral unit in Game from 1961. Its native region row
 * is headquarters-only, so its source-generated voter table lives here and is
 * only exposed to the presidential tally adapter. Generated by Game's
 * generateStateDemographicsForTest from the pinned US census bundles.
 * Source: Egg3901/AHDGame cb66acdf0129616b8a09902727e9b58715c8bacb,
 * stateDemographics.ts + usStateCensusData{,1953,1979,1991}.ts.
 */
const DC_BY_ERA = {
  "1953": {
    "categoryWeights": {
      "voterGroups": 100
    },
    "groups": {
      "young_renters": {
        "population": 11.3,
        "economicLean": -1.5,
        "socialLean": -1.5,
        "turnout": 37
      },
      "evangelicals": {
        "population": 8.8,
        "economicLean": 2.2,
        "socialLean": 3.6,
        "turnout": 59
      },
      "rural_traditionalists": {
        "population": 6.64,
        "economicLean": 1.7,
        "socialLean": 2,
        "turnout": 64
      },
      "union_trades": {
        "population": 10.28,
        "economicLean": -5,
        "socialLean": -0.9,
        "turnout": 50
      },
      "soccer_moms": {
        "population": 15.07,
        "economicLean": 0,
        "socialLean": 0,
        "turnout": 59
      },
      "college_liberals": {
        "population": 8.52,
        "economicLean": -4,
        "socialLean": -3.5,
        "turnout": 64
      },
      "small_business": {
        "population": 8.95,
        "economicLean": 3.3,
        "socialLean": 1.1,
        "turnout": 63
      },
      "public_sector": {
        "population": 7.07,
        "economicLean": -4,
        "socialLean": -2.5,
        "turnout": 62
      },
      "retirees": {
        "population": 9.97,
        "economicLean": -1,
        "socialLean": -0.5,
        "turnout": 70
      },
      "libertarians": {
        "population": 4.45,
        "economicLean": 4.5,
        "socialLean": 0,
        "turnout": 59
      },
      "new_immigrants": {
        "population": 3.1,
        "economicLean": -2.5,
        "socialLean": -2,
        "turnout": 30
      },
      "secular_professionals": {
        "population": 5.85,
        "economicLean": -2.5,
        "socialLean": -3,
        "turnout": 64
      }
    }
  },
  "1979": {
    "categoryWeights": {
      "voterGroups": 100
    },
    "groups": {
      "young_renters": {
        "population": 12.98,
        "economicLean": -3,
        "socialLean": -2.5,
        "turnout": 40
      },
      "evangelicals": {
        "population": 7.24,
        "economicLean": 4.2,
        "socialLean": 4.6,
        "turnout": 68
      },
      "rural_traditionalists": {
        "population": 4.05,
        "economicLean": 2.7,
        "socialLean": 2.5,
        "turnout": 67
      },
      "union_trades": {
        "population": 16.59,
        "economicLean": -4.8,
        "socialLean": -0.4,
        "turnout": 55
      },
      "soccer_moms": {
        "population": 13.19,
        "economicLean": -0.5,
        "socialLean": -0.5,
        "turnout": 59
      },
      "college_liberals": {
        "population": 9.36,
        "economicLean": -4.5,
        "socialLean": -4.5,
        "turnout": 63
      },
      "small_business": {
        "population": 8.47,
        "economicLean": 3.3,
        "socialLean": 1.1,
        "turnout": 64
      },
      "public_sector": {
        "population": 8.83,
        "economicLean": -4,
        "socialLean": -3,
        "turnout": 65
      },
      "retirees": {
        "population": 7.83,
        "economicLean": -0.5,
        "socialLean": 0.5,
        "turnout": 70
      },
      "libertarians": {
        "population": 2.51,
        "economicLean": 5,
        "socialLean": 0,
        "turnout": 60
      },
      "new_immigrants": {
        "population": 0.32,
        "economicLean": -3,
        "socialLean": -2,
        "turnout": 30
      },
      "secular_professionals": {
        "population": 8.62,
        "economicLean": -3,
        "socialLean": -4,
        "turnout": 65
      }
    }
  },
  "1991": {
    "categoryWeights": {
      "voterGroups": 100
    },
    "groups": {
      "young_renters": {
        "population": 13.19,
        "economicLean": -3.5,
        "socialLean": -3,
        "turnout": 40
      },
      "evangelicals": {
        "population": 7.35,
        "economicLean": 3.5,
        "socialLean": 5,
        "turnout": 72
      },
      "rural_traditionalists": {
        "population": 4.71,
        "economicLean": 2.8,
        "socialLean": 2.7,
        "turnout": 64
      },
      "union_trades": {
        "population": 16.03,
        "economicLean": -4.1,
        "socialLean": -0.3,
        "turnout": 52
      },
      "soccer_moms": {
        "population": 14.09,
        "economicLean": -0.9,
        "socialLean": -0.4,
        "turnout": 59
      },
      "college_liberals": {
        "population": 8.71,
        "economicLean": -4.4,
        "socialLean": -4.4,
        "turnout": 59
      },
      "small_business": {
        "population": 8.56,
        "economicLean": 3.4,
        "socialLean": 1.7,
        "turnout": 65
      },
      "public_sector": {
        "population": 7.09,
        "economicLean": -3.4,
        "socialLean": -2.9,
        "turnout": 58
      },
      "retirees": {
        "population": 8.65,
        "economicLean": -0.4,
        "socialLean": 1.2,
        "turnout": 70
      },
      "libertarians": {
        "population": 2.63,
        "economicLean": 5,
        "socialLean": 1,
        "turnout": 60
      },
      "new_immigrants": {
        "population": 0.77,
        "economicLean": -2.5,
        "socialLean": -1.5,
        "turnout": 30
      },
      "secular_professionals": {
        "population": 8.22,
        "economicLean": -2.9,
        "socialLean": -3.9,
        "turnout": 62
      }
    }
  },
  "2019": {
    "categoryWeights": {
      "voterGroups": 100
    },
    "groups": {
      "young_renters": {
        "population": 6.54,
        "economicLean": -4,
        "socialLean": -4,
        "turnout": 41
      },
      "evangelicals": {
        "population": 6.16,
        "economicLean": 3.6,
        "socialLean": 4.7,
        "turnout": 75
      },
      "rural_traditionalists": {
        "population": 6.32,
        "economicLean": 2.5,
        "socialLean": 2.2,
        "turnout": 65
      },
      "union_trades": {
        "population": 10.35,
        "economicLean": -4.2,
        "socialLean": -1.5,
        "turnout": 52
      },
      "soccer_moms": {
        "population": 13.03,
        "economicLean": -2.4,
        "socialLean": -1.9,
        "turnout": 59
      },
      "college_liberals": {
        "population": 11.41,
        "economicLean": -5,
        "socialLean": -5,
        "turnout": 66
      },
      "small_business": {
        "population": 9.95,
        "economicLean": 3,
        "socialLean": 1.3,
        "turnout": 68
      },
      "public_sector": {
        "population": 12.3,
        "economicLean": -4.4,
        "socialLean": -4.4,
        "turnout": 65
      },
      "retirees": {
        "population": 7.48,
        "economicLean": -0.8,
        "socialLean": 0.1,
        "turnout": 70
      },
      "libertarians": {
        "population": 3.61,
        "economicLean": 5,
        "socialLean": 1,
        "turnout": 64
      },
      "new_immigrants": {
        "population": 1.76,
        "economicLean": -3,
        "socialLean": -2,
        "turnout": 40
      },
      "secular_professionals": {
        "population": 11.1,
        "economicLean": -4.4,
        "socialLean": -5,
        "turnout": 71
      }
    }
  }
} as const;

export function dcPresidentialDemographics(era: string, lastUpdated: string): EngineStateDemographics {
  const key = era in DC_BY_ERA ? era as keyof typeof DC_BY_ERA : "2019";
  const row = DC_BY_ERA[key];
  return { _id: "DC", countryId: "US", categoryWeights: { ...row.categoryWeights }, groups: structuredClone(row.groups), lastUpdated } as unknown as EngineStateDemographics;
}
