import type { StateSeed } from "../types.js";
/**
 * Germany regions for 1991-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateRosters.ts
 * Sources:
 * - src/lib/seeds/de/deRegions1991.ts
 * - src/lib/seeds/registration/registrationLanes1991.ts build1991RegistrationSeeds DE entries
 */
export const deRegions1991: StateSeed[] = [
  {
    id: "BW",
    name: "Baden-Württemberg",
    countryId: "DE",
    population: 9822000,
    gdp: 240000,
    houseSeats: 38,
    senateSeats: 146,
    region: "Süden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 38, reg: 47 }, { abbr: "SPD", org: 23, reg: 29 }, { abbr: "FDP", org: 9, reg: 12 }, { abbr: "GRN", org: 6, reg: 7 }], independent: 2, unregistered: 3, unaffiliatedOrg: 24 },
  },
  {
    id: "BY",
    name: "Bayern",
    countryId: "DE",
    population: 11449000,
    gdp: 230000,
    houseSeats: 47,
    senateSeats: 204,
    region: "Süden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CSU", org: 41, reg: 52 }, { abbr: "SPD", org: 21, reg: 27 }, { abbr: "FDP", org: 6, reg: 8 }, { abbr: "GRN", org: 5, reg: 6 }], independent: 2, unregistered: 5, unaffiliatedOrg: 27 },
  },
  {
    id: "NW",
    name: "Nordrhein-Westfalen",
    countryId: "DE",
    population: 17400000,
    gdp: 350000,
    houseSeats: 64,
    senateSeats: 201,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 33, reg: 42 }, { abbr: "CDU", org: 28, reg: 36 }, { abbr: "FDP", org: 8, reg: 10 }, { abbr: "GRN", org: 5, reg: 5 }], independent: 1, unregistered: 6, unaffiliatedOrg: 26 },
  },
  {
    id: "HE",
    name: "Hessen",
    countryId: "DE",
    population: 5792000,
    gdp: 140000,
    houseSeats: 22,
    senateSeats: 110,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 31, reg: 41 }, { abbr: "SPD", org: 28, reg: 36 }, { abbr: "FDP", org: 8, reg: 10 }, { abbr: "GRN", org: 6, reg: 7 }], independent: 1, unregistered: 5, unaffiliatedOrg: 27 },
  },
  {
    id: "RP",
    name: "Rheinland-Pfalz",
    countryId: "DE",
    population: 3763000,
    gdp: 75000,
    houseSeats: 15,
    senateSeats: 101,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 32, reg: 42 }, { abbr: "SPD", org: 27, reg: 34 }, { abbr: "FDP", org: 9, reg: 11 }, { abbr: "GRN", org: 5, reg: 6 }], independent: 1, unregistered: 6, unaffiliatedOrg: 27 },
  },
  {
    id: "SL",
    name: "Saarland",
    countryId: "DE",
    population: 1073000,
    gdp: 20000,
    houseSeats: 4,
    senateSeats: 51,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 31, reg: 40 }, { abbr: "CDU", org: 30, reg: 38 }, { abbr: "FDP", org: 7, reg: 9 }, { abbr: "GRN", org: 4, reg: 5 }], independent: 1, unregistered: 7, unaffiliatedOrg: 28 },
  },
  {
    id: "NI",
    name: "Niedersachsen",
    countryId: "DE",
    population: 7388000,
    gdp: 130000,
    houseSeats: 30,
    senateSeats: 155,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 31, reg: 40 }, { abbr: "CDU", org: 28, reg: 36 }, { abbr: "FDP", org: 8, reg: 10 }, { abbr: "GRN", org: 5, reg: 6 }], independent: 1, unregistered: 7, unaffiliatedOrg: 28 },
  },
  {
    id: "SH",
    name: "Schleswig-Holstein",
    countryId: "DE",
    population: 2626000,
    gdp: 50000,
    houseSeats: 11,
    senateSeats: 89,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 30, reg: 40 }, { abbr: "CDU", org: 29, reg: 37 }, { abbr: "FDP", org: 8, reg: 10 }, { abbr: "GRN", org: 5, reg: 7 }], independent: 1, unregistered: 5, unaffiliatedOrg: 28 },
  },
  {
    id: "HH",
    name: "Hamburg",
    countryId: "DE",
    population: 1661000,
    gdp: 50000,
    houseSeats: 6,
    senateSeats: 121,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 33, reg: 42 }, { abbr: "CDU", org: 25, reg: 32 }, { abbr: "GRN", org: 7, reg: 9 }, { abbr: "FDP", org: 7, reg: 9 }], independent: 2, unregistered: 6, unaffiliatedOrg: 28 },
  },
  {
    id: "BRE",
    name: "Bremen",
    countryId: "DE",
    population: 685000,
    gdp: 19000,
    houseSeats: 3,
    senateSeats: 100,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 35, reg: 45 }, { abbr: "CDU", org: 22, reg: 28 }, { abbr: "GRN", org: 8, reg: 10 }, { abbr: "FDP", org: 7, reg: 9 }], independent: 2, unregistered: 6, unaffiliatedOrg: 28 },
  },
  {
    id: "BE",
    name: "Berlin",
    countryId: "DE",
    population: 3433000,
    gdp: 60000,
    houseSeats: 12,
    senateSeats: 200,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 28, reg: 36 }, { abbr: "SPD", org: 26, reg: 33 }, { abbr: "PDS", org: 9, reg: 12 }, { abbr: "FDP", org: 7, reg: 8 }, { abbr: "GRN", org: 6, reg: 7 }], independent: 1, unregistered: 3, unaffiliatedOrg: 24 },
  },
  {
    id: "BB",
    name: "Brandenburg",
    countryId: "DE",
    population: 2578000,
    gdp: 18000,
    houseSeats: 10,
    senateSeats: 88,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 27, reg: 35 }, { abbr: "CDU", org: 24, reg: 30 }, { abbr: "PDS", org: 14, reg: 18 }, { abbr: "FDP", org: 7, reg: 9 }], independent: 2, unregistered: 6, unaffiliatedOrg: 28 },
  },
  {
    id: "MV",
    name: "Mecklenburg-Vorpommern",
    countryId: "DE",
    population: 1924000,
    gdp: 12000,
    houseSeats: 7,
    senateSeats: 66,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 28, reg: 36 }, { abbr: "SPD", org: 22, reg: 27 }, { abbr: "PDS", org: 14, reg: 19 }, { abbr: "FDP", org: 7, reg: 9 }], independent: 2, unregistered: 7, unaffiliatedOrg: 29 },
  },
  {
    id: "SN",
    name: "Sachsen",
    countryId: "DE",
    population: 4771000,
    gdp: 30000,
    houseSeats: 17,
    senateSeats: 160,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 33, reg: 43 }, { abbr: "SPD", org: 18, reg: 22 }, { abbr: "PDS", org: 13, reg: 17 }, { abbr: "FDP", org: 9, reg: 11 }], independent: 1, unregistered: 6, unaffiliatedOrg: 27 },
  },
  {
    id: "ST",
    name: "Sachsen-Anhalt",
    countryId: "DE",
    population: 2873000,
    gdp: 18000,
    houseSeats: 10,
    senateSeats: 106,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 30, reg: 38 }, { abbr: "SPD", org: 23, reg: 28 }, { abbr: "PDS", org: 12, reg: 16 }, { abbr: "FDP", org: 9, reg: 10 }], independent: 1, unregistered: 7, unaffiliatedOrg: 26 },
  },
  {
    id: "TH",
    name: "Thüringen",
    countryId: "DE",
    population: 2611000,
    gdp: 16000,
    houseSeats: 9,
    senateSeats: 89,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 31, reg: 40 }, { abbr: "SPD", org: 22, reg: 27 }, { abbr: "PDS", org: 13, reg: 17 }, { abbr: "FDP", org: 8, reg: 10 }], independent: 1, unregistered: 5, unaffiliatedOrg: 26 },
  },
];

// Totals: 16 regions, 305 lower-house seats, 1987 upper/subnational seats (sum).
