import type { StateSeed } from "../types.js";
/**
 * Germany regions for 2019-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateRosters.ts
 * Sources:
 * - src/lib/seeds/de/deRegions.ts (2019-default bundle)
 * - src/lib/seeds/registration/registrationLanes.ts buildAllRegistrationSeeds DE entries
 */
export const deRegions2019: StateSeed[] = [
  {
    id: "BW",
    name: "Baden-Württemberg",
    countryId: "DE",
    population: 11280000,
    gdp: 579000,
    houseSeats: 38,
    senateSeats: 154,
    region: "Süden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CDU", org: 22, reg: 28 }, { abbr: "SPD", org: 16, reg: 22 }, { abbr: "GRN", org: 16, reg: 19 }, { abbr: "FDP", org: 9, reg: 10 }, { abbr: "AFD", org: 5, reg: 8 }], independent: 8, unregistered: 5, unaffiliatedOrg: 32 },
  },
  {
    id: "BY",
    name: "Bayern",
    countryId: "DE",
    population: 13176000,
    gdp: 716000,
    houseSeats: 47,
    senateSeats: 203,
    region: "Süden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CSU", org: 28, reg: 36 }, { abbr: "SPD", org: 12, reg: 18 }, { abbr: "GRN", org: 14, reg: 16 }, { abbr: "FDP", org: 7, reg: 9 }, { abbr: "AFD", org: 4, reg: 7 }], independent: 9, unregistered: 5, unaffiliatedOrg: 35 },
  },
  {
    id: "NW",
    name: "Nordrhein-Westfalen",
    countryId: "DE",
    population: 18140000,
    gdp: 774000,
    houseSeats: 64,
    senateSeats: 195,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 21, reg: 29 }, { abbr: "CDU", org: 19, reg: 27 }, { abbr: "GRN", org: 12, reg: 16 }, { abbr: "FDP", org: 8, reg: 10 }, { abbr: "AFD", org: 4, reg: 7 }], independent: 7, unregistered: 4, unaffiliatedOrg: 36 },
  },
  {
    id: "HE",
    name: "Hessen",
    countryId: "DE",
    population: 6392000,
    gdp: 321000,
    houseSeats: 22,
    senateSeats: 137,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 20, reg: 28 }, { abbr: "CDU", org: 17, reg: 23 }, { abbr: "GRN", org: 12, reg: 16 }, { abbr: "FDP", org: 9, reg: 11 }, { abbr: "AFD", org: 5, reg: 8 }], independent: 9, unregistered: 5, unaffiliatedOrg: 37 },
  },
  {
    id: "RP",
    name: "Rheinland-Pfalz",
    countryId: "DE",
    population: 4162000,
    gdp: 170000,
    houseSeats: 15,
    senateSeats: 101,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 21, reg: 30 }, { abbr: "CDU", org: 18, reg: 25 }, { abbr: "FDP", org: 8, reg: 11 }, { abbr: "GRN", org: 9, reg: 13 }, { abbr: "AFD", org: 5, reg: 8 }], independent: 8, unregistered: 5, unaffiliatedOrg: 39 },
  },
  {
    id: "SL",
    name: "Saarland",
    countryId: "DE",
    population: 993000,
    gdp: 37000,
    houseSeats: 4,
    senateSeats: 51,
    region: "Westen",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 27, reg: 37 }, { abbr: "CDU", org: 14, reg: 23 }, { abbr: "AFD", org: 5, reg: 10 }, { abbr: "FDP", org: 5, reg: 7 }, { abbr: "LNK", org: 5, reg: 7 }], independent: 10, unregistered: 6, unaffiliatedOrg: 44 },
  },
  {
    id: "NI",
    name: "Niedersachsen",
    countryId: "DE",
    population: 8141000,
    gdp: 345000,
    houseSeats: 30,
    senateSeats: 146,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 23, reg: 32 }, { abbr: "CDU", org: 15, reg: 23 }, { abbr: "GRN", org: 11, reg: 16 }, { abbr: "FDP", org: 7, reg: 10 }, { abbr: "AFD", org: 5, reg: 7 }], independent: 8, unregistered: 4, unaffiliatedOrg: 39 },
  },
  {
    id: "SH",
    name: "Schleswig-Holstein",
    countryId: "DE",
    population: 2933000,
    gdp: 108000,
    houseSeats: 11,
    senateSeats: 73,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 18, reg: 28 }, { abbr: "CDU", org: 17, reg: 22 }, { abbr: "GRN", org: 13, reg: 18 }, { abbr: "FDP", org: 9, reg: 11 }, { abbr: "AFD", org: 3, reg: 6 }], independent: 10, unregistered: 5, unaffiliatedOrg: 40 },
  },
  {
    id: "HH",
    name: "Hamburg",
    countryId: "DE",
    population: 1930000,
    gdp: 142000,
    houseSeats: 6,
    senateSeats: 123,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 23, reg: 30 }, { abbr: "GRN", org: 18, reg: 25 }, { abbr: "CDU", org: 9, reg: 15 }, { abbr: "FDP", org: 6, reg: 8 }, { abbr: "LNK", org: 5, reg: 7 }], independent: 9, unregistered: 6, unaffiliatedOrg: 39 },
  },
  {
    id: "BRE",
    name: "Bremen",
    countryId: "DE",
    population: 685000,
    gdp: 35000,
    houseSeats: 2,
    senateSeats: 87,
    region: "Norden",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 24, reg: 32 }, { abbr: "GRN", org: 16, reg: 21 }, { abbr: "CDU", org: 10, reg: 17 }, { abbr: "LNK", org: 6, reg: 8 }, { abbr: "FDP", org: 4, reg: 5 }], independent: 10, unregistered: 7, unaffiliatedOrg: 40 },
  },
  {
    id: "BE",
    name: "Berlin",
    countryId: "DE",
    population: 3850000,
    gdp: 180000,
    houseSeats: 12,
    senateSeats: 159,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 16, reg: 22 }, { abbr: "GRN", org: 16, reg: 22 }, { abbr: "CDU", org: 12, reg: 17 }, { abbr: "LNK", org: 11, reg: 12 }, { abbr: "AFD", org: 4, reg: 8 }, { abbr: "FDP", org: 4, reg: 6 }], independent: 8, unregistered: 5, unaffiliatedOrg: 37 },
  },
  {
    id: "BB",
    name: "Brandenburg",
    countryId: "DE",
    population: 2573000,
    gdp: 85000,
    houseSeats: 10,
    senateSeats: 88,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 20, reg: 30 }, { abbr: "AFD", org: 12, reg: 18 }, { abbr: "CDU", org: 8, reg: 15 }, { abbr: "LNK", org: 8, reg: 9 }, { abbr: "GRN", org: 4, reg: 8 }, { abbr: "FDP", org: 4, reg: 5 }], independent: 9, unregistered: 6, unaffiliatedOrg: 44 },
  },
  {
    id: "MV",
    name: "Mecklenburg-Vorpommern",
    countryId: "DE",
    population: 1624000,
    gdp: 52000,
    houseSeats: 6,
    senateSeats: 79,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SPD", org: 21, reg: 29 }, { abbr: "AFD", org: 11, reg: 18 }, { abbr: "CDU", org: 8, reg: 17 }, { abbr: "LNK", org: 8, reg: 11 }, { abbr: "GRN", org: 3, reg: 6 }, { abbr: "FDP", org: 0, reg: 4 }], independent: 9, unregistered: 6, unaffiliatedOrg: 49 },
  },
  {
    id: "SN",
    name: "Sachsen",
    countryId: "DE",
    population: 4057000,
    gdp: 145000,
    houseSeats: 16,
    senateSeats: 120,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "AFD", org: 16, reg: 25 }, { abbr: "CDU", org: 12, reg: 17 }, { abbr: "SPD", org: 10, reg: 19 }, { abbr: "LNK", org: 7, reg: 9 }, { abbr: "FDP", org: 5, reg: 6 }, { abbr: "GRN", org: 0, reg: 6 }], independent: 11, unregistered: 7, unaffiliatedOrg: 50 },
  },
  {
    id: "ST",
    name: "Sachsen-Anhalt",
    countryId: "DE",
    population: 2186000,
    gdp: 74000,
    houseSeats: 8,
    senateSeats: 97,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "AFD", org: 14, reg: 20 }, { abbr: "SPD", org: 12, reg: 24 }, { abbr: "CDU", org: 12, reg: 21 }, { abbr: "LNK", org: 8, reg: 10 }, { abbr: "FDP", org: 4, reg: 5 }, { abbr: "GRN", org: 0, reg: 4 }], independent: 9, unregistered: 7, unaffiliatedOrg: 50 },
  },
  {
    id: "TH",
    name: "Thüringen",
    countryId: "DE",
    population: 2115000,
    gdp: 68000,
    houseSeats: 8,
    senateSeats: 88,
    region: "Osten",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "AFD", org: 15, reg: 24 }, { abbr: "SPD", org: 10, reg: 22 }, { abbr: "CDU", org: 10, reg: 17 }, { abbr: "LNK", org: 10, reg: 12 }, { abbr: "FDP", org: 4, reg: 5 }, { abbr: "GRN", org: 0, reg: 4 }], independent: 9, unregistered: 7, unaffiliatedOrg: 51 },
  },
];

// Totals: 16 regions, 299 lower-house seats, 1901 upper/subnational seats (sum).
