import type { StateSeed } from "../types.js";
/**
 * Ireland regions for 2019-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateRosters.ts
 * Sources:
 * - src/lib/seeds/ie/ieRegions.ts (2019-default bundle)
 * - src/lib/seeds/ie/ieRegionVoteShares.ts IE_REGION_VOTE_SHARES_2024 (mainline's 2019-default selection) via calculateIEPartyOrg
 */
export const ieRegions2019: StateSeed[] = [
  {
    id: "DUB",
    name: "Dublin",
    countryId: "IE",
    population: 1458000,
    gdp: 180000,
    houseSeats: 49,
    senateSeats: 9,
    region: "Leinster",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 30, reg: 19 }, { abbr: "FG", org: 28, reg: 18 }, { abbr: "SF", org: 32, reg: 21 }, { abbr: "LAB", org: 14, reg: 7 }, { abbr: "GP", org: 13, reg: 6 }], independent: 29, unregistered: 0, unaffiliatedOrg: 0 },
  },
  {
    id: "KIL",
    name: "Kildare",
    countryId: "IE",
    population: 610000,
    gdp: 42000,
    houseSeats: 21,
    senateSeats: 8,
    region: "Leinster",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 35, reg: 23 }, { abbr: "FG", org: 32, reg: 21 }, { abbr: "SF", org: 28, reg: 18 }, { abbr: "LAB", org: 12, reg: 5 }, { abbr: "GP", org: 10, reg: 4 }], independent: 29, unregistered: 0, unaffiliatedOrg: 0 },
  },
  {
    id: "MID",
    name: "Midlands",
    countryId: "IE",
    population: 315000,
    gdp: 18000,
    houseSeats: 11,
    senateSeats: 7,
    region: "Leinster",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 39, reg: 26 }, { abbr: "FG", org: 35, reg: 23 }, { abbr: "SF", org: 27, reg: 17 }, { abbr: "LAB", org: 10, reg: 4 }, { abbr: "GP", org: 9, reg: 3 }], independent: 27, unregistered: 0, unaffiliatedOrg: 0 },
  },
  {
    id: "WEX",
    name: "Wexford",
    countryId: "IE",
    population: 389000,
    gdp: 28000,
    houseSeats: 13,
    senateSeats: 7,
    region: "Leinster",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 34, reg: 22 }, { abbr: "FG", org: 30, reg: 19 }, { abbr: "SF", org: 27, reg: 17 }, { abbr: "LAB", org: 12, reg: 5 }, { abbr: "GP", org: 9, reg: 3 }], independent: 34, unregistered: 0, unaffiliatedOrg: 0 },
  },
  {
    id: "LIM",
    name: "Limerick",
    countryId: "IE",
    population: 432000,
    gdp: 38000,
    houseSeats: 15,
    senateSeats: 7,
    region: "Munster",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 38, reg: 25 }, { abbr: "FG", org: 34, reg: 22 }, { abbr: "SF", org: 27, reg: 17 }, { abbr: "LAB", org: 10, reg: 4 }, { abbr: "GP", org: 10, reg: 4 }], independent: 28, unregistered: 0, unaffiliatedOrg: 0 },
  },
  {
    id: "COR",
    name: "Cork",
    countryId: "IE",
    population: 598000,
    gdp: 65000,
    houseSeats: 20,
    senateSeats: 8,
    region: "Munster",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 34, reg: 22 }, { abbr: "FG", org: 35, reg: 23 }, { abbr: "SF", org: 27, reg: 17 }, { abbr: "LAB", org: 12, reg: 5 }, { abbr: "GP", org: 10, reg: 4 }], independent: 29, unregistered: 0, unaffiliatedOrg: 0 },
  },
  {
    id: "GAL",
    name: "Galway",
    countryId: "IE",
    population: 453000,
    gdp: 35000,
    houseSeats: 15,
    senateSeats: 7,
    region: "Connacht",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 36, reg: 24 }, { abbr: "FG", org: 34, reg: 22 }, { abbr: "SF", org: 27, reg: 17 }, { abbr: "LAB", org: 10, reg: 4 }, { abbr: "GP", org: 9, reg: 3 }], independent: 30, unregistered: 0, unaffiliatedOrg: 0 },
  },
  {
    id: "DON",
    name: "Donegal",
    countryId: "IE",
    population: 485000,
    gdp: 25000,
    houseSeats: 16,
    senateSeats: 7,
    region: "Ulster",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "FF", org: 36, reg: 24 }, { abbr: "FG", org: 30, reg: 19 }, { abbr: "SF", org: 34, reg: 22 }, { abbr: "LAB", org: 10, reg: 4 }, { abbr: "GP", org: 9, reg: 3 }], independent: 28, unregistered: 0, unaffiliatedOrg: 0 },
  },
];

// Totals: 8 regions, 160 lower-house seats, 60 upper/subnational seats (sum).
