import type { SeedPack } from "../types.js";
import { pack1953 } from "./1953.js";
import { pack1979 } from "./1979.js";
import { pack1991 } from "./1991.js";
import { pack2019 } from "./2019.js";
import { pack1999, pack2007, pack2023 } from "./sourceEraPacks.js";
import { nigeriaSourceNppBackground } from "./nigeriaSourceNpp.js";
export { US_STATE_DEMOGRAPHICS_1953 } from "./usStateDemographics1953.js";
export { UK_DEMOGRAPHICS_1953 } from "./ukDemographics1953.js";
export { RU_DEMOGRAPHICS_1953 } from "./ruDemographics1953.js";
export { DD_DEMOGRAPHICS_1953 } from "./ddDemographics1953.js";
export type { StateDemographicsSeed } from "./usStateDemographics1953.js";
export { ukRegions1953 } from "./ukRegions1953.js";
export { ruRegions1953 } from "./ruRegions1953.js";
export { ddRegions1953 } from "./ddRegions1953.js";
export { cnRegions1953 } from "./cnRegions1953.js";

export { pack1953 } from "./1953.js";
export { pack1979 } from "./1979.js";
export { pack1991 } from "./1991.js";
export { pack2019 } from "./2019.js";
export { pack1999, pack2007, pack2023 } from "./sourceEraPacks.js";

/**
 * The seven real mainline era presets shipped here. Source-returned outputs
 * and lane-level fallback provenance for 1999/2007/2023 are generated by
 * packages/content/scripts/exportSourceReferenceEraOutputs.cjs and
 * generateBudgets.ts. The fabricated
 * "1960" pack (invented era, interpolation-derived numbers) has been
 * deleted; see docs/briefs for the removal writeup. A "1960"-era SAVE FILE
 * can still be loaded — packages/engine/src/calendar.ts keeps a legacy
 * date anchor for it so old saves migrate and advance correctly — but no
 * new world can be created in it, because no pack exists for it.
 */
const BASE_PACKS: SeedPack[] = [pack1953, pack1979, pack1991, pack1999, pack2007, pack2019, pack2023];
for (const pack of BASE_PACKS) {
  const sourceNppBackground = nigeriaSourceNppBackground(pack.era.id);
  pack.parties = [...(pack.parties ?? []), ...sourceNppBackground.parties];
  pack.sourceNppBackground = sourceNppBackground;
}
export const PACKS: SeedPack[] = BASE_PACKS;

// Sorted by startDate ascending for era ladder use
export const PACKS_BY_DATE: SeedPack[] = [...PACKS].sort((a, b) =>
  a.era.startDate.localeCompare(b.era.startDate),
);

const PACK_BY_ERA = new Map<string, SeedPack>(PACKS.map((p) => [p.era.id, p]));

export function getPackByEra(era: string): SeedPack | undefined {
  return PACK_BY_ERA.get(era);
}
