import type { StateSeed } from "../types.js";
/**
 * Japan regions for 2019-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateRosters.ts
 * Sources:
 * - src/lib/seeds/jp/jpRegions.ts (2019-default bundle)
 * - src/lib/seeds/registration/registrationLanes.ts buildAllRegistrationSeeds JP entries
 */
export const jpRegions2019: StateSeed[] = [
  {
    id: "HOK",
    name: "Hokkaido",
    countryId: "JP",
    population: 5200000,
    gdp: 19300000,
    houseSeats: 12,
    senateSeats: 100,
    region: "Hokkaido",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 24, reg: 32 }, { abbr: "CDP", org: 20, reg: 26 }, { abbr: "KMT", org: 8, reg: 9 }, { abbr: "JCP", org: 5, reg: 8 }, { abbr: "DPFP", org: 4, reg: 5 }], independent: 12, unregistered: 8, unaffiliatedOrg: 39 },
  },
  {
    id: "TOH",
    name: "Tohoku",
    countryId: "JP",
    population: 8600000,
    gdp: 33500000,
    houseSeats: 37,
    senateSeats: 299,
    region: "Tohoku",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 27, reg: 37 }, { abbr: "CDP", org: 16, reg: 23 }, { abbr: "KMT", org: 8, reg: 9 }, { abbr: "JCP", org: 4, reg: 6 }, { abbr: "DPFP", org: 3, reg: 4 }], independent: 13, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "KAN",
    name: "Kanto",
    countryId: "JP",
    population: 43500000,
    gdp: 213000000,
    houseSeats: 150,
    senateSeats: 581,
    region: "Kanto",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 24, reg: 31 }, { abbr: "CDP", org: 17, reg: 22 }, { abbr: "KMT", org: 10, reg: 12 }, { abbr: "JCP", org: 6, reg: 9 }, { abbr: "DPFP", org: 5, reg: 5 }, { abbr: "ISH", org: 4, reg: 6 }], independent: 9, unregistered: 6, unaffiliatedOrg: 34 },
  },
  {
    id: "CHU",
    name: "Chubu",
    countryId: "JP",
    population: 21100000,
    gdp: 82000000,
    houseSeats: 81,
    senateSeats: 483,
    region: "Chubu",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 28, reg: 38 }, { abbr: "CDP", org: 13, reg: 18 }, { abbr: "KMT", org: 8, reg: 10 }, { abbr: "ISH", org: 6, reg: 9 }, { abbr: "DPFP", org: 4, reg: 5 }, { abbr: "JCP", org: 3, reg: 5 }], independent: 9, unregistered: 6, unaffiliatedOrg: 38 },
  },
  {
    id: "KNS",
    name: "Kansai",
    countryId: "JP",
    population: 22500000,
    gdp: 85000000,
    houseSeats: 82,
    senateSeats: 414,
    region: "Kansai",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 22, reg: 24 }, { abbr: "ISH", org: 20, reg: 28 }, { abbr: "KMT", org: 12, reg: 11 }, { abbr: "CDP", org: 8, reg: 11 }, { abbr: "JCP", org: 4, reg: 7 }, { abbr: "DPFP", org: 3, reg: 4 }], independent: 9, unregistered: 6, unaffiliatedOrg: 31 },
  },
  {
    id: "CGK",
    name: "Chugoku",
    countryId: "JP",
    population: 7100000,
    gdp: 28500000,
    houseSeats: 28,
    senateSeats: 238,
    region: "Chugoku",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 30, reg: 41 }, { abbr: "KMT", org: 9, reg: 11 }, { abbr: "CDP", org: 10, reg: 15 }, { abbr: "ISH", org: 4, reg: 6 }, { abbr: "JCP", org: 3, reg: 5 }, { abbr: "DPFP", org: 0, reg: 3 }], independent: 11, unregistered: 8, unaffiliatedOrg: 44 },
  },
  {
    id: "SHI",
    name: "Shikoku",
    countryId: "JP",
    population: 3700000,
    gdp: 13800000,
    houseSeats: 14,
    senateSeats: 163,
    region: "Shikoku",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 29, reg: 40 }, { abbr: "KMT", org: 10, reg: 12 }, { abbr: "ISH", org: 5, reg: 8 }, { abbr: "CDP", org: 8, reg: 13 }, { abbr: "JCP", org: 3, reg: 5 }, { abbr: "DPFP", org: 0, reg: 3 }], independent: 11, unregistered: 8, unaffiliatedOrg: 45 },
  },
  {
    id: "KYU",
    name: "Kyushu & Okinawa",
    countryId: "JP",
    population: 14300000,
    gdp: 50600000,
    houseSeats: 61,
    senateSeats: 401,
    region: "Kyushu",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LDP", org: 26, reg: 33 }, { abbr: "KMT", org: 11, reg: 14 }, { abbr: "CDP", org: 11, reg: 18 }, { abbr: "JCP", org: 4, reg: 6 }, { abbr: "DPFP", org: 4, reg: 4 }, { abbr: "ISH", org: 3, reg: 4 }], independent: 13, unregistered: 8, unaffiliatedOrg: 41 },
  },
];

// Totals: 8 regions, 465 lower-house seats, 2679 upper/subnational seats (sum).
