import type { StateSeed } from "../types.js";

/**
 * USSR regions for 1953-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Sources:
 * - ruRegions1953.ts (population, gdp, houseDistricts, stateSenateSeats, region) — 1939/1950 Soviet census + 1953 output-share, ×4.417 re-scaled, sum 148.5M / 526 Union seats / ₽1,029,166M
 * - ruRegionCensusData1953.ts is not used for registration; registration uses ruStatePartyOrgCalculations.ts RU_REGION_ORG_1953 (CPSU org) and registrationLanes1953.ts buildRUSeeds1953: parties [{abbr:"CPSU", org:cpsu, reg:cpsu}], independent = 100 - cpsu, unaffiliatedOrg = 100 - cpsu
 * Total: 14 regions (10 RSFSR macro-regions + KAZ/TRA/CAS/MOL), 148,500,000 population, 526 House seats (Soviet of the Union, 708 total minus 182 for UKR/BLR/BAL per ruRegions1953 header), ~3,487 stateSenateSeats (regional Supreme Soviets)
 * SenateClasses: no mainline Senate-class table for RU (Soviet system has no staggered classes); using neutral [1,2] placeholder. Documented as PORT-STUB.
 */
export const ruRegions1953: StateSeed[] = [
  {
    id: "CEN",
    name: "Central Russia",
    countryId: "RU",
    population: 22500000,
    gdp: 179167,
    houseSeats: 80,
    senateSeats: 575,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 98, reg: 98 }], independent: 2, unregistered: 0, unaffiliatedOrg: 2 },
  },
  {
    id: "NWR",
    name: "Northwest Russia",
    countryId: "RU",
    population: 10500000,
    gdp: 91667,
    houseSeats: 37,
    senateSeats: 266,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 97, reg: 97 }], independent: 3, unregistered: 0, unaffiliatedOrg: 3 },
  },
  {
    id: "NOR",
    name: "European North",
    countryId: "RU",
    population: 4800000,
    gdp: 33333,
    houseSeats: 17,
    senateSeats: 123,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "CBE",
    name: "Central Black Earth",
    countryId: "RU",
    population: 8500000,
    gdp: 37500,
    houseSeats: 30,
    senateSeats: 164,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "VOL",
    name: "Volga",
    countryId: "RU",
    population: 17000000,
    gdp: 116667,
    houseSeats: 60,
    senateSeats: 410,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "NCA",
    name: "North Caucasus",
    countryId: "RU",
    population: 13000000,
    gdp: 66667,
    houseSeats: 46,
    senateSeats: 307,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "URA",
    name: "Urals",
    countryId: "RU",
    population: 15500000,
    gdp: 158333,
    houseSeats: 55,
    senateSeats: 389,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 97, reg: 97 }], independent: 3, unregistered: 0, unaffiliatedOrg: 3 },
  },
  {
    id: "WSB",
    name: "West Siberia",
    countryId: "RU",
    population: 9500000,
    gdp: 83333,
    houseSeats: 34,
    senateSeats: 246,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "ESB",
    name: "East Siberia",
    countryId: "RU",
    population: 6000000,
    gdp: 45833,
    houseSeats: 21,
    senateSeats: 164,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "FEA",
    name: "Russian Far East",
    countryId: "RU",
    population: 5200000,
    gdp: 41667,
    houseSeats: 18,
    senateSeats: 143,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "KAZ",
    name: "Kazakhstan",
    countryId: "RU",
    population: 8500000,
    gdp: 45833,
    houseSeats: 30,
    senateSeats: 510,
    region: "Kazakhstan",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "TRA",
    name: "Transcaucasia",
    countryId: "RU",
    population: 11000000,
    gdp: 58333,
    houseSeats: 39,
    senateSeats: 440,
    region: "Caucasus",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "CAS",
    name: "Central Asia",
    countryId: "RU",
    population: 14000000,
    gdp: 58333,
    houseSeats: 50,
    senateSeats: 500,
    region: "Central Asia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 94, reg: 94 }], independent: 6, unregistered: 0, unaffiliatedOrg: 6 },
  },
  {
    id: "MOL",
    name: "Moldova",
    countryId: "RU",
    population: 2500000,
    gdp: 12500,
    houseSeats: 9,
    senateSeats: 350,
    region: "Moldova",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 91, reg: 91 }], independent: 9, unregistered: 0, unaffiliatedOrg: 9 },
  },
];
