import type { StateSeed } from "../types.js";
/**
 * USSR regions for 1979-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/ru/ruRegions.ts (population, gdp, houseDistricts, stateSenateSeats, region) — the bundle mainline seeds for 1979-default
 * - src/lib/seeds/ru/ruStatePartyOrgCalculations.ts RU_REGION_ORG_1979 (CPSU org per region)
 *
 * Regions: mainline has no dedicated 1979 region bundle for this country; admin/seed/seedRU.ts maps "1979-default" to ruRegions.ts (and seedDD.ts / selectPresetBundle fall back to the 2019-default bundle). This file applies that same mapping.
 * houseDistricts sum 559 = pack sovietOfTheUnion seats; stateSenateSeats sum 4587 = republicSupremeSoviet.
 */
export const ruRegions1979: StateSeed[] = [
  {
    id: "CEN",
    name: "Central Russia",
    countryId: "RU",
    population: 28000000,
    gdp: 60000,
    houseSeats: 81,
    senateSeats: 575,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 97, reg: 97 }], independent: 3, unregistered: 0, unaffiliatedOrg: 3 },
  },
  {
    id: "NWR",
    name: "Northwest Russia",
    countryId: "RU",
    population: 13000000,
    gdp: 30000,
    houseSeats: 38,
    senateSeats: 266,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "NOR",
    name: "European North",
    countryId: "RU",
    population: 6000000,
    gdp: 12000,
    houseSeats: 17,
    senateSeats: 123,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "CBE",
    name: "Central Black Earth",
    countryId: "RU",
    population: 8000000,
    gdp: 12000,
    houseSeats: 23,
    senateSeats: 164,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "VOL",
    name: "Volga",
    countryId: "RU",
    population: 20000000,
    gdp: 38000,
    houseSeats: 58,
    senateSeats: 410,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "NCA",
    name: "North Caucasus",
    countryId: "RU",
    population: 15000000,
    gdp: 22000,
    houseSeats: 43,
    senateSeats: 307,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "URA",
    name: "Urals",
    countryId: "RU",
    population: 19000000,
    gdp: 42000,
    houseSeats: 55,
    senateSeats: 389,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "WSB",
    name: "West Siberia",
    countryId: "RU",
    population: 12000000,
    gdp: 30000,
    houseSeats: 35,
    senateSeats: 246,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 96, reg: 96 }], independent: 4, unregistered: 0, unaffiliatedOrg: 4 },
  },
  {
    id: "ESB",
    name: "East Siberia",
    countryId: "RU",
    population: 8000000,
    gdp: 16000,
    houseSeats: 23,
    senateSeats: 164,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "FEA",
    name: "Russian Far East",
    countryId: "RU",
    population: 7000000,
    gdp: 14000,
    houseSeats: 20,
    senateSeats: 143,
    region: "Russia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "KAZ",
    name: "Kazakhstan",
    countryId: "RU",
    population: 14700000,
    gdp: 22000,
    houseSeats: 42,
    senateSeats: 510,
    region: "Kazakhstan",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "TRA",
    name: "Transcaucasia",
    countryId: "RU",
    population: 14000000,
    gdp: 20000,
    houseSeats: 40,
    senateSeats: 440,
    region: "Caucasus",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "CAS",
    name: "Central Asia",
    countryId: "RU",
    population: 25500000,
    gdp: 28000,
    houseSeats: 73,
    senateSeats: 500,
    region: "Central Asia",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 95, reg: 95 }], independent: 5, unregistered: 0, unaffiliatedOrg: 5 },
  },
  {
    id: "MOL",
    name: "Moldova",
    countryId: "RU",
    population: 3900000,
    gdp: 6000,
    houseSeats: 11,
    senateSeats: 350,
    region: "Moldova",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CPSU", org: 94, reg: 94 }], independent: 6, unregistered: 0, unaffiliatedOrg: 6 },
  },
];

// Totals: 14 regions, 194,100,000 population, 559 house seats, 4587 upper-state seats (sum).
