import type { StateSeed } from "../types.js";

/**
 * UK regions for 1953-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Sources:
 * - ukRegions1953.ts (population, gdp, houseDistricts, stateSenateSeats, region) — ~1951 Census / ~1953 GVA, 625-seat 1950-1955 distribution
 * - registrationLanes1953.ts buildUKSeeds1953 (lane + polling) — UK polling 1951 via UK_REGION_POLLING_1951, org = max(3, round(voteShare*0.6)), reg = voteShare, independent = 100 - sumReg, unaffiliatedOrg = 100 - sumOrg
 *   UK_SLUG_TO_ABBR maps uk_labour->LAB, uk_conservative->CON, uk_liberal->LIB, uk_snp->SNP (SCO only), uk_plaid->PC (WAL only), uk_sf->SF (NIR only); NIR also carries nationalist SF 30 as deliberate stand-in (see UK_REGION_POLLING_1951 header)
 * Granularity: 12 electoral regions (mainline's State granularity for UK — see src/lib/seeds/uk/ukRegions.ts header "Phase 1 uses the 12 UK electoral regions as the top-level playable units. A future phase will expand to all 650 individual constituencies."). Not per-constituency.
 * SenateClasses: no mainline Senate-class table for UK (FPTP Commons has no staggered classes); using neutral [1,2] placeholder. Documented as PORT-STUB.
 * Total: 12 regions, 50,600,000 population (sum matches 1951-census 1953 bundle), 625 House seats (commons), 578
 * regionalCouncil seats (sum of per-region `senateSeats` below matches mainline's UK_REGIONAL_COUNCIL_SEATS table
 * verbatim — SCO 129/WAL 60/NIR 90 are the real modern devolved-legislature sizes, used as-is even in the 1953
 * era per mainline's own `stateSenateSeats` seeding, not scaled down; this stale comment previously said 364,
 * which never matched the per-region data below — W40 fix, corrected to match the data and the legislature
 * chamber's `seats`/`vacancies` in 1953.ts/1960.ts, which carried the same stale 364 before W40).
 */
export const ukRegions1953: StateSeed[] = [
  {
    id: "LON",
    name: "London",
    countryId: "UK",
    population: 8200000,
    gdp: 3800,
    houseSeats: 91,
    senateSeats: 32,
    region: "London",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 31, reg: 51 }, { abbr: "CON", org: 28, reg: 46 }, { abbr: "LIB", org: 3, reg: 2 }], independent: 1, unregistered: 0, unaffiliatedOrg: 38 },
  },
  {
    id: "SEE",
    name: "South East England",
    countryId: "UK",
    population: 6100000,
    gdp: 2800,
    houseSeats: 81,
    senateSeats: 67,
    region: "South East",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 23, reg: 39 }, { abbr: "CON", org: 35, reg: 58 }, { abbr: "LIB", org: 3, reg: 3 }], independent: 0, unregistered: 0, unaffiliatedOrg: 39 },
  },
  {
    id: "SWE",
    name: "South West England",
    countryId: "UK",
    population: 3400000,
    gdp: 1200,
    houseSeats: 43,
    senateSeats: 39,
    region: "South West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 25, reg: 41 }, { abbr: "CON", org: 32, reg: 53 }, { abbr: "LIB", org: 4, reg: 6 }], independent: 0, unregistered: 0, unaffiliatedOrg: 39 },
  },
  {
    id: "EAE",
    name: "East of England",
    countryId: "UK",
    population: 3700000,
    gdp: 1300,
    houseSeats: 47,
    senateSeats: 39,
    region: "East of England",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 26, reg: 43 }, { abbr: "CON", org: 32, reg: 54 }, { abbr: "LIB", org: 3, reg: 3 }], independent: 0, unregistered: 0, unaffiliatedOrg: 39 },
  },
  {
    id: "EMI",
    name: "East Midlands",
    countryId: "UK",
    population: 3200000,
    gdp: 1100,
    houseSeats: 37,
    senateSeats: 39,
    region: "East Midlands",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 30, reg: 50 }, { abbr: "CON", org: 28, reg: 47 }, { abbr: "LIB", org: 3, reg: 3 }], independent: 0, unregistered: 0, unaffiliatedOrg: 39 },
  },
  {
    id: "WMI",
    name: "West Midlands",
    countryId: "UK",
    population: 4700000,
    gdp: 1900,
    houseSeats: 53,
    senateSeats: 18,
    region: "West Midlands",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 29, reg: 49 }, { abbr: "CON", org: 29, reg: 49 }, { abbr: "LIB", org: 3, reg: 2 }], independent: 0, unregistered: 0, unaffiliatedOrg: 39 },
  },
  {
    id: "YHU",
    name: "Yorkshire & the Humber",
    countryId: "UK",
    population: 4600000,
    gdp: 1800,
    houseSeats: 52,
    senateSeats: 21,
    region: "Yorkshire",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 32, reg: 54 }, { abbr: "CON", org: 26, reg: 44 }, { abbr: "LIB", org: 3, reg: 2 }], independent: 0, unregistered: 0, unaffiliatedOrg: 39 },
  },
  {
    id: "NWE",
    name: "North West England",
    countryId: "UK",
    population: 6500000,
    gdp: 2400,
    houseSeats: 75,
    senateSeats: 27,
    region: "North West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 31, reg: 52 }, { abbr: "CON", org: 28, reg: 46 }, { abbr: "LIB", org: 3, reg: 2 }], independent: 0, unregistered: 0, unaffiliatedOrg: 38 },
  },
  {
    id: "NEE",
    name: "North East England",
    countryId: "UK",
    population: 3100000,
    gdp: 1000,
    houseSeats: 27,
    senateSeats: 17,
    region: "North East",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 37, reg: 61 }, { abbr: "CON", org: 22, reg: 37 }, { abbr: "LIB", org: 3, reg: 2 }], independent: 0, unregistered: 0, unaffiliatedOrg: 38 },
  },
  {
    id: "SCO",
    name: "Scotland",
    countryId: "UK",
    population: 5100000,
    gdp: 1500,
    houseSeats: 71,
    senateSeats: 129,
    region: "Scotland",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 29, reg: 48 }, { abbr: "CON", org: 29, reg: 48 }, { abbr: "LIB", org: 3, reg: 3 }, { abbr: "SNP", org: 3, reg: 0 }], independent: 1, unregistered: 0, unaffiliatedOrg: 36 },
  },
  {
    id: "WAL",
    name: "Wales",
    countryId: "UK",
    population: 2600000,
    gdp: 630,
    houseSeats: 36,
    senateSeats: 60,
    region: "Wales",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 36, reg: 60 }, { abbr: "CON", org: 19, reg: 31 }, { abbr: "LIB", org: 4, reg: 7 }, { abbr: "PC", org: 3, reg: 1 }], independent: 1, unregistered: 0, unaffiliatedOrg: 38 },
  },
  {
    id: "NIR",
    name: "Northern Ireland",
    countryId: "UK",
    population: 1400000,
    gdp: 370,
    houseSeats: 12,
    senateSeats: 90,
    region: "Northern Ireland",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 4, reg: 7 }, { abbr: "CON", org: 38, reg: 63 }, { abbr: "SF", org: 18, reg: 30 }], independent: 0, unregistered: 0, unaffiliatedOrg: 40 },
  },
];
