import type { StateSeed } from "../types.js";
/**
 * UK regions for 1979-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/uk/ukRegions1979.ts (population, gdp, houseDistricts, stateSenateSeats, region)
 * - src/lib/seeds/registration/registrationLanes.ts buildAllRegistrationSeeds UK entries — mainline's registrationLanes1979.ts is US-only and states "non-US countries fall back to their 2019 lanes on a 1979 reset"; this file applies exactly that fallback
 *
 * Granularity: mainline's 12 electoral regions (its State granularity for UK), not per-constituency.
 * senateClasses: no mainline Senate-class table for UK (FPTP Commons has no staggered classes); neutral [1,2] placeholder, PORT-STUB as in ukRegions1953.ts.
 * Per-region houseDistricts sum is mainline's regional Commons apportionment; the pack's national commons chamber seat count is the era-neutral COUNTRY_CONFIGS base (see pack header).
 */
export const ukRegions1979: StateSeed[] = [
  {
    id: "LON",
    name: "London",
    countryId: "UK",
    population: 6800000,
    gdp: 32000,
    houseSeats: 92,
    senateSeats: 32,
    region: "London",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 30, reg: 38 }, { abbr: "CON", org: 15, reg: 20 }, { abbr: "LD", org: 10, reg: 13 }, { abbr: "GRN", org: 8, reg: 7 }], independent: 14, unregistered: 8, unaffiliatedOrg: 37 },
  },
  {
    id: "SEE",
    name: "South East England",
    countryId: "UK",
    population: 7000000,
    gdp: 30000,
    houseSeats: 82,
    senateSeats: 67,
    region: "South East",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 31, reg: 39 }, { abbr: "LAB", org: 17, reg: 22 }, { abbr: "LD", org: 10, reg: 14 }, { abbr: "RUK", org: 4, reg: 5 }, { abbr: "GRN", org: 3, reg: 4 }], independent: 10, unregistered: 6, unaffiliatedOrg: 35 },
  },
  {
    id: "SWE",
    name: "South West England",
    countryId: "UK",
    population: 4300000,
    gdp: 16000,
    houseSeats: 44,
    senateSeats: 39,
    region: "South West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 28, reg: 34 }, { abbr: "LD", org: 14, reg: 18 }, { abbr: "LAB", org: 13, reg: 18 }, { abbr: "GRN", org: 5, reg: 6 }, { abbr: "RUK", org: 4, reg: 5 }], independent: 11, unregistered: 8, unaffiliatedOrg: 36 },
  },
  {
    id: "EAE",
    name: "East of England",
    countryId: "UK",
    population: 4850000,
    gdp: 18000,
    houseSeats: 48,
    senateSeats: 39,
    region: "East of England",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 31, reg: 40 }, { abbr: "LAB", org: 16, reg: 21 }, { abbr: "LD", org: 9, reg: 12 }, { abbr: "RUK", org: 4, reg: 5 }, { abbr: "GRN", org: 3, reg: 3 }], independent: 11, unregistered: 8, unaffiliatedOrg: 37 },
  },
  {
    id: "EMI",
    name: "East Midlands",
    countryId: "UK",
    population: 3850000,
    gdp: 13000,
    houseSeats: 38,
    senateSeats: 39,
    region: "East Midlands",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 29, reg: 37 }, { abbr: "LAB", org: 20, reg: 26 }, { abbr: "LD", org: 6, reg: 7 }, { abbr: "RUK", org: 5, reg: 6 }, { abbr: "GRN", org: 2, reg: 3 }], independent: 12, unregistered: 9, unaffiliatedOrg: 38 },
  },
  {
    id: "WMI",
    name: "West Midlands",
    countryId: "UK",
    population: 5150000,
    gdp: 16000,
    houseSeats: 56,
    senateSeats: 18,
    region: "West Midlands",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 27, reg: 34 }, { abbr: "LAB", org: 24, reg: 31 }, { abbr: "LD", org: 6, reg: 8 }, { abbr: "RUK", org: 4, reg: 5 }, { abbr: "GRN", org: 2, reg: 3 }], independent: 11, unregistered: 8, unaffiliatedOrg: 37 },
  },
  {
    id: "YHU",
    name: "Yorkshire & the Humber",
    countryId: "UK",
    population: 4900000,
    gdp: 14000,
    houseSeats: 54,
    senateSeats: 21,
    region: "Yorkshire",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 25, reg: 31 }, { abbr: "CON", org: 25, reg: 31 }, { abbr: "LD", org: 5, reg: 6 }, { abbr: "RUK", org: 5, reg: 7 }, { abbr: "GRN", org: 2, reg: 3 }], independent: 13, unregistered: 9, unaffiliatedOrg: 38 },
  },
  {
    id: "NWE",
    name: "North West England",
    countryId: "UK",
    population: 6950000,
    gdp: 21000,
    houseSeats: 77,
    senateSeats: 27,
    region: "North West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 28, reg: 36 }, { abbr: "CON", org: 20, reg: 25 }, { abbr: "LD", org: 7, reg: 8 }, { abbr: "RUK", org: 4, reg: 5 }, { abbr: "GRN", org: 3, reg: 4 }], independent: 13, unregistered: 9, unaffiliatedOrg: 38 },
  },
  {
    id: "NEE",
    name: "North East England",
    countryId: "UK",
    population: 2640000,
    gdp: 7600,
    houseSeats: 25,
    senateSeats: 17,
    region: "North East",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 24, reg: 30 }, { abbr: "CON", org: 24, reg: 30 }, { abbr: "RUK", org: 6, reg: 8 }, { abbr: "LD", org: 4, reg: 5 }, { abbr: "GRN", org: 2, reg: 3 }], independent: 14, unregistered: 10, unaffiliatedOrg: 40 },
  },
  {
    id: "SCO",
    name: "Scotland",
    countryId: "UK",
    population: 5180000,
    gdp: 17000,
    houseSeats: 71,
    senateSeats: 129,
    region: "Scotland",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "SNP", org: 30, reg: 40 }, { abbr: "LAB", org: 16, reg: 20 }, { abbr: "CON", org: 10, reg: 12 }, { abbr: "LD", org: 5, reg: 7 }, { abbr: "GRN", org: 4, reg: 4 }], independent: 11, unregistered: 6, unaffiliatedOrg: 35 },
  },
  {
    id: "WAL",
    name: "Wales",
    countryId: "UK",
    population: 2790000,
    gdp: 8000,
    houseSeats: 36,
    senateSeats: 60,
    region: "Wales",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 24, reg: 31 }, { abbr: "CON", org: 16, reg: 21 }, { abbr: "PC", org: 14, reg: 18 }, { abbr: "LD", org: 4, reg: 5 }, { abbr: "GRN", org: 3, reg: 4 }], independent: 13, unregistered: 8, unaffiliatedOrg: 39 },
  },
  {
    id: "NIR",
    name: "Northern Ireland",
    countryId: "UK",
    population: 1540000,
    gdp: 5000,
    houseSeats: 12,
    senateSeats: 90,
    region: "Northern Ireland",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DUP", org: 18, reg: 22 }, { abbr: "SF", org: 18, reg: 21 }], independent: 39, unregistered: 18, unaffiliatedOrg: 64 },
  },
];

// Totals: 12 regions, 55,950,000 population, 635 house seats, 578 upper-state seats (sum).
