import type { StateSeed } from "../types.js";
/**
 * UK regions for 1991-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/uk/ukRegions1991.ts (population, gdp, houseDistricts, stateSenateSeats, region)
 * - src/lib/seeds/registration/registrationLanes1991.ts build1991RegistrationSeeds UK entries
 *
 * Granularity: mainline's 12 electoral regions (its State granularity for UK), not per-constituency.
 * senateClasses: no mainline Senate-class table for UK (FPTP Commons has no staggered classes); neutral [1,2] placeholder, PORT-STUB as in ukRegions1953.ts.
 * Per-region houseDistricts sum is mainline's regional Commons apportionment; the pack's national commons chamber seat count is the era-neutral COUNTRY_CONFIGS base (see pack header).
 */
export const ukRegions1991: StateSeed[] = [
  {
    id: "LON",
    name: "London",
    countryId: "UK",
    population: 6889000,
    gdp: 80000,
    houseSeats: 84,
    senateSeats: 32,
    region: "London",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 33, reg: 41 }, { abbr: "CON", org: 27, reg: 36 }, { abbr: "LD", org: 9, reg: 12 }], independent: 5, unregistered: 6, unaffiliatedOrg: 31 },
  },
  {
    id: "SEE",
    name: "South East England",
    countryId: "UK",
    population: 7550000,
    gdp: 65000,
    houseSeats: 91,
    senateSeats: 67,
    region: "South East",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 41, reg: 54 }, { abbr: "LAB", org: 15, reg: 21 }, { abbr: "LD", org: 13, reg: 18 }], independent: 3, unregistered: 4, unaffiliatedOrg: 31 },
  },
  {
    id: "SWE",
    name: "South West England",
    countryId: "UK",
    population: 4682000,
    gdp: 32000,
    houseSeats: 51,
    senateSeats: 39,
    region: "South West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 38, reg: 48 }, { abbr: "LD", org: 17, reg: 23 }, { abbr: "LAB", org: 14, reg: 21 }], independent: 3, unregistered: 5, unaffiliatedOrg: 31 },
  },
  {
    id: "EAE",
    name: "East of England",
    countryId: "UK",
    population: 5106000,
    gdp: 39000,
    houseSeats: 54,
    senateSeats: 39,
    region: "East",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 41, reg: 51 }, { abbr: "LAB", org: 17, reg: 25 }, { abbr: "LD", org: 11, reg: 17 }], independent: 3, unregistered: 4, unaffiliatedOrg: 31 },
  },
  {
    id: "EMI",
    name: "East Midlands",
    countryId: "UK",
    population: 4032000,
    gdp: 28000,
    houseSeats: 42,
    senateSeats: 39,
    region: "East Midlands",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 36, reg: 46 }, { abbr: "LAB", org: 24, reg: 34 }, { abbr: "LD", org: 9, reg: 13 }], independent: 3, unregistered: 4, unaffiliatedOrg: 31 },
  },
  {
    id: "WMI",
    name: "West Midlands",
    countryId: "UK",
    population: 5265000,
    gdp: 36000,
    houseSeats: 58,
    senateSeats: 18,
    region: "West Midlands",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "CON", org: 34, reg: 45 }, { abbr: "LAB", org: 28, reg: 38 }, { abbr: "LD", org: 9, reg: 11 }], independent: 2, unregistered: 4, unaffiliatedOrg: 29 },
  },
  {
    id: "YHU",
    name: "Yorkshire & the Humber",
    countryId: "UK",
    population: 4983000,
    gdp: 32000,
    houseSeats: 54,
    senateSeats: 21,
    region: "Yorkshire & the Humber",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 33, reg: 45 }, { abbr: "CON", org: 25, reg: 34 }, { abbr: "LD", org: 11, reg: 16 }], independent: 1, unregistered: 4, unaffiliatedOrg: 31 },
  },
  {
    id: "NWE",
    name: "North West England",
    countryId: "UK",
    population: 6834000,
    gdp: 44000,
    houseSeats: 74,
    senateSeats: 27,
    region: "North West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 33, reg: 45 }, { abbr: "CON", org: 26, reg: 35 }, { abbr: "LD", org: 11, reg: 14 }], independent: 2, unregistered: 4, unaffiliatedOrg: 30 },
  },
  {
    id: "NEE",
    name: "North East England",
    countryId: "UK",
    population: 2603000,
    gdp: 16500,
    houseSeats: 30,
    senateSeats: 17,
    region: "North East",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 39, reg: 55 }, { abbr: "CON", org: 21, reg: 28 }, { abbr: "LD", org: 9, reg: 12 }], independent: 1, unregistered: 4, unaffiliatedOrg: 31 },
  },
  {
    id: "SCO",
    name: "Scotland",
    countryId: "UK",
    population: 5102000,
    gdp: 36000,
    houseSeats: 72,
    senateSeats: 129,
    region: "Scotland",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 33, reg: 39 }, { abbr: "CON", org: 19, reg: 26 }, { abbr: "SNP", org: 14, reg: 21 }, { abbr: "LD", org: 9, reg: 13 }], independent: 0, unregistered: 1, unaffiliatedOrg: 25 },
  },
  {
    id: "WAL",
    name: "Wales",
    countryId: "UK",
    population: 2891000,
    gdp: 17000,
    houseSeats: 38,
    senateSeats: 60,
    region: "Wales",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "LAB", org: 36, reg: 49 }, { abbr: "CON", org: 21, reg: 29 }, { abbr: "LD", org: 9, reg: 12 }, { abbr: "PC", org: 5, reg: 6 }], independent: 0, unregistered: 4, unaffiliatedOrg: 29 },
  },
  {
    id: "NIR",
    name: "Northern Ireland",
    countryId: "UK",
    population: 1577000,
    gdp: 7500,
    houseSeats: 17,
    senateSeats: 90,
    region: "Northern Ireland",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DUP", org: 28, reg: 38 }, { abbr: "SF", org: 12, reg: 16 }], independent: 27, unregistered: 19, unaffiliatedOrg: 60 },
  },
];

// Totals: 12 regions, 57,514,000 population, 665 house seats, 578 upper-state seats (sum).
