import type { StateSeed } from "../types.js";
/**
 * US states for 2019-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/reference/states.ts (mainline's 2019-default bundle per admin/seed/seedStates.ts selectStatesBundleForPreset: 2020-Census population, current GDP, houseDistricts, stateSenateSeats, region)
 * - src/lib/seeds/registration/registrationLanes.ts buildAllRegistrationSeeds (2019 lanes)
 * - src/lib/constants/states.ts SENATE_CLASSES_BY_STATE
 *
 * DC excluded (non-state: no House seats, no electors; same as usStates1953.ts).
 * senateClasses from constants/states.ts SENATE_CLASSES_BY_STATE (era-invariant).
 */
export const usStates2019: StateSeed[] = [
  {
    id: "CT",
    name: "Connecticut",
    countryId: "US",
    population: 3605944,
    gdp: 289500,
    houseSeats: 5,
    senateSeats: 36,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 45 }, { abbr: "REP", org: 24, reg: 31 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "DE",
    name: "Delaware",
    countryId: "US",
    population: 989948,
    gdp: 79500,
    houseSeats: 1,
    senateSeats: 21,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 45 }, { abbr: "REP", org: 24, reg: 31 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "MA",
    name: "Massachusetts",
    countryId: "US",
    population: 7029917,
    gdp: 629500,
    houseSeats: 9,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 49 }, { abbr: "REP", org: 22, reg: 27 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "MD",
    name: "Maryland",
    countryId: "US",
    population: 6177224,
    gdp: 433500,
    houseSeats: 8,
    senateSeats: 47,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 49 }, { abbr: "REP", org: 22, reg: 27 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "ME",
    name: "Maine",
    countryId: "US",
    population: 1362359,
    gdp: 73500,
    houseSeats: 2,
    senateSeats: 35,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 41 }, { abbr: "REP", org: 27, reg: 34 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "NH",
    name: "New Hampshire",
    countryId: "US",
    population: 1377529,
    gdp: 94500,
    houseSeats: 2,
    senateSeats: 24,
    region: "Northeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 41 }, { abbr: "REP", org: 27, reg: 34 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "NJ",
    name: "New Jersey",
    countryId: "US",
    population: 9288994,
    gdp: 679500,
    houseSeats: 12,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 45 }, { abbr: "REP", org: 24, reg: 31 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "NY",
    name: "New York",
    countryId: "US",
    population: 20201249,
    gdp: 1893500,
    houseSeats: 26,
    senateSeats: 63,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 49 }, { abbr: "REP", org: 22, reg: 27 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "PA",
    name: "Pennsylvania",
    countryId: "US",
    population: 13002700,
    gdp: 839500,
    houseSeats: 17,
    senateSeats: 50,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 38 }, { abbr: "REP", org: 28, reg: 36 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "RI",
    name: "Rhode Island",
    countryId: "US",
    population: 1097379,
    gdp: 65500,
    houseSeats: 2,
    senateSeats: 38,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 45 }, { abbr: "REP", org: 24, reg: 31 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "VT",
    name: "Vermont",
    countryId: "US",
    population: 643077,
    gdp: 36500,
    houseSeats: 1,
    senateSeats: 30,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 49 }, { abbr: "REP", org: 22, reg: 27 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "AL",
    name: "Alabama",
    countryId: "US",
    population: 5024279,
    gdp: 258500,
    houseSeats: 7,
    senateSeats: 35,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "AR",
    name: "Arkansas",
    countryId: "US",
    population: 3011524,
    gdp: 143500,
    houseSeats: 4,
    senateSeats: 35,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "FL",
    name: "Florida",
    countryId: "US",
    population: 21538187,
    gdp: 1289500,
    houseSeats: 28,
    senateSeats: 40,
    region: "Southeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 35 }, { abbr: "REP", org: 29, reg: 39 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "GA",
    name: "Georgia",
    countryId: "US",
    population: 10711908,
    gdp: 688500,
    houseSeats: 14,
    senateSeats: 56,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 38 }, { abbr: "REP", org: 29, reg: 37 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "KY",
    name: "Kentucky",
    countryId: "US",
    population: 4505836,
    gdp: 225500,
    houseSeats: 6,
    senateSeats: 38,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "LA",
    name: "Louisiana",
    countryId: "US",
    population: 4657757,
    gdp: 263500,
    houseSeats: 6,
    senateSeats: 39,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "MS",
    name: "Mississippi",
    countryId: "US",
    population: 2961279,
    gdp: 125500,
    houseSeats: 4,
    senateSeats: 52,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "NC",
    name: "North Carolina",
    countryId: "US",
    population: 10439388,
    gdp: 642500,
    houseSeats: 14,
    senateSeats: 50,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 36 }, { abbr: "REP", org: 29, reg: 38 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "SC",
    name: "South Carolina",
    countryId: "US",
    population: 5118425,
    gdp: 268500,
    houseSeats: 7,
    senateSeats: 46,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 31 }, { abbr: "REP", org: 34, reg: 45 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "TN",
    name: "Tennessee",
    countryId: "US",
    population: 6910840,
    gdp: 409500,
    houseSeats: 9,
    senateSeats: 33,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "VA",
    name: "Virginia",
    countryId: "US",
    population: 8631393,
    gdp: 586500,
    houseSeats: 11,
    senateSeats: 40,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 41 }, { abbr: "REP", org: 27, reg: 34 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "WV",
    name: "West Virginia",
    countryId: "US",
    population: 1793716,
    gdp: 83500,
    houseSeats: 2,
    senateSeats: 34,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "IA",
    name: "Iowa",
    countryId: "US",
    population: 3190369,
    gdp: 204500,
    houseSeats: 4,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 34 }, { abbr: "REP", org: 31, reg: 41 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "IL",
    name: "Illinois",
    countryId: "US",
    population: 12812508,
    gdp: 938500,
    houseSeats: 17,
    senateSeats: 59,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 45 }, { abbr: "REP", org: 24, reg: 31 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "IN",
    name: "Indiana",
    countryId: "US",
    population: 6785528,
    gdp: 408500,
    houseSeats: 9,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 31 }, { abbr: "REP", org: 34, reg: 45 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "KS",
    name: "Kansas",
    countryId: "US",
    population: 2937880,
    gdp: 188500,
    houseSeats: 4,
    senateSeats: 40,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 31 }, { abbr: "REP", org: 34, reg: 45 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "MI",
    name: "Michigan",
    countryId: "US",
    population: 10077331,
    gdp: 576500,
    houseSeats: 13,
    senateSeats: 38,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 38 }, { abbr: "REP", org: 28, reg: 36 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MN",
    name: "Minnesota",
    countryId: "US",
    population: 5706494,
    gdp: 405500,
    houseSeats: 8,
    senateSeats: 67,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 41 }, { abbr: "REP", org: 27, reg: 34 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "MO",
    name: "Missouri",
    countryId: "US",
    population: 6154913,
    gdp: 356500,
    houseSeats: 8,
    senateSeats: 34,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 31 }, { abbr: "REP", org: 34, reg: 45 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "ND",
    name: "North Dakota",
    countryId: "US",
    population: 779094,
    gdp: 60500,
    houseSeats: 1,
    senateSeats: 47,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "NE",
    name: "Nebraska",
    countryId: "US",
    population: 1961504,
    gdp: 143500,
    houseSeats: 3,
    senateSeats: 49,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 31 }, { abbr: "REP", org: 34, reg: 45 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "OH",
    name: "Ohio",
    countryId: "US",
    population: 11799448,
    gdp: 715500,
    houseSeats: 15,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 34 }, { abbr: "REP", org: 31, reg: 41 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "SD",
    name: "South Dakota",
    countryId: "US",
    population: 886667,
    gdp: 58500,
    houseSeats: 1,
    senateSeats: 35,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "WI",
    name: "Wisconsin",
    countryId: "US",
    population: 5893718,
    gdp: 367500,
    houseSeats: 8,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 38 }, { abbr: "REP", org: 28, reg: 36 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "AZ",
    name: "Arizona",
    countryId: "US",
    population: 7151502,
    gdp: 407500,
    houseSeats: 9,
    senateSeats: 30,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 38 }, { abbr: "REP", org: 28, reg: 36 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NM",
    name: "New Mexico",
    countryId: "US",
    population: 2117522,
    gdp: 107500,
    houseSeats: 3,
    senateSeats: 42,
    region: "Southwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 41 }, { abbr: "REP", org: 27, reg: 34 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "NV",
    name: "Nevada",
    countryId: "US",
    population: 3104614,
    gdp: 188500,
    houseSeats: 4,
    senateSeats: 21,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 38 }, { abbr: "REP", org: 28, reg: 36 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "OK",
    name: "Oklahoma",
    countryId: "US",
    population: 3959353,
    gdp: 210500,
    houseSeats: 5,
    senateSeats: 48,
    region: "Southwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "TX",
    name: "Texas",
    countryId: "US",
    population: 29145505,
    gdp: 1987500,
    houseSeats: 38,
    senateSeats: 31,
    region: "Southwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 35 }, { abbr: "REP", org: 31, reg: 41 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "UT",
    name: "Utah",
    countryId: "US",
    population: 3271616,
    gdp: 214500,
    houseSeats: 4,
    senateSeats: 29,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 16, reg: 22 }, { abbr: "REP", org: 32, reg: 44 }], independent: 24, unregistered: 10, unaffiliatedOrg: 52 },
  },
  {
    id: "AK",
    name: "Alaska",
    countryId: "US",
    population: 733391,
    gdp: 55500,
    houseSeats: 1,
    senateSeats: 20,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 20, reg: 29 }, { abbr: "REP", org: 28, reg: 38 }], independent: 23, unregistered: 10, unaffiliatedOrg: 52 },
  },
  {
    id: "CA",
    name: "California",
    countryId: "US",
    population: 39538223,
    gdp: 3598500,
    houseSeats: 52,
    senateSeats: 40,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 49 }, { abbr: "REP", org: 22, reg: 27 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "CO",
    name: "Colorado",
    countryId: "US",
    population: 5773714,
    gdp: 415500,
    houseSeats: 8,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 41 }, { abbr: "REP", org: 27, reg: 34 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "HI",
    name: "Hawaii",
    countryId: "US",
    population: 1455271,
    gdp: 94500,
    houseSeats: 2,
    senateSeats: 25,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 49 }, { abbr: "REP", org: 22, reg: 27 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "ID",
    name: "Idaho",
    countryId: "US",
    population: 1839106,
    gdp: 97500,
    houseSeats: 2,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "MT",
    name: "Montana",
    countryId: "US",
    population: 1084225,
    gdp: 57500,
    houseSeats: 2,
    senateSeats: 50,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 31 }, { abbr: "REP", org: 34, reg: 45 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "OR",
    name: "Oregon",
    countryId: "US",
    population: 4237256,
    gdp: 263500,
    houseSeats: 6,
    senateSeats: 30,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 41 }, { abbr: "REP", org: 27, reg: 34 }], independent: 17, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "WA",
    name: "Washington",
    countryId: "US",
    population: 7614893,
    gdp: 646500,
    houseSeats: 10,
    senateSeats: 49,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 45 }, { abbr: "REP", org: 24, reg: 31 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "WY",
    name: "Wyoming",
    countryId: "US",
    population: 576851,
    gdp: 40500,
    houseSeats: 1,
    senateSeats: 30,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 27 }, { abbr: "REP", org: 36, reg: 49 }], independent: 16, unregistered: 8, unaffiliatedOrg: 42 },
  },
];

// Totals: 50 regions, 330,669,348 population, 435 house seats, 1972 upper-state seats (sum).
