import type { StateSeed } from "../types.js";

/**
 * US states for 1953-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Sources:
 * - states1953.ts (population, gdp, houseDistricts, stateSenateSeats, region) — 1950 Census + 1953 GSP
 * - states.ts HOUSE_SEATS_1953 (apportionment, sum 435 for 83rd Congress; AK/HI 0 excluded) — mirrors houseDistricts
 * - states.ts SENATE_CLASSES_BY_STATE (class I/II/III per state)
 * - registrationLanes1953.ts (lane + per-state overrides; org/reg + independent/unregistered/unaffiliatedOrg)
 *   lanes: solidD RI,MA; leanD MN,MI,IL,WA,MD; competitiveD NY,NJ,PA,MO,DE,NV,FL; competitiveR OH,CT,CA,OR,MT,NM,AZ; leanR WI,IN,IA,CO,ID,WY; solidR KS,NE,ND,SD; overrides for Solid South and border states (disenfranchisement via unregistered pool, e.g. MS 25, AL 22)
 * AK/HI absent until statehood (territories in 1953, houseSeats 0; see states1953.ts comment). DC excluded (non-state).
 * Leans implicit in DEM vs REP reg share; turnout anchors neutral (RegionTurnout modifiers 0).
 * Total: 48 states, 149,895,183 population (1950 Census sum), 435 House seats, 1972 state-senate seats (sum).
 */
export const usStates1953: StateSeed[] = [
  {
    id: "AL",
    name: "Alabama",
    countryId: "US",
    population: 3061743,
    gdp: 4500,
    houseSeats: 9,
    senateSeats: 35,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 67 }, { abbr: "REP", org: 10, reg: 8 }], independent: 3, unregistered: 22, unaffiliatedOrg: 54 },
  },
  {
    id: "AR",
    name: "Arkansas",
    countryId: "US",
    population: 1909511,
    gdp: 2300,
    houseSeats: 6,
    senateSeats: 35,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 36, reg: 71 }, { abbr: "REP", org: 10, reg: 9 }], independent: 4, unregistered: 16, unaffiliatedOrg: 54 },
  },
  {
    id: "AZ",
    name: "Arizona",
    countryId: "US",
    population: 749587,
    gdp: 1700,
    houseSeats: 2,
    senateSeats: 30,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 42 }, { abbr: "REP", org: 31, reg: 44 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "CA",
    name: "California",
    countryId: "US",
    population: 10586223,
    gdp: 38000,
    houseSeats: 30,
    senateSeats: 40,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 42 }, { abbr: "REP", org: 31, reg: 44 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "CO",
    name: "Colorado",
    countryId: "US",
    population: 1325089,
    gdp: 3200,
    houseSeats: 4,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 50 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "CT",
    name: "Connecticut",
    countryId: "US",
    population: 2007280,
    gdp: 6500,
    houseSeats: 6,
    senateSeats: 36,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 42 }, { abbr: "REP", org: 31, reg: 44 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "DE",
    name: "Delaware",
    countryId: "US",
    population: 318085,
    gdp: 1000,
    houseSeats: 1,
    senateSeats: 21,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 42 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "FL",
    name: "Florida",
    countryId: "US",
    population: 2771305,
    gdp: 4500,
    houseSeats: 8,
    senateSeats: 40,
    region: "Southeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 42 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "GA",
    name: "Georgia",
    countryId: "US",
    population: 3444578,
    gdp: 5500,
    houseSeats: 10,
    senateSeats: 56,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 66 }, { abbr: "REP", org: 12, reg: 10 }], independent: 4, unregistered: 20, unaffiliatedOrg: 54 },
  },
  {
    id: "IA",
    name: "Iowa",
    countryId: "US",
    population: 2621073,
    gdp: 5500,
    houseSeats: 8,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 50 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "ID",
    name: "Idaho",
    countryId: "US",
    population: 588637,
    gdp: 1300,
    houseSeats: 2,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 50 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "IL",
    name: "Illinois",
    countryId: "US",
    population: 8712176,
    gdp: 30000,
    houseSeats: 25,
    senateSeats: 59,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 50 }, { abbr: "REP", org: 24, reg: 35 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "IN",
    name: "Indiana",
    countryId: "US",
    population: 3934224,
    gdp: 10000,
    houseSeats: 11,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 50 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "KS",
    name: "Kansas",
    countryId: "US",
    population: 1905299,
    gdp: 4000,
    houseSeats: 6,
    senateSeats: 40,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 20, reg: 29 }, { abbr: "REP", org: 38, reg: 58 }], independent: 7, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "KY",
    name: "Kentucky",
    countryId: "US",
    population: 2944806,
    gdp: 4500,
    houseSeats: 8,
    senateSeats: 38,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 68 }, { abbr: "REP", org: 20, reg: 23 }], independent: 3, unregistered: 6, unaffiliatedOrg: 46 },
  },
  {
    id: "LA",
    name: "Louisiana",
    countryId: "US",
    population: 2683516,
    gdp: 5500,
    houseSeats: 8,
    senateSeats: 39,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 71 }, { abbr: "REP", org: 12, reg: 9 }], independent: 4, unregistered: 16, unaffiliatedOrg: 53 },
  },
  {
    id: "MA",
    name: "Massachusetts",
    countryId: "US",
    population: 4690514,
    gdp: 14000,
    houseSeats: 14,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 38, reg: 58 }, { abbr: "REP", org: 20, reg: 29 }], independent: 7, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "MD",
    name: "Maryland",
    countryId: "US",
    population: 2343001,
    gdp: 6500,
    houseSeats: 7,
    senateSeats: 47,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 50 }, { abbr: "REP", org: 24, reg: 35 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "ME",
    name: "Maine",
    countryId: "US",
    population: 913774,
    gdp: 1800,
    houseSeats: 3,
    senateSeats: 35,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 18, reg: 28 }, { abbr: "REP", org: 36, reg: 55 }], independent: 8, unregistered: 9, unaffiliatedOrg: 46 },
  },
  {
    id: "MI",
    name: "Michigan",
    countryId: "US",
    population: 6371766,
    gdp: 20000,
    houseSeats: 18,
    senateSeats: 38,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 50 }, { abbr: "REP", org: 24, reg: 35 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "MN",
    name: "Minnesota",
    countryId: "US",
    population: 2982483,
    gdp: 7500,
    houseSeats: 9,
    senateSeats: 67,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 50 }, { abbr: "REP", org: 24, reg: 35 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "MO",
    name: "Missouri",
    countryId: "US",
    population: 3954653,
    gdp: 11000,
    houseSeats: 11,
    senateSeats: 34,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 42 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "MS",
    name: "Mississippi",
    countryId: "US",
    population: 2178914,
    gdp: 2300,
    houseSeats: 6,
    senateSeats: 52,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 38, reg: 66 }, { abbr: "REP", org: 8, reg: 6 }], independent: 3, unregistered: 25, unaffiliatedOrg: 54 },
  },
  {
    id: "MT",
    name: "Montana",
    countryId: "US",
    population: 591024,
    gdp: 1400,
    houseSeats: 2,
    senateSeats: 50,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 42 }, { abbr: "REP", org: 31, reg: 44 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "NC",
    name: "North Carolina",
    countryId: "US",
    population: 4061929,
    gdp: 6500,
    houseSeats: 12,
    senateSeats: 50,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 63 }, { abbr: "REP", org: 18, reg: 18 }], independent: 4, unregistered: 15, unaffiliatedOrg: 48 },
  },
  {
    id: "ND",
    name: "North Dakota",
    countryId: "US",
    population: 619636,
    gdp: 1300,
    houseSeats: 2,
    senateSeats: 47,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 20, reg: 29 }, { abbr: "REP", org: 38, reg: 58 }], independent: 7, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "NE",
    name: "Nebraska",
    countryId: "US",
    population: 1325510,
    gdp: 3200,
    houseSeats: 4,
    senateSeats: 49,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 20, reg: 29 }, { abbr: "REP", org: 38, reg: 58 }], independent: 7, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "NH",
    name: "New Hampshire",
    countryId: "US",
    population: 533242,
    gdp: 1300,
    houseSeats: 2,
    senateSeats: 24,
    region: "Northeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 20, reg: 30 }, { abbr: "REP", org: 34, reg: 54 }], independent: 9, unregistered: 7, unaffiliatedOrg: 46 },
  },
  {
    id: "NJ",
    name: "New Jersey",
    countryId: "US",
    population: 4835329,
    gdp: 16000,
    houseSeats: 14,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 42 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "NM",
    name: "New Mexico",
    countryId: "US",
    population: 681187,
    gdp: 1200,
    houseSeats: 2,
    senateSeats: 42,
    region: "Southwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 42 }, { abbr: "REP", org: 31, reg: 44 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "NV",
    name: "Nevada",
    countryId: "US",
    population: 160083,
    gdp: 450,
    houseSeats: 1,
    senateSeats: 21,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 42 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "NY",
    name: "New York",
    countryId: "US",
    population: 14830192,
    gdp: 50000,
    houseSeats: 43,
    senateSeats: 61,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 42 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "OH",
    name: "Ohio",
    countryId: "US",
    population: 7946627,
    gdp: 24000,
    houseSeats: 23,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 42 }, { abbr: "REP", org: 31, reg: 44 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "OK",
    name: "Oklahoma",
    countryId: "US",
    population: 2233351,
    gdp: 4000,
    houseSeats: 6,
    senateSeats: 48,
    region: "Southwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 71 }, { abbr: "REP", org: 18, reg: 19 }], independent: 3, unregistered: 7, unaffiliatedOrg: 50 },
  },
  {
    id: "OR",
    name: "Oregon",
    countryId: "US",
    population: 1521341,
    gdp: 3600,
    houseSeats: 4,
    senateSeats: 30,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 42 }, { abbr: "REP", org: 31, reg: 44 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "PA",
    name: "Pennsylvania",
    countryId: "US",
    population: 10498012,
    gdp: 30000,
    houseSeats: 30,
    senateSeats: 50,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 42 }], independent: 8, unregistered: 6, unaffiliatedOrg: 41 },
  },
  {
    id: "RI",
    name: "Rhode Island",
    countryId: "US",
    population: 791896,
    gdp: 2300,
    houseSeats: 2,
    senateSeats: 38,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 38, reg: 58 }, { abbr: "REP", org: 20, reg: 29 }], independent: 7, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "SC",
    name: "South Carolina",
    countryId: "US",
    population: 2117027,
    gdp: 2800,
    houseSeats: 6,
    senateSeats: 46,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 67 }, { abbr: "REP", org: 10, reg: 8 }], independent: 3, unregistered: 22, unaffiliatedOrg: 55 },
  },
  {
    id: "SD",
    name: "South Dakota",
    countryId: "US",
    population: 652740,
    gdp: 1300,
    houseSeats: 2,
    senateSeats: 35,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 20, reg: 29 }, { abbr: "REP", org: 38, reg: 58 }], independent: 7, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "TN",
    name: "Tennessee",
    countryId: "US",
    population: 3291718,
    gdp: 5500,
    houseSeats: 9,
    senateSeats: 33,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 61 }, { abbr: "REP", org: 20, reg: 23 }], independent: 4, unregistered: 12, unaffiliatedOrg: 48 },
  },
  {
    id: "TX",
    name: "Texas",
    countryId: "US",
    population: 7711194,
    gdp: 18000,
    houseSeats: 22,
    senateSeats: 31,
    region: "Southwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 63 }, { abbr: "REP", org: 18, reg: 20 }], independent: 5, unregistered: 12, unaffiliatedOrg: 47 },
  },
  {
    id: "UT",
    name: "Utah",
    countryId: "US",
    population: 688862,
    gdp: 1400,
    houseSeats: 2,
    senateSeats: 29,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 16, reg: 22 }, { abbr: "REP", org: 40, reg: 62 }], independent: 9, unregistered: 7, unaffiliatedOrg: 44 },
  },
  {
    id: "VA",
    name: "Virginia",
    countryId: "US",
    population: 3318680,
    gdp: 6500,
    houseSeats: 10,
    senateSeats: 40,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 60 }, { abbr: "REP", org: 18, reg: 20 }], independent: 4, unregistered: 16, unaffiliatedOrg: 50 },
  },
  {
    id: "VT",
    name: "Vermont",
    countryId: "US",
    population: 377747,
    gdp: 750,
    houseSeats: 1,
    senateSeats: 30,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 12, reg: 22 }, { abbr: "REP", org: 42, reg: 68 }], independent: 6, unregistered: 4, unaffiliatedOrg: 46 },
  },
  {
    id: "WA",
    name: "Washington",
    countryId: "US",
    population: 2378963,
    gdp: 6500,
    houseSeats: 7,
    senateSeats: 49,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 50 }, { abbr: "REP", org: 24, reg: 35 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "WI",
    name: "Wisconsin",
    countryId: "US",
    population: 3434575,
    gdp: 8500,
    houseSeats: 10,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 50 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "WV",
    name: "West Virginia",
    countryId: "US",
    population: 2005552,
    gdp: 3500,
    houseSeats: 6,
    senateSeats: 34,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 71 }, { abbr: "REP", org: 18, reg: 21 }], independent: 3, unregistered: 5, unaffiliatedOrg: 47 },
  },
  {
    id: "WY",
    name: "Wyoming",
    countryId: "US",
    population: 290529,
    gdp: 650,
    houseSeats: 1,
    senateSeats: 30,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 50 }], independent: 8, unregistered: 7, unaffiliatedOrg: 42 },
  },
];
