import type { StateSeed } from "../types.js";
/**
 * US states for 1979-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/reference/states1979.ts (population, gdp, houseDistricts, stateSenateSeats, region) — 96th Congress snapshot
 * - src/lib/seeds/registration/registrationLanes1979.ts build1979RegistrationSeeds (org/reg per party, independent/unregistered/unaffiliatedOrg)
 * - src/lib/constants/states.ts SENATE_CLASSES_BY_STATE
 *
 * DC excluded (non-state: no House seats, no electors; same as usStates1953.ts).
 * senateClasses from constants/states.ts SENATE_CLASSES_BY_STATE (era-invariant).
 * 1979 US Congress starts VACANT: mainline's own RESET_PRESETS["1979-default"]
 * description reads "Legislatures start vacant (historical seat maps are a
 * follow-up)" and historicalSeats.ts has no US_HOUSE_1979/US_SENATE_1979;
 * the first per-state House/Senate cycle fills it, as in mainline.
 */
export const usStates1979: StateSeed[] = [
  {
    id: "CT",
    name: "Connecticut",
    countryId: "US",
    population: 3107576,
    gdp: 42000,
    houseSeats: 6,
    senateSeats: 36,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "DE",
    name: "Delaware",
    countryId: "US",
    population: 594338,
    gdp: 8000,
    houseSeats: 1,
    senateSeats: 21,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 40 }, { abbr: "REP", org: 31, reg: 44 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "MA",
    name: "Massachusetts",
    countryId: "US",
    population: 5737037,
    gdp: 68000,
    houseSeats: 12,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 40, reg: 60 }, { abbr: "REP", org: 18, reg: 24 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "MD",
    name: "Maryland",
    countryId: "US",
    population: 4216975,
    gdp: 48000,
    houseSeats: 8,
    senateSeats: 47,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "ME",
    name: "Maine",
    countryId: "US",
    population: 1124660,
    gdp: 10000,
    houseSeats: 2,
    senateSeats: 35,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "NH",
    name: "New Hampshire",
    countryId: "US",
    population: 920610,
    gdp: 9000,
    houseSeats: 2,
    senateSeats: 24,
    region: "Northeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 40 }, { abbr: "REP", org: 31, reg: 44 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "NJ",
    name: "New Jersey",
    countryId: "US",
    population: 7364823,
    gdp: 90000,
    houseSeats: 15,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "NY",
    name: "New York",
    countryId: "US",
    population: 17558072,
    gdp: 215000,
    houseSeats: 39,
    senateSeats: 61,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "PA",
    name: "Pennsylvania",
    countryId: "US",
    population: 11863895,
    gdp: 125000,
    houseSeats: 25,
    senateSeats: 50,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "RI",
    name: "Rhode Island",
    countryId: "US",
    population: 947154,
    gdp: 9000,
    houseSeats: 2,
    senateSeats: 38,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 40, reg: 60 }, { abbr: "REP", org: 18, reg: 24 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "VT",
    name: "Vermont",
    countryId: "US",
    population: 511456,
    gdp: 4500,
    houseSeats: 1,
    senateSeats: 30,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 40 }, { abbr: "REP", org: 31, reg: 44 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "AL",
    name: "Alabama",
    countryId: "US",
    population: 3893888,
    gdp: 34000,
    houseSeats: 7,
    senateSeats: 35,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "AR",
    name: "Arkansas",
    countryId: "US",
    population: 2286435,
    gdp: 19000,
    houseSeats: 4,
    senateSeats: 35,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 38, reg: 56 }, { abbr: "REP", org: 18, reg: 22 }], independent: 12, unregistered: 10, unaffiliatedOrg: 42 },
  },
  {
    id: "FL",
    name: "Florida",
    countryId: "US",
    population: 9746324,
    gdp: 95000,
    houseSeats: 15,
    senateSeats: 40,
    region: "Southeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 40 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "GA",
    name: "Georgia",
    countryId: "US",
    population: 5463105,
    gdp: 55000,
    houseSeats: 10,
    senateSeats: 56,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 40, reg: 60 }, { abbr: "REP", org: 18, reg: 24 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "KY",
    name: "Kentucky",
    countryId: "US",
    population: 3660777,
    gdp: 34000,
    houseSeats: 7,
    senateSeats: 38,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 67 }, { abbr: "REP", org: 30, reg: 27 }], independent: 3, unregistered: 3, unaffiliatedOrg: 42 },
  },
  {
    id: "LA",
    name: "Louisiana",
    countryId: "US",
    population: 4205900,
    gdp: 48000,
    houseSeats: 8,
    senateSeats: 39,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 30, reg: 72 }, { abbr: "REP", org: 26, reg: 16 }], independent: 6, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "MS",
    name: "Mississippi",
    countryId: "US",
    population: 2520638,
    gdp: 20000,
    houseSeats: 5,
    senateSeats: 52,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "NC",
    name: "North Carolina",
    countryId: "US",
    population: 5881766,
    gdp: 55000,
    houseSeats: 11,
    senateSeats: 50,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "SC",
    name: "South Carolina",
    countryId: "US",
    population: 3121820,
    gdp: 27000,
    houseSeats: 6,
    senateSeats: 46,
    region: "Southeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "TN",
    name: "Tennessee",
    countryId: "US",
    population: 4591120,
    gdp: 42000,
    houseSeats: 8,
    senateSeats: 33,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "VA",
    name: "Virginia",
    countryId: "US",
    population: 5346818,
    gdp: 55000,
    houseSeats: 10,
    senateSeats: 40,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "WV",
    name: "West Virginia",
    countryId: "US",
    population: 1949644,
    gdp: 18000,
    houseSeats: 4,
    senateSeats: 34,
    region: "Southeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 30, reg: 63 }, { abbr: "REP", org: 28, reg: 30 }], independent: 3, unregistered: 4, unaffiliatedOrg: 42 },
  },
  {
    id: "IA",
    name: "Iowa",
    countryId: "US",
    population: 2913808,
    gdp: 33000,
    houseSeats: 6,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 40 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "IL",
    name: "Illinois",
    countryId: "US",
    population: 11426518,
    gdp: 135000,
    houseSeats: 24,
    senateSeats: 59,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "IN",
    name: "Indiana",
    countryId: "US",
    population: 5490224,
    gdp: 60000,
    houseSeats: 11,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 48 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "KS",
    name: "Kansas",
    countryId: "US",
    population: 2363679,
    gdp: 27000,
    houseSeats: 5,
    senateSeats: 40,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 21, reg: 30 }, { abbr: "REP", org: 37, reg: 54 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "MI",
    name: "Michigan",
    countryId: "US",
    population: 9262078,
    gdp: 105000,
    houseSeats: 19,
    senateSeats: 38,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "MN",
    name: "Minnesota",
    countryId: "US",
    population: 4075970,
    gdp: 45000,
    houseSeats: 8,
    senateSeats: 67,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "MO",
    name: "Missouri",
    countryId: "US",
    population: 4916686,
    gdp: 52000,
    houseSeats: 10,
    senateSeats: 34,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "ND",
    name: "North Dakota",
    countryId: "US",
    population: 652717,
    gdp: 8000,
    houseSeats: 1,
    senateSeats: 47,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 21, reg: 30 }, { abbr: "REP", org: 37, reg: 54 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "NE",
    name: "Nebraska",
    countryId: "US",
    population: 1569825,
    gdp: 18000,
    houseSeats: 3,
    senateSeats: 49,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 21, reg: 30 }, { abbr: "REP", org: 37, reg: 54 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "OH",
    name: "Ohio",
    countryId: "US",
    population: 10797630,
    gdp: 120000,
    houseSeats: 23,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 40 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "SD",
    name: "South Dakota",
    countryId: "US",
    population: 690768,
    gdp: 7000,
    houseSeats: 2,
    senateSeats: 35,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 21, reg: 30 }, { abbr: "REP", org: 37, reg: 54 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "WI",
    name: "Wisconsin",
    countryId: "US",
    population: 4705767,
    gdp: 50000,
    houseSeats: 9,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "AZ",
    name: "Arizona",
    countryId: "US",
    population: 2718215,
    gdp: 28000,
    houseSeats: 4,
    senateSeats: 30,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 48 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "NM",
    name: "New Mexico",
    countryId: "US",
    population: 1302894,
    gdp: 13000,
    houseSeats: 2,
    senateSeats: 42,
    region: "Southwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 31, reg: 44 }, { abbr: "REP", org: 28, reg: 40 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "NV",
    name: "Nevada",
    countryId: "US",
    population: 800493,
    gdp: 10000,
    houseSeats: 1,
    senateSeats: 21,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 40 }, { abbr: "REP", org: 31, reg: 44 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "OK",
    name: "Oklahoma",
    countryId: "US",
    population: 3025290,
    gdp: 33000,
    houseSeats: 6,
    senateSeats: 48,
    region: "Southwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 70 }, { abbr: "REP", org: 30, reg: 24 }], independent: 3, unregistered: 3, unaffiliatedOrg: 42 },
  },
  {
    id: "TX",
    name: "Texas",
    countryId: "US",
    population: 14229191,
    gdp: 170000,
    houseSeats: 24,
    senateSeats: 31,
    region: "Southwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 26, reg: 33 }], independent: 11, unregistered: 8, unaffiliatedOrg: 42 },
  },
  {
    id: "UT",
    name: "Utah",
    countryId: "US",
    population: 1461037,
    gdp: 14000,
    houseSeats: 2,
    senateSeats: 29,
    region: "Southwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 18, reg: 24 }, { abbr: "REP", org: 38, reg: 47 }], independent: 20, unregistered: 9, unaffiliatedOrg: 52 },
  },
  {
    id: "AK",
    name: "Alaska",
    countryId: "US",
    population: 401851,
    gdp: 12000,
    houseSeats: 1,
    senateSeats: 20,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 26 }, { abbr: "REP", org: 30, reg: 33 }], independent: 28, unregistered: 13, unaffiliatedOrg: 54 },
  },
  {
    id: "CA",
    name: "California",
    countryId: "US",
    population: 23667902,
    gdp: 285000,
    houseSeats: 43,
    senateSeats: 40,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 40 }, { abbr: "REP", org: 31, reg: 44 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "CO",
    name: "Colorado",
    countryId: "US",
    population: 2889964,
    gdp: 34000,
    houseSeats: 5,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 35 }, { abbr: "REP", org: 34, reg: 48 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "HI",
    name: "Hawaii",
    countryId: "US",
    population: 964691,
    gdp: 11000,
    houseSeats: 2,
    senateSeats: 25,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 37, reg: 54 }, { abbr: "REP", org: 21, reg: 30 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "ID",
    name: "Idaho",
    countryId: "US",
    population: 943935,
    gdp: 9000,
    houseSeats: 2,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 21, reg: 30 }, { abbr: "REP", org: 37, reg: 54 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "MT",
    name: "Montana",
    countryId: "US",
    population: 786690,
    gdp: 8000,
    houseSeats: 2,
    senateSeats: 50,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 28, reg: 40 }, { abbr: "REP", org: 31, reg: 44 }], independent: 10, unregistered: 6, unaffiliatedOrg: 42 },
  },
  {
    id: "OR",
    name: "Oregon",
    countryId: "US",
    population: 2633105,
    gdp: 30000,
    houseSeats: 4,
    senateSeats: 30,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "WA",
    name: "Washington",
    countryId: "US",
    population: 4132156,
    gdp: 48000,
    houseSeats: 7,
    senateSeats: 49,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 34, reg: 48 }, { abbr: "REP", org: 24, reg: 35 }], independent: 10, unregistered: 7, unaffiliatedOrg: 42 },
  },
  {
    id: "WY",
    name: "Wyoming",
    countryId: "US",
    population: 469557,
    gdp: 7000,
    houseSeats: 1,
    senateSeats: 30,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 18, reg: 25 }, { abbr: "REP", org: 40, reg: 59 }], independent: 9, unregistered: 7, unaffiliatedOrg: 42 },
  },
];

// Totals: 50 regions, 225,907,472 population, 435 house seats, 1970 upper-state seats (sum).
