import type { StateSeed } from "../types.js";
/**
 * US states for 1991-default. Generated from mainline AHDGame — DO NOT HAND-EDIT.
 * Generated: 2026-09-02 by packages/content/scripts/generateStateLayer.ts
 * Sources:
 * - src/lib/seeds/reference/states1991.ts (1990 Census population, 1991 nominal GSP, houseDistricts = 1990 apportionment, stateSenateSeats, region)
 * - src/lib/seeds/registration/registrationLanes1991.ts build1991RegistrationSeeds
 * - src/lib/constants/states.ts SENATE_CLASSES_BY_STATE
 *
 * DC excluded (non-state: no House seats, no electors; same as usStates1953.ts).
 * senateClasses from constants/states.ts SENATE_CLASSES_BY_STATE (era-invariant).
 */
export const usStates1991: StateSeed[] = [
  {
    id: "CT",
    name: "Connecticut",
    countryId: "US",
    population: 3287116,
    gdp: 92500,
    houseSeats: 6,
    senateSeats: 36,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "DE",
    name: "Delaware",
    countryId: "US",
    population: 666168,
    gdp: 17500,
    houseSeats: 1,
    senateSeats: 21,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MA",
    name: "Massachusetts",
    countryId: "US",
    population: 6016425,
    gdp: 153000,
    houseSeats: 10,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 50 }, { abbr: "REP", org: 22, reg: 22 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MD",
    name: "Maryland",
    countryId: "US",
    population: 4781468,
    gdp: 117000,
    houseSeats: 8,
    senateSeats: 47,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "ME",
    name: "Maine",
    countryId: "US",
    population: 1227928,
    gdp: 24000,
    houseSeats: 2,
    senateSeats: 35,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NH",
    name: "New Hampshire",
    countryId: "US",
    population: 1109252,
    gdp: 24000,
    houseSeats: 2,
    senateSeats: 24,
    region: "Northeast",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NJ",
    name: "New Jersey",
    countryId: "US",
    population: 7730188,
    gdp: 209000,
    houseSeats: 13,
    senateSeats: 40,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NY",
    name: "New York",
    countryId: "US",
    population: 17990455,
    gdp: 460000,
    houseSeats: 31,
    senateSeats: 63,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "PA",
    name: "Pennsylvania",
    countryId: "US",
    population: 11881643,
    gdp: 234000,
    houseSeats: 21,
    senateSeats: 50,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "RI",
    name: "Rhode Island",
    countryId: "US",
    population: 1003464,
    gdp: 20000,
    houseSeats: 2,
    senateSeats: 38,
    region: "Northeast",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 50 }, { abbr: "REP", org: 22, reg: 22 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "VT",
    name: "Vermont",
    countryId: "US",
    population: 562758,
    gdp: 11500,
    houseSeats: 1,
    senateSeats: 30,
    region: "Northeast",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "AL",
    name: "Alabama",
    countryId: "US",
    population: 4040587,
    gdp: 67000,
    houseSeats: 7,
    senateSeats: 35,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "AR",
    name: "Arkansas",
    countryId: "US",
    population: 2350725,
    gdp: 35000,
    houseSeats: 4,
    senateSeats: 35,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 50 }, { abbr: "REP", org: 22, reg: 22 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "FL",
    name: "Florida",
    countryId: "US",
    population: 12937926,
    gdp: 235000,
    houseSeats: 23,
    senateSeats: 40,
    region: "South",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "GA",
    name: "Georgia",
    countryId: "US",
    population: 6478216,
    gdp: 124000,
    houseSeats: 11,
    senateSeats: 56,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "KY",
    name: "Kentucky",
    countryId: "US",
    population: 3685296,
    gdp: 62000,
    houseSeats: 6,
    senateSeats: 38,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "LA",
    name: "Louisiana",
    countryId: "US",
    population: 4219973,
    gdp: 80000,
    houseSeats: 7,
    senateSeats: 39,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MS",
    name: "Mississippi",
    countryId: "US",
    population: 2573216,
    gdp: 35000,
    houseSeats: 5,
    senateSeats: 52,
    region: "South",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NC",
    name: "North Carolina",
    countryId: "US",
    population: 6628637,
    gdp: 124000,
    houseSeats: 12,
    senateSeats: 50,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "OK",
    name: "Oklahoma",
    countryId: "US",
    population: 3145585,
    gdp: 57000,
    houseSeats: 6,
    senateSeats: 48,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "SC",
    name: "South Carolina",
    countryId: "US",
    population: 3486703,
    gdp: 55000,
    houseSeats: 6,
    senateSeats: 46,
    region: "South",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "TN",
    name: "Tennessee",
    countryId: "US",
    population: 4877185,
    gdp: 92000,
    houseSeats: 9,
    senateSeats: 33,
    region: "South",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "TX",
    name: "Texas",
    countryId: "US",
    population: 16986510,
    gdp: 350000,
    houseSeats: 30,
    senateSeats: 31,
    region: "South",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "VA",
    name: "Virginia",
    countryId: "US",
    population: 6187358,
    gdp: 138000,
    houseSeats: 11,
    senateSeats: 40,
    region: "South",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "WV",
    name: "West Virginia",
    countryId: "US",
    population: 1793477,
    gdp: 26000,
    houseSeats: 3,
    senateSeats: 34,
    region: "South",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 50 }, { abbr: "REP", org: 22, reg: 22 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "IL",
    name: "Illinois",
    countryId: "US",
    population: 11430602,
    gdp: 275000,
    houseSeats: 20,
    senateSeats: 59,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "IN",
    name: "Indiana",
    countryId: "US",
    population: 5544159,
    gdp: 110000,
    houseSeats: 10,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 27, reg: 33 }, { abbr: "REP", org: 30, reg: 40 }], independent: 19, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "IA",
    name: "Iowa",
    countryId: "US",
    population: 2776755,
    gdp: 56000,
    houseSeats: 5,
    senateSeats: 50,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "KS",
    name: "Kansas",
    countryId: "US",
    population: 2477574,
    gdp: 53000,
    houseSeats: 4,
    senateSeats: 40,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MI",
    name: "Michigan",
    countryId: "US",
    population: 9295297,
    gdp: 200000,
    houseSeats: 16,
    senateSeats: 38,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MN",
    name: "Minnesota",
    countryId: "US",
    population: 4375099,
    gdp: 110000,
    houseSeats: 8,
    senateSeats: 67,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 50 }, { abbr: "REP", org: 22, reg: 22 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MO",
    name: "Missouri",
    countryId: "US",
    population: 5117073,
    gdp: 105000,
    houseSeats: 9,
    senateSeats: 34,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NE",
    name: "Nebraska",
    countryId: "US",
    population: 1578385,
    gdp: 33000,
    houseSeats: 3,
    senateSeats: 49,
    region: "Midwest",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "ND",
    name: "North Dakota",
    countryId: "US",
    population: 638800,
    gdp: 12000,
    houseSeats: 1,
    senateSeats: 47,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "OH",
    name: "Ohio",
    countryId: "US",
    population: 10847115,
    gdp: 230000,
    houseSeats: 19,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "SD",
    name: "South Dakota",
    countryId: "US",
    population: 696004,
    gdp: 13000,
    houseSeats: 1,
    senateSeats: 35,
    region: "Midwest",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "WI",
    name: "Wisconsin",
    countryId: "US",
    population: 4891769,
    gdp: 105000,
    houseSeats: 9,
    senateSeats: 33,
    region: "Midwest",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "AK",
    name: "Alaska",
    countryId: "US",
    population: 550043,
    gdp: 24000,
    houseSeats: 1,
    senateSeats: 20,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 22 }, { abbr: "REP", org: 35, reg: 52 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "AZ",
    name: "Arizona",
    countryId: "US",
    population: 3665228,
    gdp: 70000,
    houseSeats: 6,
    senateSeats: 30,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "CA",
    name: "California",
    countryId: "US",
    population: 29760021,
    gdp: 740000,
    houseSeats: 52,
    senateSeats: 40,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "CO",
    name: "Colorado",
    countryId: "US",
    population: 3294394,
    gdp: 70000,
    houseSeats: 6,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "HI",
    name: "Hawaii",
    countryId: "US",
    population: 1108229,
    gdp: 30000,
    houseSeats: 2,
    senateSeats: 25,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 35, reg: 50 }, { abbr: "REP", org: 22, reg: 22 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "ID",
    name: "Idaho",
    countryId: "US",
    population: 1006749,
    gdp: 16000,
    houseSeats: 2,
    senateSeats: 35,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 22 }, { abbr: "REP", org: 35, reg: 52 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "MT",
    name: "Montana",
    countryId: "US",
    population: 799065,
    gdp: 13000,
    houseSeats: 1,
    senateSeats: 50,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NV",
    name: "Nevada",
    countryId: "US",
    population: 1201833,
    gdp: 30000,
    houseSeats: 2,
    senateSeats: 21,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 24, reg: 28 }, { abbr: "REP", org: 33, reg: 46 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "NM",
    name: "New Mexico",
    countryId: "US",
    population: 1515069,
    gdp: 26000,
    houseSeats: 3,
    senateSeats: 42,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 29, reg: 40 }, { abbr: "REP", org: 28, reg: 32 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "OR",
    name: "Oregon",
    countryId: "US",
    population: 2842321,
    gdp: 55000,
    houseSeats: 5,
    senateSeats: 30,
    region: "West",
    senateClasses: [2, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "UT",
    name: "Utah",
    countryId: "US",
    population: 1722850,
    gdp: 30000,
    houseSeats: 3,
    senateSeats: 29,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 22 }, { abbr: "REP", org: 35, reg: 52 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "WA",
    name: "Washington",
    countryId: "US",
    population: 4866692,
    gdp: 115000,
    houseSeats: 9,
    senateSeats: 49,
    region: "West",
    senateClasses: [1, 3],
    registration: { parties: [{ abbr: "DEM", org: 32, reg: 45 }, { abbr: "REP", org: 25, reg: 27 }], independent: 20, unregistered: 8, unaffiliatedOrg: 43 },
  },
  {
    id: "WY",
    name: "Wyoming",
    countryId: "US",
    population: 453588,
    gdp: 12000,
    houseSeats: 1,
    senateSeats: 30,
    region: "West",
    senateClasses: [1, 2],
    registration: { parties: [{ abbr: "DEM", org: 22, reg: 22 }, { abbr: "REP", org: 35, reg: 52 }], independent: 18, unregistered: 8, unaffiliatedOrg: 43 },
  },
];

// Totals: 50 regions, 248,102,973 population, 435 house seats, 1972 upper-state seats (sum).
