/**
 * Achievement catalog — W35 port of src/lib/seeds/achievements.ts
 * ACHIEVEMENT_SEED (58 entries, slug/name/description/icon/category/order
 * transcribed verbatim; `isHidden` is a display-only UI flag mainline itself
 * defines and is not modeled here — every entry is listed so a UI decides
 * hidden-until-earned rendering itself, same as legislation/catalog.ts and
 * actions/catalog.ts already do for their own "hidden until reachable"
 * entries).
 *
 * `status`/`blockingSystem` mark which triggers solo can evaluate for real
 * today (see achievements/evaluate.ts) versus which need an unported system
 * (name given per entry). This is a data file: the trigger LOGIC lives in
 * evaluate.ts, keyed by slug.
 */
import type { AchievementCatalogEntry } from "./types.js";

export const ACHIEVEMENT_CATALOG: AchievementCatalogEntry[] = [
  // ── Special ──────────────────────────────────────────────────────────
  {
    slug: "alpha_tester",
    name: "Founding Father",
    description: "Joined during the alpha phase of the game",
    icon: "FlaskConical",
    category: "special",
    order: 0,
    status: "unavailable",
    blockingSystem: "account/server provenance (character_created is not world-state)",
  },
  {
    slug: "patreon_supporter_plus",
    name: "Patron Plus",
    description: "Reached Supporter+ on Patreon",
    icon: "Sparkles",
    category: "special",
    order: 1,
    status: "unavailable",
    blockingSystem: "external payment system (Patreon) — manual grant only",
  },
  {
    slug: "beta2_veteran",
    name: "Cold War Veteran",
    description: "Played during Beta 2, the era before the 1953 relaunch",
    icon: "History",
    category: "special",
    order: 2,
    status: "unavailable",
    blockingSystem: "account/server provenance — manual grant only",
  },
  {
    slug: "iteration4_founder",
    name: "Fourth Founding",
    description: "Joined the Fourth Founding and the 1953 relaunch",
    icon: "Landmark",
    category: "special",
    order: 3,
    status: "unavailable",
    blockingSystem: "season/iteration concept — not applicable to a single-world solo save",
  },
  {
    slug: "wiki_contributor",
    name: "Keeper of the Record",
    description: "Contributed research, corrections, or new lore to the wiki",
    icon: "BookOpen",
    category: "special",
    order: 4,
    status: "unavailable",
    blockingSystem: "wiki contribution tracking — manual grant only",
  },
  {
    slug: "iron_triangle",
    name: "Iron Triangle",
    description: "Held elected office, a Cabinet seat, and party leadership at once",
    icon: "Triangle",
    category: "special",
    order: 5,
    status: "available",
  },
  {
    slug: "turn_one",
    name: "In at the Ground Floor",
    description: "Took an action in turn one of a brand-new era",
    icon: "Rocket",
    category: "special",
    order: 6,
    status: "available",
  },
  {
    slug: "night_shift",
    name: "Night Shift",
    description: "Took an action between midnight and 1am server time",
    icon: "Moon",
    category: "special",
    order: 7,
    status: "unavailable",
    blockingSystem: "wall-clock time (determinism doctrine forbids Date.now in packages/engine)",
  },
  {
    slug: "completionist",
    name: "The Completionist",
    description: "Earned every other achievement in the game",
    icon: "Gem",
    category: "special",
    order: 8,
    status: "unavailable",
    blockingSystem: "depends on the manual-only achievements above (patreon_supporter_plus, alpha_tester, etc.), which have no real trigger in solo",
  },
  // ── Action-based ─────────────────────────────────────────────────────
  {
    slug: "first_fundraise",
    name: "Passing the Hat",
    description: "Completed your first fundraise",
    icon: "HandCoins",
    category: "action",
    order: 10,
    status: "available",
  },
  {
    slug: "fundraiser",
    name: "K Street Regular",
    description: "Raised funds 10 times",
    icon: "BadgeDollarSign",
    category: "action",
    order: 11,
    status: "available",
  },
  {
    slug: "big_fundraiser",
    name: "Money Machine",
    description: "Raised funds 50 times",
    icon: "Banknote",
    category: "action",
    order: 12,
    status: "available",
  },
  {
    slug: "campaigner",
    name: "Stump Speaker",
    description: "Campaigned 10 times",
    icon: "Vote",
    category: "action",
    order: 13,
    status: "available",
  },
  {
    slug: "grassroots",
    name: "Whistle Stop",
    description: "Built donor base 5 times",
    icon: "Sprout",
    category: "action",
    order: 14,
    status: "available",
  },
  {
    slug: "pollster",
    name: "Gallup's Ghost",
    description: "Commissioned 5 polls",
    icon: "ChartNoAxesColumnIncreasing",
    category: "action",
    order: 15,
    status: "unavailable",
    blockingSystem: "polling/election polling (see actions/catalog.ts poll/pollLarge entries — unavailable there too)",
  },
  {
    slug: "advertiser",
    name: "Prime Time",
    description: "Ran 3 ad campaigns",
    icon: "Tv",
    category: "action",
    order: 16,
    status: "available",
  },
  {
    slug: "rested",
    name: "Executive Time",
    description: "Rested to recover actions",
    icon: "Bed",
    category: "action",
    order: 17,
    status: "available",
  },
  {
    slug: "century_club",
    name: "Century Club",
    description: "Logged 100 actions with one character",
    icon: "Award",
    category: "action",
    order: 18,
    status: "available",
  },
  // ── Election-based ───────────────────────────────────────────────────
  {
    slug: "first_candidate",
    name: "Throwing Your Hat In",
    description: "Entered your first election",
    icon: "Target",
    category: "election",
    order: 20,
    status: "available",
  },
  {
    slug: "house_candidate",
    name: "Mr. Smith Goes to Washington",
    description: "Ran for the U.S. House",
    icon: "House",
    category: "election",
    order: 21,
    status: "available",
  },
  {
    slug: "senate_candidate",
    name: "Senatorial Ambition",
    description: "Ran for the U.S. Senate",
    icon: "Building2",
    category: "election",
    order: 22,
    status: "available",
  },
  {
    slug: "governor_candidate",
    name: "Mansion on the Hill",
    description: "Ran for Governor",
    icon: "Star",
    category: "election",
    order: 23,
    status: "unavailable",
    blockingSystem: "state governor office (not modeled — elections/orchestration.ts has no governor electionType)",
  },
  {
    slug: "president_candidate",
    name: "Hail to the Chief",
    description: "Entered a presidential race",
    icon: "Flag",
    category: "election",
    order: 24,
    status: "available",
  },
  {
    slug: "presidential_nominee",
    name: "The Nomination",
    description: "Won your party's presidential primary",
    icon: "Medal",
    category: "election",
    order: 25,
    status: "unavailable",
    blockingSystem: "primary election stage (solo elections have no separate primary-vs-general phase to win)",
  },
  {
    slug: "house_member",
    name: "The People's Voice",
    description: "Won a U.S. House seat",
    icon: "Landmark",
    category: "election",
    order: 30,
    status: "available",
  },
  {
    slug: "senator",
    name: "The Upper Chamber",
    description: "Won a U.S. Senate seat",
    icon: "Scale",
    category: "election",
    order: 31,
    status: "available",
  },
  {
    slug: "governor",
    name: "The Governor's Mansion",
    description: "Won a gubernatorial election",
    icon: "Badge",
    category: "election",
    order: 32,
    status: "unavailable",
    blockingSystem: "state governor office (not modeled)",
  },
  {
    slug: "state_senator",
    name: "The Statehouse",
    description: "Won a state senate seat",
    icon: "ScrollText",
    category: "election",
    order: 33,
    status: "unavailable",
    blockingSystem: "state senate office (not modeled)",
  },
  {
    slug: "president",
    name: "Leader of the Free World",
    description: "Became President",
    icon: "Shield",
    category: "election",
    order: 34,
    status: "available",
  },
  {
    slug: "vice_president",
    name: "A Heartbeat Away",
    description: "Became Vice President",
    icon: "Bird",
    category: "election",
    order: 35,
    status: "available",
  },
  {
    slug: "three_terms",
    name: "The Incumbent",
    description: "Won 3 elections",
    icon: "ClipboardCheck",
    category: "election",
    order: 36,
    status: "unavailable",
    blockingSystem: "historical term count (solo tracks only current officeholding, no electedOfficials-equivalent win log)",
  },
  {
    slug: "cabinet_seat",
    name: "At the President's Table",
    description: "Accepted an appointment to a Cabinet position",
    icon: "Users",
    category: "election",
    order: 37,
    status: "available",
  },
  {
    slug: "central_banker",
    name: "Master of the Mint",
    description: "Became Chair of a Central Bank",
    icon: "PiggyBank",
    category: "election",
    order: 38,
    status: "unavailable",
    blockingSystem: "character-held central bank chair (centralBank/types.ts: every solo bank runs the autonomous NPP technocrat, no nomination pool exists)",
  },
  {
    slug: "party_founder",
    name: "A Party of One",
    description: "Founded a new political party",
    icon: "FlagTriangleRight",
    category: "election",
    order: 39,
    status: "unavailable",
    blockingSystem: "manual grant only — actions/catalog.ts foundParty exists but this achievement is not currently tracked as a countable trigger",
  },
  // ── Legislation ──────────────────────────────────────────────────────
  {
    slug: "first_bill",
    name: "The First Draft",
    description: "Sponsored your first bill",
    icon: "FileText",
    category: "legislation",
    order: 40,
    status: "available",
  },
  {
    slug: "lawmaker",
    name: "Filibuster Buster",
    description: "Had a bill pass into law",
    icon: "CircleCheck",
    category: "legislation",
    order: 41,
    status: "available",
  },
  {
    slug: "cosponsor",
    name: "Across the Aisle",
    description: "Cosponsored a bill",
    icon: "Handshake",
    category: "legislation",
    order: 42,
    status: "unavailable",
    blockingSystem: "bill cosponsorship (legislation/types.ts Bill has a single sponsorId, no cosponsor list)",
  },
  // ── Social ───────────────────────────────────────────────────────────
  {
    slug: "influencer",
    name: "Pulling Strings",
    description: "Influenced another character 5 times",
    icon: "Megaphone",
    category: "social",
    order: 50,
    status: "unavailable",
    blockingSystem: "supportPlayer/attackPlayer/barnstorm actions (not in the solo action catalog)",
  },
  {
    slug: "barnstormer",
    name: "Rough Rider",
    description: "Used barnstorm on a character",
    icon: "Tornado",
    category: "social",
    order: 51,
    status: "unavailable",
    blockingSystem: "barnstorm action (not in the solo action catalog)",
  },
  {
    slug: "first_subscriber",
    name: "Following the Trail",
    description: "Subscribed to another character",
    icon: "Eye",
    category: "social",
    order: 52,
    status: "unavailable",
    blockingSystem: "subscription/follower system (not modeled — no other human players to subscribe to)",
  },
  {
    slug: "popular",
    name: "Beltway Buzz",
    description: "Gained 5 subscribers",
    icon: "Heart",
    category: "social",
    order: 53,
    status: "unavailable",
    blockingSystem: "subscription/follower system (not modeled)",
  },
  {
    slug: "celebrity",
    name: "Front Page News",
    description: "Gained 20 subscribers",
    icon: "Newspaper",
    category: "social",
    order: 54,
    status: "unavailable",
    blockingSystem: "subscription/follower system (not modeled)",
  },
  {
    slug: "first_post",
    name: "Off the Record",
    description: "Made your first news post",
    icon: "FilePenLine",
    category: "social",
    order: 80,
    status: "unavailable",
    blockingSystem: "player news posts/forum (world.news is system-generated headlines only)",
  },
  {
    slug: "commenter",
    name: "The Pundit",
    description: "Replied to 5 news posts",
    icon: "MessageCircle",
    category: "social",
    order: 81,
    status: "unavailable",
    blockingSystem: "player news posts/forum (not modeled)",
  },
  {
    slug: "policy_shift",
    name: "Flip-Flopper",
    description: "Changed your policy positions",
    icon: "RefreshCw",
    category: "social",
    order: 82,
    status: "unavailable",
    blockingSystem: "player-authored policy-position change tracking (not modeled)",
  },
  // ── Milestone ────────────────────────────────────────────────────────
  {
    slug: "millionaire",
    name: "Fat Cat",
    description: "Reached $1,000,000 in campaign funds",
    icon: "CircleDollarSign",
    category: "milestone",
    order: 60,
    status: "available",
  },
  {
    slug: "big_spender",
    name: "Pork Barrel",
    description: "Received funds from another character",
    icon: "Gift",
    category: "milestone",
    order: 61,
    status: "unavailable",
    blockingSystem: "no NPC-initiated wires exist — the solo player is always the wire sender, never a receiver",
  },
  {
    slug: "donor",
    name: "The Bundler",
    description: "Donated to another character's campaign",
    icon: "HandHeart",
    category: "milestone",
    order: 62,
    status: "available",
  },
  {
    slug: "corner_office",
    name: "Corner Office",
    description: "Took the CEO seat of a corporation",
    icon: "Briefcase",
    category: "milestone",
    order: 63,
    status: "unavailable",
    blockingSystem: "player-run corporations (corporation/types.ts: every corp is NPC-run until wave U3)",
  },
  {
    slug: "bondholder",
    name: "Clip the Coupon",
    description: "Collected steady income from bonds",
    icon: "ScrollText",
    category: "milestone",
    order: 64,
    status: "available",
  },
  {
    slug: "dividend_day",
    name: "Dividend Day",
    description: "Collected dividend income from shares",
    icon: "Coins",
    category: "milestone",
    order: 65,
    status: "unavailable",
    blockingSystem: "dividend distribution (corporation/types.ts: dividendMult is a growth-policy multiplier only, no cash payout to shareholders is ported)",
  },
  {
    slug: "elder_statesman",
    name: "Elder Statesman",
    description: "Kept one character active for 30 real-world days",
    icon: "Hourglass",
    category: "milestone",
    order: 66,
    status: "unavailable",
    blockingSystem: "wall-clock elapsed time (determinism doctrine forbids Date.now in packages/engine; no turn-based equivalent redefinition attempted)",
  },
  {
    slug: "built_different",
    name: "Built Different",
    description: "Allocated every point that makes a politician tick",
    icon: "Dumbbell",
    category: "milestone",
    order: 67,
    status: "unavailable",
    blockingSystem: "character stat-allocation system (not modeled)",
  },
  {
    slug: "onboarded",
    name: "Learned the Ropes",
    description: "Completed new-player onboarding",
    icon: "GraduationCap",
    category: "milestone",
    order: 68,
    status: "unavailable",
    blockingSystem: "onboarding flow (not modeled — no UI tutorial state on WorldState)",
  },
  {
    slug: "hall_of_famer",
    name: "Hall of Famer",
    description: "Cracked the Top 10 of the global Hall of Fame",
    icon: "Trophy",
    category: "milestone",
    order: 69,
    status: "unavailable",
    blockingSystem: "cross-world leaderboard/Hall of Fame (not modeled — solo has no other worlds to rank against)",
  },
  {
    slug: "dealmaker",
    name: "Dealmaker",
    description: "Closed a corporate merger or acquisition",
    icon: "Handshake",
    category: "milestone",
    order: 70,
    status: "unavailable",
    blockingSystem: "corporate M&A (not modeled — corporation/types.ts file doc lists M&A as a future wave)",
  },
  {
    slug: "speaker_candidate",
    name: "Order in the House",
    description: "Ran for Speaker of the House",
    icon: "AudioLines",
    category: "milestone",
    order: 71,
    status: "unavailable",
    blockingSystem: "Speaker of the House election (not modeled)",
  },
  {
    slug: "party_leader",
    name: "The Kingmaker",
    description: "Held a party leadership position",
    icon: "Crown",
    category: "milestone",
    order: 72,
    status: "available",
  },
];
