import { test, expect } from '@playwright/test';
test('a real singleplayer world survives save and relaunch on a phone sized screen', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'New game', exact: true }).click();
  await page.getByLabel('Your name').fill('Smoke Player');
  await page.getByLabel('Seed', { exact: false }).fill('native-smoke-1953');
  await page.getByLabel('Country', { exact: true }).selectOption('US');
  await page.getByRole('button', { name: 'Start', exact: true }).click();
  await expect(page.getByRole('button', { name: 'End turn', exact: true })).toBeEnabled();
  await page.getByRole('tab', { name: 'Character', exact: true }).click();
  const amount = page.getByRole('spinbutton', { name: /Amount for/ });
  await amount.fill('2000');
  await amount.locator('xpath=../..').getByRole('button').click();
  await expect(page.getByRole('status')).toContainText(/2,000|2000/);
  await page.getByRole('tab', { name: 'Overview', exact: true }).click();
  await page.getByRole('button', { name: 'End turn', exact: true }).click();
  await expect(page.getByText(/^1953 · Turn 1 ·/)).toBeVisible();
  await page.getByRole('button', { name: 'Save game', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Game saved' })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: /Continue Smoke Player/ }).click();
  await expect(page.getByText(/^1953 · Turn 1 ·/)).toBeVisible();
  await page.getByRole('button', { name: 'End turn', exact: true }).click();
  await expect(page.getByText(/^1953 · Turn 2 ·/)).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await page.screenshot({ path: 'artifacts/smoke/mobile-world.png', fullPage: true });
});
