import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { gameReady, navigateGame } from './game-navigation';

test('saved party and regional rosters expose every page through compact phone controls', async ({ page }) => {
  const fixture = gunzipSync(readFileSync(new URL('../fixtures/career-elected-1953-US.save.json.gz', import.meta.url)));
  await page.goto('/');
  await page.getByLabel('Import saved game', { exact: true }).setInputFiles({ name: 'elected.json', mimeType: 'application/json', buffer: fixture });
  await gameReady(page);
  await page.context().setOffline(true);
  await navigateGame(page, 'Parties');
  await page.getByRole('button', { name: 'View Democratic Party details', exact: true }).click();
  const party = page.getByRole('article', { name: 'Democratic Party', exact: true });
  const summary = party.locator('summary').filter({ hasText: /^Roster \(/ });
  await summary.scrollIntoViewIfNeeded();
  expect((await summary.boundingBox())!.height).toBeGreaterThanOrEqual(44);
  await expect(party.getByRole('searchbox', { name: 'Search roster' })).toHaveCount(0);
  await summary.click();
  const roster = party.getByRole('list', { name: 'Party roster', exact: true });
  await expect(roster.getByRole('listitem')).toHaveCount(12);
  const first = await roster.getByRole('listitem').first().innerText();
  await party.getByRole('button', { name: 'Next roster page' }).click();
  const secondPageName = await roster.getByRole('listitem').first().innerText();
  expect(secondPageName).not.toBe(first);
  await party.getByRole('searchbox', { name: 'Search roster' }).fill(secondPageName);
  await expect(roster).toContainText(secondPageName);
  await party.getByRole('searchbox', { name: 'Search roster' }).fill('Muse');
  await expect(roster.getByText('Muse', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/reviews/mobile-readability/party-roster-depth.png', fullPage: true });

  await navigateGame(page, 'Regions');
  await page.getByText('Browse regions', { exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search regions' }).fill('California');
  await page.getByRole('button', { name: 'Search directory', exact: true }).click();
  await page.getByRole('button', { name: 'View California details', exact: true }).click();
  const chamber = page.getByRole('listitem', { name: 'House of Representatives', exact: true });
  await chamber.locator('summary').click();
  await expect(chamber.getByRole('listitem')).toHaveCount(12);
  const firstMember = await chamber.getByRole('listitem').first().innerText();
  await chamber.getByRole('button', { name: 'Next House of Representatives members' }).click();
  expect(await chamber.getByRole('listitem').first().innerText()).not.toBe(firstMember);
  await chamber.locator('summary').click();
  const budget = page.locator('summary').filter({ hasText: /^Revenue and spending detail/ });
  await budget.click();
  await expect(page.getByRole('heading', { name: 'Spending by category', exact: true })).toBeVisible();
  await budget.click();
  const demographics = page.locator('summary').filter({ hasText: /^Demographic detail/ });
  await demographics.click();
  await expect(page.getByRole('heading', { name: 'Demographic groups', exact: true })).toBeVisible();
  await demographics.click();
  await page.evaluate(() => scrollTo(0, 0));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/reviews/mobile-readability/regional-details-compact.png', fullPage: true });
  await expect(page.getByRole('contentinfo')).toContainText('Turn 98');
});
