/**
 * NPP name pools — Eastern-bloc lists: HU, PL, CS, BG, RO, YU, BLR, the BAL
 * composite (Estonia/Latvia/Lithuania), Soviet minority sub-pools for RU, and
 * the GDR-era first names for DD.
 *
 * Same conventions as nameLists1-3: pools are ASCII-only (diacritics are
 * dropped the way English-language sources drop them — "Wojcik" not "Wójcik",
 * "Novak" not "Novák"), and the names read correctly for a legislator seated
 * anywhere in the 1950s-1980s window these countries are playable in.
 *
 * Real bloc-era leaders are deliberately absent as surnames where the pairing
 * would be unmistakable (no Zhivkov, Ceausescu, Gomulka, Ulbricht, Honecker,
 * Husak, Kadar, Tito/Broz, or Hoxha). Common surnames that merely happen to
 * be shared with a public figure are kept — they are common for a reason.
 *
 * The generator functions and country routing stay in nameGenerator.ts.
 */

// ─── Hungary ────────────────────────────────────────────────────────────────
// Hungarian usage is family name first ("Nagy Istvan"); the generator honours
// that via the surnameFirst flag, same mechanism as the CN pool.

export const HU_SURNAMES = [
  "Nagy",
  "Kovacs",
  "Toth",
  "Szabo",
  "Horvath",
  "Varga",
  "Kiss",
  "Molnar",
  "Nemeth",
  "Farkas",
  "Balogh",
  "Papp",
  "Takacs",
  "Juhasz",
  "Lakatos",
  "Meszaros",
  "Olah",
  "Simon",
  "Racz",
  "Fekete",
  "Szilagyi",
  "Torok",
  "Feher",
  "Balazs",
  "Gal",
  "Szucs",
  "Kocsis",
  "Pinter",
  "Fodor",
  "Szalai",
  "Sipos",
  "Magyar",
  "Lukacs",
  "Gulyas",
  "Biro",
  "Kiraly",
  "Katona",
  "Jakab",
  "Sandor",
  "Boros",
  "Fabian",
  "Kelemen",
  "Vass",
  "Somogyi",
  "Halasz",
  "Fulop",
  "Antal",
  "Bodnar",
  "Illes",
  "Vincze",
  "Deak",
  "Pataki",
  "Barta",
  "Orosz",
  "Hegedus",
  "Balla",
  "Szollosi",
  "Bakos",
  "Csonka",
  "Vamos",
] as const;

export const HU_FIRST_NAMES_MALE = [
  "Istvan",
  "Janos",
  "Jozsef",
  "Laszlo",
  "Ferenc",
  "Sandor",
  "Zoltan",
  "Gabor",
  "Gyula",
  "Imre",
  "Bela",
  "Karoly",
  "Miklos",
  "Andras",
  "Peter",
  "Gyorgy",
  "Tibor",
  "Lajos",
  "Attila",
  "Tamas",
  "Pal",
  "Antal",
  "Geza",
  "Erno",
  "Dezso",
  "Kalman",
  "Vilmos",
  "Balazs",
  "Csaba",
  "Denes",
  "Elemer",
  "Endre",
  "Frigyes",
  "Gergely",
  "Ignac",
  "Kornel",
  "Marton",
  "Odon",
  "Rezso",
  "Szilard",
  "Vince",
  "Zsigmond",
  "Arpad",
  "Barnabas",
  "Benedek",
] as const;

export const HU_FIRST_NAMES_FEMALE = [
  "Maria",
  "Erzsebet",
  "Ilona",
  "Katalin",
  "Margit",
  "Anna",
  "Zsuzsanna",
  "Eva",
  "Julianna",
  "Agnes",
  "Judit",
  "Iren",
  "Magdolna",
  "Piroska",
  "Terez",
  "Gizella",
  "Klara",
  "Rozalia",
  "Veronika",
  "Ibolya",
  "Etelka",
  "Aranka",
  "Borbala",
  "Cecilia",
  "Dorottya",
  "Emma",
  "Franciska",
  "Gabriella",
  "Hajnalka",
  "Jolan",
  "Kornelia",
  "Lidia",
  "Marta",
  "Olga",
  "Sarolta",
  "Valeria",
  "Vilma",
  "Zita",
  "Edit",
  "Emese",
  "Gyongyi",
  "Ildiko",
  "Krisztina",
  "Livia",
  "Melinda",
] as const;

// ─── Poland ─────────────────────────────────────────────────────────────────
// Adjectival surnames (-ski/-cki/-dzki) inflect for gender; the feminine form
// is derived in nameGenerator.ts, not stored here.

export const PL_SURNAMES = [
  "Nowak",
  "Kowalski",
  "Wisniewski",
  "Wojcik",
  "Kowalczyk",
  "Kaminski",
  "Lewandowski",
  "Zielinski",
  "Szymanski",
  "Wozniak",
  "Dabrowski",
  "Kozlowski",
  "Jankowski",
  "Mazur",
  "Wojciechowski",
  "Kwiatkowski",
  "Krawczyk",
  "Kaczmarek",
  "Piotrowski",
  "Grabowski",
  "Zajac",
  "Pawlowski",
  "Michalski",
  "Krol",
  "Nowakowski",
  "Wieczorek",
  "Wrobel",
  "Jablonski",
  "Dudek",
  "Adamczyk",
  "Majewski",
  "Nowicki",
  "Olszewski",
  "Stepien",
  "Malinowski",
  "Jaworski",
  "Gorski",
  "Rutkowski",
  "Witkowski",
  "Sikora",
  "Baran",
  "Walczak",
  "Ostrowski",
  "Tomaszewski",
  "Pietrzak",
  "Zalewski",
  "Wroblewski",
  "Marciniak",
  "Sadowski",
  "Jasinski",
  "Zawadzki",
  "Sobczak",
  "Kubiak",
  "Wilk",
  "Lis",
  "Mazurek",
  "Szewczyk",
  "Czarnecki",
  "Borkowski",
  "Sawicki",
] as const;

export const PL_FIRST_NAMES_MALE = [
  "Jan",
  "Stanislaw",
  "Andrzej",
  "Jozef",
  "Tadeusz",
  "Jerzy",
  "Zbigniew",
  "Krzysztof",
  "Henryk",
  "Ryszard",
  "Kazimierz",
  "Marek",
  "Marian",
  "Piotr",
  "Janusz",
  "Wladyslaw",
  "Adam",
  "Wieslaw",
  "Zdzislaw",
  "Edward",
  "Mieczyslaw",
  "Roman",
  "Waldemar",
  "Wojciech",
  "Grzegorz",
  "Czeslaw",
  "Stefan",
  "Leszek",
  "Slawomir",
  "Antoni",
  "Bogdan",
  "Dariusz",
  "Eugeniusz",
  "Franciszek",
  "Ireneusz",
  "Jacek",
  "Jaroslaw",
  "Karol",
  "Lech",
  "Lucjan",
  "Maciej",
  "Miroslaw",
  "Pawel",
  "Przemyslaw",
  "Rafal",
  "Tomasz",
  "Witold",
  "Zygmunt",
] as const;

export const PL_FIRST_NAMES_FEMALE = [
  "Maria",
  "Krystyna",
  "Anna",
  "Barbara",
  "Teresa",
  "Elzbieta",
  "Janina",
  "Zofia",
  "Jadwiga",
  "Danuta",
  "Halina",
  "Irena",
  "Ewa",
  "Malgorzata",
  "Helena",
  "Grazyna",
  "Bozena",
  "Stanislawa",
  "Jolanta",
  "Urszula",
  "Wanda",
  "Alicja",
  "Dorota",
  "Genowefa",
  "Hanna",
  "Iwona",
  "Joanna",
  "Kazimiera",
  "Lidia",
  "Lucyna",
  "Magdalena",
  "Marianna",
  "Miroslawa",
  "Renata",
  "Regina",
  "Stefania",
  "Wieslawa",
  "Wladyslawa",
  "Aleksandra",
  "Beata",
  "Celina",
  "Eugenia",
  "Felicja",
  "Gabriela",
  "Henryka",
] as const;

// ─── Czechoslovakia ─────────────────────────────────────────────────────────
// A Czech-majority mix with a Slovak minority share, matching the federation.
// Czech female surnames take -ova (Novak → Novakova) or inflect the
// adjectival -y ending (Novotny → Novotna); derived in nameGenerator.ts.

export const CS_SURNAMES = [
  "Novak",
  "Svoboda",
  "Novotny",
  "Dvorak",
  "Cerny",
  "Prochazka",
  "Kucera",
  "Vesely",
  "Horak",
  "Nemec",
  "Marek",
  "Pospisil",
  "Pokorny",
  "Hajek",
  "Kral",
  "Jelinek",
  "Ruzicka",
  "Sedlacek",
  "Dolezal",
  "Kolar",
  "Navratil",
  "Cermak",
  "Urban",
  "Vanek",
  "Blaha",
  "Kovar",
  "Kratochvil",
  "Bartos",
  "Polak",
  "Musil",
  "Kopecky",
  "Simek",
  "Konecny",
  "Stastny",
  "Mach",
  "Blazek",
  "Sykora",
  "Moravec",
  "Tichy",
  "Vavra",
  "Rehak",
  "Matousek",
  "Kovac",
  "Balaz",
  "Lukac",
  "Hudak",
  "Gajdos",
  "Mikula",
  "Slavik",
  "Urbanek",
  "Benda",
  "Fiser",
  "Havlik",
  "Janda",
  "Kadlec",
] as const;

export const CS_FIRST_NAMES_MALE = [
  "Josef",
  "Jan",
  "Vaclav",
  "Frantisek",
  "Antonin",
  "Jaroslav",
  "Miroslav",
  "Jiri",
  "Karel",
  "Ladislav",
  "Zdenek",
  "Milan",
  "Vladimir",
  "Stanislav",
  "Petr",
  "Pavel",
  "Miloslav",
  "Bohumil",
  "Oldrich",
  "Rudolf",
  "Otakar",
  "Emil",
  "Alois",
  "Bedrich",
  "Lubomir",
  "Dusan",
  "Juraj",
  "Stefan",
  "Ondrej",
  "Marek",
  "Tomas",
  "Vlastimil",
  "Radomir",
  "Bohuslav",
  "Premysl",
  "Vojtech",
  "Kamil",
  "Roman",
  "Igor",
  "Ivan",
  "Marian",
  "Matej",
  "Norbert",
  "Viliam",
  "Vratislav",
] as const;

export const CS_FIRST_NAMES_FEMALE = [
  "Marie",
  "Jana",
  "Vera",
  "Alena",
  "Hana",
  "Jarmila",
  "Jaroslava",
  "Ludmila",
  "Anna",
  "Zdenka",
  "Marta",
  "Bozena",
  "Vlasta",
  "Milada",
  "Libuse",
  "Helena",
  "Eva",
  "Kveta",
  "Blanka",
  "Dagmar",
  "Ivana",
  "Jitka",
  "Milena",
  "Miroslava",
  "Olga",
  "Ruzena",
  "Stanislava",
  "Zuzana",
  "Katarina",
  "Maria",
  "Elena",
  "Viera",
  "Darina",
  "Gabriela",
  "Iveta",
  "Klara",
  "Lenka",
  "Magdalena",
  "Nadezda",
  "Pavla",
  "Renata",
  "Sona",
  "Tatiana",
  "Bohumila",
  "Drahomira",
] as const;

// ─── Bulgaria ───────────────────────────────────────────────────────────────
// All surnames end -ov/-ev so the shared Slavic feminizer produces the
// correct -ova/-eva forms (Dimitrov → Dimitrova).

export const BG_SURNAMES = [
  "Ivanov",
  "Georgiev",
  "Dimitrov",
  "Petrov",
  "Nikolov",
  "Todorov",
  "Hristov",
  "Stoyanov",
  "Iliev",
  "Angelov",
  "Atanasov",
  "Petkov",
  "Kolev",
  "Marinov",
  "Stefanov",
  "Vasilev",
  "Mihaylov",
  "Yordanov",
  "Popov",
  "Kostov",
  "Velikov",
  "Pavlov",
  "Nedelchev",
  "Boyanov",
  "Simeonov",
  "Draganov",
  "Kirilov",
  "Antonov",
  "Bogdanov",
  "Valchev",
  "Donchev",
  "Ganchev",
  "Genov",
  "Grozdanov",
  "Kalinov",
  "Lazarov",
  "Manolov",
  "Mladenov",
  "Nenov",
  "Panayotov",
  "Penev",
  "Rusev",
  "Slavov",
  "Spasov",
  "Tomov",
  "Tsvetkov",
  "Vulkov",
  "Zahariev",
  "Andonov",
  "Damyanov",
  "Enchev",
  "Filipov",
  "Kanev",
  "Borisov",
] as const;

export const BG_FIRST_NAMES_MALE = [
  "Georgi",
  "Ivan",
  "Dimitar",
  "Nikola",
  "Petar",
  "Hristo",
  "Todor",
  "Stoyan",
  "Vasil",
  "Atanas",
  "Angel",
  "Iliya",
  "Yordan",
  "Kiril",
  "Stefan",
  "Boris",
  "Simeon",
  "Lyuben",
  "Krum",
  "Asen",
  "Bogdan",
  "Boyan",
  "Dragan",
  "Emil",
  "Encho",
  "Gancho",
  "Kalin",
  "Kosta",
  "Lazar",
  "Lyubomir",
  "Marin",
  "Metodi",
  "Mihail",
  "Milko",
  "Mladen",
  "Nedelcho",
  "Nikolay",
  "Pavel",
  "Pencho",
  "Petko",
  "Plamen",
  "Radoslav",
  "Rumen",
  "Slavcho",
  "Spas",
  "Stanimir",
  "Tsvetan",
  "Valentin",
  "Vladimir",
  "Zahari",
] as const;

export const BG_FIRST_NAMES_FEMALE = [
  "Maria",
  "Elena",
  "Ivanka",
  "Yordanka",
  "Penka",
  "Todorka",
  "Stoyanka",
  "Nadezhda",
  "Violeta",
  "Margarita",
  "Radka",
  "Tsvetanka",
  "Ganka",
  "Donka",
  "Stanka",
  "Nedyalka",
  "Petya",
  "Zdravka",
  "Bogdana",
  "Boryana",
  "Darina",
  "Desislava",
  "Dimitrina",
  "Ekaterina",
  "Emiliya",
  "Evdokiya",
  "Gergana",
  "Hristina",
  "Iliana",
  "Kalina",
  "Katya",
  "Lilyana",
  "Lyudmila",
  "Milka",
  "Nevena",
  "Pavlina",
  "Rada",
  "Rositsa",
  "Rumyana",
  "Snezhana",
  "Stefka",
  "Svetla",
  "Vasilka",
  "Vesela",
  "Zlatka",
] as const;

// ─── Romania ────────────────────────────────────────────────────────────────
// Romanian surnames do not inflect for gender; no feminizer needed.

export const RO_SURNAMES = [
  "Popescu",
  "Ionescu",
  "Popa",
  "Radu",
  "Dumitrescu",
  "Stan",
  "Stoica",
  "Gheorghe",
  "Munteanu",
  "Matei",
  "Constantinescu",
  "Marinescu",
  "Serban",
  "Tudor",
  "Barbu",
  "Nistor",
  "Florea",
  "Diaconu",
  "Albu",
  "Cristea",
  "Toma",
  "Vasile",
  "Moldovan",
  "Rusu",
  "Lungu",
  "Ciobanu",
  "Dragomir",
  "Ene",
  "Neagu",
  "Oprea",
  "Preda",
  "Sandu",
  "Voinea",
  "Ilie",
  "Nedelcu",
  "Balan",
  "Bucur",
  "Dinu",
  "Dobre",
  "Dragan",
  "Enache",
  "Georgescu",
  "Grigore",
  "Iordache",
  "Lazar",
  "Lupu",
  "Manole",
  "Mihai",
  "Mocanu",
  "Nita",
  "Olteanu",
  "Pavel",
  "Petrescu",
  "Rotaru",
  "Sava",
  "Tanase",
  "Ursu",
  "Vlad",
  "Zamfir",
] as const;

export const RO_FIRST_NAMES_MALE = [
  "Ion",
  "Gheorghe",
  "Vasile",
  "Constantin",
  "Nicolae",
  "Dumitru",
  "Mihai",
  "Petre",
  "Stefan",
  "Alexandru",
  "Ilie",
  "Marin",
  "Tudor",
  "Andrei",
  "Aurel",
  "Cornel",
  "Cristian",
  "Dan",
  "Doru",
  "Emil",
  "Eugen",
  "Florin",
  "Gabriel",
  "Grigore",
  "Horia",
  "Iancu",
  "Ionel",
  "Iosif",
  "Liviu",
  "Lucian",
  "Marcel",
  "Marius",
  "Mircea",
  "Octavian",
  "Ovidiu",
  "Paul",
  "Radu",
  "Remus",
  "Sandu",
  "Sergiu",
  "Silviu",
  "Sorin",
  "Teodor",
  "Traian",
  "Valentin",
  "Valeriu",
  "Victor",
  "Viorel",
  "Virgil",
  "Vintila",
] as const;

export const RO_FIRST_NAMES_FEMALE = [
  "Maria",
  "Elena",
  "Ana",
  "Ioana",
  "Floarea",
  "Constanta",
  "Ecaterina",
  "Vasilica",
  "Georgeta",
  "Ileana",
  "Victoria",
  "Elisabeta",
  "Marioara",
  "Stefania",
  "Aurelia",
  "Cornelia",
  "Doina",
  "Dorina",
  "Eugenia",
  "Felicia",
  "Florica",
  "Gabriela",
  "Ilinca",
  "Irina",
  "Lidia",
  "Lucia",
  "Lucretia",
  "Magdalena",
  "Marcela",
  "Margareta",
  "Mariana",
  "Mihaela",
  "Mirela",
  "Monica",
  "Natalia",
  "Olga",
  "Paraschiva",
  "Petruta",
  "Rodica",
  "Sanda",
  "Silvia",
  "Simona",
  "Sofia",
  "Stela",
  "Tudora",
  "Valeria",
  "Veronica",
  "Viorica",
] as const;

// ─── Yugoslavia ─────────────────────────────────────────────────────────────
// Pan-Yugoslav mix: predominantly the -ic patronymics shared across
// Serbia/Croatia/Bosnia/Montenegro, with Slovene and Macedonian entries.
// The -ic surnames do not inflect for gender.

export const YU_SURNAMES = [
  "Jovanovic",
  "Petrovic",
  "Nikolic",
  "Markovic",
  "Djordjevic",
  "Stojanovic",
  "Ilic",
  "Stankovic",
  "Pavlovic",
  "Todorovic",
  "Popovic",
  "Ristic",
  "Kovacevic",
  "Babic",
  "Horvat",
  "Kovacic",
  "Knezevic",
  "Vukovic",
  "Radovanovic",
  "Simic",
  "Zivkovic",
  "Lukic",
  "Mitrovic",
  "Kostic",
  "Savic",
  "Jankovic",
  "Maric",
  "Tomic",
  "Bogdanovic",
  "Lazic",
  "Mihajlovic",
  "Filipovic",
  "Radic",
  "Matic",
  "Milic",
  "Nedeljkovic",
  "Obradovic",
  "Perisic",
  "Rakic",
  "Simovic",
  "Stevanovic",
  "Vasic",
  "Vidovic",
  "Zoric",
  "Bozic",
  "Cvetkovic",
  "Dimitrijevic",
  "Gajic",
  "Zupan",
  "Kranjc",
  "Stojanovski",
  "Trajanovski",
  "Begic",
  "Hodzic",
  "Delic",
] as const;

export const YU_FIRST_NAMES_MALE = [
  "Dragan",
  "Zoran",
  "Milan",
  "Dusan",
  "Petar",
  "Ivan",
  "Josip",
  "Branko",
  "Milorad",
  "Nikola",
  "Djordje",
  "Aleksandar",
  "Ante",
  "Bogdan",
  "Bojan",
  "Boris",
  "Borislav",
  "Bozidar",
  "Branislav",
  "Damir",
  "Danilo",
  "Davor",
  "Dejan",
  "Dimitrije",
  "Dragoljub",
  "Dragutin",
  "Goran",
  "Ilija",
  "Janez",
  "Jovan",
  "Lazar",
  "Ljubomir",
  "Marko",
  "Mate",
  "Milenko",
  "Milos",
  "Miodrag",
  "Mirko",
  "Miroslav",
  "Mladen",
  "Nebojsa",
  "Nenad",
  "Predrag",
  "Ranko",
  "Sava",
  "Sinisa",
  "Slavko",
  "Srdjan",
  "Stevan",
  "Stjepan",
  "Tomislav",
  "Velimir",
  "Vladimir",
  "Zeljko",
  "Zivorad",
] as const;

export const YU_FIRST_NAMES_FEMALE = [
  "Marija",
  "Ana",
  "Milica",
  "Jelena",
  "Dragica",
  "Zorica",
  "Vesna",
  "Ljubica",
  "Gordana",
  "Radmila",
  "Slavica",
  "Snezana",
  "Mirjana",
  "Verica",
  "Danica",
  "Dusanka",
  "Grozdana",
  "Jasmina",
  "Jelica",
  "Jovanka",
  "Katarina",
  "Ljiljana",
  "Milena",
  "Mira",
  "Nada",
  "Nevenka",
  "Olga",
  "Olivera",
  "Radojka",
  "Ruzica",
  "Sanja",
  "Senka",
  "Slobodanka",
  "Smilja",
  "Sofija",
  "Stana",
  "Stanislava",
  "Svetlana",
  "Vera",
  "Vidosava",
  "Zagorka",
  "Zdenka",
  "Zlata",
  "Branka",
  "Biljana",
  "Bosiljka",
  "Cvijeta",
] as const;

// ─── Belarus ────────────────────────────────────────────────────────────────
// Belarusian patronymic surnames (-vich) and nature names do not inflect;
// the russified -ov/-sky minority share does, via the shared Slavic feminizer.
// Given names use Belarusian forms in plain transliteration.

export const BLR_SURNAMES = [
  "Abramovich",
  "Adamovich",
  "Bogdanovich",
  "Klimovich",
  "Makarevich",
  "Mitskevich",
  "Senkevich",
  "Stankevich",
  "Yushkevich",
  "Dashkevich",
  "Zhdanovich",
  "Naumovich",
  "Yurkevich",
  "Filipovich",
  "Karpovich",
  "Danilovich",
  "Gurinovich",
  "Sidorovich",
  "Borisevich",
  "Lukashevich",
  "Voitovich",
  "Matusevich",
  "Tarasevich",
  "Yatskevich",
  "Zinkevich",
  "Kazakevich",
  "Zhuk",
  "Maroz",
  "Kazak",
  "Shpak",
  "Kulik",
  "Dubovik",
  "Savitsky",
  "Kaminsky",
  "Novikov",
  "Kovalyov",
  "Drazdou",
  "Sakalou",
  "Lebedz",
  "Verabei",
  "Halavach",
  "Krupenka",
  "Sauko",
  "Tsyhanok",
  "Charnyak",
] as const;

export const BLR_FIRST_NAMES_MALE = [
  "Ales",
  "Aleh",
  "Andrei",
  "Anatol",
  "Anton",
  "Arseni",
  "Barys",
  "Bronislau",
  "Dzmitry",
  "Eduard",
  "Fyodar",
  "Henadz",
  "Ihar",
  "Ivan",
  "Kanstantsin",
  "Kastus",
  "Kiryl",
  "Leanid",
  "Maksim",
  "Mikalai",
  "Mikhas",
  "Pavel",
  "Pyotr",
  "Ryhor",
  "Siarhei",
  "Stanislau",
  "Stsiapan",
  "Uladzimir",
  "Vasil",
  "Viktar",
  "Vital",
  "Yanka",
  "Yauhen",
  "Yazep",
  "Yury",
  "Zmitser",
  "Alyaksandr",
  "Alyaksei",
  "Valery",
  "Mikola",
] as const;

export const BLR_FIRST_NAMES_FEMALE = [
  "Alena",
  "Aksana",
  "Alesia",
  "Ala",
  "Anastasiya",
  "Hanna",
  "Halina",
  "Iryna",
  "Katsiaryna",
  "Larysa",
  "Lidziya",
  "Lyudmila",
  "Maryna",
  "Maryya",
  "Nadzeya",
  "Natallia",
  "Nina",
  "Volha",
  "Palina",
  "Raisa",
  "Sviatlana",
  "Tamara",
  "Tatsiana",
  "Valiantsina",
  "Vera",
  "Veranika",
  "Viktoryia",
  "Yadviha",
  "Yanina",
  "Yauheniya",
  "Zinaida",
  "Zoya",
  "Sofiya",
  "Regina",
  "Danuta",
  "Vanda",
  "Alina",
  "Darya",
  "Klaudziya",
  "Stanislava",
] as const;

// ─── Baltics (BAL composite: Estonia / Latvia / Lithuania) ──────────────────
// BAL is a composite macro-country, so the pool is three national sub-pools;
// the generator picks one nationality per politician so given name and
// surname always come from the same tradition. Latvian and Lithuanian
// surnames inflect for gender; Estonian ones do not.

export const BAL_EE_SURNAMES = [
  "Tamm",
  "Saar",
  "Sepp",
  "Magi",
  "Kask",
  "Kukk",
  "Rebane",
  "Lepik",
  "Oja",
  "Luik",
  "Raudsepp",
  "Vaher",
  "Parn",
  "Koppel",
  "Laur",
  "Toom",
  "Uibo",
  "Valk",
  "Kuusk",
  "Mets",
  "Kivi",
  "Allik",
  "Kangur",
  "Karu",
  "Lill",
  "Nurk",
  "Ots",
  "Pold",
  "Raag",
  "Sikk",
  "Susi",
  "Teder",
  "Vares",
] as const;

export const BAL_EE_FIRST_NAMES_MALE = [
  "Jaan",
  "Juhan",
  "Peeter",
  "Andres",
  "Toomas",
  "Mart",
  "Mati",
  "Rein",
  "Tiit",
  "Enn",
  "Ants",
  "Arvo",
  "Eino",
  "Endel",
  "Heino",
  "Jaak",
  "Kalev",
  "Lembit",
  "Olev",
  "Priit",
  "Raivo",
  "Tarmo",
  "Urmas",
  "Vello",
  "Villem",
] as const;

export const BAL_EE_FIRST_NAMES_FEMALE = [
  "Aino",
  "Anne",
  "Ene",
  "Helgi",
  "Helle",
  "Hilja",
  "Kai",
  "Katrin",
  "Krista",
  "Leida",
  "Liia",
  "Linda",
  "Maie",
  "Mall",
  "Mare",
  "Merike",
  "Reet",
  "Salme",
  "Silvi",
  "Sirje",
  "Tiina",
  "Tiiu",
  "Ulle",
  "Virve",
  "Maret",
] as const;

export const BAL_LV_SURNAMES = [
  "Berzins",
  "Kalnins",
  "Ozolins",
  "Ozols",
  "Liepins",
  "Krumins",
  "Balodis",
  "Eglitis",
  "Vitols",
  "Zarins",
  "Sprogis",
  "Vanags",
  "Dzenis",
  "Purins",
  "Rozitis",
  "Strazdins",
  "Zvirbulis",
  "Lacis",
  "Vilks",
  "Briedis",
  "Celms",
  "Klavins",
  "Priede",
  "Roze",
  "Skuja",
  "Zeltins",
  "Auzins",
  "Dumins",
] as const;

export const BAL_LV_FIRST_NAMES_MALE = [
  "Janis",
  "Andris",
  "Juris",
  "Peteris",
  "Karlis",
  "Aivars",
  "Gunars",
  "Imants",
  "Ivars",
  "Maris",
  "Ojars",
  "Uldis",
  "Valdis",
  "Vilis",
  "Ziedonis",
  "Arturs",
  "Edgars",
  "Guntis",
  "Raimonds",
  "Visvaldis",
] as const;

export const BAL_LV_FIRST_NAMES_FEMALE = [
  "Anna",
  "Ilze",
  "Inese",
  "Maija",
  "Mara",
  "Aina",
  "Ausma",
  "Biruta",
  "Dzidra",
  "Elza",
  "Gaida",
  "Inta",
  "Laima",
  "Lidija",
  "Ligita",
  "Mirdza",
  "Rasma",
  "Skaidrite",
  "Velta",
  "Vija",
  "Zenta",
] as const;

export const BAL_LT_SURNAMES = [
  "Kazlauskas",
  "Jankauskas",
  "Petrauskas",
  "Stankevicius",
  "Vasiliauskas",
  "Zukauskas",
  "Butkus",
  "Paulauskas",
  "Urbonas",
  "Kavaliauskas",
  "Balciunas",
  "Rimkus",
  "Navickas",
  "Zilinskas",
  "Adomaitis",
  "Norkus",
  "Petraitis",
  "Ramanauskas",
  "Sakalauskas",
  "Simkus",
  "Vaitkus",
  "Venckus",
  "Zemaitis",
  "Gudaitis",
  "Jonaitis",
] as const;

export const BAL_LT_FIRST_NAMES_MALE = [
  "Jonas",
  "Antanas",
  "Juozas",
  "Petras",
  "Vytautas",
  "Kazys",
  "Algirdas",
  "Vincas",
  "Stasys",
  "Povilas",
  "Bronius",
  "Kestutis",
  "Gediminas",
  "Rimantas",
  "Algimantas",
  "Vladas",
  "Zenonas",
  "Saulius",
  "Mindaugas",
  "Romualdas",
] as const;

export const BAL_LT_FIRST_NAMES_FEMALE = [
  "Ona",
  "Aldona",
  "Birute",
  "Danute",
  "Elena",
  "Genovaite",
  "Irena",
  "Janina",
  "Jadvyga",
  "Regina",
  "Vida",
  "Nijole",
  "Ruta",
  "Laima",
  "Grazina",
  "Rasa",
  "Vitalija",
  "Zita",
  "Egle",
  "Audrone",
] as const;

// ─── RU minority sub-pools ──────────────────────────────────────────────────
// The RU country spans the whole Union, but name generation has no per-region
// hook (the generator receives only a countryId). These sub-pools give the
// non-Russian republics a weighted share of the single RU pool instead.
// Belarusian, Baltic, and Moldovan/Romanian shares reuse the pools above.

export const RU_UA_SURNAMES = [
  "Shevchenko",
  "Kovalenko",
  "Bondarenko",
  "Boyko",
  "Tkachenko",
  "Kravchenko",
  "Oliynyk",
  "Shevchuk",
  "Polishchuk",
  "Lysenko",
  "Savchenko",
  "Rudenko",
  "Marchenko",
  "Melnyk",
  "Kravets",
  "Sydorenko",
  "Havrylyuk",
  "Petrenko",
  "Klymenko",
  "Pavlenko",
] as const;

export const RU_UA_FIRST_NAMES_MALE = [
  "Taras",
  "Bohdan",
  "Ostap",
  "Mykola",
  "Petro",
  "Vasyl",
  "Oleksandr",
  "Oleh",
  "Yaroslav",
  "Volodymyr",
  "Dmytro",
  "Andriy",
  "Serhiy",
  "Mykhailo",
  "Ihor",
] as const;

export const RU_UA_FIRST_NAMES_FEMALE = [
  "Oksana",
  "Halyna",
  "Lesya",
  "Kateryna",
  "Olena",
  "Iryna",
  "Nadiya",
  "Natalka",
  "Solomiya",
  "Yaryna",
  "Zoryana",
  "Larysa",
  "Maryana",
  "Svitlana",
  "Tetyana",
] as const;

// Georgian (-dze/-shvili) and Armenian (-yan) surnames do not inflect;
// the russified Azerbaijani -ov forms do, correctly, via the shared feminizer.
export const RU_CAUCASUS_SURNAMES = [
  "Beridze",
  "Lomidze",
  "Gelashvili",
  "Kapanadze",
  "Tsiklauri",
  "Maisuradze",
  "Japaridze",
  "Chkheidze",
  "Abashidze",
  "Petrosyan",
  "Hakobyan",
  "Grigoryan",
  "Harutyunyan",
  "Vardanyan",
  "Avagyan",
  "Mammadov",
  "Hasanov",
  "Huseynov",
  "Ismayilov",
  "Guliyev",
] as const;

export const RU_CAUCASUS_FIRST_NAMES_MALE = [
  "Giorgi",
  "Levan",
  "Zurab",
  "Davit",
  "Irakli",
  "Armen",
  "Ashot",
  "Tigran",
  "Vahan",
  "Suren",
  "Rustam",
  "Elchin",
  "Farid",
  "Vugar",
  "Anar",
] as const;

export const RU_CAUCASUS_FIRST_NAMES_FEMALE = [
  "Nino",
  "Tamar",
  "Ketevan",
  "Natela",
  "Anush",
  "Gayane",
  "Siranush",
  "Lusine",
  "Anahit",
  "Leyla",
  "Aygun",
  "Sevinj",
  "Gulnara",
  "Nigar",
  "Manana",
] as const;

// Soviet-era Central Asian surnames carry the russified -ov/-ev endings and
// inflect for gender the Russian way (Akhmetov → Akhmetova).
export const RU_CENTRAL_ASIA_SURNAMES = [
  "Akhmetov",
  "Omarov",
  "Suleimenov",
  "Iskakov",
  "Yusupov",
  "Saidov",
  "Mirzayev",
  "Abdullayev",
  "Nurmatov",
  "Sultanov",
  "Alimov",
  "Ergashev",
  "Kasymov",
  "Zhumagulov",
  "Bekbolatov",
] as const;

export const RU_CENTRAL_ASIA_FIRST_NAMES_MALE = [
  "Serik",
  "Bolat",
  "Marat",
  "Askar",
  "Timur",
  "Bakhyt",
  "Yerlan",
  "Ulugbek",
  "Farrukh",
  "Aibek",
  "Daniyar",
  "Kairat",
  "Sanzhar",
  "Nurlan",
] as const;

export const RU_CENTRAL_ASIA_FIRST_NAMES_FEMALE = [
  "Aigul",
  "Gulnar",
  "Dinara",
  "Saule",
  "Zarina",
  "Madina",
  "Aliya",
  "Botagoz",
  "Dilnoza",
  "Feruza",
  "Gulmira",
  "Nargiza",
  "Zhanna",
  "Zulfiya",
] as const;

// ─── DD (GDR-era first names) ───────────────────────────────────────────────
// East Germany reuses the DE surname pool (the names are German either side
// of the wall) but draws first names from the 1950s-1980s cohorts that
// actually sat in the Volkskammer — no post-1990 fashions.

export const DD_FIRST_NAMES_MALE = [
  "Hans",
  "Werner",
  "Heinz",
  "Horst",
  "Klaus",
  "Guenter",
  "Gerhard",
  "Manfred",
  "Wolfgang",
  "Dieter",
  "Helmut",
  "Herbert",
  "Kurt",
  "Walter",
  "Karl",
  "Erich",
  "Rolf",
  "Siegfried",
  "Rudolf",
  "Wilhelm",
  "Otto",
  "Paul",
  "Ernst",
  "Fritz",
  "Willi",
  "Alfred",
  "Harry",
  "Joachim",
  "Lothar",
  "Rainer",
  "Reinhard",
  "Bernd",
  "Detlef",
  "Eberhard",
  "Egon",
  "Frank",
  "Gerd",
  "Hartmut",
  "Juergen",
  "Norbert",
  "Peter",
  "Uwe",
  "Volker",
  "Winfried",
  "Wolfram",
] as const;

export const DD_FIRST_NAMES_FEMALE = [
  "Ursula",
  "Helga",
  "Ingrid",
  "Gisela",
  "Christa",
  "Renate",
  "Monika",
  "Karin",
  "Erika",
  "Elke",
  "Hannelore",
  "Brigitte",
  "Gudrun",
  "Sigrid",
  "Barbara",
  "Marianne",
  "Ingeborg",
  "Edith",
  "Ilse",
  "Irmgard",
  "Hildegard",
  "Ruth",
  "Elfriede",
  "Gertrud",
  "Margot",
  "Anneliese",
  "Annemarie",
  "Baerbel",
  "Christel",
  "Dagmar",
  "Doris",
  "Edeltraud",
  "Gerda",
  "Hanna",
  "Heidrun",
  "Inge",
  "Jutta",
  "Katrin",
  "Kerstin",
  "Petra",
  "Regina",
  "Sabine",
  "Sieglinde",
  "Waltraud",
  "Ute",
] as const;
